-- GENERATED by scripts/build_data.py -- do not edit by hand; the next build
-- overwrites it. Sources: AzerothCore world DB, the realm client's DBC files,
-- and the Wowhead guides listed in scripts/guides.json.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/blood/tank-bis-gear-pre-raid-pve
ns:RegisterBiS("DEATHKNIGHT", "Blood", "PreRaid", {
	Head = {
		{ 41387, 1 }, -- Tempered Titansteel Helm
		{ 42549, 3 }, -- Armored Titanium Goggles
		{ 37135, 3 }, -- Arcane-Shielded Helm
		{ 37633, 3 }, -- Ground Tremor Helm
	},
	Neck = {
		{ 40679, 1 }, -- Chained Military Gorget
		{ 42646, 1 }, -- Titanium Earthguard Chain
		{ 43282, 3 }, -- Shadowseeker's Pendant
		{ 37689, 3 }, -- Pendant of the Nathrezim
	},
	Shoulder = {
		{ 44312, 1 }, -- Wapach's Spaulders of Solidarity
		{ 37814, 3 }, -- Iron Dwarf Smith Pauldrons
		{ 37115, 3 }, -- Crusader's Square Pauldrons
	},
	Back = {
		{ 43565, 1 }, -- Durable Nerubhide Cape
		{ 37728, 1 }, -- Cloak of the Enemy
		{ 44188, 3 }, -- Cloak of Peaceful Resolutions
	},
	Chest = {
		{ 39623, 1 }, -- Heroes' Scourgeborne Chestguard
		{ 37658, 3 }, -- Sun-Emblazoned Chestplate
		{ 44198, 3 }, -- Breastplate of the Solemn Council
		{ 37735, 3 }, -- Ziggurat Imprinted Chestguard
	},
	Wrist = {
		{ 37620, 1 }, -- Bracers of the Herald
		{ 37682, 3 }, -- Bindings of Dark Will
		{ 37040, 3 }, -- Svala's Bloodied Shackles
		{ 44341, 3 }, -- Bracers of Reverence
	},
	Hands = {
		{ 39624, 1 }, -- Heroes' Scourgeborne Handguards
		{ 44183, 1 }, -- Fireproven Gauntlets
		{ 37645, 1 }, -- Horn-Tipped Gauntlets
		{ 37862, 3 }, -- Gauntlets of the Water Revenant
	},
	Waist = {
		{ 40689, 1 }, -- Waistguard of Living Iron
		{ 37241, 3 }, -- Ancient Aligned Girdle
		{ 37801, 3 }, -- Waistguard of the Risen Knight
	},
	Legs = {
		{ 43500, 1 }, -- Bolstered Legplates
		{ 37292, 3 }, -- Ley-Guardian's Legguards
		{ 37688, 3 }, -- Legplates of the Infinite Drakonid
	},
	Feet = {
		{ 41392, 1 }, -- Tempered Titansteel Treads
		{ 44201, 3 }, -- Sabatons of Draconic Vigor
		{ 37618, 3 }, -- Greaves of Ancient Evil
	},
	Ring = {
		{ 42643, 1 }, -- Titanium Earthguard Ring
		{ 40718, 1 }, -- Signet of the Impregnable Fortress
		{ 37784, 1 }, -- Keystone Great-Ring
		{ 37257, 1 }, -- Band of Torture
		{ 37591, 3 }, -- Nerubian Shield Ring
		{ 38617, 3 }, -- Woeful Band
		{ 36961, 3 }, -- Dragonflight Great-Ring
	},
	Trinket = {
		{ 44063, 1 }, -- Figurine - Monarch Crab
		{ 42341, 1 }, -- Figurine - Ruby Hare
		{ 37220, 1 }, -- Essence of Gossamer
		{ 40683, 3 }, -- Valor Medal of the First War
		{ 36993, 3 }, -- Seal of the Pantheon
		{ 40767, 3 }, -- Sonic Booster
	},
	TwoHand = {
		{ 42322, 1 }, -- Deadly Gladiator's Bonegrinder
		{ 42317, 1 }, -- Deadly Gladiator's Decapitator
		{ 42332, 1 }, -- Deadly Gladiator's Greatsword
		{ 41257, 1 }, -- Titansteel Destroyer
		{ 43409, 1 }, -- Saliva Corroded Pike
		{ 37653, 3 }, -- Sword of Justice
		{ 43281, 3 }, -- Edge of Oblivion
	},
	MainHand = {
		{ 37401, 1 }, -- Red Sword of Courage
		{ 41383, 1 }, -- Titansteel Bonecrusher
		{ 42208, 1 }, -- Deadly Gladiator's Cleaver
		{ 42275, 1 }, -- Deadly Gladiator's Pummeler
		{ 42285, 1 }, -- Deadly Gladiator's Slicer
		{ 37260, 1 }, -- Cloudstrider's Waraxe
		{ 37179, 1 }, -- Infantry Assault Blade
	},
	Ranged = {
		{ 40714, 1 }, -- Sigil of the Unfaltering Knight
		{ 40822, 1 }, -- Sigil of the Frozen Conscience
		{ 40715, 3 }, -- Sigil of Haunted Dreams
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/blood/tank-bis-gear-pve-phase-1
ns:RegisterBiS("DEATHKNIGHT", "Blood", "P1", {
	Head = {
		{ 40565, 1 }, -- Valorous Scourgeborne Faceguard
		{ 40328, 3 }, -- Helm of Vital Protection
		{ 39395, 3 }, -- Thane's Tainted Greathelm
	},
	Neck = {
		{ 40387, 1 }, -- Boundless Ambition
		{ 40069, 1 }, -- Heritage
		{ 40679, 3 }, -- Chained Military Gorget
	},
	Shoulder = {
		{ 40568, 1 }, -- Valorous Scourgeborne Pauldrons
		{ 39704, 3 }, -- Pauldrons of Unnatural Death
		{ 39267, 3 }, -- Abomination Shoulderblades
	},
	Back = {
		{ 40252, 1 }, -- Cloak of the Shadowed Sun
		{ 40722, 3 }, -- Platinum Mesh Cloak
		{ 43988, 3 }, -- Gale-Proof Cloak
	},
	Chest = {
		{ 40559, 1 }, -- Valorous Scourgeborne Chestguard
		{ 44000, 3 }, -- Dragonstorm Breastplate
		{ 40203, 3 }, -- Breastplate of Tormented Rage
	},
	Wrist = {
		{ 40306, 1 }, -- Bracers of the Unholy Knight
		{ 40734, 3 }, -- Bracers of Dalaran's Parapets
		{ 39467, 3 }, -- Minion Bracers
	},
	Hands = {
		{ 40563, 1 }, -- Valorous Scourgeborne Handguards
		{ 39726, 3 }, -- Callous-Hearted Gauntlets
		{ 39624, 3 }, -- Heroes' Scourgeborne Handguards
	},
	Waist = {
		{ 39759, 1 }, -- Ablative Chitin Girdle
		{ 40689, 3 }, -- Waistguard of Living Iron
		{ 37241, 3 }, -- Ancient Aligned Girdle
	},
	Legs = {
		{ 40589, 1 }, -- Legplates of Sovereignty
		{ 40567, 3 }, -- Valorous Scourgeborne Legguards
		{ 40446, 3 }, -- Dragon Brood Legguards
	},
	Feet = {
		{ 40297, 1 }, -- Sabatons of Endurance
		{ 40743, 3 }, -- Kyzoc's Ground Stompers
		{ 39234, 3 }, -- Plague-Impervious Boots
	},
	Ring = {
		{ 40718, 1 }, -- Signet of the Impregnable Fortress
		{ 40370, 1 }, -- Gatekeeper
		{ 40107, 1 }, -- Sand-Worn Band
		{ 39141, 3 }, -- Deflection Band
		{ 40426, 3 }, -- Signet of the Accord
		{ 42643, 3 }, -- Titanium Earthguard Ring
	},
	Trinket = {
		{ 44063, 1 }, -- Figurine - Monarch Crab
		{ 42341, 1 }, -- Figurine - Ruby Hare
		{ 37220, 1 }, -- Essence of Gossamer
		{ 40683, 3 }, -- Valor Medal of the First War
		{ 36993, 3 }, -- Seal of the Pantheon
		{ 40767, 3 }, -- Sonic Booster
	},
	TwoHand = {
		{ 42322, 1 }, -- Deadly Gladiator's Bonegrinder
		{ 42317, 1 }, -- Deadly Gladiator's Decapitator
		{ 42332, 1 }, -- Deadly Gladiator's Greatsword
		{ 40406, 1 }, -- Inevitable Defeat
		{ 40384, 3 }, -- Betrayer of Humanity
	},
	MainHand = {
		{ 40402, 1 }, -- Last Laugh
		{ 42208, 1 }, -- Deadly Gladiator's Cleaver
		{ 42275, 1 }, -- Deadly Gladiator's Pummeler
		{ 42285, 1 }, -- Deadly Gladiator's Slicer
		{ 40345, 1 }, -- Broken Promise
		{ 39344, 3 }, -- Slayer of the Lifeless
	},
	Ranged = {
		{ 40714, 1 }, -- Sigil of the Unfaltering Knight
		{ 40822, 1 }, -- Sigil of the Frozen Conscience
		{ 40207, 3 }, -- Sigil of Awareness
		{ 40715, 3 }, -- Sigil of Haunted Dreams
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/blood/tank-bis-gear-pve-phase-2
ns:RegisterBiS("DEATHKNIGHT", "Blood", "P2", {
	Head = {
		{ 46120, 1 }, -- Conqueror's Darkruned Faceguard
		{ 45502, 3 }, -- Helm of the Faceless
		{ 45336, 3 }, -- Valorous Darkruned Faceguard
		{ 45935, 3 }, -- Ironbark Faceguard
	},
	Neck = {
		{ 45485, 1 }, -- Bronze Pendant of the Vanir
		{ 45538, 3 }, -- Titanstone Pendant
		{ 45821, 3 }, -- Shard of the Crystal Forest
		{ 45696, 3 }, -- Mark of the Unyielding
	},
	Shoulder = {
		{ 46122, 1 }, -- Conqueror's Darkruned Pauldrons
		{ 45251, 3 }, -- Shoulderplates of the Deconstructor
		{ 45339, 3 }, -- Valorous Darkruned Pauldrons
	},
	Back = {
		{ 45496, 1 }, -- Titanskin Cloak
		{ 45319, 3 }, -- Cloak of the Makers
		{ 46014, 3 }, -- Saronite Animus Cloak
	},
	Chest = {
		{ 46118, 1 }, -- Conqueror's Darkruned Chestguard
		{ 46039, 3 }, -- Breastplate of the Timeless
		{ 45335, 3 }, -- Valorous Darkruned Chestguard
	},
	Wrist = {
		{ 45111, 1 }, -- Mimiron's Inferno Couplings
		{ 45283, 3 }, -- Flamewatch Armguards
	},
	Hands = {
		{ 46119, 1 }, -- Conqueror's Darkruned Handguards
		{ 45487, 3 }, -- Handguards of Revitalization
		{ 45834, 3 }, -- Gauntlets of the Royal Watch
		{ 45337, 3 }, -- Valorous Darkruned Handguards
	},
	Waist = {
		{ 45551, 1 }, -- Indestructible Plate Girdle
		{ 45241, 1 }, -- Belt of Colossal Rage
		{ 45825, 1 }, -- Shieldwarder Girdle
		{ 45304, 3 }, -- Stormtempered Girdle
	},
	Legs = {
		{ 45594, 1 }, -- Legplates of the Endless Void
		{ 45267, 1 }, -- Saronite Plated Legguards
		{ 46121, 1 }, -- Conqueror's Darkruned Legguards
		{ 45295, 1 }, -- Gilded Steel Legplates
		{ 45338, 3 }, -- Valorous Darkruned Legguards
	},
	Feet = {
		{ 45988, 1 }, -- Greaves of the Iron Army
		{ 45166, 1 }, -- Charred Saronite Greaves
		{ 45560, 1 }, -- Spiked Deathdealers
	},
	Ring = {
		{ 45471, 1 }, -- Fate's Clutch
		{ 45871, 1 }, -- Seal of Ulduar
		{ 45326, 3 }, -- Platinum Band of the Aesir
		{ 45112, 3 }, -- The Leviathan's Coil
	},
	Trinket = {
		{ 46021, 1 }, -- Royal Seal of King Llane
		{ 45158, 1 }, -- Heart of Iron
		{ 44063, 1 }, -- Figurine - Monarch Crab
		{ 42341, 1 }, -- Figurine - Ruby Hare
		{ 45507, 3 }, -- The General's Heart
		{ 45313, 3 }, -- Furnace Stone
	},
	TwoHand = {
		{ 45533, 1 }, -- Dark Edge of Depravity
		{ 45950, 1 }, -- Furious Gladiator's Claymore
		{ 45516, 1 }, -- Voldrethar, Dark Blade of Oblivion
		{ 46067, 1 }, -- Hammer of Crushing Whispers
	},
	MainHand = {
		{ 45442, 1 }, -- Sorthalis, Hammer of the Watchers
		{ 45876, 1 }, -- Shiver
		{ 45960, 1 }, -- Furious Gladiator's Longblade
		{ 45110, 1 }, -- Titanguard
	},
	Ranged = {
		{ 45144, 1 }, -- Sigil of Deflection
		{ 40714, 3 }, -- Sigil of the Unfaltering Knight
		{ 40207, 3 }, -- Sigil of Awareness
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/blood/tank-bis-gear-pve-phase-3
ns:RegisterBiS("DEATHKNIGHT", "Blood", "P3", {
	Head = {
		{ 48545, 1 }, -- Thassarian's Faceguard of Triumph
		{ 48550, 1 }, -- Koltira's Faceguard of Triumph
		{ 49467, 1 }, -- Frostforged Greathelm
		{ 47677, 3 }, -- Faceplate of the Honorbound
	},
	Neck = {
		{ 47133, 1 }, -- The Arbiter's Muse
		{ 47466, 1 }, -- Legionnaire's Gorget
		{ 47939, 3 }, -- Endurance of the Infernal
		{ 48011, 3 }, -- Fortitude of the Infernal
		{ 45485, 3 }, -- Bronze Pendant of the Vanir
	},
	Shoulder = {
		{ 48543, 1 }, -- Thassarian's Pauldrons of Triumph
		{ 48552, 1 }, -- Koltira's Pauldrons of Triumph
		{ 47698, 1 }, -- Shoulderplates of Enduring Order
		{ 48542, 3 }, -- Thassarian's Pauldrons of Triumph
		{ 48553, 3 }, -- Koltira's Pauldrons of Triumph
	},
	Back = {
		{ 47549, 1 }, -- Magni's Resolution
		{ 47550, 1 }, -- Cairne's Endurance
		{ 47063, 3 }, -- Pride of the Eredar
		{ 47436, 3 }, -- Pride of the Demon Lord
		{ 45496, 3 }, -- Titanskin Cloak
		{ 48675, 3 }, -- Cloak of the Unmoving Guardian
		{ 48670, 3 }, -- Cloak of the Unflinching Guardian
	},
	Chest = {
		{ 46968, 1 }, -- Chestplate of the Towering Monstrosity
		{ 47415, 1 }, -- Hauberk of the Towering Monstrosity
		{ 48547, 3 }, -- Thassarian's Chestguard of Triumph
		{ 48548, 3 }, -- Koltira's Chestguard of Triumph
		{ 46962, 3 }, -- Chestplate of the Towering Monstrosity
		{ 47254, 3 }, -- Hauberk of the Towering Monstrosity
		{ 47964, 3 }, -- Chestguard of the Warden
		{ 48041, 3 }, -- Stoneskin Chestplate
		{ 48538, 3 }, -- Thassarian's Chestguard of Triumph
		{ 48557, 3 }, -- Koltira's Chestguard of Triumph
	},
	Wrist = {
		{ 47111, 1 }, -- Bracers of the Shieldmaiden
		{ 47459, 1 }, -- Armguards of the Shieldmaiden
		{ 47570, 3 }, -- Saronite Swordbreakers
		{ 47571, 3 }, -- Saronite Swordbreakers
		{ 47918, 3 }, -- Dreadscale Armguards
		{ 47991, 3 }, -- Dreadscale Bracers
		{ 47108, 3 }, -- Bracers of the Shieldmaiden
		{ 47298, 3 }, -- Armguards of the Shieldmaiden
	},
	Hands = {
		{ 48546, 1 }, -- Thassarian's Handguards of Triumph
		{ 48549, 1 }, -- Koltira's Handguards of Triumph
		{ 45487, 3 }, -- Handguards of Revitalization
		{ 48539, 3 }, -- Thassarian's Handguards of Triumph
		{ 48556, 3 }, -- Koltira's Handguards of Triumph
	},
	Waist = {
		{ 47076, 1 }, -- Girdle of Bloodied Scars
		{ 47444, 1 }, -- Belt of Bloodied Scars
		{ 47072, 3 }, -- Girdle of Bloodied Scars
		{ 47283, 3 }, -- Belt of Bloodied Scars
		{ 47937, 1 }, -- Girdle of the Nether Champion
		{ 48009, 1 }, -- Belt of the Nether Champion
	},
	Legs = {
		{ 47061, 1 }, -- Legguards of Feverish Dedication
		{ 47434, 1 }, -- Legplates of Feverish Dedication
		{ 48544, 3 }, -- Thassarian's Legguards of Triumph
		{ 48551, 3 }, -- Koltira's Legguards of Triumph
		{ 45594, 3 }, -- Legplates of the Endless Void
		{ 47052, 3 }, -- Legguards of Feverish Dedication
		{ 47273, 3 }, -- Legplates of Feverish Dedication
		{ 48541, 3 }, -- Thassarian's Legguards of Triumph
		{ 48554, 3 }, -- Koltira's Legguards of Triumph
	},
	Feet = {
		{ 47003, 1 }, -- Dawnbreaker Greaves
		{ 47430, 1 }, -- Dawnbreaker Sabatons
		{ 47952, 1 }, -- Sabatons of the Lingering Vortex
		{ 48024, 1 }, -- Greaves of the Lingering Vortex
		{ 45988, 3 }, -- Greaves of the Iron Army
		{ 46997, 3 }, -- Dawnbreaker Greaves
		{ 47269, 3 }, -- Dawnbreaker Sabatons
		{ 47738, 3 }, -- Sabatons of the Lingering Vortex
		{ 47885, 3 }, -- Greaves of the Lingering Vortex
	},
	Ring = {
		{ 47955, 1 }, -- Loop of the Twin Val'kyr
		{ 48027, 1 }, -- Band of the Twin Val'kyr
		{ 49489, 1 }, -- Signified Ring of Binding
		{ 47157, 3 }, -- Signet of the Traitor King
		{ 47476, 3 }, -- Band of the Traitor King
		{ 45471, 3 }, -- Fate's Clutch
		{ 47731, 3 }, -- Clutch of Fortification
	},
	Trinket = {
		{ 47088, 1 }, -- Satrina's Impeding Scarab
		{ 47451, 1 }, -- Juggernaut's Vitality
		{ 47080, 1 }, -- Satrina's Impeding Scarab
		{ 47290, 1 }, -- Juggernaut's Vitality
		{ 45158, 1 }, -- Heart of Iron
		{ 46021, 3 }, -- Royal Seal of King Llane
		{ 47735, 3 }, -- Glyph of Indomitability
	},
	TwoHand = {
		{ 47515, 1 }, -- Decimation
		{ 47516, 1 }, -- Fleshrender
		{ 48406, 1 }, -- Relentless Gladiator's Claymore
		{ 48404, 1 }, -- Relentless Gladiator's Crusher
		{ 48517, 1 }, -- Relentless Gladiator's Halberd
		{ 48402, 1 }, -- Relentless Gladiator's Sunderer
		{ 47519, 3 }, -- Catastrophe
		{ 47520, 3 }, -- Grievance
		{ 47078, 3 }, -- Justicebringer
		{ 47446, 3 }, -- Dual-blade Butcher
	},
	Ranged = {
		{ 47672, 1 }, -- Sigil of Insolence
		{ 45144, 3 }, -- Sigil of Deflection
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/blood/tank-bis-gear-pve-phase-4
ns:RegisterBiS("DEATHKNIGHT", "Blood", "P4", {
	Head = {
		{ 51306, 1 }, -- Sanctified Scourgelord Faceguard
		{ 50640, 1 }, -- Broken Ram Skull Helm
		{ 51133, 3 }, -- Sanctified Scourgelord Faceguard
		{ 49986, 3 }, -- Broken Ram Skull Helm
		{ 48545, 3 }, -- Thassarian's Faceguard of Triumph
		{ 48550, 3 }, -- Koltira's Faceguard of Triumph
		{ 50855, 3 }, -- Scourgelord Faceguard
	},
	Neck = {
		{ 50682, 1 }, -- Bile-Encrusted Medallion
		{ 50627, 3 }, -- Noose of Malachite
		{ 50023, 3 }, -- Bile-Encrusted Medallion
		{ 50195, 3 }, -- Noose of Malachite
		{ 51934, 3 }, -- Marrowgar's Scratching Choker
	},
	Shoulder = {
		{ 51309, 1 }, -- Sanctified Scourgelord Pauldrons
		{ 50660, 3 }, -- Boneguard Commander's Pauldrons
		{ 51130, 3 }, -- Sanctified Scourgelord Pauldrons
		{ 51847, 3 }, -- Spaulders of the Blood Princes
		{ 50003, 3 }, -- Boneguard Commander's Pauldrons
		{ 48543, 3 }, -- Thassarian's Pauldrons of Triumph
		{ 48552, 3 }, -- Koltira's Pauldrons of Triumph
		{ 50853, 3 }, -- Scourgelord Pauldrons
	},
	Back = {
		{ 50718, 1 }, -- Royal Crimson Cloak
		{ 47549, 3 }, -- Magni's Resolution
		{ 47550, 3 }, -- Cairne's Endurance
		{ 50466, 3 }, -- Sentinel's Winter Cloak
		{ 50074, 3 }, -- Royal Crimson Cloak
	},
	Chest = {
		{ 51305, 1 }, -- Sanctified Scourgelord Chestguard
		{ 51134, 3 }, -- Sanctified Scourgelord Chestguard
		{ 50968, 3 }, -- Cataclysmic Chestguard
		{ 50857, 3 }, -- Scourgelord Chestguard
		{ 50681, 3 }, -- Blightborne Warplate
		{ 50024, 3 }, -- Blightborne Warplate
	},
	Wrist = {
		{ 51901, 1 }, -- Gargoyle Spit Bracers
		{ 50611, 1 }, -- Bracers of Dark Reckoning
		{ 50802, 3 }, -- Gargoyle Spit Bracers
		{ 49960, 3 }, -- Bracers of Dark Reckoning
		{ 47111, 3 }, -- Bracers of the Shieldmaiden
		{ 47459, 3 }, -- Armguards of the Shieldmaiden
	},
	Hands = {
		{ 51307, 1 }, -- Sanctified Scourgelord Handguards
		{ 51132, 1 }, -- Sanctified Scourgelord Handguards
		{ 50716, 3 }, -- Taldaram's Plated Fists
		{ 50978, 3 }, -- Gauntlets of the Kraken
		{ 51835, 3 }, -- Veincrusher Gauntlets
		{ 50856, 3 }, -- Scourgelord Handguards
	},
	Waist = {
		{ 50691, 1 }, -- Belt of Broken Bones
		{ 50991, 3 }, -- Verdigris Chain Belt
		{ 51831, 3 }, -- Ironrope Belt of Ymirjar
		{ 50036, 3 }, -- Belt of Broken Bones
	},
	Legs = {
		{ 51308, 1 }, -- Sanctified Scourgelord Legguards
		{ 50612, 1 }, -- Legguards of Lost Hope
		{ 51131, 3 }, -- Sanctified Scourgelord Legguards
		{ 51895, 3 }, -- Deathforged Legplates
		{ 49904, 3 }, -- Pillars of Might
		{ 50854, 3 }, -- Scourgelord Legguards
	},
	Feet = {
		{ 54579, 1 }, -- Treads of Impending Resurrection
		{ 50625, 3 }, -- Grinning Skull Greatboots
		{ 50190, 3 }, -- Grinning Skull Greatboots
		{ 51816, 3 }, -- Scourge Fanged Stompers
		{ 49907, 3 }, -- Boots of Kingly Upheaval
		{ 47003, 3 }, -- Dawnbreaker Greaves
		{ 47430, 3 }, -- Dawnbreaker Sabatons
	},
	Ring = {
		{ 50404, 1 }, -- Ashen Band of Endless Courage
		{ 50622, 1 }, -- Devium's Eternally Cold Ring
		{ 50642, 3 }, -- Juggernaut Band
		{ 50403, 3 }, -- Ashen Band of Unmatched Courage
		{ 51913, 3 }, -- Abomination's Bloody Ring
		{ 50447, 3 }, -- Harbinger's Bone Band
		{ 50185, 3 }, -- Devium's Eternally Cold Ring
		{ 49985, 3 }, -- Juggernaut Band
	},
	Trinket = {
		{ 50364, 1 }, -- Sindragosa's Flawless Fang
		{ 50344, 1 }, -- Unidentifiable Organ
		{ 47088, 1 }, -- Satrina's Impeding Scarab
		{ 47451, 1 }, -- Juggernaut's Vitality
		{ 54591, 3 }, -- Petrified Twilight Scale
		{ 50356, 3 }, -- Corroded Skeleton Key
	},
	TwoHand = {
		{ 50735, 1 }, -- Oathbinder, Charge of the Ranger-General
		{ 50730, 1 }, -- Glorenzelg, High-Blade of the Silver Hand
		{ 51393, 3 }, -- Wrathful Gladiator's Claymore
		{ 50727, 3 }, -- Bloodfall
		{ 50603, 3 }, -- Cryptmaker
	},
	Ranged = {
		{ 50462, 1 }, -- Sigil of the Bone Gryphon
		{ 47672, 3 }, -- Sigil of Insolence
		{ 45144, 3 }, -- Sigil of Deflection
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/blood/dps-bis-gear-pve-phase-4
ns:RegisterBiS("DEATHKNIGHT", "Blood DPS", "P4", {
	Head = {
		{ 51312, 1 }, -- Sanctified Scourgelord Helmet
		{ 51127, 3 }, -- Sanctified Scourgelord Helmet
		{ 50096, 3 }, -- Scourgelord Helmet
		{ 50712, 3 }, -- Landsoul's Horned Greathelm
		{ 51924, 3 }, -- Deathspeaker Zealot's Helm
	},
	Neck = {
		{ 54581, 1 }, -- Penumbra Pendant
		{ 50728, 3 }, -- Lana'thel's Chain of Flagellation
		{ 50180, 3 }, -- Lana'thel's Chain of Flagellation
		{ 51867, 3 }, -- Infected Choker
		{ 51842, 3 }, -- Collar of Haughty Disdain
	},
	Shoulder = {
		{ 51314, 1 }, -- Sanctified Scourgelord Shoulderplates
		{ 51125, 3 }, -- Sanctified Scourgelord Shoulderplates
		{ 50098, 3 }, -- Scourgelord Shoulderplates
		{ 50674, 3 }, -- Raging Behemoth's Shoulderplates
		{ 51865, 3 }, -- Scalpel-Sharpening Shoulderguards
	},
	Back = {
		{ 50677, 1 }, -- Winding Sheet
		{ 47547, 3 }, -- Varian's Furor
		{ 47548, 3 }, -- Garrosh's Rage
		{ 50467, 3 }, -- Might of the Ocean Serpent
		{ 51912, 3 }, -- Saronite Gargoyle Cloak
	},
	Chest = {
		{ 51310, 1 }, -- Sanctified Scourgelord Battleplate
		{ 51129, 3 }, -- Sanctified Scourgelord Battleplate
		{ 50606, 3 }, -- Gendarme's Cuirass
		{ 49951, 3 }, -- Gendarme's Cuirass
		{ 50094, 3 }, -- Scourgelord Battleplate
	},
	Wrist = {
		{ 54580, 1 }, -- Umbrage Armbands
		{ 50659, 3 }, -- Polar Bear Claw Bracers
		{ 50002, 3 }, -- Polar Bear Claw Bracers
		{ 51832, 3 }, -- Taiga Bindings
		{ 51563, 3 }, -- Taiga Bindings
	},
	Hands = {
		{ 50675, 1 }, -- Aldriana's Gloves of Secrecy
		{ 51311, 3 }, -- Sanctified Scourgelord Gauntlets
		{ 50690, 3 }, -- Fleshrending Gauntlets
		{ 51128, 3 }, -- Sanctified Scourgelord Gauntlets
		{ 51844, 3 }, -- Throatrender Handguards
	},
	Waist = {
		{ 50620, 1 }, -- Coldwraith Links
		{ 51879, 3 }, -- Flesh-Shaper's Gurney Strap
		{ 50187, 3 }, -- Coldwraith Links
		{ 50987, 3 }, -- Malevolent Girdle
		{ 51821, 3 }, -- Etched Dragonbone Girdle
	},
	Legs = {
		{ 51313, 1 }, -- Sanctified Scourgelord Legplates
		{ 50624, 3 }, -- Scourge Reaver's Legplates
		{ 51126, 3 }, -- Sanctified Scourgelord Legplates
		{ 50097, 3 }, -- Scourgelord Legplates
	},
	Feet = {
		{ 54578, 1 }, -- Apocalypse's Advance
		{ 50639, 3 }, -- Blood-Soaked Saronite Stompers
		{ 49983, 3 }, -- Blood-Soaked Saronite Stompers
		{ 49906, 3 }, -- Hellfrozen Bonegrinders
		{ 51915, 3 }, -- Bone Drake's Enameled Boots
	},
	Ring = {
		{ 52572, 1 }, -- Ashen Band of Endless Might
		{ 54576, 1 }, -- Signet of Twilight
		{ 50693, 3 }, -- Might of Blight
		{ 50657, 3 }, -- Skeleton Lord's Circle
		{ 52571, 3 }, -- Ashen Band of Unmatched Might
		{ 50453, 3 }, -- Ring of Rotting Sinew
		{ 51855, 3 }, -- Thrice Fanged Signet
	},
	Trinket = {
		{ 50363, 1 }, -- Deathbringer's Will
		{ 54590, 1 }, -- Sharpened Twilight Scale
		{ 47131, 3 }, -- Death's Verdict
		{ 47464, 3 }, -- Death's Choice
		{ 50362, 3 }, -- Deathbringer's Will
		{ 47115, 3 }, -- Death's Verdict
		{ 47303, 3 }, -- Death's Choice
		{ 45931, 3 }, -- Mjolnir Runestone
	},
	TwoHand = {
		{ 49623, 1 }, -- Shadowmourne
		{ 50730, 3 }, -- Glorenzelg, High-Blade of the Silver Hand
		{ 50603, 3 }, -- Cryptmaker
		{ 50070, 3 }, -- Glorenzelg, High-Blade of the Silver Hand
		{ 49888, 3 }, -- Shadow's Edge
	},
	Ranged = {
		{ 47673, 1 }, -- Sigil of Virulence
		{ 50459, 3 }, -- Sigil of the Hanged Man
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/frost/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("DEATHKNIGHT", "Frost", "PreRaid", {
	Head = {
		{ 41386, 1 }, -- Spiked Titansteel Helm
		{ 42552, 3 }, -- Charged Titanium Specs
		{ 37237, 3 }, -- Chitin Shell Greathelm
	},
	Neck = {
		{ 42645, 1 }, -- Titanium Impact Choker
		{ 37397, 3 }, -- Gold Amulet of Kings
		{ 37861, 3 }, -- Necklace of Arcane Spheres
	},
	Shoulder = {
		{ 34388, 1 }, -- Pauldrons of Berserking
		{ 44195, 3 }, -- Spaulders of the Giant Lords
		{ 37627, 3 }, -- Snake Den Spaulders
	},
	Back = {
		{ 37647, 1 }, -- Cloak of Bloodied Waters
		{ 34241, 3 }, -- Cloak of Unforgivable Sin
		{ 37840, 3 }, -- Shroud of Reverberation
	},
	Chest = {
		{ 39617, 1 }, -- Heroes' Scourgeborne Battleplate
		{ 34397, 3 }, -- Bladed Chaos Tunic
		{ 37612, 3 }, -- Bonegrinder Breastplate
	},
	Wrist = {
		{ 41355, 1 }, -- Vengeance Bindings
		{ 37853, 3 }, -- Advanced Tooled-Leather Bands
		{ 44203, 3 }, -- Dragonfriend Bracers
	},
	Hands = {
		{ 39618, 1 }, -- Heroes' Scourgeborne Gauntlets
		{ 37363, 3 }, -- Gauntlets of Dragon Wrath
		{ 34378, 3 }, -- Hard Khorium Battlefists
	},
	Waist = {
		{ 40688, 1 }, -- Verdungo's Barbarian Cord
		{ 37243, 3 }, -- Treasure Seeker's Belt
		{ 37407, 3 }, -- Sovereign's Belt
	},
	Legs = {
		{ 37193, 1 }, -- Staggering Legplates
		{ 34180, 3 }, -- Felfury Legplates
		{ 44205, 3 }, -- Legplates of Bloody Reprisal
	},
	Feet = {
		{ 44306, 1 }, -- Death-Inured Sabatons
		{ 43402, 3 }, -- The Obliterator Greaves
		{ 37367, 3 }, -- Echoing Stompers
	},
	Ring = {
		{ 42642, 1 }, -- Titanium Impact Band
		{ 44935, 1 }, -- Ring of the Kirin Tor
		{ 37642, 3 }, -- Hemorrhaging Circle
		{ 43251, 3 }, -- Ring of Scarlet Shadows
		{ 37624, 3 }, -- Stained-Glass Shard Ring
		{ 37151, 3 }, -- Band of Frosted Thorns
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 37723, 3 }, -- Incisor Fragment
		{ 34472, 3 }, -- Shard of Contempt
		{ 33831, 3 }, -- Berserker's Call
	},
	MainHand = {
		{ 41383, 1 }, -- Titansteel Bonecrusher
		{ 44250, 3 }, -- Reaper of Dark Souls
		{ 37235, 3 }, -- Crypt Lord's Deft Blade
		{ 37871, 3 }, -- The Key
	},
	OffHand = {
		{ 44250, 1 }, -- Reaper of Dark Souls
		{ 37235, 3 }, -- Crypt Lord's Deft Blade
		{ 37871, 3 }, -- The Key
	},
	Ranged = {
		{ 40715, 1 }, -- Sigil of Haunted Dreams
		{ 39208, 3 }, -- Sigil of the Dark Rider
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/frost/dps-bis-gear-pve-phase-1
ns:RegisterBiS("DEATHKNIGHT", "Frost", "P1", {
	Head = {
		{ 44006, 1 }, -- Obsidian Greathelm
		{ 40554, 3 }, -- Valorous Scourgeborne Helmet
		{ 39403, 3 }, -- Helm of the Unsubmissive
		{ 41386, 3 }, -- Spiked Titansteel Helm
	},
	Neck = {
		{ 44664, 1 }, -- Favor of the Dragon Queen
		{ 44659, 3 }, -- Pendant of the Dragonsworn
		{ 39421, 3 }, -- Gem of Imprisoned Vassals
	},
	Shoulder = {
		{ 40557, 1 }, -- Valorous Scourgeborne Shoulderplates
		{ 39621, 1 }, -- Heroes' Scourgeborne Shoulderplates
		{ 40185, 3 }, -- Shoulderguards of Opportunity
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 40250, 3 }, -- Aged Winter Cloak
		{ 39297, 3 }, -- Cloak of Darkening
	},
	Chest = {
		{ 40550, 1 }, -- Valorous Scourgeborne Battleplate
		{ 39617, 1 }, -- Heroes' Scourgeborne Battleplate
		{ 40539, 3 }, -- Chestguard of the Recluse
		{ 40365, 3 }, -- Breastplate of Frozen Pain
	},
	Wrist = {
		{ 40330, 1 }, -- Bracers of Unrelenting Attack
		{ 39729, 3 }, -- Bracers of the Tyrant
		{ 39195, 3 }, -- Bracers of Lost Sentiments
	},
	Hands = {
		{ 40552, 1 }, -- Valorous Scourgeborne Gauntlets
		{ 39618, 1 }, -- Heroes' Scourgeborne Gauntlets
		{ 40347, 3 }, -- Zeliek's Gauntlets
		{ 40261, 3 }, -- Crude Discolored Battlegrips
	},
	Waist = {
		{ 40278, 1 }, -- Girdle of Chivalry
		{ 40317, 3 }, -- Girdle of Razuvious
		{ 40688, 3 }, -- Verdungo's Barbarian Cord
	},
	Legs = {
		{ 40556, 1 }, -- Valorous Scourgeborne Legplates
		{ 39620, 1 }, -- Heroes' Scourgeborne Legplates
		{ 40318, 3 }, -- Legplates of Double Strikes
		{ 40294, 3 }, -- Riveted Abomination Leggings
	},
	Feet = {
		{ 40591, 1 }, -- Melancholy Sabatons
		{ 39706, 3 }, -- Sabatons of Sudden Reprisal
		{ 40206, 3 }, -- Iron-Spring Jumpers
	},
	Ring = {
		{ 40075, 1 }, -- Ruthlessness
		{ 43993, 1 }, -- Greatring of Collision
		{ 39401, 3 }, -- Circle of Death
		{ 42642, 3 }, -- Titanium Impact Band
		{ 44935, 3 }, -- Ring of the Kirin Tor
		{ 37642, 3 }, -- Hemorrhaging Circle
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 40431, 1 }, -- Fury of the Five Flights
		{ 40256, 1 }, -- Grim Toll
		{ 40684, 3 }, -- Mirror of Truth
		{ 39257, 3 }, -- Loatheb's Shadow
		{ 37723, 3 }, -- Incisor Fragment
		{ 37390, 3 }, -- Meteorite Whetstone
	},
	MainHand = {
		{ 40189, 1 }, -- Angry Dread
		{ 42208, 3 }, -- Deadly Gladiator's Cleaver
		{ 40407, 3 }, -- Silent Crusader
		{ 40345, 3 }, -- Broken Promise
		{ 39291, 3 }, -- Torment of the Banished
	},
	OffHand = {
		{ 40189, 1 }, -- Angry Dread
		{ 42208, 3 }, -- Deadly Gladiator's Cleaver
		{ 40407, 3 }, -- Silent Crusader
		{ 40345, 3 }, -- Broken Promise
		{ 39291, 3 }, -- Torment of the Banished
	},
	Ranged = {
		{ 40207, 1 }, -- Sigil of Awareness
		{ 40715, 3 }, -- Sigil of Haunted Dreams
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/frost/dps-bis-gear-pve-phase-2
ns:RegisterBiS("DEATHKNIGHT", "Frost", "P2", {
	Head = {
		{ 46115, 1 }, -- Conqueror's Darkruned Helmet
		{ 45472, 3 }, -- Warhelm of the Champion
		{ 45107, 3 }, -- Iron Riveted War Helm
		{ 45610, 3 }, -- Boundless Gaze
		{ 44006, 3 }, -- Obsidian Greathelm
	},
	Neck = {
		{ 45459, 1 }, -- Frigid Strength of Hodir
		{ 46040, 3 }, -- Strength of the Heavens
		{ 45193, 3 }, -- Insurmountable Fervor
		{ 45819, 3 }, -- Spiked Battleguard Choker
		{ 45517, 3 }, -- Pendulum of Infinity
	},
	Shoulder = {
		{ 46117, 1 }, -- Conqueror's Darkruned Shoulderplates
		{ 46037, 3 }, -- Shoulderplates of the Celestial Watch
		{ 45320, 3 }, -- Shoulderplates of the Eternal
		{ 45245, 3 }, -- Shoulderpads of the Intruder
	},
	Back = {
		{ 46032, 1 }, -- Drape of the Faceless General
		{ 46320, 3 }, -- Drape of the Skyherald
		{ 45138, 3 }, -- Drape of the Drakerider
		{ 45973, 3 }, -- Stylish Power Cape
		{ 40403, 3 }, -- Drape of the Deadly Foe
	},
	Chest = {
		{ 46111, 1 }, -- Conqueror's Darkruned Battleplate
		{ 45473, 3 }, -- Embrace of the Gladiator
		{ 45225, 3 }, -- Steelbreaker's Embrace
		{ 45340, 3 }, -- Valorous Darkruned Battleplate
		{ 45712, 3 }, -- Chestplate of Titanic Fury
	},
	Wrist = {
		{ 45663, 1 }, -- Armbands of Bedlam
		{ 45888, 3 }, -- Bitter Cold Armguards
		{ 45264, 3 }, -- Decimator's Armguards
		{ 40330, 3 }, -- Bracers of Unrelenting Attack
	},
	Hands = {
		{ 46113, 1 }, -- Conqueror's Darkruned Gauntlets
		{ 45444, 3 }, -- Gloves of the Steady Hand
		{ 45481, 3 }, -- Gauntlets of Ruthless Reprisal
		{ 45341, 3 }, -- Valorous Darkruned Gauntlets
		{ 45833, 3 }, -- Bladebreaker Gauntlets
	},
	Waist = {
		{ 45241, 1 }, -- Belt of Colossal Rage
		{ 46041, 3 }, -- Starfall Girdle
		{ 45550, 3 }, -- Belt of the Titans
		{ 45161, 3 }, -- Girdle of Embers
		{ 45824, 3 }, -- Belt of the Singing Blade
	},
	Legs = {
		{ 45134, 1 }, -- Plated Leggings of Ruination
		{ 45982, 3 }, -- Fused Alloy Legplates
		{ 46116, 3 }, -- Conqueror's Darkruned Legplates
		{ 45841, 3 }, -- Legplates of the Violet Champion
		{ 45343, 3 }, -- Valorous Darkruned Legplates
	},
	Feet = {
		{ 45599, 1 }, -- Sabatons of Lifeless Night
		{ 45559, 3 }, -- Battlelord's Plate Boots
		{ 45501, 3 }, -- Boots of the Underdweller
		{ 45330, 3 }, -- Greaves of Iron Intensity
		{ 40591, 3 }, -- Melancholy Sabatons
	},
	Ring = {
		{ 45534, 1 }, -- Seal of the Betrayed King
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 45250, 3 }, -- Crazed Construct Ring
		{ 45540, 3 }, -- Bladebearer's Signet
		{ 45469, 3 }, -- Sif's Promise
		{ 45106, 3 }, -- Strength of the Automaton
	},
	Trinket = {
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 46038, 3 }, -- Dark Matter
		{ 45609, 3 }, -- Comet's Trail
		{ 45263, 3 }, -- Wrathstone
		{ 45522, 3 }, -- Blood of the Old God
		{ 45286, 3 }, -- Pyrite Infuser
	},
	MainHand = {
		{ 46097, 1 }, -- Caress of Insanity
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 45957, 3 }, -- Furious Gladiator's Handaxe
		{ 45463, 3 }, -- Vulmir, the Northern Tempest
		{ 45266, 3 }, -- Malice
		{ 45298, 3 }, -- Razorscale Talon
	},
	OffHand = {
		{ 46097, 1 }, -- Caress of Insanity
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 45957, 3 }, -- Furious Gladiator's Handaxe
		{ 45463, 3 }, -- Vulmir, the Northern Tempest
		{ 45266, 3 }, -- Malice
		{ 45298, 3 }, -- Razorscale Talon
	},
	Ranged = {
		{ 40207, 1 }, -- Sigil of Awareness
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/frost/dps-bis-gear-pve-phase-3
ns:RegisterBiS("DEATHKNIGHT", "Frost", "P3", {
	Head = {
		{ 48493, 1 }, -- Koltira's Helmet of Triumph
		{ 48488, 1 }, -- Thassarian's Helmet of Triumph
		{ 48498, 3 }, -- Koltira's Helmet of Triumph
		{ 48483, 3 }, -- Thassarian's Helmet of Triumph
		{ 45472, 3 }, -- Warhelm of the Champion
		{ 46115, 3 }, -- Conqueror's Darkruned Helmet
	},
	Neck = {
		{ 47458, 1 }, -- The Executioner's Vice
		{ 47110, 1 }, -- The Executioner's Malice
		{ 45459, 3 }, -- Frigid Strength of Hodir
		{ 47297, 3 }, -- The Executioner's Vice
		{ 47105, 3 }, -- The Executioner's Malice
		{ 46040, 3 }, -- Strength of the Heavens
	},
	Shoulder = {
		{ 48495, 1 }, -- Koltira's Shoulderplates of Triumph
		{ 48486, 1 }, -- Thassarian's Shoulderplates of Triumph
		{ 48496, 3 }, -- Koltira's Shoulderplates of Triumph
		{ 48485, 3 }, -- Thassarian's Shoulderplates of Triumph
		{ 46117, 3 }, -- Conqueror's Darkruned Shoulderplates
		{ 46037, 3 }, -- Shoulderplates of the Celestial Watch
	},
	Back = {
		{ 47548, 1 }, -- Garrosh's Rage
		{ 47547, 1 }, -- Varian's Furor
		{ 48669, 3 }, -- Cloak of the Triumphant Combatant
		{ 48674, 3 }, -- Cloak of the Victorious Combatant
		{ 47481, 3 }, -- Might of the Nerub
		{ 47192, 3 }, -- Strength of the Nerub
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 46320, 3 }, -- Drape of the Skyherald
	},
	Chest = {
		{ 48491, 1 }, -- Koltira's Battleplate of Triumph
		{ 48490, 1 }, -- Thassarian's Battleplate of Triumph
		{ 48500, 3 }, -- Koltira's Battleplate of Triumph
		{ 48481, 3 }, -- Thassarian's Battleplate of Triumph
		{ 47449, 3 }, -- Chestplate of the Frostwolf Hero
		{ 47086, 3 }, -- Chestplate of the Frostborn Hero
		{ 46111, 3 }, -- Conqueror's Darkruned Battleplate
	},
	Wrist = {
		{ 45663, 1 }, -- Armbands of Bedlam
		{ 47414, 3 }, -- Boneshatter Vambraces
		{ 46967, 3 }, -- Boneshatter Armplates
		{ 48008, 3 }, -- Armplates of the Nether Lord
		{ 47935, 3 }, -- Armguards of the Nether Lord
		{ 47573, 3 }, -- Titanium Spikeguards
	},
	Hands = {
		{ 47492, 1 }, -- Gauntlets of Bitter Reprisal
		{ 47240, 1 }, -- Gloves of Bitter Reprisal
		{ 48492, 3 }, -- Koltira's Gauntlets of Triumph
		{ 48499, 3 }, -- Koltira's Gauntlets of Triumph
		{ 48482, 3 }, -- Thassarian's Gauntlets of Triumph
		{ 46113, 3 }, -- Conqueror's Darkruned Gauntlets
	},
	Waist = {
		{ 45241, 1 }, -- Belt of Colossal Rage
		{ 47429, 3 }, -- Bloodbath Girdle
		{ 47002, 3 }, -- Bloodbath Belt
		{ 47998, 3 }, -- Belt of the Impaler
		{ 47925, 3 }, -- Girdle of the Impaler
		{ 46041, 3 }, -- Starfall Girdle
	},
	Legs = {
		{ 48494, 1 }, -- Koltira's Legplates of Triumph
		{ 48487, 1 }, -- Thassarian's Legplates of Triumph
		{ 48497, 3 }, -- Koltira's Legplates of Triumph
		{ 48484, 3 }, -- Thassarian's Legplates of Triumph
		{ 47465, 3 }, -- Legplates of Ascension
		{ 47132, 3 }, -- Legguards of Ascension
		{ 45134, 3 }, -- Plated Leggings of Ruination
		{ 45982, 3 }, -- Fused Alloy Legplates
	},
	Feet = {
		{ 45599, 1 }, -- Sabatons of Lifeless Night
		{ 47473, 3 }, -- Greaves of the Saronite Citadel
		{ 47154, 3 }, -- Greaves of the 7th Legion
		{ 47312, 3 }, -- Greaves of the Saronite Citadel
		{ 47150, 3 }, -- Greaves of the 7th Legion
		{ 45559, 3 }, -- Battlelord's Plate Boots
	},
	Ring = {
		{ 47413, 1 }, -- Ring of the Violent Temperament
		{ 46966, 1 }, -- Band of the Violent Temperment
		{ 45534, 1 }, -- Seal of the Betrayed King
		{ 45608, 3 }, -- Brann's Signet Ring
		{ 47993, 3 }, -- Gormok's Band
		{ 47920, 3 }, -- Carnivorous Band
		{ 47252, 3 }, -- Ring of the Violent Temperament
		{ 46959, 3 }, -- Band of the Violent Temperment
	},
	Trinket = {
		{ 47464, 1 }, -- Death's Choice
		{ 47131, 1 }, -- Death's Verdict
		{ 47303, 1 }, -- Death's Choice
		{ 47115, 1 }, -- Death's Verdict
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 42987, 3 }, -- Darkmoon Card: Greatness
		{ 46038, 3 }, -- Dark Matter
		{ 45609, 3 }, -- Comet's Trail
	},
	MainHand = {
		{ 47475, 1 }, -- Hellscream Slicer
		{ 47156, 1 }, -- Stormpike Cleaver
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 47526, 3 }, -- Remorseless
		{ 48513, 3 }, -- Relentless Gladiator's Longblade
		{ 46097, 3 }, -- Caress of Insanity
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 48050, 3 }, -- Blackhorn Bludgeon
		{ 47973, 3 }, -- The Grinder
	},
	OffHand = {
		{ 47475, 1 }, -- Hellscream Slicer
		{ 47156, 1 }, -- Stormpike Cleaver
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 47526, 3 }, -- Remorseless
		{ 48513, 3 }, -- Relentless Gladiator's Longblade
		{ 46097, 3 }, -- Caress of Insanity
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 48050, 3 }, -- Blackhorn Bludgeon
		{ 47973, 3 }, -- The Grinder
	},
	Ranged = {
		{ 40207, 1 }, -- Sigil of Awareness
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/frost/dps-bis-gear-pve-phase-4
ns:RegisterBiS("DEATHKNIGHT", "Frost", "P4", {
	Head = {
		{ 51312, 1 }, -- Sanctified Scourgelord Helmet
		{ 51127, 3 }, -- Sanctified Scourgelord Helmet
		{ 50712, 3 }, -- Landsoul's Horned Greathelm
		{ 50072, 3 }, -- Landsoul's Horned Greathelm
		{ 48493, 3 }, -- Koltira's Helmet of Triumph
		{ 48488, 3 }, -- Thassarian's Helmet of Triumph
	},
	Neck = {
		{ 50728, 1 }, -- Lana'thel's Chain of Flagellation
		{ 50647, 3 }, -- Ahn'kahar Onyx Neckguard
		{ 51842, 3 }, -- Collar of Haughty Disdain
		{ 47458, 3 }, -- The Executioner's Vice
		{ 47110, 3 }, -- The Executioner's Malice
	},
	Shoulder = {
		{ 51314, 1 }, -- Sanctified Scourgelord Shoulderplates
		{ 51125, 3 }, -- Sanctified Scourgelord Shoulderplates
		{ 50674, 3 }, -- Raging Behemoth's Shoulderplates
		{ 50020, 3 }, -- Raging Behemoth's Shoulderplates
		{ 48495, 3 }, -- Koltira's Shoulderplates of Triumph
		{ 48486, 3 }, -- Thassarian's Shoulderplates of Triumph
	},
	Back = {
		{ 47548, 3 }, -- Garrosh's Rage
		{ 47547, 3 }, -- Varian's Furor
		{ 50677, 1 }, -- Winding Sheet
		{ 50019, 3 }, -- Winding Sheet
		{ 51912, 3 }, -- Saronite Gargoyle Cloak
	},
	Chest = {
		{ 51310, 1 }, -- Sanctified Scourgelord Battleplate
		{ 51129, 3 }, -- Sanctified Scourgelord Battleplate
		{ 50606, 1 }, -- Gendarme's Cuirass
		{ 51902, 3 }, -- Blade-Scored Carapace
		{ 48491, 3 }, -- Koltira's Battleplate of Triumph
		{ 48490, 3 }, -- Thassarian's Battleplate of Triumph
	},
	Wrist = {
		{ 50659, 1 }, -- Polar Bear Claw Bracers
		{ 50002, 3 }, -- Polar Bear Claw Bracers
		{ 51832, 3 }, -- Taiga Bindings
		{ 45663, 3 }, -- Armbands of Bedlam
		{ 47414, 3 }, -- Boneshatter Vambraces
		{ 46967, 3 }, -- Boneshatter Armplates
	},
	Hands = {
		{ 51311, 1 }, -- Sanctified Scourgelord Gauntlets
		{ 51128, 3 }, -- Sanctified Scourgelord Gauntlets
		{ 50675, 1 }, -- Aldriana's Gloves of Secrecy
		{ 50690, 3 }, -- Fleshrending Gauntlets
		{ 50037, 3 }, -- Fleshrending Gauntlets
		{ 48492, 3 }, -- Koltira's Gauntlets of Triumph
	},
	Waist = {
		{ 50620, 1 }, -- Coldwraith Links
		{ 51821, 3 }, -- Etched Dragonbone Girdle
		{ 51879, 3 }, -- Flesh-Shaper's Gurney Strap
		{ 50987, 3 }, -- Malevolent Girdle
		{ 50187, 3 }, -- Coldwraith Links
		{ 47429, 3 }, -- Bloodbath Girdle
		{ 47002, 3 }, -- Bloodbath Belt
		{ 45241, 3 }, -- Belt of Colossal Rage
	},
	Legs = {
		{ 51817, 1 }, -- Legplates of Aetheric Strife
		{ 50624, 3 }, -- Scourge Reaver's Legplates
		{ 51313, 1 }, -- Sanctified Scourgelord Legplates
		{ 50192, 3 }, -- Scourge Reaver's Legplates
		{ 51854, 3 }, -- Battle-Maiden's Legguards
		{ 48494, 3 }, -- Koltira's Legplates of Triumph
		{ 48487, 3 }, -- Thassarian's Legplates of Triumph
	},
	Feet = {
		{ 50639, 1 }, -- Blood-Soaked Saronite Stompers
		{ 49983, 3 }, -- Blood-Soaked Saronite Stompers
		{ 51915, 3 }, -- Bone Drake's Enameled Boots
		{ 47473, 3 }, -- Greaves of the Saronite Citadel
		{ 47154, 3 }, -- Greaves of the 7th Legion
	},
	Ring = {
		{ 52572, 1 }, -- Ashen Band of Endless Might
		{ 50693, 1 }, -- Might of Blight
		{ 50657, 3 }, -- Skeleton Lord's Circle
		{ 51855, 3 }, -- Thrice Fanged Signet
		{ 50453, 3 }, -- Ring of Rotting Sinew
		{ 47413, 3 }, -- Ring of the Violent Temperament
		{ 46966, 3 }, -- Band of the Violent Temperment
	},
	Trinket = {
		{ 50363, 1 }, -- Deathbringer's Will
		{ 54590, 1 }, -- Sharpened Twilight Scale
		{ 54569, 1 }, -- Sharpened Twilight Scale
		{ 47464, 1 }, -- Death's Choice
		{ 47131, 1 }, -- Death's Verdict
		{ 47303, 1 }, -- Death's Choice
		{ 47115, 1 }, -- Death's Verdict
		{ 45931, 3 }, -- Mjolnir Runestone
		{ 50343, 3 }, -- Whispering Fanged Skull
		{ 50355, 3 }, -- Herkuml War Token
		{ 42987, 3 }, -- Darkmoon Card: Greatness
	},
	MainHand = {
		{ 50737, 1 }, -- Havoc's Call, Blade of Lordaeron Kings
		{ 50672, 3 }, -- Bloodvenom Blade
		{ 51893, 3 }, -- Gutbuster
		{ 51916, 3 }, -- Frost Giant's Cleaver
		{ 47475, 3 }, -- Hellscream Slicer
		{ 47156, 3 }, -- Stormpike Cleaver
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 47526, 3 }, -- Remorseless
	},
	OffHand = {
		{ 50737, 1 }, -- Havoc's Call, Blade of Lordaeron Kings
		{ 50672, 3 }, -- Bloodvenom Blade
		{ 51893, 3 }, -- Gutbuster
		{ 51916, 3 }, -- Frost Giant's Cleaver
		{ 47475, 3 }, -- Hellscream Slicer
		{ 47156, 3 }, -- Stormpike Cleaver
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 47526, 3 }, -- Remorseless
	},
	Ranged = {
		{ 40207, 1 }, -- Sigil of Awareness
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/unholy/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("DEATHKNIGHT", "Unholy", "PreRaid", {
	Head = {
		{ 41386, 1 }, -- Spiked Titansteel Helm
		{ 42552, 3 }, -- Charged Titanium Specs
		{ 37237, 3 }, -- Chitin Shell Greathelm
		{ 37293, 3 }, -- Mask of the Watcher
	},
	Neck = {
		{ 42646, 1 }, -- Titanium Earthguard Chain
		{ 37397, 1 }, -- Gold Amulet of Kings
		{ 37861, 3 }, -- Necklace of Arcane Spheres
	},
	Shoulder = {
		{ 34388, 1 }, -- Pauldrons of Berserking
		{ 44195, 3 }, -- Spaulders of the Giant Lords
		{ 37627, 3 }, -- Snake Den Spaulders
	},
	Back = {
		{ 37647, 1 }, -- Cloak of Bloodied Waters
		{ 34241, 3 }, -- Cloak of Unforgivable Sin
		{ 37840, 3 }, -- Shroud of Reverberation
	},
	Chest = {
		{ 39617, 1 }, -- Heroes' Scourgeborne Battleplate
		{ 34397, 3 }, -- Bladed Chaos Tunic
		{ 37612, 3 }, -- Bonegrinder Breastplate
	},
	Wrist = {
		{ 37668, 1 }, -- Bands of the Stoneforge
		{ 41355, 3 }, -- Vengeance Bindings
		{ 37853, 3 }, -- Advanced Tooled-Leather Bands
		{ 44203, 3 }, -- Dragonfriend Bracers
	},
	Hands = {
		{ 39618, 1 }, -- Heroes' Scourgeborne Gauntlets
		{ 37363, 3 }, -- Gauntlets of Dragon Wrath
		{ 34378, 3 }, -- Hard Khorium Battlefists
	},
	Waist = {
		{ 40688, 1 }, -- Verdungo's Barbarian Cord
		{ 37243, 3 }, -- Treasure Seeker's Belt
		{ 37407, 3 }, -- Sovereign's Belt
	},
	Legs = {
		{ 37193, 1 }, -- Staggering Legplates
		{ 34180, 3 }, -- Felfury Legplates
		{ 44205, 3 }, -- Legplates of Bloody Reprisal
	},
	Feet = {
		{ 43402, 1 }, -- The Obliterator Greaves
		{ 44306, 3 }, -- Death-Inured Sabatons
		{ 37367, 3 }, -- Echoing Stompers
	},
	Ring = {
		{ 42643, 1 }, -- Titanium Earthguard Ring
		{ 44935, 1 }, -- Ring of the Kirin Tor
		{ 43251, 3 }, -- Ring of Scarlet Shadows
		{ 37642, 3 }, -- Hemorrhaging Circle
		{ 37624, 3 }, -- Stained-Glass Shard Ring
		{ 37151, 3 }, -- Band of Frosted Thorns
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 37390, 1 }, -- Meteorite Whetstone
		{ 40684, 3 }, -- Mirror of Truth
		{ 37723, 3 }, -- Incisor Fragment
		{ 34472, 3 }, -- Shard of Contempt
		{ 33831, 3 }, -- Berserker's Call
	},
	TwoHand = {
		{ 41257, 1 }, -- Titansteel Destroyer
		{ 37852, 3 }, -- Colossal Skull-Clad Cleaver
	},
	MainHand = {
		{ 41383, 1 }, -- Titansteel Bonecrusher
		{ 44250, 3 }, -- Reaper of Dark Souls
		{ 37235, 3 }, -- Crypt Lord's Deft Blade
		{ 37871, 3 }, -- The Key
	},
	OffHand = {
		{ 40703, 1 }, -- Grasscutter
		{ 44250, 3 }, -- Reaper of Dark Souls
		{ 37235, 3 }, -- Crypt Lord's Deft Blade
		{ 37871, 3 }, -- The Key
	},
	Ranged = {
		{ 40867, 1 }, -- Sigil of the Wild Buck
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/unholy/dps-bis-gear-pve-phase-1
ns:RegisterBiS("DEATHKNIGHT", "Unholy", "P1", {
	Head = {
		{ 44006, 1 }, -- Obsidian Greathelm
		{ 40554, 3 }, -- Valorous Scourgeborne Helmet
		{ 39403, 3 }, -- Helm of the Unsubmissive
		{ 41386, 3 }, -- Spiked Titansteel Helm
	},
	Neck = {
		{ 44664, 1 }, -- Favor of the Dragon Queen
		{ 44659, 3 }, -- Pendant of the Dragonsworn
		{ 39421, 3 }, -- Gem of Imprisoned Vassals
	},
	Shoulder = {
		{ 40557, 1 }, -- Valorous Scourgeborne Shoulderplates
		{ 39621, 1 }, -- Heroes' Scourgeborne Shoulderplates
		{ 40185, 3 }, -- Shoulderguards of Opportunity
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 40250, 3 }, -- Aged Winter Cloak
		{ 39297, 3 }, -- Cloak of Darkening
	},
	Chest = {
		{ 40550, 1 }, -- Valorous Scourgeborne Battleplate
		{ 39617, 1 }, -- Heroes' Scourgeborne Battleplate
		{ 40539, 3 }, -- Chestguard of the Recluse
		{ 40365, 3 }, -- Breastplate of Frozen Pain
	},
	Wrist = {
		{ 40330, 1 }, -- Bracers of Unrelenting Attack
		{ 39729, 3 }, -- Bracers of the Tyrant
		{ 39195, 3 }, -- Bracers of Lost Sentiments
	},
	Hands = {
		{ 40552, 1 }, -- Valorous Scourgeborne Gauntlets
		{ 39618, 1 }, -- Heroes' Scourgeborne Gauntlets
		{ 40347, 1 }, -- Zeliek's Gauntlets
		{ 40261, 3 }, -- Crude Discolored Battlegrips
	},
	Waist = {
		{ 40278, 1 }, -- Girdle of Chivalry
		{ 40317, 3 }, -- Girdle of Razuvious
		{ 40688, 3 }, -- Verdungo's Barbarian Cord
	},
	Legs = {
		{ 40556, 1 }, -- Valorous Scourgeborne Legplates
		{ 39620, 1 }, -- Heroes' Scourgeborne Legplates
		{ 40294, 1 }, -- Riveted Abomination Leggings
		{ 40318, 3 }, -- Legplates of Double Strikes
	},
	Feet = {
		{ 40591, 1 }, -- Melancholy Sabatons
		{ 39706, 1 }, -- Sabatons of Sudden Reprisal
		{ 40206, 3 }, -- Iron-Spring Jumpers
	},
	Ring = {
		{ 40075, 1 }, -- Ruthlessness
		{ 39401, 1 }, -- Circle of Death
		{ 40074, 3 }, -- Strong-Handed Ring
		{ 43993, 3 }, -- Greatring of Collision
		{ 44935, 3 }, -- Ring of the Kirin Tor
		{ 37642, 3 }, -- Hemorrhaging Circle
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 37390, 1 }, -- Meteorite Whetstone
		{ 40256, 3 }, -- Grim Toll
		{ 40431, 3 }, -- Fury of the Five Flights
		{ 40684, 3 }, -- Mirror of Truth
		{ 39257, 3 }, -- Loatheb's Shadow
		{ 37723, 3 }, -- Incisor Fragment
	},
	TwoHand = {
		{ 40384, 1 }, -- Betrayer of Humanity
	},
	MainHand = {
		{ 40402, 1 }, -- Last Laugh
		{ 40189, 1 }, -- Angry Dread
		{ 42208, 1 }, -- Deadly Gladiator's Cleaver
		{ 40407, 3 }, -- Silent Crusader
		{ 40345, 3 }, -- Broken Promise
		{ 39291, 3 }, -- Torment of the Banished
	},
	OffHand = {
		{ 40491, 1 }, -- Hailstorm
		{ 40402, 1 }, -- Last Laugh
		{ 40189, 3 }, -- Angry Dread
		{ 42208, 3 }, -- Deadly Gladiator's Cleaver
		{ 40407, 3 }, -- Silent Crusader
		{ 40345, 3 }, -- Broken Promise
		{ 39291, 3 }, -- Torment of the Banished
	},
	Ranged = {
		{ 42620, 1 }, -- Deadly Gladiator's Sigil of Strife
		{ 40207, 1 }, -- Sigil of Awareness
		{ 40867, 3 }, -- Sigil of the Wild Buck
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/unholy/dps-bis-gear-pve-phase-2
ns:RegisterBiS("DEATHKNIGHT", "Unholy", "P2", {
	Head = {
		{ 45472, 1 }, -- Warhelm of the Champion
		{ 45107, 3 }, -- Iron Riveted War Helm
		{ 46115, 3 }, -- Conqueror's Darkruned Helmet
		{ 45610, 3 }, -- Boundless Gaze
		{ 44006, 3 }, -- Obsidian Greathelm
	},
	Neck = {
		{ 46040, 1 }, -- Strength of the Heavens
		{ 45459, 3 }, -- Frigid Strength of Hodir
		{ 45193, 3 }, -- Insurmountable Fervor
		{ 45819, 3 }, -- Spiked Battleguard Choker
		{ 45517, 3 }, -- Pendulum of Infinity
	},
	Shoulder = {
		{ 46117, 1 }, -- Conqueror's Darkruned Shoulderplates
		{ 45320, 3 }, -- Shoulderplates of the Eternal
		{ 46037, 3 }, -- Shoulderplates of the Celestial Watch
		{ 45245, 3 }, -- Shoulderpads of the Intruder
	},
	Back = {
		{ 45588, 1 }, -- Drape of the Skyborn
		{ 45318, 3 }, -- Drape of Fuming Anger
		{ 46320, 3 }, -- Drape of the Skyherald
		{ 45138, 3 }, -- Drape of the Drakerider
		{ 45973, 3 }, -- Stylish Power Cape
		{ 40403, 3 }, -- Drape of the Deadly Foe
	},
	Chest = {
		{ 46111, 1 }, -- Conqueror's Darkruned Battleplate
		{ 45473, 2 }, -- Embrace of the Gladiator
		{ 45225, 3 }, -- Steelbreaker's Embrace
		{ 45340, 3 }, -- Valorous Darkruned Battleplate
		{ 45712, 3 }, -- Chestplate of Titanic Fury
	},
	Wrist = {
		{ 45663, 1 }, -- Armbands of Bedlam
		{ 45888, 3 }, -- Bitter Cold Armguards
		{ 45264, 3 }, -- Decimator's Armguards
		{ 40330, 3 }, -- Bracers of Unrelenting Attack
	},
	Hands = {
		{ 45481, 1 }, -- Gauntlets of Ruthless Reprisal
		{ 45444, 2 }, -- Gloves of the Steady Hand
		{ 46113, 3 }, -- Conqueror's Darkruned Gauntlets
		{ 45341, 3 }, -- Valorous Darkruned Gauntlets
		{ 45833, 3 }, -- Bladebreaker Gauntlets
	},
	Waist = {
		{ 45241, 1 }, -- Belt of Colossal Rage
		{ 46041, 3 }, -- Starfall Girdle
		{ 45550, 3 }, -- Belt of the Titans
		{ 45161, 3 }, -- Girdle of Embers
		{ 45824, 3 }, -- Belt of the Singing Blade
	},
	Legs = {
		{ 45134, 1 }, -- Plated Leggings of Ruination
		{ 45982, 3 }, -- Fused Alloy Legplates
		{ 46116, 3 }, -- Conqueror's Darkruned Legplates
		{ 45841, 3 }, -- Legplates of the Violet Champion
		{ 45343, 3 }, -- Valorous Darkruned Legplates
	},
	Feet = {
		{ 45599, 1 }, -- Sabatons of Lifeless Night
		{ 45559, 3 }, -- Battlelord's Plate Boots
		{ 45501, 3 }, -- Boots of the Underdweller
		{ 45330, 3 }, -- Greaves of Iron Intensity
		{ 40591, 3 }, -- Melancholy Sabatons
	},
	Ring = {
		{ 45534, 1 }, -- Seal of the Betrayed King
		{ 45250, 1 }, -- Crazed Construct Ring
		{ 45540, 3 }, -- Bladebearer's Signet
		{ 45469, 3 }, -- Sif's Promise
		{ 45675, 3 }, -- Power Enhancing Loop
		{ 45106, 3 }, -- Strength of the Automaton
	},
	Trinket = {
		{ 45609, 1 }, -- Comet's Trail
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 40531, 3 }, -- Mark of Norgannon
		{ 45263, 3 }, -- Wrathstone
		{ 46038, 3 }, -- Dark Matter
		{ 45522, 3 }, -- Blood of the Old God
		{ 45286, 3 }, -- Pyrite Infuser
	},
	MainHand = {
		{ 46097, 1 }, -- Caress of Insanity
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 45442, 3 }, -- Sorthalis, Hammer of the Watchers
		{ 45957, 3 }, -- Furious Gladiator's Handaxe
		{ 46036, 3 }, -- Void Sabre
		{ 45266, 3 }, -- Malice
		{ 45298, 3 }, -- Razorscale Talon
	},
	OffHand = {
		{ 46097, 1 }, -- Caress of Insanity
		{ 46036, 1 }, -- Void Sabre
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 45442, 3 }, -- Sorthalis, Hammer of the Watchers
		{ 45966, 3 }, -- Furious Gladiator's Splitter
		{ 45266, 3 }, -- Malice
		{ 45298, 3 }, -- Razorscale Talon
	},
	Ranged = {
		{ 45254, 1 }, -- Sigil of the Vengeful Heart
		{ 42621, 3 }, -- Furious Gladiator's Sigil of Strife
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/unholy/dps-bis-gear-pve-phase-3
ns:RegisterBiS("DEATHKNIGHT", "Unholy", "P3", {
	Head = {
		{ 48493, 1 }, -- Koltira's Helmet of Triumph
		{ 48488, 1 }, -- Thassarian's Helmet of Triumph
		{ 48498, 3 }, -- Koltira's Helmet of Triumph
		{ 48483, 3 }, -- Thassarian's Helmet of Triumph
		{ 45472, 3 }, -- Warhelm of the Champion
		{ 46115, 3 }, -- Conqueror's Darkruned Helmet
	},
	Neck = {
		{ 47458, 1 }, -- The Executioner's Vice
		{ 47110, 1 }, -- The Executioner's Malice
		{ 45459, 3 }, -- Frigid Strength of Hodir
		{ 47297, 3 }, -- The Executioner's Vice
		{ 47105, 3 }, -- The Executioner's Malice
		{ 46040, 3 }, -- Strength of the Heavens
	},
	Shoulder = {
		{ 48495, 1 }, -- Koltira's Shoulderplates of Triumph
		{ 48486, 1 }, -- Thassarian's Shoulderplates of Triumph
		{ 48496, 3 }, -- Koltira's Shoulderplates of Triumph
		{ 48485, 3 }, -- Thassarian's Shoulderplates of Triumph
		{ 46117, 3 }, -- Conqueror's Darkruned Shoulderplates
		{ 46037, 3 }, -- Shoulderplates of the Celestial Watch
	},
	Back = {
		{ 47548, 1 }, -- Garrosh's Rage
		{ 47547, 1 }, -- Varian's Furor
		{ 48669, 3 }, -- Cloak of the Triumphant Combatant
		{ 48674, 3 }, -- Cloak of the Victorious Combatant
		{ 47481, 3 }, -- Might of the Nerub
		{ 47192, 3 }, -- Strength of the Nerub
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 46320, 3 }, -- Drape of the Skyherald
	},
	Chest = {
		{ 48491, 1 }, -- Koltira's Battleplate of Triumph
		{ 48490, 1 }, -- Thassarian's Battleplate of Triumph
		{ 48500, 3 }, -- Koltira's Battleplate of Triumph
		{ 48481, 3 }, -- Thassarian's Battleplate of Triumph
		{ 47449, 3 }, -- Chestplate of the Frostwolf Hero
		{ 47086, 3 }, -- Chestplate of the Frostborn Hero
		{ 46111, 3 }, -- Conqueror's Darkruned Battleplate
	},
	Wrist = {
		{ 45663, 1 }, -- Armbands of Bedlam
		{ 47414, 3 }, -- Boneshatter Vambraces
		{ 46967, 3 }, -- Boneshatter Armplates
		{ 48008, 3 }, -- Armplates of the Nether Lord
		{ 47935, 3 }, -- Armguards of the Nether Lord
		{ 47573, 3 }, -- Titanium Spikeguards
	},
	Hands = {
		{ 48492, 1 }, -- Koltira's Gauntlets of Triumph
		{ 48499, 3 }, -- Koltira's Gauntlets of Triumph
		{ 48482, 3 }, -- Thassarian's Gauntlets of Triumph
		{ 47492, 3 }, -- Gauntlets of Bitter Reprisal
		{ 47240, 3 }, -- Gloves of Bitter Reprisal
		{ 46113, 3 }, -- Conqueror's Darkruned Gauntlets
	},
	Waist = {
		{ 47429, 1 }, -- Bloodbath Girdle
		{ 47002, 1 }, -- Bloodbath Belt
		{ 45241, 3 }, -- Belt of Colossal Rage
		{ 47998, 3 }, -- Belt of the Impaler
		{ 47925, 3 }, -- Girdle of the Impaler
		{ 46041, 3 }, -- Starfall Girdle
	},
	Legs = {
		{ 47465, 1 }, -- Legplates of Ascension
		{ 47132, 1 }, -- Legguards of Ascension
		{ 45134, 3 }, -- Plated Leggings of Ruination
		{ 48494, 3 }, -- Koltira's Legplates of Triumph
		{ 48487, 3 }, -- Thassarian's Legplates of Triumph
		{ 48497, 3 }, -- Koltira's Legplates of Triumph
		{ 48484, 3 }, -- Thassarian's Legplates of Triumph
		{ 45982, 3 }, -- Fused Alloy Legplates
	},
	Feet = {
		{ 45599, 1 }, -- Sabatons of Lifeless Night
		{ 47473, 3 }, -- Greaves of the Saronite Citadel
		{ 47154, 3 }, -- Greaves of the 7th Legion
		{ 47312, 3 }, -- Greaves of the Saronite Citadel
		{ 47150, 3 }, -- Greaves of the 7th Legion
		{ 45559, 3 }, -- Battlelord's Plate Boots
	},
	Ring = {
		{ 47413, 1 }, -- Ring of the Violent Temperament
		{ 46966, 1 }, -- Band of the Violent Temperment
		{ 47993, 1 }, -- Gormok's Band
		{ 47920, 1 }, -- Carnivorous Band
		{ 45534, 3 }, -- Seal of the Betrayed King
		{ 47252, 3 }, -- Ring of the Violent Temperament
		{ 46959, 3 }, -- Band of the Violent Temperment
		{ 45608, 3 }, -- Brann's Signet Ring
	},
	Trinket = {
		{ 47464, 1 }, -- Death's Choice
		{ 47131, 1 }, -- Death's Verdict
		{ 47303, 1 }, -- Death's Choice
		{ 47115, 1 }, -- Death's Verdict
		{ 45609, 1 }, -- Comet's Trail
		{ 42987, 3 }, -- Darkmoon Card: Greatness
		{ 46038, 3 }, -- Dark Matter
	},
	MainHand = {
		{ 47475, 1 }, -- Hellscream Slicer
		{ 47156, 1 }, -- Stormpike Cleaver
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 47526, 3 }, -- Remorseless
		{ 48513, 3 }, -- Relentless Gladiator's Longblade
		{ 46097, 3 }, -- Caress of Insanity
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 48050, 3 }, -- Blackhorn Bludgeon
		{ 47973, 3 }, -- The Grinder
	},
	OffHand = {
		{ 47528, 1 }, -- Cudgel of the Damned
		{ 47526, 1 }, -- Remorseless
		{ 47475, 3 }, -- Hellscream Slicer
		{ 47156, 3 }, -- Stormpike Cleaver
		{ 48513, 3 }, -- Relentless Gladiator's Longblade
		{ 47427, 3 }, -- Blood Fury
		{ 47001, 3 }, -- Lionhead Slasher
		{ 46097, 3 }, -- Caress of Insanity
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 48050, 3 }, -- Blackhorn Bludgeon
		{ 47973, 3 }, -- The Grinder
	},
	Ranged = {
		{ 47673, 1 }, -- Sigil of Virulence
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/death-knight/unholy/dps-bis-gear-pve-phase-4
ns:RegisterBiS("DEATHKNIGHT", "Unholy", "P4", {
	Head = {
		{ 51312, 1 }, -- Sanctified Scourgelord Helmet
		{ 50712, 1 }, -- Landsoul's Horned Greathelm
		{ 50072, 3 }, -- Landsoul's Horned Greathelm
		{ 51127, 3 }, -- Sanctified Scourgelord Helmet
		{ 48493, 3 }, -- Koltira's Helmet of Triumph
		{ 48488, 3 }, -- Thassarian's Helmet of Triumph
	},
	Neck = {
		{ 50647, 1 }, -- Ahn'kahar Onyx Neckguard
		{ 51842, 1 }, -- Collar of Haughty Disdain
		{ 50728, 3 }, -- Lana'thel's Chain of Flagellation
		{ 47458, 3 }, -- The Executioner's Vice
		{ 47110, 3 }, -- The Executioner's Malice
	},
	Shoulder = {
		{ 51314, 1 }, -- Sanctified Scourgelord Shoulderplates
		{ 50674, 1 }, -- Raging Behemoth's Shoulderplates
		{ 50020, 3 }, -- Raging Behemoth's Shoulderplates
		{ 51125, 3 }, -- Sanctified Scourgelord Shoulderplates
		{ 48495, 3 }, -- Koltira's Shoulderplates of Triumph
		{ 48486, 3 }, -- Thassarian's Shoulderplates of Triumph
	},
	Back = {
		{ 50677, 1 }, -- Winding Sheet
		{ 50019, 3 }, -- Winding Sheet
		{ 51912, 3 }, -- Saronite Gargoyle Cloak
		{ 47548, 3 }, -- Garrosh's Rage
		{ 47547, 3 }, -- Varian's Furor
	},
	Chest = {
		{ 51310, 1 }, -- Sanctified Scourgelord Battleplate
		{ 50606, 1 }, -- Gendarme's Cuirass
		{ 51902, 3 }, -- Blade-Scored Carapace
		{ 51129, 3 }, -- Sanctified Scourgelord Battleplate
		{ 48491, 3 }, -- Koltira's Battleplate of Triumph
		{ 48490, 3 }, -- Thassarian's Battleplate of Triumph
	},
	Wrist = {
		{ 50659, 1 }, -- Polar Bear Claw Bracers
		{ 51832, 1 }, -- Taiga Bindings
		{ 50002, 3 }, -- Polar Bear Claw Bracers
		{ 45663, 3 }, -- Armbands of Bedlam
		{ 47414, 3 }, -- Boneshatter Vambraces
		{ 46967, 3 }, -- Boneshatter Armplates
	},
	Hands = {
		{ 51311, 1 }, -- Sanctified Scourgelord Gauntlets
		{ 50690, 1 }, -- Fleshrending Gauntlets
		{ 50037, 3 }, -- Fleshrending Gauntlets
		{ 51128, 3 }, -- Sanctified Scourgelord Gauntlets
		{ 48492, 3 }, -- Koltira's Gauntlets of Triumph
	},
	Waist = {
		{ 50620, 1 }, -- Coldwraith Links
		{ 51821, 3 }, -- Etched Dragonbone Girdle
		{ 51879, 3 }, -- Flesh-Shaper's Gurney Strap
		{ 50987, 3 }, -- Malevolent Girdle
		{ 50187, 3 }, -- Coldwraith Links
		{ 47429, 3 }, -- Bloodbath Girdle
		{ 47002, 3 }, -- Bloodbath Belt
		{ 45241, 3 }, -- Belt of Colossal Rage
	},
	Legs = {
		{ 50624, 1 }, -- Scourge Reaver's Legplates
		{ 50192, 3 }, -- Scourge Reaver's Legplates
		{ 51854, 3 }, -- Battle-Maiden's Legguards
		{ 47465, 3 }, -- Legplates of Ascension
		{ 47132, 3 }, -- Legguards of Ascension
		{ 45134, 3 }, -- Plated Leggings of Ruination
		{ 48494, 3 }, -- Koltira's Legplates of Triumph
		{ 48487, 3 }, -- Thassarian's Legplates of Triumph
	},
	Feet = {
		{ 50639, 1 }, -- Blood-Soaked Saronite Stompers
		{ 49983, 3 }, -- Blood-Soaked Saronite Stompers
		{ 51915, 3 }, -- Bone Drake's Enameled Boots
		{ 47473, 3 }, -- Greaves of the Saronite Citadel
		{ 47154, 3 }, -- Greaves of the 7th Legion
	},
	Ring = {
		{ 52572, 1 }, -- Ashen Band of Endless Might
		{ 50693, 1 }, -- Might of Blight
		{ 50657, 1 }, -- Skeleton Lord's Circle
		{ 51855, 3 }, -- Thrice Fanged Signet
		{ 50453, 3 }, -- Ring of Rotting Sinew
		{ 47413, 3 }, -- Ring of the Violent Temperament
		{ 46966, 3 }, -- Band of the Violent Temperment
	},
	Trinket = {
		{ 50363, 1 }, -- Deathbringer's Will
		{ 47464, 1 }, -- Death's Choice
		{ 47131, 1 }, -- Death's Verdict
		{ 47303, 1 }, -- Death's Choice
		{ 47115, 1 }, -- Death's Verdict
		{ 45609, 1 }, -- Comet's Trail
		{ 50343, 3 }, -- Whispering Fanged Skull
		{ 50355, 3 }, -- Herkuml War Token
		{ 42987, 3 }, -- Darkmoon Card: Greatness
	},
	TwoHand = {
		{ 49623, 1 }, -- Shadowmourne
	},
	MainHand = {
		{ 50737, 1 }, -- Havoc's Call, Blade of Lordaeron Kings
		{ 50672, 3 }, -- Bloodvenom Blade
		{ 51893, 3 }, -- Gutbuster
		{ 51916, 3 }, -- Frost Giant's Cleaver
		{ 47475, 3 }, -- Hellscream Slicer
		{ 47156, 3 }, -- Stormpike Cleaver
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 47526, 3 }, -- Remorseless
	},
	OffHand = {
		{ 50737, 1 }, -- Havoc's Call, Blade of Lordaeron Kings
		{ 50708, 3 }, -- Last Word
		{ 50672, 3 }, -- Bloodvenom Blade
		{ 50738, 3 }, -- Mithrios, Bronzebeard's Legacy
		{ 50654, 3 }, -- Scourgeborne Waraxe
		{ 51893, 3 }, -- Gutbuster
		{ 51916, 3 }, -- Frost Giant's Cleaver
		{ 47475, 3 }, -- Hellscream Slicer
		{ 47156, 3 }, -- Stormpike Cleaver
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 47526, 3 }, -- Remorseless
	},
	Ranged = {
		{ 50459, 1 }, -- Sigil of the Hanged Man
		{ 47673, 1 }, -- Sigil of Virulence
	},
})
