-- GENERATED by scripts/build_data.py -- do not edit by hand; the next build
-- overwrites it. Sources: AzerothCore world DB, the realm client's DBC files,
-- and the Wowhead guides listed in scripts/guides.json.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/rogue/assassination/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("ROGUE", "Assassination", "PreRaid", {
	Head = {
		{ 42550, 1 }, -- Weakness Spectralizers
		{ 37293, 1 }, -- Mask of the Watcher
		{ 34244, 3 }, -- Duplicitous Guise
		{ 32235, 3 }, -- Cursed Vision of Sargeras
		{ 34353, 3 }, -- Quad Deathblow X44 Goggles
		{ 31027, 3 }, -- Slayer's Helm
		{ 43403, 3 }, -- Shroud of Darkness
	},
	Neck = {
		{ 40678, 1 }, -- Pendant of the Outcast Hero
		{ 42645, 3 }, -- Titanium Impact Choker
		{ 37861, 3 }, -- Necklace of Arcane Spheres
		{ 37096, 3 }, -- Necklace of the Chrono-Lord
	},
	Shoulder = {
		{ 37139, 1 }, -- Spaulders of the Careless Thief
		{ 43481, 3 }, -- Trollwoven Spaulders
		{ 34195, 3 }, -- Shoulderpads of Vehemence
	},
	Back = {
		{ 38614, 1 }, -- Embrace of Sorrow
		{ 43406, 3 }, -- Cloak of the Gushing Wound
		{ 34241, 3 }, -- Cloak of Unforgivable Sin
		{ 43566, 3 }, -- Ice Striker's Cloak
		{ 37840, 3 }, -- Shroud of Reverberation
	},
	Chest = {
		{ 39558, 1 }, -- Heroes' Bonescythe Breastplate
		{ 37219, 3 }, -- Custodian's Chestpiece
		{ 34369, 3 }, -- Carapace of Sun and Shadow
		{ 44303, 3 }, -- Darkheart Chestguard
	},
	Wrist = {
		{ 44203, 1 }, -- Dragonfriend Bracers
		{ 37366, 3 }, -- Drake-Champion's Bracers
		{ 37853, 3 }, -- Advanced Tooled-Leather Bands
		{ 34448, 3 }, -- Slayer's Bracers
	},
	Hands = {
		{ 39560, 1 }, -- Heroes' Bonescythe Gauntlets
		{ 37409, 3 }, -- Gilt-Edged Leather Gauntlets
		{ 34370, 3 }, -- Gloves of Immortal Dusk
		{ 37846, 3 }, -- Charged-Bolt Grips
	},
	Waist = {
		{ 40694, 1 }, -- Jorach's Crocolisk Skin Belt
		{ 37194, 3 }, -- Sharp-Barbed Leather Belt
		{ 43484, 3 }, -- Trollwoven Girdle
		{ 37243, 3 }, -- Treasure Seeker's Belt
		{ 34558, 3 }, -- Slayer's Belt
	},
	Legs = {
		{ 37644, 1 }, -- Gored Hide Legguards
		{ 44179, 3 }, -- Mind-Expanding Leggings
		{ 34188, 3 }, -- Leggings of the Immortal Night
	},
	Feet = {
		{ 44297, 1 }, -- Boots of the Neverending Path
		{ 34575, 3 }, -- Slayer's Boots
		{ 37666, 3 }, -- Boots of the Whirling Mist
	},
	Ring = {
		{ 40586, 1 }, -- Band of the Kirin Tor
		{ 37642, 1 }, -- Hemorrhaging Circle
		{ 43251, 3 }, -- Ring of Scarlet Shadows
		{ 44308, 3 }, -- Signet of Edward the Odd
		{ 42642, 3 }, -- Titanium Impact Band
		{ 37685, 3 }, -- Mobius Band
	},
	Trinket = {
		{ 44253, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 34427, 3 }, -- Blackened Naaru Sliver
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
		{ 43573, 3 }, -- Tears of Bitter Anguish
	},
	MainHand = {
		{ 37667, 1 }, -- The Fleshshaper
		{ 37856, 1 }, -- Librarian's Paper Cutter
		{ 44310, 3 }, -- Namlak's Supernumerary Sticker
		{ 44193, 3 }, -- Broken Stalactite
		{ 42435, 3 }, -- Titansteel Shanker
		{ 37181, 3 }, -- Dagger of Betrayal
		{ 37037, 3 }, -- Ritualistic Athame
		{ 44166, 3 }, -- Lightblade Rivener
		{ 36944, 3 }, -- Lifeblade of Belgaristrasz
	},
	Ranged = {
		{ 37191, 1 }, -- Drake-Mounted Crossbow
		{ 44504, 1 }, -- Nesingwary 4000
		{ 43612, 1 }, -- Spineslicer
		{ 43284, 3 }, -- Amanitar Skullbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/assassination/dps-bis-gear-pve-phase-1
ns:RegisterBiS("ROGUE", "Assassination", "P1", {
	Head = {
		{ 40499, 1 }, -- Valorous Bonescythe Helmet
		{ 40329, 3 }, -- Hood of the Exodus
		{ 39561, 3 }, -- Heroes' Bonescythe Helmet
		{ 39399, 3 }, -- Helm of the Vast Legions
		{ 37293, 3 }, -- Mask of the Watcher
		{ 42550, 3 }, -- Weakness Spectralizers
		{ 40296, 3 }, -- Cover of Silence
	},
	Neck = {
		{ 44664, 1 }, -- Favor of the Dragon Queen
		{ 40369, 3 }, -- Icy Blast Amulet
		{ 39146, 3 }, -- Collar of Dissolution
		{ 39421, 3 }, -- Gem of Imprisoned Vassals
		{ 40065, 3 }, -- Fool's Trial
		{ 44659, 3 }, -- Pendant of the Dragonsworn
	},
	Shoulder = {
		{ 40502, 1 }, -- Valorous Bonescythe Pauldrons
		{ 40437, 3 }, -- Concealment Shoulderpads
		{ 40305, 3 }, -- Spaulders of Egotism
		{ 39237, 3 }, -- Spaulders of Resumed Battle
		{ 39565, 3 }, -- Heroes' Bonescythe Pauldrons
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 40721, 3 }, -- Hammerhead Sharkskin Cloak
		{ 40250, 3 }, -- Aged Winter Cloak
		{ 39404, 3 }, -- Cloak of Mastery
		{ 39297, 3 }, -- Cloak of Darkening
		{ 43566, 3 }, -- Ice Striker's Cloak
	},
	Chest = {
		{ 40539, 1 }, -- Chestguard of the Recluse
		{ 40495, 3 }, -- Valorous Bonescythe Breastplate
		{ 40277, 3 }, -- Tunic of Indulgence
		{ 39386, 3 }, -- Tunic of Dislocation
		{ 40319, 3 }, -- Chestpiece of Suspicion
		{ 37219, 3 }, -- Custodian's Chestpiece
		{ 39558, 3 }, -- Heroes' Bonescythe Breastplate
		{ 43990, 3 }, -- Blade-Scarred Tunic
	},
	Wrist = {
		{ 40186, 1 }, -- Thrusting Bands
		{ 34448, 1 }, -- Slayer's Bracers
		{ 39765, 3 }, -- Sinner's Bindings
		{ 40738, 3 }, -- Wristwraps of the Cutthroat
		{ 44203, 3 }, -- Dragonfriend Bracers
		{ 39247, 3 }, -- Cuffs of Dark Shadows
	},
	Hands = {
		{ 40496, 1 }, -- Valorous Bonescythe Gauntlets
		{ 40541, 3 }, -- Frosted Adroit Handguards
		{ 39727, 3 }, -- Dislocating Handguards
		{ 40362, 3 }, -- Gloves of Fast Reactions
		{ 39299, 3 }, -- Rapid Attack Gloves
		{ 39560, 3 }, -- Heroes' Bonescythe Gauntlets
	},
	Waist = {
		{ 40205, 1 }, -- Stalk-Skin Belt
		{ 34558, 1 }, -- Slayer's Belt
		{ 40694, 3 }, -- Jorach's Crocolisk Skin Belt
		{ 40260, 3 }, -- Belt of the Tortured
		{ 37194, 3 }, -- Sharp-Barbed Leather Belt
		{ 43484, 3 }, -- Trollwoven Girdle
		{ 39279, 3 }, -- Blistered Belt of Decay
	},
	Legs = {
		{ 44011, 1 }, -- Leggings of the Honored
		{ 39224, 3 }, -- Leggings of Discord
		{ 39761, 3 }, -- Infectious Skitterer Leggings
		{ 40500, 3 }, -- Valorous Bonescythe Legplates
		{ 40333, 3 }, -- Leggings of Fleeting Moments
		{ 39564, 3 }, -- Heroes' Bonescythe Legplates
		{ 37644, 3 }, -- Gored Hide Legguards
	},
	Feet = {
		{ 39701, 1 }, -- Dawnwalkers
		{ 40243, 3 }, -- Footwraps of Vile Deceit
		{ 40748, 3 }, -- Boots of Captain Ellis
		{ 39196, 3 }, -- Boots of the Worshiper
		{ 44297, 3 }, -- Boots of the Neverending Path
	},
	Ring = {
		{ 40474, 1 }, -- Surge Needle Ring
		{ 40717, 3 }, -- Ring of Invincibility
		{ 40074, 3 }, -- Strong-Handed Ring
		{ 37642, 3 }, -- Hemorrhaging Circle
		{ 39277, 3 }, -- Sealing Ring of Grobbulus
		{ 40586, 3 }, -- Band of the Kirin Tor
		{ 43993, 3 }, -- Greatring of Collision
	},
	Trinket = {
		{ 44253, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 40431, 3 }, -- Fury of the Five Flights
		{ 40531, 3 }, -- Mark of Norgannon
		{ 34427, 3 }, -- Blackened Naaru Sliver
		{ 40371, 3 }, -- Bandit's Insignia
		{ 39257, 3 }, -- Loatheb's Shadow
		{ 40256, 3 }, -- Grim Toll
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
	},
	MainHand = {
		{ 40386, 1 }, -- Sinister Revenge
		{ 39714, 1 }, -- Webbed Death
		{ 40281, 3 }, -- Twilight Mist
		{ 40368, 3 }, -- Murder
		{ 37856, 3 }, -- Librarian's Paper Cutter
		{ 39420, 3 }, -- Anarchy
		{ 39140, 3 }, -- Knife of Incision
		{ 39427, 3 }, -- Omen of Ruin
	},
	Ranged = {
		{ 40385, 1 }, -- Envoy of Mortality
		{ 40190, 3 }, -- Spinning Fate
		{ 40346, 3 }, -- Final Voyage
		{ 40265, 3 }, -- Arrowsong
		{ 39419, 3 }, -- Nerubian Conquerer
		{ 39296, 3 }, -- Accursed Bow of the Elite
		{ 37191, 3 }, -- Drake-Mounted Crossbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/assassination/dps-bis-gear-pve-phase-2
ns:RegisterBiS("ROGUE", "Assassination", "P2", {
	Head = {
		{ 46125, 1 }, -- Conqueror's Terrorblade Helmet
		{ 45523, 3 }, -- Garona's Guise
		{ 45993, 3 }, -- Mimiron's Flight Goggles
		{ 45893, 3 }, -- Guise of the Midgard Serpent
		{ 45398, 3 }, -- Valorous Terrorblade Helmet
		{ 40499, 3 }, -- Valorous Bonescythe Helmet
	},
	Neck = {
		{ 45517, 1 }, -- Pendulum of Infinity
		{ 45945, 3 }, -- Seed of Budding Carnage
		{ 45480, 3 }, -- Nymph Heart Charm
		{ 45820, 3 }, -- Broach of the Wailing Night
		{ 44664, 3 }, -- Favor of the Dragon Queen
	},
	Shoulder = {
		{ 45245, 1 }, -- Shoulderpads of the Intruder
		{ 46127, 3 }, -- Conqueror's Terrorblade Pauldrons
		{ 45265, 3 }, -- Shoulderpads of the Monolith
		{ 45400, 3 }, -- Valorous Terrorblade Pauldrons
		{ 45677, 3 }, -- Treacherous Shoulderpads
		{ 40502, 3 }, -- Valorous Bonescythe Pauldrons
	},
	Back = {
		{ 45461, 1 }, -- Drape of Icy Intent
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 45224, 3 }, -- Drape of the Lithe
		{ 45704, 3 }, -- Shawl of the Shattered Giant
		{ 45873, 3 }, -- Winter's Frigid Embrace
		{ 40403, 3 }, -- Drape of the Deadly Foe
	},
	Chest = {
		{ 45473, 1 }, -- Embrace of the Gladiator
		{ 46123, 3 }, -- Conqueror's Terrorblade Breastplate
		{ 45396, 3 }, -- Valorous Terrorblade Breastplate
		{ 40539, 3 }, -- Chestguard of the Recluse
		{ 45453, 3 }, -- Winter's Icy Embrace
	},
	Wrist = {
		{ 45611, 1 }, -- Solar Bindings
		{ 45869, 3 }, -- Fluxing Energy Coils
		{ 45108, 3 }, -- Mechanist's Bindings
		{ 40186, 3 }, -- Thrusting Bands
		{ 39765, 3 }, -- Sinner's Bindings
	},
	Hands = {
		{ 46124, 1 }, -- Conqueror's Terrorblade Gauntlets
		{ 46043, 3 }, -- Gloves of the Endless Dark
		{ 40541, 3 }, -- Frosted Adroit Handguards
		{ 45397, 3 }, -- Valorous Terrorblade Gauntlets
		{ 45325, 3 }, -- Gloves of the Stonereaper
		{ 45838, 3 }, -- Gloves of the Blind Stalker
	},
	Waist = {
		{ 46095, 1 }, -- Soul-Devouring Cinch
		{ 45829, 3 }, -- Belt of the Twilight Assassin
		{ 45555, 3 }, -- Death-warmed Belt
		{ 45491, 3 }, -- Waistguard of the Creator
		{ 45709, 3 }, -- Nimble Climber's Belt
		{ 45547, 3 }, -- Relic Hunter's Cord
		{ 40260, 3 }, -- Belt of the Tortured
		{ 40205, 3 }, -- Stalk-Skin Belt
	},
	Legs = {
		{ 45536, 1 }, -- Legguards of Cunning Deception
		{ 45141, 3 }, -- Proto-hide Leggings
		{ 45846, 3 }, -- Leggings of Wavering Shadow
		{ 46126, 3 }, -- Conqueror's Terrorblade Legplates
		{ 44011, 3 }, -- Leggings of the Honored
		{ 45399, 3 }, -- Valorous Terrorblade Legplates
	},
	Feet = {
		{ 45564, 1 }, -- Footpads of Silence
		{ 45232, 3 }, -- Runed Ironhide Boots
		{ 45162, 3 }, -- Flamestalker Boots
		{ 45302, 3 }, -- Treads of the Invader
		{ 39701, 3 }, -- Dawnwalkers
	},
	Ring = {
		{ 46048, 1 }, -- Band of Lights
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 45456, 3 }, -- Loop of the Agile
		{ 46322, 3 }, -- Brann's Sealing Ring
		{ 45525, 3 }, -- Godbane Signet
		{ 45503, 3 }, -- Metallic Loop of the Sufferer
		{ 45157, 3 }, -- Cindershard Ring
		{ 40474, 3 }, -- Surge Needle Ring
		{ 45303, 3 }, -- Band of Draconic Guile
	},
	Trinket = {
		{ 45609, 1 }, -- Comet's Trail
		{ 46038, 1 }, -- Dark Matter
		{ 45522, 3 }, -- Blood of the Old God
		{ 45286, 3 }, -- Pyrite Infuser
		{ 45931, 3 }, -- Mjolnir Runestone
		{ 45263, 3 }, -- Wrathstone
		{ 44253, 3 }, -- Darkmoon Card: Greatness
		{ 40684, 3 }, -- Mirror of Truth
	},
	MainHand = {
		{ 45484, 1 }, -- Bladetwister
		{ 45930, 3 }, -- Combatant's Bootblade
		{ 45607, 3 }, -- Fang of Oblivion
		{ 45246, 3 }, -- Golem-Shard Sticker
		{ 45448, 3 }, -- Perilous Bite
		{ 46024, 3 }, -- Kingsbane
		{ 45605, 3 }, -- Daschal's Bite
		{ 45958, 3 }, -- Furious Gladiator's Spike
		{ 46011, 3 }, -- Shadowbite
		{ 40386, 3 }, -- Sinister Revenge
		{ 39714, 3 }, -- Webbed Death
	},
	OffHand = {
		{ 45962, 3 }, -- Furious Gladiator's Dirk
	},
	Ranged = {
		{ 45570, 1 }, -- Skyforge Crossbow
		{ 45296, 3 }, -- Twirling Blades
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 45086, 3 }, -- Rising Sun
		{ 45327, 3 }, -- Siren's Cry
		{ 45261, 3 }, -- Giant's Bane
		{ 46342, 3 }, -- Golemheart Longbow
		{ 46018, 3 }, -- Deliverance
		{ 40385, 3 }, -- Envoy of Mortality
		{ 40190, 3 }, -- Spinning Fate
		{ 45872, 3 }, -- Avalanche
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/assassination/dps-bis-gear-pve-phase-3
ns:RegisterBiS("ROGUE", "Assassination", "P3", {
	Head = {
		{ 48230, 1 }, -- VanCleef's Helmet of Triumph
		{ 48235, 1 }, -- Garona's Helmet of Triumph
		{ 48225, 3 }, -- VanCleef's Helmet of Triumph
		{ 48240, 3 }, -- Garona's Helmet of Triumph
		{ 49477, 3 }, -- Bloodfang Hood
		{ 45993, 3 }, -- Mimiron's Flight Goggles
		{ 48218, 3 }, -- VanCleef's Helmet of Conquest
		{ 48245, 3 }, -- Garona's Helmet of Conquest
		{ 46125, 3 }, -- Conqueror's Terrorblade Helmet
		{ 47689, 3 }, -- Hood of Lethal Intent
		{ 47688, 3 }, -- Mask of Lethal Intent
	},
	Neck = {
		{ 47060, 1 }, -- Charge of the Demon Lord
		{ 47433, 1 }, -- Charge of the Eredar
		{ 45517, 3 }, -- Pendulum of Infinity
		{ 47043, 3 }, -- Charge of the Demon Lord
		{ 47272, 3 }, -- Charge of the Eredar
		{ 47915, 3 }, -- Collar of Ceaseless Torment
		{ 47988, 3 }, -- Collar of Unending Torment
		{ 49485, 3 }, -- Sparkling Onyxia Tooth Pendant
		{ 45945, 3 }, -- Seed of Budding Carnage
		{ 45480, 3 }, -- Nymph Heart Charm
		{ 49314, 3 }, -- Sparkling Onyxia Tooth Pendant
		{ 47607, 3 }, -- Collar of Ceaseless Torment
		{ 47849, 3 }, -- Collar of Unending Torment
	},
	Shoulder = {
		{ 48228, 1 }, -- VanCleef's Pauldrons of Triumph
		{ 48237, 1 }, -- Garona's Pauldrons of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
		{ 48227, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48238, 3 }, -- Garona's Pauldrons of Triumph
		{ 47972, 3 }, -- Spaulders of the Snow Bandit
		{ 48049, 3 }, -- Shoulderpads of the Snow Bandit
		{ 47708, 3 }, -- Duskstalker Shoulderpads
		{ 47709, 3 }, -- Duskstalker Pauldrons
		{ 48221, 3 }, -- VanCleef's Pauldrons of Conquest
		{ 48247, 3 }, -- Garona's Pauldrons of Conquest
		{ 47832, 3 }, -- Spaulders of the Snow Bandit
		{ 47904, 3 }, -- Shoulderpads of the Snow Bandit
		{ 46127, 3 }, -- Conqueror's Terrorblade Pauldrons
	},
	Back = {
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 46971, 3 }, -- Drape of the Untamed Predator
		{ 47418, 3 }, -- Cloak of the Untamed Predator
		{ 48673, 3 }, -- Cloak of the Silver Covenant
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 45461, 3 }, -- Drape of Icy Intent
		{ 46970, 3 }, -- Drape of the Untamed Predator
		{ 47257, 3 }, -- Cloak of the Untamed Predator
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 45224, 3 }, -- Drape of the Lithe
		{ 45873, 3 }, -- Winter's Frigid Embrace
		{ 45704, 3 }, -- Shawl of the Shattered Giant
	},
	Chest = {
		{ 48232, 1 }, -- VanCleef's Breastplate of Triumph
		{ 48233, 1 }, -- Garona's Breastplate of Triumph
		{ 47004, 3 }, -- Cuirass of Calamitous Fate
		{ 47431, 3 }, -- Vest of Calamitous Fate
		{ 45473, 3 }, -- Embrace of the Gladiator
		{ 47000, 3 }, -- Cuirass of Calamitous Fate
		{ 47270, 3 }, -- Vest of Calamitous Fate
		{ 47954, 3 }, -- Armor of Shifting Shadows
		{ 48026, 3 }, -- Vest of Shifting Shadows
		{ 48223, 3 }, -- VanCleef's Breastplate of Triumph
		{ 48242, 3 }, -- Garona's Breastplate of Triumph
		{ 47599, 3 }, -- Knightbane Carapace
		{ 47600, 3 }, -- Knightbane Carapace
		{ 48219, 3 }, -- VanCleef's Breastplate of Conquest
		{ 48243, 3 }, -- Garona's Breastplate of Conquest
		{ 46123, 3 }, -- Conqueror's Terrorblade Breastplate
	},
	Wrist = {
		{ 47155, 1 }, -- Bracers of Dark Determination
		{ 47474, 1 }, -- Armbands of Dark Determination
		{ 45611, 3 }, -- Solar Bindings
		{ 47151, 3 }, -- Bracers of Dark Determination
		{ 47313, 3 }, -- Armbands of Dark Determination
		{ 47581, 3 }, -- Bracers of Swift Death
		{ 47582, 3 }, -- Bracers of Swift Death
		{ 45869, 3 }, -- Fluxing Energy Coils
		{ 45108, 3 }, -- Mechanist's Bindings
	},
	Hands = {
		{ 48231, 1 }, -- VanCleef's Gauntlets of Triumph
		{ 48234, 1 }, -- Garona's Gauntlets of Triumph
		{ 48224, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48241, 3 }, -- Garona's Gauntlets of Triumph
		{ 47945, 3 }, -- Gloves of the Silver Assassin
		{ 48017, 3 }, -- Sunreaver Assassin's Gloves
		{ 46043, 3 }, -- Gloves of the Endless Dark
		{ 46124, 3 }, -- Conqueror's Terrorblade Gauntlets
		{ 48222, 3 }, -- VanCleef's Gauntlets of Conquest
		{ 48244, 3 }, -- Garona's Gauntlets of Conquest
		{ 47719, 3 }, -- Gloves of the Silver Assassin
		{ 47878, 3 }, -- Sunreaver Assassin's Gloves
	},
	Waist = {
		{ 47112, 1 }, -- Belt of the Merciless Killer
		{ 47460, 1 }, -- Belt of the Pitiless Killer
		{ 46095, 3 }, -- Soul-Devouring Cinch
		{ 47107, 3 }, -- Belt of the Merciless Killer
		{ 47299, 3 }, -- Belt of the Pitiless Killer
		{ 45829, 3 }, -- Belt of the Twilight Assassin
		{ 45555, 3 }, -- Death-warmed Belt
		{ 45491, 3 }, -- Waistguard of the Creator
		{ 45709, 3 }, -- Nimble Climber's Belt
		{ 45547, 3 }, -- Relic Hunter's Cord
	},
	Legs = {
		{ 46975, 1 }, -- Leggings of the Broken Beast
		{ 47420, 1 }, -- Legwraps of the Broken Beast
		{ 48229, 3 }, -- VanCleef's Legplates of Triumph
		{ 48236, 3 }, -- Garona's Legplates of Triumph
		{ 45536, 3 }, -- Legguards of Cunning Deception
		{ 46974, 3 }, -- Leggings of the Broken Beast
		{ 47259, 3 }, -- Legwraps of the Broken Beast
		{ 48226, 3 }, -- VanCleef's Legplates of Triumph
		{ 48239, 3 }, -- Garona's Legplates of Triumph
		{ 46126, 3 }, -- Conqueror's Terrorblade Legplates
		{ 45846, 3 }, -- Leggings of Wavering Shadow
		{ 48220, 3 }, -- VanCleef's Legplates of Conquest
		{ 48246, 3 }, -- Garona's Legplates of Conquest
	},
	Feet = {
		{ 47077, 1 }, -- Treads of the Icewalker
		{ 47445, 1 }, -- Icewalker Treads
		{ 47919, 3 }, -- Acidmaw Boots
		{ 47992, 3 }, -- Acidmaw Treads
		{ 47071, 3 }, -- Treads of the Icewalker
		{ 47284, 3 }, -- Icewalker Treads
		{ 47608, 3 }, -- Acidmaw Boots
		{ 47853, 3 }, -- Acidmaw Treads
		{ 45564, 3 }, -- Footpads of Silence
		{ 45162, 3 }, -- Flamestalker Boots
		{ 45302, 3 }, -- Treads of the Invader
	},
	Ring = {
		{ 47075, 1 }, -- Ring of Callous Aggression
		{ 47443, 1 }, -- Band of Callous Aggression
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 47070, 3 }, -- Ring of Callous Aggression
		{ 47282, 3 }, -- Band of Callous Aggression
		{ 45456, 3 }, -- Loop of the Agile
		{ 47934, 3 }, -- Planestalker Signet
		{ 48007, 3 }, -- Planestalker Band
		{ 46048, 3 }, -- Band of Lights
		{ 47730, 3 }, -- Dexterous Brightstone Ring
		{ 46322, 3 }, -- Brann's Sealing Ring
		{ 47703, 3 }, -- Planestalker Signet
		{ 47868, 3 }, -- Planestalker Band
	},
	Trinket = {
		{ 47131, 1 }, -- Death's Verdict
		{ 47464, 1 }, -- Death's Choice
		{ 45609, 1 }, -- Comet's Trail
		{ 47115, 3 }, -- Death's Verdict
		{ 47303, 3 }, -- Death's Choice
		{ 46038, 3 }, -- Dark Matter
		{ 45522, 3 }, -- Blood of the Old God
		{ 45931, 3 }, -- Mjolnir Runestone
		{ 47734, 3 }, -- Mark of Supremacy
		{ 45286, 3 }, -- Pyrite Infuser
		{ 47948, 3 }, -- Victor's Call
		{ 48020, 3 }, -- Vengeance of the Forsaken
		{ 47725, 3 }, -- Victor's Call
		{ 47881, 3 }, -- Vengeance of the Forsaken
		{ 47214, 3 }, -- Banner of Victory
	},
	MainHand = {
		{ 46969, 1 }, -- Steel Bladebreaker
		{ 47416, 1 }, -- Stygian Bladebreaker
		{ 47113, 3 }, -- Twin Spike
		{ 47461, 3 }, -- Gouge of the Frigid Heart
		{ 45484, 3 }, -- Bladetwister
		{ 45930, 3 }, -- Combatant's Bootblade
		{ 47938, 3 }, -- Dirk of the Night Watch
		{ 48010, 3 }, -- Orcish Deathblade
		{ 45607, 3 }, -- Fang of Oblivion
		{ 46958, 3 }, -- Steel Bladebreaker
		{ 47255, 3 }, -- Stygian Bladebreaker
		{ 47953, 3 }, -- Icefall Blade
		{ 48025, 3 }, -- Nemesis Blade
		{ 47104, 3 }, -- Twin Spike
		{ 47300, 3 }, -- Gouge of the Frigid Heart
		{ 45448, 3 }, -- Perilous Bite
		{ 45246, 3 }, -- Golem-Shard Sticker
		{ 46024, 3 }, -- Kingsbane
		{ 45605, 3 }, -- Daschal's Bite
		{ 47736, 3 }, -- Icefall Blade
		{ 47886, 3 }, -- Nemesis Blade
	},
	Ranged = {
		{ 47521, 1 }, -- BRK-1000
		{ 47523, 1 }, -- Fezzik's Autocannon
		{ 47950, 3 }, -- The Diplomat
		{ 48022, 3 }, -- Widebarrel Flintlock
		{ 46995, 3 }, -- Talonstrike
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 45570, 3 }, -- Skyforge Crossbow
		{ 47975, 3 }, -- Baelgun's Heavy Crossbow
		{ 48052, 3 }, -- Darkmaw Crossbow
		{ 48711, 3 }, -- Rhok'shalla, the Shadow's Bane
		{ 48697, 3 }, -- Frenzystrike Longbow
		{ 47659, 3 }, -- Crimson Star
		{ 45296, 3 }, -- Twirling Blades
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 46994, 3 }, -- Talonstrike
		{ 47267, 3 }, -- Death's Head Crossbow
		{ 45327, 3 }, -- Siren's Cry
		{ 45261, 3 }, -- Giant's Bane
		{ 45086, 3 }, -- Rising Sun
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/assassination/dps-bis-gear-pve-phase-4
ns:RegisterBiS("ROGUE", "Assassination", "P4", {
	Head = {
		{ 51252, 1 }, -- Sanctified Shadowblade Helmet
		{ 50713, 3 }, -- Geistlord's Punishment Sack
		{ 51187, 3 }, -- Sanctified Shadowblade Helmet
		{ 51866, 3 }, -- Discarded Bag of Entrails
		{ 50073, 3 }, -- Geistlord's Punishment Sack
		{ 51013, 3 }, -- Discarded Bag of Entrails
		{ 48230, 3 }, -- VanCleef's Helmet of Triumph
		{ 48235, 3 }, -- Garona's Helmet of Triumph
		{ 51745, 3 }, -- Shadowblade Helmet
		{ 48225, 3 }, -- VanCleef's Helmet of Triumph
		{ 48240, 3 }, -- Garona's Helmet of Triumph
		{ 49477, 3 }, -- Bloodfang Hood
		{ 45993, 3 }, -- Mimiron's Flight Goggles
		{ 47689, 3 }, -- Hood of Lethal Intent
		{ 47688, 3 }, -- Mask of Lethal Intent
	},
	Neck = {
		{ 50633, 1 }, -- Sindragosa's Cruel Claw
		{ 51890, 3 }, -- Precious's Putrid Collar
		{ 50452, 3 }, -- Wodin's Lucky Necklace
		{ 51822, 3 }, -- Rimetooth Pendant
		{ 50421, 3 }, -- Sindragosa's Cruel Claw
		{ 47060, 3 }, -- Charge of the Demon Lord
		{ 47433, 3 }, -- Charge of the Eredar
		{ 45517, 3 }, -- Pendulum of Infinity
		{ 51779, 3 }, -- Rimetooth Pendant
		{ 47043, 3 }, -- Charge of the Demon Lord
		{ 47272, 3 }, -- Charge of the Eredar
		{ 49485, 3 }, -- Sparkling Onyxia Tooth Pendant
		{ 47915, 3 }, -- Collar of Ceaseless Torment
		{ 47988, 3 }, -- Collar of Unending Torment
	},
	Shoulder = {
		{ 51254, 1 }, -- Sanctified Shadowblade Pauldrons
		{ 50646, 3 }, -- Cultist's Bloodsoaked Spaulders
		{ 51185, 3 }, -- Sanctified Shadowblade Pauldrons
		{ 51830, 3 }, -- Skinned Whelp Shoulders
		{ 49987, 3 }, -- Cultist's Bloodsoaked Spaulders
		{ 48228, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48237, 3 }, -- Garona's Pauldrons of Triumph
		{ 51565, 3 }, -- Skinned Whelp Shoulders
		{ 50105, 3 }, -- Shadowblade Pauldrons
		{ 47972, 3 }, -- Spaulders of the Snow Bandit
		{ 48049, 3 }, -- Shoulderpads of the Snow Bandit
		{ 47708, 3 }, -- Duskstalker Shoulderpads
		{ 47709, 3 }, -- Duskstalker Pauldrons
		{ 48227, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48238, 3 }, -- Garona's Pauldrons of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
	},
	Back = {
		{ 50653, 1 }, -- Shadowvault Slayer's Cloak
		{ 47545, 3 }, -- Vereesa's Dexterity
		{ 47546, 3 }, -- Sylvanas' Cunning
		{ 51933, 3 }, -- Shawl of Nerubian Silk
		{ 48673, 3 }, -- Cloak of the Silver Covenant
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 49998, 3 }, -- Shadowvault Slayer's Cloak
		{ 50764, 3 }, -- Shawl of Nerubian Silk
		{ 50470, 3 }, -- Recovered Scarlet Onslaught Cape
		{ 46971, 3 }, -- Drape of the Untamed Predator
		{ 47418, 3 }, -- Cloak of the Untamed Predator
		{ 45461, 3 }, -- Drape of Icy Intent
		{ 46032, 3 }, -- Drape of the Faceless General
	},
	Chest = {
		{ 50656, 1 }, -- Ikfirus's Sack of Wonder
		{ 50001, 3 }, -- Ikfirus's Sack of Wonder
		{ 50972, 3 }, -- Shadow Seeker's Tunic
		{ 51250, 3 }, -- Sanctified Shadowblade Breastplate
		{ 51923, 3 }, -- Chestguard of the Frigid Noose
		{ 51189, 3 }, -- Sanctified Shadowblade Breastplate
		{ 47004, 3 }, -- Cuirass of Calamitous Fate
		{ 47431, 3 }, -- Vest of Calamitous Fate
		{ 48232, 3 }, -- VanCleef's Breastplate of Triumph
		{ 48233, 3 }, -- Garona's Breastplate of Triumph
		{ 50780, 3 }, -- Chestguard of the Frigid Noose
		{ 45473, 3 }, -- Embrace of the Gladiator
		{ 50087, 3 }, -- Shadowblade Breastplate
		{ 47954, 3 }, -- Armor of Shifting Shadows
		{ 48026, 3 }, -- Vest of Shifting Shadows
		{ 47599, 3 }, -- Knightbane Carapace
		{ 47600, 3 }, -- Knightbane Carapace
	},
	Wrist = {
		{ 54580, 1 }, -- Umbrage Armbands
		{ 50670, 3 }, -- Toskk's Maximized Wristguards
		{ 51820, 3 }, -- Vambraces of the Frost Wyrm Queen
		{ 50333, 3 }, -- Toskk's Maximized Wristguards
		{ 47155, 3 }, -- Bracers of Dark Determination
		{ 47474, 3 }, -- Armbands of Dark Determination
		{ 51783, 3 }, -- Vambraces of the Frost Wyrm Queen
		{ 47581, 3 }, -- Bracers of Swift Death
		{ 47582, 3 }, -- Bracers of Swift Death
		{ 45611, 3 }, -- Solar Bindings
		{ 47151, 3 }, -- Bracers of Dark Determination
		{ 47313, 3 }, -- Armbands of Dark Determination
		{ 45869, 3 }, -- Fluxing Energy Coils
	},
	Hands = {
		{ 51251, 1 }, -- Sanctified Shadowblade Gauntlets
		{ 51188, 3 }, -- Sanctified Shadowblade Gauntlets
		{ 50675, 3 }, -- Aldriana's Gloves of Secrecy
		{ 51904, 3 }, -- Scourge Stranglers
		{ 50021, 3 }, -- Aldriana's Gloves of Secrecy
		{ 50088, 3 }, -- Shadowblade Gauntlets
		{ 50982, 3 }, -- Cat Burglar's Grips
		{ 50799, 3 }, -- Scourge Stranglers
		{ 48231, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48234, 3 }, -- Garona's Gauntlets of Triumph
		{ 48224, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48241, 3 }, -- Garona's Gauntlets of Triumph
		{ 47945, 3 }, -- Gloves of the Silver Assassin
		{ 48017, 3 }, -- Sunreaver Assassin's Gloves
	},
	Waist = {
		{ 50707, 1 }, -- Astrylian's Sutured Cinch
		{ 51925, 3 }, -- Soulthief's Braided Belt
		{ 50995, 3 }, -- Vengeful Noose
		{ 50067, 3 }, -- Astrylian's Sutured Cinch
		{ 47112, 3 }, -- Belt of the Merciless Killer
		{ 47460, 3 }, -- Belt of the Pitiless Killer
		{ 50778, 3 }, -- Soulthief's Braided Belt
		{ 46095, 3 }, -- Soul-Devouring Cinch
		{ 47107, 3 }, -- Belt of the Merciless Killer
		{ 47299, 3 }, -- Belt of the Pitiless Killer
		{ 45555, 3 }, -- Death-warmed Belt
		{ 45547, 3 }, -- Relic Hunter's Cord
	},
	Legs = {
		{ 51253, 1 }, -- Sanctified Shadowblade Legplates
		{ 51186, 3 }, -- Sanctified Shadowblade Legplates
		{ 50697, 3 }, -- Gangrenous Leggings
		{ 51889, 3 }, -- Plague-Soaked Leather Leggings
		{ 50042, 3 }, -- Gangrenous Leggings
		{ 50090, 3 }, -- Shadowblade Legplates
		{ 51841, 3 }, -- Ivory-Inlaid Leggings
		{ 49899, 3 }, -- Bladeborn Leggings
		{ 46975, 3 }, -- Leggings of the Broken Beast
		{ 47420, 3 }, -- Legwraps of the Broken Beast
		{ 50858, 3 }, -- Plague-Soaked Leather Leggings
		{ 48229, 3 }, -- VanCleef's Legplates of Triumph
		{ 48236, 3 }, -- Garona's Legplates of Triumph
		{ 51550, 3 }, -- Ivory-Inlaid Leggings
		{ 45536, 3 }, -- Legguards of Cunning Deception
		{ 46974, 3 }, -- Leggings of the Broken Beast
		{ 47259, 3 }, -- Legwraps of the Broken Beast
		{ 48226, 3 }, -- VanCleef's Legplates of Triumph
		{ 48239, 3 }, -- Garona's Legplates of Triumph
	},
	Feet = {
		{ 50607, 1 }, -- Frostbitten Fur Boots
		{ 51856, 3 }, -- Taldaram's Soft Slippers
		{ 49950, 3 }, -- Frostbitten Fur Boots
		{ 47077, 3 }, -- Treads of the Icewalker
		{ 47445, 3 }, -- Icewalker Treads
		{ 49895, 3 }, -- Footpads of Impending Death
		{ 51023, 3 }, -- Taldaram's Soft Slippers
		{ 47071, 3 }, -- Treads of the Icewalker
		{ 47284, 3 }, -- Icewalker Treads
		{ 47919, 3 }, -- Acidmaw Boots
		{ 47992, 3 }, -- Acidmaw Treads
		{ 45564, 3 }, -- Footpads of Silence
	},
	Ring = {
		{ 50402, 1 }, -- Ashen Band of Endless Vengeance
		{ 54576, 1 }, -- Signet of Twilight
		{ 50604, 3 }, -- Band of the Bone Colossus
		{ 50401, 3 }, -- Ashen Band of Unmatched Vengeance
		{ 50618, 3 }, -- Frostbrood Sapphire Ring
		{ 51843, 3 }, -- Seal of the Twilight Queen
		{ 49949, 3 }, -- Band of the Bone Colossus
		{ 51900, 3 }, -- Saurfang's Cold-Forged Band
		{ 50678, 3 }, -- Seal of Many Mouths
		{ 50186, 3 }, -- Frostbrood Sapphire Ring
		{ 50387, 3 }, -- Ashen Band of Greater Vengeance
		{ 47075, 3 }, -- Ring of Callous Aggression
		{ 47443, 3 }, -- Band of Callous Aggression
		{ 51387, 3 }, -- Seal of the Twilight Queen
		{ 50803, 3 }, -- Saurfang's Cold-Forged Band
		{ 45608, 3 }, -- Brann's Signet Ring
		{ 47070, 3 }, -- Ring of Callous Aggression
		{ 47282, 3 }, -- Band of Callous Aggression
		{ 47934, 3 }, -- Planestalker Signet
		{ 48007, 3 }, -- Planestalker Band
		{ 47730, 3 }, -- Dexterous Brightstone Ring
		{ 46048, 3 }, -- Band of Lights
	},
	Trinket = {
		{ 50363, 1 }, -- Deathbringer's Will
		{ 54590, 1 }, -- Sharpened Twilight Scale
		{ 50706, 3 }, -- Tiny Abomination in a Jar
		{ 50343, 3 }, -- Whispering Fanged Skull
		{ 50355, 3 }, -- Herkuml War Token
		{ 50351, 3 }, -- Tiny Abomination in a Jar
		{ 50362, 3 }, -- Deathbringer's Will
		{ 45609, 3 }, -- Comet's Trail
		{ 50342, 3 }, -- Whispering Fanged Skull
		{ 47131, 3 }, -- Death's Verdict
		{ 47464, 3 }, -- Death's Choice
		{ 47115, 3 }, -- Death's Verdict
		{ 47303, 3 }, -- Death's Choice
		{ 46038, 3 }, -- Dark Matter
		{ 45522, 3 }, -- Blood of the Old God
		{ 47734, 3 }, -- Mark of Supremacy
		{ 45931, 3 }, -- Mjolnir Runestone
	},
	MainHand = {
		{ 50621, 1 }, -- Lungbreaker
		{ 50736, 1 }, -- Heaven's Fall, Kryss of a Thousand Lies
		{ 50641, 3 }, -- Heartpierce
		{ 50676, 3 }, -- Rib Spreader
		{ 51868, 3 }, -- Flesh-Carving Scalpel
		{ 50183, 3 }, -- Lungbreaker
		{ 49982, 3 }, -- Heartpierce
		{ 50426, 3 }, -- Heaven's Fall, Kryss of a Thousand Lies
		{ 46969, 3 }, -- Steel Bladebreaker
		{ 47416, 3 }, -- Stygian Bladebreaker
		{ 51846, 3 }, -- Bloodsipper
		{ 51942, 3 }, -- Stormfury, Black Blade of the Betrayer
		{ 45484, 3 }, -- Bladetwister
		{ 47113, 3 }, -- Twin Spike
		{ 47461, 3 }, -- Gouge of the Frigid Heart
	},
	OffHand = {
		{ 51442, 3 }, -- Wrathful Gladiator's Dirk
	},
	Ranged = {
		{ 50733, 1 }, -- Fal'inrush, Defender of Quel'thalas
		{ 51927, 3 }, -- Njorndar Bone Bow
		{ 51940, 3 }, -- Windrunner's Heartseeker
		{ 51880, 3 }, -- Gluth's Fetching Knife
		{ 51845, 3 }, -- Stakethrower
		{ 49981, 3 }, -- Fal'inrush, Defender of Quel'thalas
		{ 50474, 3 }, -- Shrapnel Star
		{ 47521, 3 }, -- BRK-1000
		{ 47523, 3 }, -- Fezzik's Autocannon
		{ 46995, 3 }, -- Talonstrike
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 51802, 3 }, -- Windrunner's Heartseeker
		{ 50999, 3 }, -- Gluth's Fetching Knife
		{ 51385, 3 }, -- Stakethrower
		{ 47950, 3 }, -- The Diplomat
		{ 48022, 3 }, -- Widebarrel Flintlock
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/combat/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("ROGUE", "Combat", "PreRaid", {
	Head = {
		{ 42550, 1 }, -- Weakness Spectralizers
		{ 34244, 3 }, -- Duplicitous Guise
		{ 37293, 3 }, -- Mask of the Watcher
		{ 32235, 3 }, -- Cursed Vision of Sargeras
		{ 34353, 3 }, -- Quad Deathblow X44 Goggles
		{ 31027, 3 }, -- Slayer's Helm
		{ 43403, 3 }, -- Shroud of Darkness
	},
	Neck = {
		{ 40678, 1 }, -- Pendant of the Outcast Hero
		{ 42645, 3 }, -- Titanium Impact Choker
		{ 37861, 3 }, -- Necklace of Arcane Spheres
		{ 37096, 3 }, -- Necklace of the Chrono-Lord
	},
	Shoulder = {
		{ 37139, 1 }, -- Spaulders of the Careless Thief
		{ 43481, 3 }, -- Trollwoven Spaulders
		{ 34195, 3 }, -- Shoulderpads of Vehemence
	},
	Back = {
		{ 38614, 1 }, -- Embrace of Sorrow
		{ 43406, 3 }, -- Cloak of the Gushing Wound
		{ 34241, 3 }, -- Cloak of Unforgivable Sin
		{ 43566, 3 }, -- Ice Striker's Cloak
		{ 37840, 3 }, -- Shroud of Reverberation
	},
	Chest = {
		{ 39558, 1 }, -- Heroes' Bonescythe Breastplate
		{ 34369, 3 }, -- Carapace of Sun and Shadow
		{ 37219, 3 }, -- Custodian's Chestpiece
		{ 44303, 3 }, -- Darkheart Chestguard
	},
	Wrist = {
		{ 44203, 1 }, -- Dragonfriend Bracers
		{ 37366, 3 }, -- Drake-Champion's Bracers
		{ 37853, 3 }, -- Advanced Tooled-Leather Bands
		{ 34448, 3 }, -- Slayer's Bracers
	},
	Hands = {
		{ 39560, 1 }, -- Heroes' Bonescythe Gauntlets
		{ 37409, 3 }, -- Gilt-Edged Leather Gauntlets
		{ 34370, 3 }, -- Gloves of Immortal Dusk
		{ 37846, 3 }, -- Charged-Bolt Grips
	},
	Waist = {
		{ 40694, 1 }, -- Jorach's Crocolisk Skin Belt
		{ 37194, 3 }, -- Sharp-Barbed Leather Belt
		{ 43484, 3 }, -- Trollwoven Girdle
		{ 37243, 3 }, -- Treasure Seeker's Belt
		{ 34558, 3 }, -- Slayer's Belt
	},
	Legs = {
		{ 37644, 1 }, -- Gored Hide Legguards
		{ 34188, 3 }, -- Leggings of the Immortal Night
		{ 44179, 3 }, -- Mind-Expanding Leggings
	},
	Feet = {
		{ 44297, 1 }, -- Boots of the Neverending Path
		{ 34575, 3 }, -- Slayer's Boots
		{ 37666, 3 }, -- Boots of the Whirling Mist
	},
	Ring = {
		{ 40586, 1 }, -- Band of the Kirin Tor
		{ 37642, 1 }, -- Hemorrhaging Circle
		{ 43251, 3 }, -- Ring of Scarlet Shadows
		{ 44308, 3 }, -- Signet of Edward the Odd
		{ 42642, 3 }, -- Titanium Impact Band
		{ 37685, 3 }, -- Mobius Band
	},
	Trinket = {
		{ 44253, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 34427, 3 }, -- Blackened Naaru Sliver
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
		{ 43573, 3 }, -- Tears of Bitter Anguish
	},
	MainHand = {
		{ 43611, 1 }, -- Krol Cleaver
		{ 37693, 1 }, -- Greed
		{ 32837, 3 }, -- Warglaive of Azzinoth
		{ 44250, 3 }, -- Reaper of Dark Souls
	},
	OffHand = {
		{ 44311, 3 }, -- Avool's Sword of Jin
		{ 37856, 3 }, -- Librarian's Paper Cutter
		{ 32838, 3 }, -- Warglaive of Azzinoth
		{ 44187, 3 }, -- Fang of Truth
	},
	Ranged = {
		{ 37191, 1 }, -- Drake-Mounted Crossbow
		{ 44504, 1 }, -- Nesingwary 4000
		{ 43612, 1 }, -- Spineslicer
		{ 43284, 3 }, -- Amanitar Skullbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/combat/dps-bis-gear-pve-phase-1
ns:RegisterBiS("ROGUE", "Combat", "P1", {
	Head = {
		{ 40499, 1 }, -- Valorous Bonescythe Helmet
		{ 40329, 3 }, -- Hood of the Exodus
		{ 39399, 3 }, -- Helm of the Vast Legions
		{ 39561, 3 }, -- Heroes' Bonescythe Helmet
		{ 42550, 3 }, -- Weakness Spectralizers
		{ 40296, 3 }, -- Cover of Silence
	},
	Neck = {
		{ 44664, 1 }, -- Favor of the Dragon Queen
		{ 40369, 3 }, -- Icy Blast Amulet
		{ 39421, 3 }, -- Gem of Imprisoned Vassals
		{ 40065, 3 }, -- Fool's Trial
		{ 44659, 3 }, -- Pendant of the Dragonsworn
		{ 39146, 3 }, -- Collar of Dissolution
		{ 40678, 3 }, -- Pendant of the Outcast Hero
	},
	Shoulder = {
		{ 40502, 1 }, -- Valorous Bonescythe Pauldrons
		{ 40437, 3 }, -- Concealment Shoulderpads
		{ 40305, 3 }, -- Spaulders of Egotism
		{ 39237, 3 }, -- Spaulders of Resumed Battle
		{ 39565, 3 }, -- Heroes' Bonescythe Pauldrons
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 40250, 3 }, -- Aged Winter Cloak
		{ 40721, 3 }, -- Hammerhead Sharkskin Cloak
		{ 39404, 3 }, -- Cloak of Mastery
		{ 39297, 3 }, -- Cloak of Darkening
		{ 43566, 3 }, -- Ice Striker's Cloak
	},
	Chest = {
		{ 40539, 1 }, -- Chestguard of the Recluse
		{ 40495, 3 }, -- Valorous Bonescythe Breastplate
		{ 40277, 3 }, -- Tunic of Indulgence
		{ 39386, 3 }, -- Tunic of Dislocation
		{ 40319, 3 }, -- Chestpiece of Suspicion
		{ 43990, 3 }, -- Blade-Scarred Tunic
		{ 39558, 3 }, -- Heroes' Bonescythe Breastplate
	},
	Wrist = {
		{ 39765, 1 }, -- Sinner's Bindings
		{ 34448, 1 }, -- Slayer's Bracers
		{ 40186, 3 }, -- Thrusting Bands
		{ 40738, 3 }, -- Wristwraps of the Cutthroat
		{ 39247, 3 }, -- Cuffs of Dark Shadows
		{ 44203, 3 }, -- Dragonfriend Bracers
	},
	Hands = {
		{ 40541, 1 }, -- Frosted Adroit Handguards
		{ 39727, 3 }, -- Dislocating Handguards
		{ 40496, 3 }, -- Valorous Bonescythe Gauntlets
		{ 40362, 3 }, -- Gloves of Fast Reactions
		{ 39299, 3 }, -- Rapid Attack Gloves
		{ 39560, 3 }, -- Heroes' Bonescythe Gauntlets
	},
	Waist = {
		{ 40205, 1 }, -- Stalk-Skin Belt
		{ 40260, 1 }, -- Belt of the Tortured
		{ 34558, 1 }, -- Slayer's Belt
		{ 40694, 3 }, -- Jorach's Crocolisk Skin Belt
		{ 39279, 3 }, -- Blistered Belt of Decay
	},
	Legs = {
		{ 44011, 1 }, -- Leggings of the Honored
		{ 40500, 3 }, -- Valorous Bonescythe Legplates
		{ 39761, 3 }, -- Infectious Skitterer Leggings
		{ 40333, 3 }, -- Leggings of Fleeting Moments
		{ 39224, 3 }, -- Leggings of Discord
		{ 39564, 3 }, -- Heroes' Bonescythe Legplates
		{ 37644, 3 }, -- Gored Hide Legguards
	},
	Feet = {
		{ 39701, 1 }, -- Dawnwalkers
		{ 40243, 3 }, -- Footwraps of Vile Deceit
		{ 40748, 3 }, -- Boots of Captain Ellis
		{ 39196, 3 }, -- Boots of the Worshiper
		{ 44297, 3 }, -- Boots of the Neverending Path
	},
	Ring = {
		{ 40474, 1 }, -- Surge Needle Ring
		{ 40074, 3 }, -- Strong-Handed Ring
		{ 40717, 3 }, -- Ring of Invincibility
		{ 43993, 3 }, -- Greatring of Collision
		{ 39277, 3 }, -- Sealing Ring of Grobbulus
		{ 40586, 3 }, -- Band of the Kirin Tor
		{ 37642, 3 }, -- Hemorrhaging Circle
	},
	Trinket = {
		{ 44253, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 40431, 3 }, -- Fury of the Five Flights
		{ 40256, 3 }, -- Grim Toll
		{ 34427, 3 }, -- Blackened Naaru Sliver
		{ 40371, 3 }, -- Bandit's Insignia
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 39257, 3 }, -- Loatheb's Shadow
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
		{ 40531, 3 }, -- Mark of Norgannon
	},
	MainHand = {
		{ 40383, 1 }, -- Calamity's Grasp
		{ 39416, 3 }, -- Kel'Thuzad's Reach
		{ 40407, 3 }, -- Silent Crusader
		{ 42208, 3 }, -- Deadly Gladiator's Cleaver
		{ 42285, 3 }, -- Deadly Gladiator's Slicer
		{ 39291, 3 }, -- Torment of the Banished
		{ 43611, 3 }, -- Krol Cleaver
	},
	OffHand = {
		{ 39714, 1 }, -- Webbed Death
		{ 37856, 3 }, -- Librarian's Paper Cutter
		{ 42248, 3 }, -- Deadly Gladiator's Shiv
		{ 40368, 3 }, -- Murder
		{ 40491, 3 }, -- Hailstorm
		{ 39427, 3 }, -- Omen of Ruin
		{ 44311, 3 }, -- Avool's Sword of Jin
		{ 40407, 4 }, -- Silent Crusader
		{ 42208, 4 }, -- Deadly Gladiator's Cleaver
		{ 42285, 4 }, -- Deadly Gladiator's Slicer
	},
	Ranged = {
		{ 40385, 1 }, -- Envoy of Mortality
		{ 40190, 3 }, -- Spinning Fate
		{ 40346, 3 }, -- Final Voyage
		{ 40265, 3 }, -- Arrowsong
		{ 39419, 3 }, -- Nerubian Conquerer
		{ 39296, 3 }, -- Accursed Bow of the Elite
		{ 37191, 3 }, -- Drake-Mounted Crossbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/combat/dps-bis-gear-pve-phase-2
ns:RegisterBiS("ROGUE", "Combat", "P2", {
	Head = {
		{ 45993, 1 }, -- Mimiron's Flight Goggles
		{ 46125, 1 }, -- Conqueror's Terrorblade Helmet
		{ 45523, 3 }, -- Garona's Guise
		{ 45398, 3 }, -- Valorous Terrorblade Helmet
		{ 45893, 3 }, -- Guise of the Midgard Serpent
		{ 40499, 3 }, -- Valorous Bonescythe Helmet
	},
	Neck = {
		{ 45517, 1 }, -- Pendulum of Infinity
		{ 45945, 3 }, -- Seed of Budding Carnage
		{ 45480, 3 }, -- Nymph Heart Charm
		{ 45820, 3 }, -- Broach of the Wailing Night
		{ 44664, 3 }, -- Favor of the Dragon Queen
	},
	Shoulder = {
		{ 45245, 1 }, -- Shoulderpads of the Intruder
		{ 46127, 1 }, -- Conqueror's Terrorblade Pauldrons
		{ 45265, 3 }, -- Shoulderpads of the Monolith
		{ 45400, 3 }, -- Valorous Terrorblade Pauldrons
		{ 45677, 3 }, -- Treacherous Shoulderpads
		{ 40502, 3 }, -- Valorous Bonescythe Pauldrons
	},
	Back = {
		{ 45461, 1 }, -- Drape of Icy Intent
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 45224, 3 }, -- Drape of the Lithe
		{ 45704, 3 }, -- Shawl of the Shattered Giant
		{ 45873, 3 }, -- Winter's Frigid Embrace
		{ 40403, 3 }, -- Drape of the Deadly Foe
	},
	Chest = {
		{ 45473, 1 }, -- Embrace of the Gladiator
		{ 46123, 3 }, -- Conqueror's Terrorblade Breastplate
		{ 45396, 3 }, -- Valorous Terrorblade Breastplate
		{ 45453, 3 }, -- Winter's Icy Embrace
		{ 40539, 3 }, -- Chestguard of the Recluse
	},
	Wrist = {
		{ 45869, 1 }, -- Fluxing Energy Coils
		{ 45611, 1 }, -- Solar Bindings
		{ 45108, 3 }, -- Mechanist's Bindings
		{ 40186, 3 }, -- Thrusting Bands
		{ 39765, 3 }, -- Sinner's Bindings
	},
	Hands = {
		{ 46043, 1 }, -- Gloves of the Endless Dark
		{ 46124, 3 }, -- Conqueror's Terrorblade Gauntlets
		{ 45325, 3 }, -- Gloves of the Stonereaper
		{ 45838, 3 }, -- Gloves of the Blind Stalker
		{ 40541, 3 }, -- Frosted Adroit Handguards
		{ 45397, 3 }, -- Valorous Terrorblade Gauntlets
	},
	Waist = {
		{ 46095, 1 }, -- Soul-Devouring Cinch
		{ 45829, 3 }, -- Belt of the Twilight Assassin
		{ 45555, 3 }, -- Death-warmed Belt
		{ 45491, 3 }, -- Waistguard of the Creator
		{ 45547, 3 }, -- Relic Hunter's Cord
		{ 45709, 3 }, -- Nimble Climber's Belt
		{ 40205, 3 }, -- Stalk-Skin Belt
		{ 40260, 3 }, -- Belt of the Tortured
	},
	Legs = {
		{ 45536, 1 }, -- Legguards of Cunning Deception
		{ 46126, 3 }, -- Conqueror's Terrorblade Legplates
		{ 45141, 3 }, -- Proto-hide Leggings
		{ 45846, 3 }, -- Leggings of Wavering Shadow
		{ 45399, 3 }, -- Valorous Terrorblade Legplates
		{ 44011, 3 }, -- Leggings of the Honored
	},
	Feet = {
		{ 45564, 1 }, -- Footpads of Silence
		{ 45162, 3 }, -- Flamestalker Boots
		{ 45232, 3 }, -- Runed Ironhide Boots
		{ 45302, 3 }, -- Treads of the Invader
		{ 39701, 3 }, -- Dawnwalkers
	},
	Ring = {
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 46048, 1 }, -- Band of Lights
		{ 45456, 3 }, -- Loop of the Agile
		{ 46322, 3 }, -- Brann's Sealing Ring
		{ 45525, 3 }, -- Godbane Signet
		{ 45157, 3 }, -- Cindershard Ring
		{ 45503, 3 }, -- Metallic Loop of the Sufferer
		{ 45303, 3 }, -- Band of Draconic Guile
		{ 40474, 3 }, -- Surge Needle Ring
	},
	Trinket = {
		{ 45609, 1 }, -- Comet's Trail
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 46038, 1 }, -- Dark Matter
		{ 45522, 3 }, -- Blood of the Old God
		{ 45286, 3 }, -- Pyrite Infuser
		{ 45263, 3 }, -- Wrathstone
		{ 44253, 3 }, -- Darkmoon Card: Greatness
		{ 40684, 3 }, -- Mirror of Truth
	},
	MainHand = {
		{ 45132, 1 }, -- Golden Saronite Dragon
		{ 45449, 3 }, -- The Masticator
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 45957, 3 }, -- Furious Gladiator's Handaxe
		{ 45960, 3 }, -- Furious Gladiator's Longblade
		{ 45969, 3 }, -- Furious Gladiator's Grasp
		{ 45266, 3 }, -- Malice
		{ 45489, 3 }, -- Insanity's Grip
		{ 46097, 3 }, -- Caress of Insanity
		{ 45298, 3 }, -- Razorscale Talon
		{ 40383, 3 }, -- Calamity's Grasp
	},
	OffHand = {
		{ 45484, 1 }, -- Bladetwister
		{ 45930, 3 }, -- Combatant's Bootblade
		{ 46036, 3 }, -- Void Sabre
		{ 45331, 3 }, -- Rune-Etched Nightblade
		{ 45494, 3 }, -- Delirium's Touch
		{ 45962, 3 }, -- Furious Gladiator's Dirk
		{ 46024, 3 }, -- Kingsbane
		{ 45142, 3 }, -- Remorse
		{ 42249, 3 }, -- Furious Gladiator's Shiv
		{ 39714, 3 }, -- Webbed Death
	},
	Ranged = {
		{ 45296, 1 }, -- Twirling Blades
		{ 45570, 1 }, -- Skyforge Crossbow
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 45327, 3 }, -- Siren's Cry
		{ 45261, 3 }, -- Giant's Bane
		{ 45086, 3 }, -- Rising Sun
		{ 46018, 3 }, -- Deliverance
		{ 46342, 3 }, -- Golemheart Longbow
		{ 40385, 3 }, -- Envoy of Mortality
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/combat/dps-bis-gear-pve-phase-3
ns:RegisterBiS("ROGUE", "Combat", "P3", {
	Head = {
		{ 48230, 1 }, -- VanCleef's Helmet of Triumph
		{ 48235, 1 }, -- Garona's Helmet of Triumph
		{ 48225, 3 }, -- VanCleef's Helmet of Triumph
		{ 48240, 3 }, -- Garona's Helmet of Triumph
		{ 49477, 3 }, -- Bloodfang Hood
		{ 47689, 3 }, -- Hood of Lethal Intent
		{ 47688, 3 }, -- Mask of Lethal Intent
		{ 45993, 3 }, -- Mimiron's Flight Goggles
		{ 48218, 3 }, -- VanCleef's Helmet of Conquest
		{ 48245, 3 }, -- Garona's Helmet of Conquest
		{ 46125, 3 }, -- Conqueror's Terrorblade Helmet
	},
	Neck = {
		{ 47060, 1 }, -- Charge of the Demon Lord
		{ 47433, 1 }, -- Charge of the Eredar
		{ 45517, 3 }, -- Pendulum of Infinity
		{ 47915, 3 }, -- Collar of Ceaseless Torment
		{ 47988, 3 }, -- Collar of Unending Torment
		{ 49485, 3 }, -- Sparkling Onyxia Tooth Pendant
		{ 47043, 3 }, -- Charge of the Demon Lord
		{ 47272, 3 }, -- Charge of the Eredar
		{ 45945, 3 }, -- Seed of Budding Carnage
		{ 47607, 3 }, -- Collar of Ceaseless Torment
		{ 47849, 3 }, -- Collar of Unending Torment
		{ 45480, 3 }, -- Nymph Heart Charm
		{ 49314, 3 }, -- Sparkling Onyxia Tooth Pendant
	},
	Shoulder = {
		{ 48228, 1 }, -- VanCleef's Pauldrons of Triumph
		{ 48237, 1 }, -- Garona's Pauldrons of Triumph
		{ 48227, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48238, 3 }, -- Garona's Pauldrons of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
		{ 47972, 3 }, -- Spaulders of the Snow Bandit
		{ 48049, 3 }, -- Shoulderpads of the Snow Bandit
		{ 47708, 3 }, -- Duskstalker Shoulderpads
		{ 47709, 3 }, -- Duskstalker Pauldrons
		{ 48221, 3 }, -- VanCleef's Pauldrons of Conquest
		{ 48247, 3 }, -- Garona's Pauldrons of Conquest
		{ 46127, 3 }, -- Conqueror's Terrorblade Pauldrons
		{ 47832, 3 }, -- Spaulders of the Snow Bandit
		{ 47904, 3 }, -- Shoulderpads of the Snow Bandit
	},
	Back = {
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 48673, 3 }, -- Cloak of the Silver Covenant
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 46971, 3 }, -- Drape of the Untamed Predator
		{ 47418, 3 }, -- Cloak of the Untamed Predator
		{ 45461, 3 }, -- Drape of Icy Intent
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 46970, 3 }, -- Drape of the Untamed Predator
		{ 47257, 3 }, -- Cloak of the Untamed Predator
		{ 45224, 3 }, -- Drape of the Lithe
		{ 45704, 3 }, -- Shawl of the Shattered Giant
		{ 45873, 3 }, -- Winter's Frigid Embrace
	},
	Chest = {
		{ 48232, 1 }, -- VanCleef's Breastplate of Triumph
		{ 48233, 1 }, -- Garona's Breastplate of Triumph
		{ 47004, 3 }, -- Cuirass of Calamitous Fate
		{ 47431, 3 }, -- Vest of Calamitous Fate
		{ 45473, 3 }, -- Embrace of the Gladiator
		{ 47954, 3 }, -- Armor of Shifting Shadows
		{ 48026, 3 }, -- Vest of Shifting Shadows
		{ 47599, 3 }, -- Knightbane Carapace
		{ 47600, 3 }, -- Knightbane Carapace
		{ 48223, 3 }, -- VanCleef's Breastplate of Triumph
		{ 48242, 3 }, -- Garona's Breastplate of Triumph
		{ 47000, 3 }, -- Cuirass of Calamitous Fate
		{ 47270, 3 }, -- Vest of Calamitous Fate
		{ 48219, 3 }, -- VanCleef's Breastplate of Conquest
		{ 48243, 3 }, -- Garona's Breastplate of Conquest
		{ 46123, 3 }, -- Conqueror's Terrorblade Breastplate
	},
	Wrist = {
		{ 47155, 1 }, -- Bracers of Dark Determination
		{ 47474, 1 }, -- Armbands of Dark Determination
		{ 47581, 3 }, -- Bracers of Swift Death
		{ 47582, 3 }, -- Bracers of Swift Death
		{ 47151, 3 }, -- Bracers of Dark Determination
		{ 47313, 3 }, -- Armbands of Dark Determination
		{ 45869, 3 }, -- Fluxing Energy Coils
		{ 45108, 3 }, -- Mechanist's Bindings
		{ 45611, 3 }, -- Solar Bindings
	},
	Hands = {
		{ 48231, 1 }, -- VanCleef's Gauntlets of Triumph
		{ 48234, 1 }, -- Garona's Gauntlets of Triumph
		{ 48224, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48241, 3 }, -- Garona's Gauntlets of Triumph
		{ 47945, 3 }, -- Gloves of the Silver Assassin
		{ 48017, 3 }, -- Sunreaver Assassin's Gloves
		{ 46043, 3 }, -- Gloves of the Endless Dark
		{ 46124, 3 }, -- Conqueror's Terrorblade Gauntlets
		{ 47719, 3 }, -- Gloves of the Silver Assassin
		{ 47878, 3 }, -- Sunreaver Assassin's Gloves
		{ 48222, 3 }, -- VanCleef's Gauntlets of Conquest
		{ 48244, 3 }, -- Garona's Gauntlets of Conquest
	},
	Waist = {
		{ 47112, 1 }, -- Belt of the Merciless Killer
		{ 47460, 1 }, -- Belt of the Pitiless Killer
		{ 47107, 3 }, -- Belt of the Merciless Killer
		{ 47299, 3 }, -- Belt of the Pitiless Killer
		{ 45555, 3 }, -- Death-warmed Belt
		{ 45491, 3 }, -- Waistguard of the Creator
		{ 46095, 3 }, -- Soul-Devouring Cinch
		{ 45547, 3 }, -- Relic Hunter's Cord
		{ 45709, 3 }, -- Nimble Climber's Belt
	},
	Legs = {
		{ 46975, 1 }, -- Leggings of the Broken Beast
		{ 47420, 1 }, -- Legwraps of the Broken Beast
		{ 48229, 3 }, -- VanCleef's Legplates of Triumph
		{ 48236, 3 }, -- Garona's Legplates of Triumph
		{ 45536, 3 }, -- Legguards of Cunning Deception
		{ 46974, 3 }, -- Leggings of the Broken Beast
		{ 47259, 3 }, -- Legwraps of the Broken Beast
		{ 48226, 3 }, -- VanCleef's Legplates of Triumph
		{ 48239, 3 }, -- Garona's Legplates of Triumph
		{ 46126, 3 }, -- Conqueror's Terrorblade Legplates
		{ 45846, 3 }, -- Leggings of Wavering Shadow
		{ 48220, 3 }, -- VanCleef's Legplates of Conquest
		{ 48246, 3 }, -- Garona's Legplates of Conquest
	},
	Feet = {
		{ 47077, 1 }, -- Treads of the Icewalker
		{ 47445, 1 }, -- Icewalker Treads
		{ 47071, 3 }, -- Treads of the Icewalker
		{ 47284, 3 }, -- Icewalker Treads
		{ 45564, 3 }, -- Footpads of Silence
		{ 45162, 3 }, -- Flamestalker Boots
		{ 47919, 3 }, -- Acidmaw Boots
		{ 47992, 3 }, -- Acidmaw Treads
		{ 45302, 3 }, -- Treads of the Invader
		{ 47608, 3 }, -- Acidmaw Boots
		{ 47853, 3 }, -- Acidmaw Treads
	},
	Ring = {
		{ 47075, 1 }, -- Ring of Callous Aggression
		{ 47443, 1 }, -- Band of Callous Aggression
		{ 47934, 1 }, -- Planestalker Signet
		{ 48007, 1 }, -- Planestalker Band
		{ 45608, 3 }, -- Brann's Signet Ring
		{ 46048, 3 }, -- Band of Lights
		{ 47070, 3 }, -- Ring of Callous Aggression
		{ 47282, 3 }, -- Band of Callous Aggression
		{ 47730, 3 }, -- Dexterous Brightstone Ring
		{ 45456, 3 }, -- Loop of the Agile
		{ 46322, 3 }, -- Brann's Sealing Ring
		{ 47703, 3 }, -- Planestalker Signet
		{ 47868, 3 }, -- Planestalker Band
	},
	Trinket = {
		{ 47131, 1 }, -- Death's Verdict
		{ 47464, 1 }, -- Death's Choice
		{ 45609, 1 }, -- Comet's Trail
		{ 47115, 3 }, -- Death's Verdict
		{ 47303, 3 }, -- Death's Choice
		{ 45931, 3 }, -- Mjolnir Runestone
		{ 46038, 3 }, -- Dark Matter
		{ 45522, 3 }, -- Blood of the Old God
		{ 47734, 3 }, -- Mark of Supremacy
		{ 45286, 3 }, -- Pyrite Infuser
		{ 47214, 3 }, -- Banner of Victory
		{ 47948, 3 }, -- Victor's Call
		{ 48020, 3 }, -- Vengeance of the Forsaken
		{ 47725, 3 }, -- Victor's Call
		{ 47881, 3 }, -- Vengeance of the Forsaken
	},
	MainHand = {
		{ 47156, 1 }, -- Stormpike Cleaver
		{ 47475, 1 }, -- Hellscream Slicer
		{ 45132, 3 }, -- Golden Saronite Dragon
		{ 47966, 3 }, -- The Lion's Maw
		{ 48043, 3 }, -- Frostblade Hatchet
		{ 47148, 3 }, -- Stormpike Cleaver
		{ 47314, 3 }, -- Hellscream Slicer
		{ 47526, 3 }, -- Remorseless
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 48507, 3 }, -- Relentless Gladiator's Handaxe
		{ 48513, 3 }, -- Relentless Gladiator's Longblade
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 45449, 3 }, -- The Masticator
		{ 49500, 3 }, -- Raging Deathbringer
		{ 48712, 3 }, -- The Spinebreaker
		{ 48703, 3 }, -- The Facebreaker
		{ 47808, 3 }, -- The Lion's Maw
		{ 47898, 3 }, -- Frostblade Hatchet
	},
	OffHand = {
		{ 47001, 1 }, -- Lionhead Slasher
		{ 47427, 1 }, -- Blood Fury
		{ 46036, 3 }, -- Void Sabre
		{ 45331, 3 }, -- Rune-Etched Nightblade
		{ 47971, 3 }, -- Westfall Saber
		{ 48048, 3 }, -- Forsaken Bonecarver
		{ 46996, 3 }, -- Lionhead Slasher
		{ 47266, 3 }, -- Blood Fury
		{ 46969, 3 }, -- Steel Bladebreaker
		{ 47416, 3 }, -- Stygian Bladebreaker
		{ 48438, 3 }, -- Relentless Gladiator's Swiftblade
		{ 48426, 3 }, -- Relentless Gladiator's Dicer
		{ 47814, 3 }, -- Westfall Saber
		{ 47903, 3 }, -- Forsaken Bonecarver
		{ 45484, 3 }, -- Bladetwister
		{ 45142, 3 }, -- Remorse
		{ 45930, 3 }, -- Combatant's Bootblade
	},
	Ranged = {
		{ 47521, 1 }, -- BRK-1000
		{ 47523, 1 }, -- Fezzik's Autocannon
		{ 46995, 3 }, -- Talonstrike
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 47950, 3 }, -- The Diplomat
		{ 48022, 3 }, -- Widebarrel Flintlock
		{ 45296, 3 }, -- Twirling Blades
		{ 45570, 3 }, -- Skyforge Crossbow
		{ 48711, 3 }, -- Rhok'shalla, the Shadow's Bane
		{ 48697, 3 }, -- Frenzystrike Longbow
		{ 47975, 3 }, -- Baelgun's Heavy Crossbow
		{ 48052, 3 }, -- Darkmaw Crossbow
		{ 46994, 3 }, -- Talonstrike
		{ 47267, 3 }, -- Death's Head Crossbow
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 45261, 3 }, -- Giant's Bane
		{ 45327, 3 }, -- Siren's Cry
		{ 45086, 3 }, -- Rising Sun
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/combat/dps-bis-gear-pve-phase-4
ns:RegisterBiS("ROGUE", "Combat", "P4", {
	Head = {
		{ 51252, 1 }, -- Sanctified Shadowblade Helmet
		{ 51187, 3 }, -- Sanctified Shadowblade Helmet
		{ 51866, 3 }, -- Discarded Bag of Entrails
		{ 50713, 3 }, -- Geistlord's Punishment Sack
		{ 51013, 3 }, -- Discarded Bag of Entrails
		{ 50073, 3 }, -- Geistlord's Punishment Sack
		{ 51745, 3 }, -- Shadowblade Helmet
		{ 48230, 3 }, -- VanCleef's Helmet of Triumph
		{ 48235, 3 }, -- Garona's Helmet of Triumph
		{ 48225, 3 }, -- VanCleef's Helmet of Triumph
		{ 48240, 3 }, -- Garona's Helmet of Triumph
		{ 49477, 3 }, -- Bloodfang Hood
		{ 47689, 3 }, -- Hood of Lethal Intent
		{ 47688, 3 }, -- Mask of Lethal Intent
		{ 45993, 3 }, -- Mimiron's Flight Goggles
	},
	Neck = {
		{ 50633, 1 }, -- Sindragosa's Cruel Claw
		{ 50421, 3 }, -- Sindragosa's Cruel Claw
		{ 51822, 3 }, -- Rimetooth Pendant
		{ 51890, 3 }, -- Precious's Putrid Collar
		{ 51779, 3 }, -- Rimetooth Pendant
		{ 50452, 3 }, -- Wodin's Lucky Necklace
		{ 47060, 3 }, -- Charge of the Demon Lord
		{ 47433, 3 }, -- Charge of the Eredar
		{ 47915, 3 }, -- Collar of Ceaseless Torment
		{ 47988, 3 }, -- Collar of Unending Torment
		{ 45517, 3 }, -- Pendulum of Infinity
		{ 47043, 3 }, -- Charge of the Demon Lord
		{ 47272, 3 }, -- Charge of the Eredar
		{ 49485, 3 }, -- Sparkling Onyxia Tooth Pendant
	},
	Shoulder = {
		{ 51254, 1 }, -- Sanctified Shadowblade Pauldrons
		{ 51185, 3 }, -- Sanctified Shadowblade Pauldrons
		{ 50646, 3 }, -- Cultist's Bloodsoaked Spaulders
		{ 51830, 3 }, -- Skinned Whelp Shoulders
		{ 48228, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48237, 3 }, -- Garona's Pauldrons of Triumph
		{ 49987, 3 }, -- Cultist's Bloodsoaked Spaulders
		{ 51565, 3 }, -- Skinned Whelp Shoulders
		{ 50105, 3 }, -- Shadowblade Pauldrons
		{ 48227, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48238, 3 }, -- Garona's Pauldrons of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
		{ 47972, 3 }, -- Spaulders of the Snow Bandit
		{ 48049, 3 }, -- Shoulderpads of the Snow Bandit
		{ 47708, 3 }, -- Duskstalker Shoulderpads
		{ 47709, 3 }, -- Duskstalker Pauldrons
	},
	Back = {
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 50653, 3 }, -- Shadowvault Slayer's Cloak
		{ 50470, 3 }, -- Recovered Scarlet Onslaught Cape
		{ 51933, 3 }, -- Shawl of Nerubian Silk
		{ 48673, 3 }, -- Cloak of the Silver Covenant
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 49998, 3 }, -- Shadowvault Slayer's Cloak
		{ 50764, 3 }, -- Shawl of Nerubian Silk
		{ 46971, 3 }, -- Drape of the Untamed Predator
		{ 47418, 3 }, -- Cloak of the Untamed Predator
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 45461, 3 }, -- Drape of Icy Intent
	},
	Chest = {
		{ 50656, 1 }, -- Ikfirus's Sack of Wonder
		{ 50001, 3 }, -- Ikfirus's Sack of Wonder
		{ 51250, 3 }, -- Sanctified Shadowblade Breastplate
		{ 51923, 3 }, -- Chestguard of the Frigid Noose
		{ 51189, 3 }, -- Sanctified Shadowblade Breastplate
		{ 50972, 3 }, -- Shadow Seeker's Tunic
		{ 50780, 3 }, -- Chestguard of the Frigid Noose
		{ 47004, 3 }, -- Cuirass of Calamitous Fate
		{ 47431, 3 }, -- Vest of Calamitous Fate
		{ 48232, 3 }, -- VanCleef's Breastplate of Triumph
		{ 48233, 3 }, -- Garona's Breastplate of Triumph
		{ 50087, 3 }, -- Shadowblade Breastplate
		{ 47599, 3 }, -- Knightbane Carapace
		{ 47600, 3 }, -- Knightbane Carapace
		{ 47954, 3 }, -- Armor of Shifting Shadows
		{ 48026, 3 }, -- Vest of Shifting Shadows
		{ 45473, 3 }, -- Embrace of the Gladiator
	},
	Wrist = {
		{ 50670, 1 }, -- Toskk's Maximized Wristguards
		{ 54580, 1 }, -- Umbrage Armbands
		{ 50333, 3 }, -- Toskk's Maximized Wristguards
		{ 51820, 3 }, -- Vambraces of the Frost Wyrm Queen
		{ 47155, 3 }, -- Bracers of Dark Determination
		{ 47474, 3 }, -- Armbands of Dark Determination
		{ 45611, 3 }, -- Solar Bindings
		{ 47581, 3 }, -- Bracers of Swift Death
		{ 47582, 3 }, -- Bracers of Swift Death
		{ 47151, 3 }, -- Bracers of Dark Determination
		{ 47313, 3 }, -- Armbands of Dark Determination
		{ 51783, 3 }, -- Vambraces of the Frost Wyrm Queen
		{ 45869, 3 }, -- Fluxing Energy Coils
	},
	Hands = {
		{ 50675, 1 }, -- Aldriana's Gloves of Secrecy
		{ 50021, 3 }, -- Aldriana's Gloves of Secrecy
		{ 51904, 3 }, -- Scourge Stranglers
		{ 51251, 3 }, -- Sanctified Shadowblade Gauntlets
		{ 50982, 3 }, -- Cat Burglar's Grips
		{ 50799, 3 }, -- Scourge Stranglers
		{ 51188, 3 }, -- Sanctified Shadowblade Gauntlets
		{ 47945, 3 }, -- Gloves of the Silver Assassin
		{ 48017, 3 }, -- Sunreaver Assassin's Gloves
		{ 48231, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48234, 3 }, -- Garona's Gauntlets of Triumph
		{ 50088, 3 }, -- Shadowblade Gauntlets
		{ 48224, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48241, 3 }, -- Garona's Gauntlets of Triumph
	},
	Waist = {
		{ 50707, 1 }, -- Astrylian's Sutured Cinch
		{ 50995, 3 }, -- Vengeful Noose
		{ 50067, 3 }, -- Astrylian's Sutured Cinch
		{ 51925, 3 }, -- Soulthief's Braided Belt
		{ 47112, 3 }, -- Belt of the Merciless Killer
		{ 47460, 3 }, -- Belt of the Pitiless Killer
		{ 46095, 3 }, -- Soul-Devouring Cinch
		{ 50778, 3 }, -- Soulthief's Braided Belt
		{ 47107, 3 }, -- Belt of the Merciless Killer
		{ 47299, 3 }, -- Belt of the Pitiless Killer
		{ 45547, 3 }, -- Relic Hunter's Cord
		{ 45555, 3 }, -- Death-warmed Belt
	},
	Legs = {
		{ 50697, 1 }, -- Gangrenous Leggings
		{ 49899, 3 }, -- Bladeborn Leggings
		{ 51253, 3 }, -- Sanctified Shadowblade Legplates
		{ 51841, 3 }, -- Ivory-Inlaid Leggings
		{ 51186, 3 }, -- Sanctified Shadowblade Legplates
		{ 51889, 3 }, -- Plague-Soaked Leather Leggings
		{ 50042, 3 }, -- Gangrenous Leggings
		{ 48229, 3 }, -- VanCleef's Legplates of Triumph
		{ 48236, 3 }, -- Garona's Legplates of Triumph
		{ 46975, 3 }, -- Leggings of the Broken Beast
		{ 47420, 3 }, -- Legwraps of the Broken Beast
		{ 50090, 3 }, -- Shadowblade Legplates
		{ 45536, 3 }, -- Legguards of Cunning Deception
		{ 46974, 3 }, -- Leggings of the Broken Beast
		{ 47259, 3 }, -- Legwraps of the Broken Beast
		{ 48226, 3 }, -- VanCleef's Legplates of Triumph
		{ 48239, 3 }, -- Garona's Legplates of Triumph
		{ 51550, 3 }, -- Ivory-Inlaid Leggings
		{ 50858, 3 }, -- Plague-Soaked Leather Leggings
	},
	Feet = {
		{ 50607, 1 }, -- Frostbitten Fur Boots
		{ 51856, 3 }, -- Taldaram's Soft Slippers
		{ 49950, 3 }, -- Frostbitten Fur Boots
		{ 47077, 3 }, -- Treads of the Icewalker
		{ 47445, 3 }, -- Icewalker Treads
		{ 49895, 3 }, -- Footpads of Impending Death
		{ 51023, 3 }, -- Taldaram's Soft Slippers
		{ 47071, 3 }, -- Treads of the Icewalker
		{ 47284, 3 }, -- Icewalker Treads
		{ 47919, 3 }, -- Acidmaw Boots
		{ 47992, 3 }, -- Acidmaw Treads
		{ 45564, 3 }, -- Footpads of Silence
	},
	Ring = {
		{ 50402, 1 }, -- Ashen Band of Endless Vengeance
		{ 50618, 1 }, -- Frostbrood Sapphire Ring
		{ 50401, 3 }, -- Ashen Band of Unmatched Vengeance
		{ 50604, 3 }, -- Band of the Bone Colossus
		{ 51900, 3 }, -- Saurfang's Cold-Forged Band
		{ 50678, 3 }, -- Seal of Many Mouths
		{ 50186, 3 }, -- Frostbrood Sapphire Ring
		{ 49949, 3 }, -- Band of the Bone Colossus
		{ 51843, 3 }, -- Seal of the Twilight Queen
		{ 50803, 3 }, -- Saurfang's Cold-Forged Band
		{ 47075, 3 }, -- Ring of Callous Aggression
		{ 47443, 3 }, -- Band of Callous Aggression
		{ 50387, 3 }, -- Ashen Band of Greater Vengeance
		{ 51387, 3 }, -- Seal of the Twilight Queen
		{ 45608, 3 }, -- Brann's Signet Ring
		{ 47934, 3 }, -- Planestalker Signet
		{ 48007, 3 }, -- Planestalker Band
		{ 47730, 3 }, -- Dexterous Brightstone Ring
		{ 46048, 3 }, -- Band of Lights
		{ 47070, 3 }, -- Ring of Callous Aggression
		{ 47282, 3 }, -- Band of Callous Aggression
	},
	Trinket = {
		{ 54590, 1 }, -- Sharpened Twilight Scale
		{ 50363, 1 }, -- Deathbringer's Will
		{ 54569, 3 }, -- Sharpened Twilight Scale
		{ 50362, 3 }, -- Deathbringer's Will
		{ 50343, 3 }, -- Whispering Fanged Skull
		{ 45609, 3 }, -- Comet's Trail
		{ 47131, 3 }, -- Death's Verdict
		{ 47464, 3 }, -- Death's Choice
		{ 50355, 3 }, -- Herkuml War Token
		{ 50342, 3 }, -- Whispering Fanged Skull
		{ 50706, 3 }, -- Tiny Abomination in a Jar
		{ 50351, 3 }, -- Tiny Abomination in a Jar
		{ 47115, 3 }, -- Death's Verdict
		{ 47303, 3 }, -- Death's Choice
		{ 45931, 3 }, -- Mjolnir Runestone
		{ 46038, 3 }, -- Dark Matter
		{ 45522, 3 }, -- Blood of the Old God
		{ 47734, 3 }, -- Mark of Supremacy
	},
	MainHand = {
		{ 50737, 1 }, -- Havoc's Call, Blade of Lordaeron Kings
		{ 50672, 3 }, -- Bloodvenom Blade
		{ 50692, 3 }, -- Black Bruise
		{ 50012, 3 }, -- Havoc's Call, Blade of Lordaeron Kings
		{ 51893, 3 }, -- Gutbuster
		{ 47526, 3 }, -- Remorseless
		{ 47528, 3 }, -- Cudgel of the Damned
		{ 51916, 3 }, -- Frost Giant's Cleaver
		{ 50412, 3 }, -- Bloodvenom Blade
		{ 51858, 3 }, -- Soulbreaker
		{ 47156, 3 }, -- Stormpike Cleaver
		{ 47475, 3 }, -- Hellscream Slicer
	},
	OffHand = {
		{ 50654, 1 }, -- Scourgeborne Waraxe
		{ 51938, 3 }, -- Bone Warden's Splitter
		{ 50411, 3 }, -- Scourgeborne Waraxe
		{ 47001, 3 }, -- Lionhead Slasher
		{ 47427, 3 }, -- Blood Fury
		{ 50621, 3 }, -- Lungbreaker
		{ 50759, 3 }, -- Bone Warden's Splitter
		{ 51448, 3 }, -- Wrathful Gladiator's Swiftblade
		{ 51440, 3 }, -- Wrathful Gladiator's Dicer
		{ 51868, 3 }, -- Flesh-Carving Scalpel
		{ 46036, 3 }, -- Void Sabre
		{ 46996, 3 }, -- Lionhead Slasher
		{ 47266, 3 }, -- Blood Fury
		{ 45331, 3 }, -- Rune-Etched Nightblade
	},
	Ranged = {
		{ 50733, 1 }, -- Fal'inrush, Defender of Quel'thalas
		{ 51940, 3 }, -- Windrunner's Heartseeker
		{ 51845, 3 }, -- Stakethrower
		{ 49981, 3 }, -- Fal'inrush, Defender of Quel'thalas
		{ 46995, 3 }, -- Talonstrike
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 51927, 3 }, -- Njorndar Bone Bow
		{ 51880, 3 }, -- Gluth's Fetching Knife
		{ 51802, 3 }, -- Windrunner's Heartseeker
		{ 47521, 3 }, -- BRK-1000
		{ 47523, 3 }, -- Fezzik's Autocannon
		{ 51385, 3 }, -- Stakethrower
		{ 50474, 3 }, -- Shrapnel Star
		{ 47950, 3 }, -- The Diplomat
		{ 48022, 3 }, -- Widebarrel Flintlock
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/subtlety/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("ROGUE", "Subtlety", "PreRaid", {
	Head = {
		{ 42550, 1 }, -- Weakness Spectralizers
		{ 37293, 1 }, -- Mask of the Watcher
		{ 34244, 3 }, -- Duplicitous Guise
		{ 34353, 3 }, -- Quad Deathblow X44 Goggles
		{ 32235, 3 }, -- Cursed Vision of Sargeras
		{ 31027, 3 }, -- Slayer's Helm
		{ 43403, 3 }, -- Shroud of Darkness
	},
	Neck = {
		{ 42645, 1 }, -- Titanium Impact Choker
		{ 40678, 3 }, -- Pendant of the Outcast Hero
		{ 37096, 3 }, -- Necklace of the Chrono-Lord
		{ 37861, 3 }, -- Necklace of Arcane Spheres
	},
	Shoulder = {
		{ 37139, 1 }, -- Spaulders of the Careless Thief
		{ 43481, 3 }, -- Trollwoven Spaulders
		{ 37593, 3 }, -- Sprinting Shoulderpads
		{ 34195, 3 }, -- Shoulderpads of Vehemence
	},
	Back = {
		{ 38614, 1 }, -- Embrace of Sorrow
		{ 43406, 1 }, -- Cloak of the Gushing Wound
		{ 34241, 3 }, -- Cloak of Unforgivable Sin
		{ 43566, 3 }, -- Ice Striker's Cloak
		{ 37840, 3 }, -- Shroud of Reverberation
	},
	Chest = {
		{ 39558, 1 }, -- Heroes' Bonescythe Breastplate
		{ 44303, 3 }, -- Darkheart Chestguard
		{ 37219, 3 }, -- Custodian's Chestpiece
		{ 37165, 3 }, -- Crystal-Infused Tunic
		{ 34369, 3 }, -- Carapace of Sun and Shadow
	},
	Wrist = {
		{ 44203, 1 }, -- Dragonfriend Bracers
		{ 37366, 3 }, -- Drake-Champion's Bracers
		{ 37853, 3 }, -- Advanced Tooled-Leather Bands
		{ 34448, 3 }, -- Slayer's Bracers
	},
	Hands = {
		{ 39560, 1 }, -- Heroes' Bonescythe Gauntlets
		{ 37409, 3 }, -- Gilt-Edged Leather Gauntlets
		{ 34370, 3 }, -- Gloves of Immortal Dusk
		{ 37846, 3 }, -- Charged-Bolt Grips
	},
	Waist = {
		{ 40694, 1 }, -- Jorach's Crocolisk Skin Belt
		{ 37194, 3 }, -- Sharp-Barbed Leather Belt
		{ 43484, 3 }, -- Trollwoven Girdle
		{ 37243, 3 }, -- Treasure Seeker's Belt
		{ 34558, 3 }, -- Slayer's Belt
	},
	Legs = {
		{ 37644, 1 }, -- Gored Hide Legguards
		{ 34188, 3 }, -- Leggings of the Immortal Night
		{ 44179, 3 }, -- Mind-Expanding Leggings
	},
	Feet = {
		{ 44297, 1 }, -- Boots of the Neverending Path
		{ 37666, 3 }, -- Boots of the Whirling Mist
		{ 34575, 3 }, -- Slayer's Boots
	},
	Ring = {
		{ 37642, 1 }, -- Hemorrhaging Circle
		{ 40586, 1 }, -- Band of the Kirin Tor
		{ 44308, 3 }, -- Signet of Edward the Odd
		{ 42642, 3 }, -- Titanium Impact Band
		{ 37685, 3 }, -- Mobius Band
		{ 43251, 3 }, -- Ring of Scarlet Shadows
	},
	Trinket = {
		{ 44253, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
		{ 34427, 3 }, -- Blackened Naaru Sliver
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 43573, 3 }, -- Tears of Bitter Anguish
	},
	MainHand = {
		{ 37667, 1 }, -- The Fleshshaper
		{ 37856, 1 }, -- Librarian's Paper Cutter
		{ 44310, 3 }, -- Namlak's Supernumerary Sticker
		{ 44193, 3 }, -- Broken Stalactite
		{ 42435, 3 }, -- Titansteel Shanker
		{ 37181, 3 }, -- Dagger of Betrayal
		{ 37037, 3 }, -- Ritualistic Athame
		{ 44166, 3 }, -- Lightblade Rivener
		{ 36944, 3 }, -- Lifeblade of Belgaristrasz
	},
	Ranged = {
		{ 37191, 1 }, -- Drake-Mounted Crossbow
		{ 44504, 1 }, -- Nesingwary 4000
		{ 43612, 1 }, -- Spineslicer
		{ 43284, 3 }, -- Amanitar Skullbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/subtlety/dps-bis-gear-pve-phase-1
ns:RegisterBiS("ROGUE", "Subtlety", "P1", {
	Head = {
		{ 40499, 1 }, -- Valorous Bonescythe Helmet
		{ 40329, 3 }, -- Hood of the Exodus
		{ 39561, 3 }, -- Heroes' Bonescythe Helmet
		{ 39399, 3 }, -- Helm of the Vast Legions
		{ 42550, 3 }, -- Weakness Spectralizers
		{ 37293, 3 }, -- Mask of the Watcher
		{ 40296, 3 }, -- Cover of Silence
	},
	Neck = {
		{ 44664, 1 }, -- Favor of the Dragon Queen
		{ 40369, 3 }, -- Icy Blast Amulet
		{ 44659, 3 }, -- Pendant of the Dragonsworn
		{ 39421, 3 }, -- Gem of Imprisoned Vassals
		{ 40065, 3 }, -- Fool's Trial
		{ 39146, 3 }, -- Collar of Dissolution
	},
	Shoulder = {
		{ 40502, 1 }, -- Valorous Bonescythe Pauldrons
		{ 40437, 3 }, -- Concealment Shoulderpads
		{ 40305, 3 }, -- Spaulders of Egotism
		{ 39237, 3 }, -- Spaulders of Resumed Battle
		{ 39565, 3 }, -- Heroes' Bonescythe Pauldrons
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 40250, 3 }, -- Aged Winter Cloak
		{ 40721, 3 }, -- Hammerhead Sharkskin Cloak
		{ 39404, 3 }, -- Cloak of Mastery
		{ 39297, 3 }, -- Cloak of Darkening
		{ 43566, 3 }, -- Ice Striker's Cloak
	},
	Chest = {
		{ 40539, 1 }, -- Chestguard of the Recluse
		{ 40495, 3 }, -- Valorous Bonescythe Breastplate
		{ 40277, 3 }, -- Tunic of Indulgence
		{ 39386, 3 }, -- Tunic of Dislocation
		{ 40319, 3 }, -- Chestpiece of Suspicion
		{ 43990, 3 }, -- Blade-Scarred Tunic
		{ 39558, 3 }, -- Heroes' Bonescythe Breastplate
		{ 37219, 3 }, -- Custodian's Chestpiece
	},
	Wrist = {
		{ 40186, 1 }, -- Thrusting Bands
		{ 34448, 1 }, -- Slayer's Bracers
		{ 40738, 3 }, -- Wristwraps of the Cutthroat
		{ 39765, 3 }, -- Sinner's Bindings
		{ 39247, 3 }, -- Cuffs of Dark Shadows
		{ 44203, 3 }, -- Dragonfriend Bracers
	},
	Hands = {
		{ 40496, 1 }, -- Valorous Bonescythe Gauntlets
		{ 40541, 3 }, -- Frosted Adroit Handguards
		{ 39727, 3 }, -- Dislocating Handguards
		{ 40362, 3 }, -- Gloves of Fast Reactions
		{ 39299, 3 }, -- Rapid Attack Gloves
		{ 39560, 3 }, -- Heroes' Bonescythe Gauntlets
	},
	Waist = {
		{ 40205, 1 }, -- Stalk-Skin Belt
		{ 34558, 1 }, -- Slayer's Belt
		{ 40260, 3 }, -- Belt of the Tortured
		{ 40694, 3 }, -- Jorach's Crocolisk Skin Belt
		{ 39279, 3 }, -- Blistered Belt of Decay
		{ 43484, 3 }, -- Trollwoven Girdle
		{ 37194, 3 }, -- Sharp-Barbed Leather Belt
	},
	Legs = {
		{ 44011, 1 }, -- Leggings of the Honored
		{ 40500, 3 }, -- Valorous Bonescythe Legplates
		{ 39761, 3 }, -- Infectious Skitterer Leggings
		{ 40333, 3 }, -- Leggings of Fleeting Moments
		{ 39564, 3 }, -- Heroes' Bonescythe Legplates
		{ 39224, 3 }, -- Leggings of Discord
		{ 37644, 3 }, -- Gored Hide Legguards
	},
	Feet = {
		{ 39701, 1 }, -- Dawnwalkers
		{ 40243, 3 }, -- Footwraps of Vile Deceit
		{ 40748, 3 }, -- Boots of Captain Ellis
		{ 39196, 3 }, -- Boots of the Worshiper
		{ 44297, 3 }, -- Boots of the Neverending Path
	},
	Ring = {
		{ 40474, 1 }, -- Surge Needle Ring
		{ 40074, 1 }, -- Strong-Handed Ring
		{ 40717, 3 }, -- Ring of Invincibility
		{ 43993, 3 }, -- Greatring of Collision
		{ 37642, 3 }, -- Hemorrhaging Circle
		{ 39277, 3 }, -- Sealing Ring of Grobbulus
		{ 40586, 3 }, -- Band of the Kirin Tor
	},
	Trinket = {
		{ 44253, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 40431, 3 }, -- Fury of the Five Flights
		{ 40256, 3 }, -- Grim Toll
		{ 40371, 3 }, -- Bandit's Insignia
		{ 34427, 3 }, -- Blackened Naaru Sliver
		{ 39257, 3 }, -- Loatheb's Shadow
		{ 37723, 3 }, -- Incisor Fragment
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 40531, 3 }, -- Mark of Norgannon
	},
	MainHand = {
		{ 40386, 1 }, -- Sinister Revenge
		{ 39714, 1 }, -- Webbed Death
		{ 39420, 3 }, -- Anarchy
		{ 40368, 3 }, -- Murder
		{ 39427, 3 }, -- Omen of Ruin
		{ 37856, 3 }, -- Librarian's Paper Cutter
		{ 40281, 3 }, -- Twilight Mist
		{ 39140, 3 }, -- Knife of Incision
	},
	Ranged = {
		{ 40385, 1 }, -- Envoy of Mortality
		{ 40190, 3 }, -- Spinning Fate
		{ 40346, 3 }, -- Final Voyage
		{ 39419, 3 }, -- Nerubian Conquerer
		{ 40265, 3 }, -- Arrowsong
		{ 39296, 3 }, -- Accursed Bow of the Elite
		{ 37191, 3 }, -- Drake-Mounted Crossbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/subtlety/dps-bis-gear-pve-phase-2
ns:RegisterBiS("ROGUE", "Subtlety", "P2", {
	Head = {
		{ 46125, 1 }, -- Conqueror's Terrorblade Helmet
		{ 45993, 3 }, -- Mimiron's Flight Goggles
		{ 45523, 3 }, -- Garona's Guise
		{ 45893, 3 }, -- Guise of the Midgard Serpent
		{ 45398, 3 }, -- Valorous Terrorblade Helmet
		{ 40499, 3 }, -- Valorous Bonescythe Helmet
	},
	Neck = {
		{ 45945, 1 }, -- Seed of Budding Carnage
		{ 45517, 3 }, -- Pendulum of Infinity
		{ 45480, 3 }, -- Nymph Heart Charm
		{ 45820, 3 }, -- Broach of the Wailing Night
		{ 44664, 3 }, -- Favor of the Dragon Queen
	},
	Shoulder = {
		{ 45245, 1 }, -- Shoulderpads of the Intruder
		{ 46127, 3 }, -- Conqueror's Terrorblade Pauldrons
		{ 45677, 3 }, -- Treacherous Shoulderpads
		{ 45400, 3 }, -- Valorous Terrorblade Pauldrons
		{ 45265, 3 }, -- Shoulderpads of the Monolith
		{ 40502, 3 }, -- Valorous Bonescythe Pauldrons
	},
	Back = {
		{ 45461, 1 }, -- Drape of Icy Intent
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 45224, 3 }, -- Drape of the Lithe
		{ 45704, 3 }, -- Shawl of the Shattered Giant
		{ 45873, 3 }, -- Winter's Frigid Embrace
		{ 40403, 3 }, -- Drape of the Deadly Foe
	},
	Chest = {
		{ 45473, 1 }, -- Embrace of the Gladiator
		{ 46123, 3 }, -- Conqueror's Terrorblade Breastplate
		{ 45396, 3 }, -- Valorous Terrorblade Breastplate
		{ 45453, 3 }, -- Winter's Icy Embrace
		{ 40539, 3 }, -- Chestguard of the Recluse
	},
	Wrist = {
		{ 45611, 1 }, -- Solar Bindings
		{ 45869, 1 }, -- Fluxing Energy Coils
		{ 40186, 3 }, -- Thrusting Bands
		{ 45108, 3 }, -- Mechanist's Bindings
		{ 39765, 3 }, -- Sinner's Bindings
	},
	Hands = {
		{ 46124, 1 }, -- Conqueror's Terrorblade Gauntlets
		{ 46043, 3 }, -- Gloves of the Endless Dark
		{ 45325, 3 }, -- Gloves of the Stonereaper
		{ 45397, 3 }, -- Valorous Terrorblade Gauntlets
		{ 40541, 3 }, -- Frosted Adroit Handguards
		{ 45838, 3 }, -- Gloves of the Blind Stalker
	},
	Waist = {
		{ 46095, 1 }, -- Soul-Devouring Cinch
		{ 45829, 3 }, -- Belt of the Twilight Assassin
		{ 45547, 3 }, -- Relic Hunter's Cord
		{ 45555, 3 }, -- Death-warmed Belt
		{ 45709, 3 }, -- Nimble Climber's Belt
		{ 45491, 3 }, -- Waistguard of the Creator
		{ 40260, 3 }, -- Belt of the Tortured
		{ 40205, 3 }, -- Stalk-Skin Belt
	},
	Legs = {
		{ 45536, 1 }, -- Legguards of Cunning Deception
		{ 45846, 3 }, -- Leggings of Wavering Shadow
		{ 45141, 3 }, -- Proto-hide Leggings
		{ 46126, 3 }, -- Conqueror's Terrorblade Legplates
		{ 44011, 3 }, -- Leggings of the Honored
		{ 45399, 3 }, -- Valorous Terrorblade Legplates
	},
	Feet = {
		{ 45564, 1 }, -- Footpads of Silence
		{ 45232, 3 }, -- Runed Ironhide Boots
		{ 45162, 3 }, -- Flamestalker Boots
		{ 39701, 3 }, -- Dawnwalkers
		{ 45302, 3 }, -- Treads of the Invader
	},
	Ring = {
		{ 46048, 1 }, -- Band of Lights
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 45157, 3 }, -- Cindershard Ring
		{ 46322, 3 }, -- Brann's Sealing Ring
		{ 45456, 3 }, -- Loop of the Agile
		{ 45525, 3 }, -- Godbane Signet
		{ 45503, 3 }, -- Metallic Loop of the Sufferer
		{ 40474, 3 }, -- Surge Needle Ring
		{ 45303, 3 }, -- Band of Draconic Guile
	},
	Trinket = {
		{ 45609, 1 }, -- Comet's Trail
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 45522, 3 }, -- Blood of the Old God
		{ 46038, 3 }, -- Dark Matter
		{ 45286, 3 }, -- Pyrite Infuser
		{ 44253, 3 }, -- Darkmoon Card: Greatness
		{ 45263, 3 }, -- Wrathstone
		{ 40684, 3 }, -- Mirror of Truth
	},
	MainHand = {
		{ 45607, 1 }, -- Fang of Oblivion
		{ 45448, 3 }, -- Perilous Bite
		{ 45605, 3 }, -- Daschal's Bite
		{ 45958, 3 }, -- Furious Gladiator's Spike
		{ 46011, 3 }, -- Shadowbite
		{ 40386, 3 }, -- Sinister Revenge
	},
	OffHand = {
		{ 45484, 1 }, -- Bladetwister
		{ 45930, 3 }, -- Combatant's Bootblade
		{ 46036, 3 }, -- Void Sabre
		{ 45494, 3 }, -- Delirium's Touch
		{ 46024, 3 }, -- Kingsbane
		{ 45246, 3 }, -- Golem-Shard Sticker
		{ 45142, 3 }, -- Remorse
		{ 45331, 3 }, -- Rune-Etched Nightblade
		{ 45315, 3 }, -- Stonerender
		{ 45962, 3 }, -- Furious Gladiator's Dirk
		{ 39714, 3 }, -- Webbed Death
	},
	Ranged = {
		{ 45296, 1 }, -- Twirling Blades
		{ 45570, 3 }, -- Skyforge Crossbow
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 45086, 3 }, -- Rising Sun
		{ 45261, 3 }, -- Giant's Bane
		{ 46018, 3 }, -- Deliverance
		{ 45327, 3 }, -- Siren's Cry
		{ 45872, 3 }, -- Avalanche
		{ 40190, 3 }, -- Spinning Fate
		{ 40385, 3 }, -- Envoy of Mortality
		{ 46342, 3 }, -- Golemheart Longbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/subtlety/dps-bis-gear-pve-phase-3
ns:RegisterBiS("ROGUE", "Subtlety", "P3", {
	Head = {
		{ 48230, 1 }, -- VanCleef's Helmet of Triumph
		{ 48235, 1 }, -- Garona's Helmet of Triumph
		{ 48225, 3 }, -- VanCleef's Helmet of Triumph
		{ 48240, 3 }, -- Garona's Helmet of Triumph
		{ 49477, 3 }, -- Bloodfang Hood
		{ 47689, 3 }, -- Hood of Lethal Intent
		{ 47688, 3 }, -- Mask of Lethal Intent
		{ 45993, 3 }, -- Mimiron's Flight Goggles
		{ 46125, 3 }, -- Conqueror's Terrorblade Helmet
		{ 48218, 3 }, -- VanCleef's Helmet of Conquest
		{ 48245, 3 }, -- Garona's Helmet of Conquest
	},
	Neck = {
		{ 47060, 1 }, -- Charge of the Demon Lord
		{ 47433, 1 }, -- Charge of the Eredar
		{ 45517, 3 }, -- Pendulum of Infinity
		{ 47915, 3 }, -- Collar of Ceaseless Torment
		{ 47988, 3 }, -- Collar of Unending Torment
		{ 45945, 3 }, -- Seed of Budding Carnage
		{ 47043, 3 }, -- Charge of the Demon Lord
		{ 47272, 3 }, -- Charge of the Eredar
		{ 49485, 3 }, -- Sparkling Onyxia Tooth Pendant
		{ 47607, 3 }, -- Collar of Ceaseless Torment
		{ 47849, 3 }, -- Collar of Unending Torment
		{ 45820, 3 }, -- Broach of the Wailing Night
		{ 45480, 3 }, -- Nymph Heart Charm
		{ 49314, 3 }, -- Sparkling Onyxia Tooth Pendant
	},
	Shoulder = {
		{ 48228, 1 }, -- VanCleef's Pauldrons of Triumph
		{ 48237, 1 }, -- Garona's Pauldrons of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
		{ 48227, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48238, 3 }, -- Garona's Pauldrons of Triumph
		{ 47972, 3 }, -- Spaulders of the Snow Bandit
		{ 48049, 3 }, -- Shoulderpads of the Snow Bandit
		{ 48221, 3 }, -- VanCleef's Pauldrons of Conquest
		{ 48247, 3 }, -- Garona's Pauldrons of Conquest
		{ 47708, 3 }, -- Duskstalker Shoulderpads
		{ 47709, 3 }, -- Duskstalker Pauldrons
		{ 47832, 3 }, -- Spaulders of the Snow Bandit
		{ 47904, 3 }, -- Shoulderpads of the Snow Bandit
		{ 46127, 3 }, -- Conqueror's Terrorblade Pauldrons
	},
	Back = {
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 48673, 3 }, -- Cloak of the Silver Covenant
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 46971, 3 }, -- Drape of the Untamed Predator
		{ 47418, 3 }, -- Cloak of the Untamed Predator
		{ 45461, 3 }, -- Drape of Icy Intent
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 46970, 3 }, -- Drape of the Untamed Predator
		{ 47257, 3 }, -- Cloak of the Untamed Predator
		{ 45224, 3 }, -- Drape of the Lithe
		{ 45704, 3 }, -- Shawl of the Shattered Giant
		{ 45873, 3 }, -- Winter's Frigid Embrace
	},
	Chest = {
		{ 48232, 1 }, -- VanCleef's Breastplate of Triumph
		{ 48233, 1 }, -- Garona's Breastplate of Triumph
		{ 47004, 3 }, -- Cuirass of Calamitous Fate
		{ 47431, 3 }, -- Vest of Calamitous Fate
		{ 45473, 3 }, -- Embrace of the Gladiator
		{ 47954, 3 }, -- Armor of Shifting Shadows
		{ 48026, 3 }, -- Vest of Shifting Shadows
		{ 47599, 3 }, -- Knightbane Carapace
		{ 47600, 3 }, -- Knightbane Carapace
		{ 48223, 3 }, -- VanCleef's Breastplate of Triumph
		{ 48242, 3 }, -- Garona's Breastplate of Triumph
		{ 47000, 3 }, -- Cuirass of Calamitous Fate
		{ 47270, 3 }, -- Vest of Calamitous Fate
		{ 48219, 3 }, -- VanCleef's Breastplate of Conquest
		{ 48243, 3 }, -- Garona's Breastplate of Conquest
		{ 46123, 3 }, -- Conqueror's Terrorblade Breastplate
	},
	Wrist = {
		{ 47155, 1 }, -- Bracers of Dark Determination
		{ 47474, 1 }, -- Armbands of Dark Determination
		{ 45611, 3 }, -- Solar Bindings
		{ 47581, 3 }, -- Bracers of Swift Death
		{ 47582, 3 }, -- Bracers of Swift Death
		{ 47151, 3 }, -- Bracers of Dark Determination
		{ 47313, 3 }, -- Armbands of Dark Determination
		{ 45869, 3 }, -- Fluxing Energy Coils
		{ 45108, 3 }, -- Mechanist's Bindings
	},
	Hands = {
		{ 48231, 1 }, -- VanCleef's Gauntlets of Triumph
		{ 48234, 1 }, -- Garona's Gauntlets of Triumph
		{ 47945, 3 }, -- Gloves of the Silver Assassin
		{ 48017, 3 }, -- Sunreaver Assassin's Gloves
		{ 48224, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48241, 3 }, -- Garona's Gauntlets of Triumph
		{ 46043, 3 }, -- Gloves of the Endless Dark
		{ 46124, 3 }, -- Conqueror's Terrorblade Gauntlets
		{ 47719, 3 }, -- Gloves of the Silver Assassin
		{ 47878, 3 }, -- Sunreaver Assassin's Gloves
		{ 48222, 3 }, -- VanCleef's Gauntlets of Conquest
		{ 48244, 3 }, -- Garona's Gauntlets of Conquest
	},
	Waist = {
		{ 47112, 1 }, -- Belt of the Merciless Killer
		{ 47460, 1 }, -- Belt of the Pitiless Killer
		{ 46095, 3 }, -- Soul-Devouring Cinch
		{ 47107, 3 }, -- Belt of the Merciless Killer
		{ 47299, 3 }, -- Belt of the Pitiless Killer
		{ 45829, 3 }, -- Belt of the Twilight Assassin
		{ 45555, 3 }, -- Death-warmed Belt
		{ 45547, 3 }, -- Relic Hunter's Cord
		{ 45491, 3 }, -- Waistguard of the Creator
		{ 45709, 3 }, -- Nimble Climber's Belt
	},
	Legs = {
		{ 46975, 1 }, -- Leggings of the Broken Beast
		{ 47420, 1 }, -- Legwraps of the Broken Beast
		{ 48229, 3 }, -- VanCleef's Legplates of Triumph
		{ 48236, 3 }, -- Garona's Legplates of Triumph
		{ 45536, 3 }, -- Legguards of Cunning Deception
		{ 46974, 3 }, -- Leggings of the Broken Beast
		{ 47259, 3 }, -- Legwraps of the Broken Beast
		{ 48226, 3 }, -- VanCleef's Legplates of Triumph
		{ 48239, 3 }, -- Garona's Legplates of Triumph
		{ 46126, 3 }, -- Conqueror's Terrorblade Legplates
		{ 45846, 3 }, -- Leggings of Wavering Shadow
		{ 48220, 3 }, -- VanCleef's Legplates of Conquest
		{ 48246, 3 }, -- Garona's Legplates of Conquest
	},
	Feet = {
		{ 47077, 1 }, -- Treads of the Icewalker
		{ 47445, 1 }, -- Icewalker Treads
		{ 47919, 3 }, -- Acidmaw Boots
		{ 47992, 3 }, -- Acidmaw Treads
		{ 47071, 3 }, -- Treads of the Icewalker
		{ 47284, 3 }, -- Icewalker Treads
		{ 47608, 3 }, -- Acidmaw Boots
		{ 47853, 3 }, -- Acidmaw Treads
		{ 45564, 3 }, -- Footpads of Silence
		{ 45232, 3 }, -- Runed Ironhide Boots
		{ 45162, 3 }, -- Flamestalker Boots
		{ 45302, 3 }, -- Treads of the Invader
	},
	Ring = {
		{ 47075, 1 }, -- Ring of Callous Aggression
		{ 47443, 1 }, -- Band of Callous Aggression
		{ 47934, 1 }, -- Planestalker Signet
		{ 48007, 1 }, -- Planestalker Band
		{ 45608, 3 }, -- Brann's Signet Ring
		{ 46048, 3 }, -- Band of Lights
		{ 47730, 3 }, -- Dexterous Brightstone Ring
		{ 47070, 3 }, -- Ring of Callous Aggression
		{ 47282, 3 }, -- Band of Callous Aggression
		{ 45456, 3 }, -- Loop of the Agile
		{ 46322, 3 }, -- Brann's Sealing Ring
		{ 47703, 3 }, -- Planestalker Signet
		{ 47868, 3 }, -- Planestalker Band
	},
	Trinket = {
		{ 47131, 1 }, -- Death's Verdict
		{ 47464, 1 }, -- Death's Choice
		{ 45609, 1 }, -- Comet's Trail
		{ 47115, 3 }, -- Death's Verdict
		{ 47303, 3 }, -- Death's Choice
		{ 45931, 3 }, -- Mjolnir Runestone
		{ 45522, 3 }, -- Blood of the Old God
		{ 47734, 3 }, -- Mark of Supremacy
		{ 46038, 3 }, -- Dark Matter
		{ 45286, 3 }, -- Pyrite Infuser
		{ 47948, 3 }, -- Victor's Call
		{ 48020, 3 }, -- Vengeance of the Forsaken
		{ 47725, 3 }, -- Victor's Call
		{ 47881, 3 }, -- Vengeance of the Forsaken
		{ 47214, 3 }, -- Banner of Victory
	},
	MainHand = {
		{ 47526, 1 }, -- Remorseless
		{ 47528, 1 }, -- Cudgel of the Damned
		{ 47156, 1 }, -- Stormpike Cleaver
		{ 47475, 1 }, -- Hellscream Slicer
		{ 45132, 3 }, -- Golden Saronite Dragon
		{ 46097, 3 }, -- Caress of Insanity
		{ 45449, 3 }, -- The Masticator
		{ 45947, 3 }, -- Serilas, Blood Blade of Invar One-Arm
		{ 48712, 3 }, -- The Spinebreaker
		{ 48703, 3 }, -- The Facebreaker
		{ 47966, 3 }, -- The Lion's Maw
		{ 48043, 3 }, -- Frostblade Hatchet
		{ 47973, 3 }, -- The Grinder
		{ 48050, 3 }, -- Blackhorn Bludgeon
		{ 47148, 3 }, -- Stormpike Cleaver
		{ 47314, 3 }, -- Hellscream Slicer
		{ 48507, 3 }, -- Relentless Gladiator's Handaxe
		{ 48513, 3 }, -- Relentless Gladiator's Longblade
		{ 48511, 3 }, -- Relentless Gladiator's Truncheon
		{ 48515, 3 }, -- Relentless Gladiator's Grasp
		{ 47808, 3 }, -- The Lion's Maw
		{ 47898, 3 }, -- Frostblade Hatchet
		{ 49500, 3 }, -- Raging Deathbringer
	},
	OffHand = {
		{ 46969, 1 }, -- Steel Bladebreaker
		{ 47416, 1 }, -- Stygian Bladebreaker
		{ 45484, 3 }, -- Bladetwister
		{ 45930, 3 }, -- Combatant's Bootblade
		{ 46958, 3 }, -- Steel Bladebreaker
		{ 47255, 3 }, -- Stygian Bladebreaker
		{ 47001, 3 }, -- Lionhead Slasher
		{ 47427, 3 }, -- Blood Fury
		{ 45494, 3 }, -- Delirium's Touch
		{ 46036, 3 }, -- Void Sabre
		{ 47971, 3 }, -- Westfall Saber
		{ 48048, 3 }, -- Forsaken Bonecarver
		{ 48428, 3 }, -- Relentless Gladiator's Dirk
		{ 46024, 3 }, -- Kingsbane
		{ 46996, 3 }, -- Lionhead Slasher
		{ 47266, 3 }, -- Blood Fury
		{ 45331, 3 }, -- Rune-Etched Nightblade
		{ 45142, 3 }, -- Remorse
		{ 47814, 3 }, -- Westfall Saber
		{ 47903, 3 }, -- Forsaken Bonecarver
	},
	Ranged = {
		{ 47521, 1 }, -- BRK-1000
		{ 47523, 1 }, -- Fezzik's Autocannon
		{ 46995, 3 }, -- Talonstrike
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 47950, 3 }, -- The Diplomat
		{ 48022, 3 }, -- Widebarrel Flintlock
		{ 45296, 3 }, -- Twirling Blades
		{ 48711, 3 }, -- Rhok'shalla, the Shadow's Bane
		{ 48697, 3 }, -- Frenzystrike Longbow
		{ 47659, 3 }, -- Crimson Star
		{ 45570, 3 }, -- Skyforge Crossbow
		{ 47975, 3 }, -- Baelgun's Heavy Crossbow
		{ 48052, 3 }, -- Darkmaw Crossbow
		{ 46994, 3 }, -- Talonstrike
		{ 47267, 3 }, -- Death's Head Crossbow
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 45261, 3 }, -- Giant's Bane
		{ 45327, 3 }, -- Siren's Cry
		{ 45086, 3 }, -- Rising Sun
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/subtlety/dps-bis-gear-pve-phase-4
ns:RegisterBiS("ROGUE", "Subtlety", "P4", {
	Head = {
		{ 51252, 1 }, -- Sanctified Shadowblade Helmet
		{ 51187, 3 }, -- Sanctified Shadowblade Helmet
		{ 51866, 3 }, -- Discarded Bag of Entrails
		{ 50713, 3 }, -- Geistlord's Punishment Sack
		{ 51013, 3 }, -- Discarded Bag of Entrails
		{ 50073, 3 }, -- Geistlord's Punishment Sack
		{ 49477, 3 }, -- Bloodfang Hood
		{ 51745, 3 }, -- Shadowblade Helmet
		{ 47689, 3 }, -- Hood of Lethal Intent
		{ 47688, 3 }, -- Mask of Lethal Intent
		{ 48230, 3 }, -- VanCleef's Helmet of Triumph
		{ 48235, 3 }, -- Garona's Helmet of Triumph
		{ 48225, 3 }, -- VanCleef's Helmet of Triumph
		{ 48240, 3 }, -- Garona's Helmet of Triumph
		{ 45993, 3 }, -- Mimiron's Flight Goggles
	},
	Neck = {
		{ 50633, 1 }, -- Sindragosa's Cruel Claw
		{ 50421, 3 }, -- Sindragosa's Cruel Claw
		{ 51822, 3 }, -- Rimetooth Pendant
		{ 51890, 3 }, -- Precious's Putrid Collar
		{ 51779, 3 }, -- Rimetooth Pendant
		{ 50452, 3 }, -- Wodin's Lucky Necklace
		{ 47915, 3 }, -- Collar of Ceaseless Torment
		{ 47988, 3 }, -- Collar of Unending Torment
		{ 47060, 3 }, -- Charge of the Demon Lord
		{ 47433, 3 }, -- Charge of the Eredar
		{ 45517, 3 }, -- Pendulum of Infinity
		{ 47043, 3 }, -- Charge of the Demon Lord
		{ 47272, 3 }, -- Charge of the Eredar
		{ 49485, 3 }, -- Sparkling Onyxia Tooth Pendant
	},
	Shoulder = {
		{ 51254, 1 }, -- Sanctified Shadowblade Pauldrons
		{ 51185, 3 }, -- Sanctified Shadowblade Pauldrons
		{ 51830, 3 }, -- Skinned Whelp Shoulders
		{ 50646, 3 }, -- Cultist's Bloodsoaked Spaulders
		{ 48228, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48237, 3 }, -- Garona's Pauldrons of Triumph
		{ 51565, 3 }, -- Skinned Whelp Shoulders
		{ 49987, 3 }, -- Cultist's Bloodsoaked Spaulders
		{ 50105, 3 }, -- Shadowblade Pauldrons
		{ 48227, 3 }, -- VanCleef's Pauldrons of Triumph
		{ 48238, 3 }, -- Garona's Pauldrons of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
		{ 47708, 3 }, -- Duskstalker Shoulderpads
		{ 47709, 3 }, -- Duskstalker Pauldrons
		{ 47972, 3 }, -- Spaulders of the Snow Bandit
		{ 48049, 3 }, -- Shoulderpads of the Snow Bandit
	},
	Back = {
		{ 51933, 1 }, -- Shawl of Nerubian Silk
		{ 47545, 3 }, -- Vereesa's Dexterity
		{ 47546, 3 }, -- Sylvanas' Cunning
		{ 50470, 3 }, -- Recovered Scarlet Onslaught Cape
		{ 50653, 3 }, -- Shadowvault Slayer's Cloak
		{ 48673, 3 }, -- Cloak of the Silver Covenant
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 49998, 3 }, -- Shadowvault Slayer's Cloak
		{ 50764, 3 }, -- Shawl of Nerubian Silk
		{ 46032, 3 }, -- Drape of the Faceless General
		{ 45461, 3 }, -- Drape of Icy Intent
		{ 46971, 3 }, -- Drape of the Untamed Predator
		{ 47418, 3 }, -- Cloak of the Untamed Predator
	},
	Chest = {
		{ 51250, 1 }, -- Sanctified Shadowblade Breastplate
		{ 50656, 3 }, -- Ikfirus's Sack of Wonder
		{ 51189, 3 }, -- Sanctified Shadowblade Breastplate
		{ 51923, 3 }, -- Chestguard of the Frigid Noose
		{ 50780, 3 }, -- Chestguard of the Frigid Noose
		{ 50001, 3 }, -- Ikfirus's Sack of Wonder
		{ 50972, 3 }, -- Shadow Seeker's Tunic
		{ 47599, 3 }, -- Knightbane Carapace
		{ 47600, 3 }, -- Knightbane Carapace
		{ 50087, 3 }, -- Shadowblade Breastplate
		{ 47954, 3 }, -- Armor of Shifting Shadows
		{ 48026, 3 }, -- Vest of Shifting Shadows
		{ 47004, 3 }, -- Cuirass of Calamitous Fate
		{ 47431, 3 }, -- Vest of Calamitous Fate
		{ 48232, 3 }, -- VanCleef's Breastplate of Triumph
		{ 48233, 3 }, -- Garona's Breastplate of Triumph
		{ 45473, 3 }, -- Embrace of the Gladiator
	},
	Wrist = {
		{ 54580, 1 }, -- Umbrage Armbands
		{ 50670, 3 }, -- Toskk's Maximized Wristguards
		{ 50333, 3 }, -- Toskk's Maximized Wristguards
		{ 47155, 3 }, -- Bracers of Dark Determination
		{ 47474, 3 }, -- Armbands of Dark Determination
		{ 51820, 3 }, -- Vambraces of the Frost Wyrm Queen
		{ 47581, 3 }, -- Bracers of Swift Death
		{ 47582, 3 }, -- Bracers of Swift Death
		{ 45611, 3 }, -- Solar Bindings
		{ 45869, 3 }, -- Fluxing Energy Coils
		{ 51783, 3 }, -- Vambraces of the Frost Wyrm Queen
		{ 47151, 3 }, -- Bracers of Dark Determination
		{ 47313, 3 }, -- Armbands of Dark Determination
	},
	Hands = {
		{ 50675, 1 }, -- Aldriana's Gloves of Secrecy
		{ 50021, 3 }, -- Aldriana's Gloves of Secrecy
		{ 51904, 3 }, -- Scourge Stranglers
		{ 50982, 3 }, -- Cat Burglar's Grips
		{ 51251, 3 }, -- Sanctified Shadowblade Gauntlets
		{ 50799, 3 }, -- Scourge Stranglers
		{ 47945, 3 }, -- Gloves of the Silver Assassin
		{ 48017, 3 }, -- Sunreaver Assassin's Gloves
		{ 51188, 3 }, -- Sanctified Shadowblade Gauntlets
		{ 48231, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48234, 3 }, -- Garona's Gauntlets of Triumph
		{ 50088, 3 }, -- Shadowblade Gauntlets
		{ 48224, 3 }, -- VanCleef's Gauntlets of Triumph
		{ 48241, 3 }, -- Garona's Gauntlets of Triumph
	},
	Waist = {
		{ 50707, 1 }, -- Astrylian's Sutured Cinch
		{ 50995, 3 }, -- Vengeful Noose
		{ 50067, 3 }, -- Astrylian's Sutured Cinch
		{ 51925, 3 }, -- Soulthief's Braided Belt
		{ 47112, 3 }, -- Belt of the Merciless Killer
		{ 47460, 3 }, -- Belt of the Pitiless Killer
		{ 50778, 3 }, -- Soulthief's Braided Belt
		{ 46095, 3 }, -- Soul-Devouring Cinch
		{ 47107, 3 }, -- Belt of the Merciless Killer
		{ 47299, 3 }, -- Belt of the Pitiless Killer
		{ 45547, 3 }, -- Relic Hunter's Cord
		{ 45555, 3 }, -- Death-warmed Belt
	},
	Legs = {
		{ 51253, 1 }, -- Sanctified Shadowblade Legplates
		{ 51186, 3 }, -- Sanctified Shadowblade Legplates
		{ 50697, 3 }, -- Gangrenous Leggings
		{ 49899, 3 }, -- Bladeborn Leggings
		{ 51841, 3 }, -- Ivory-Inlaid Leggings
		{ 50042, 3 }, -- Gangrenous Leggings
		{ 46975, 3 }, -- Leggings of the Broken Beast
		{ 47420, 3 }, -- Legwraps of the Broken Beast
		{ 51889, 3 }, -- Plague-Soaked Leather Leggings
		{ 45536, 3 }, -- Legguards of Cunning Deception
		{ 50090, 3 }, -- Shadowblade Legplates
		{ 51550, 3 }, -- Ivory-Inlaid Leggings
		{ 48226, 3 }, -- VanCleef's Legplates of Triumph
		{ 48239, 3 }, -- Garona's Legplates of Triumph
		{ 50858, 3 }, -- Plague-Soaked Leather Leggings
		{ 46974, 3 }, -- Leggings of the Broken Beast
		{ 47259, 3 }, -- Legwraps of the Broken Beast
	},
	Feet = {
		{ 50607, 1 }, -- Frostbitten Fur Boots
		{ 51856, 3 }, -- Taldaram's Soft Slippers
		{ 47077, 3 }, -- Treads of the Icewalker
		{ 47445, 3 }, -- Icewalker Treads
		{ 49950, 3 }, -- Frostbitten Fur Boots
		{ 51023, 3 }, -- Taldaram's Soft Slippers
		{ 49895, 3 }, -- Footpads of Impending Death
		{ 47071, 3 }, -- Treads of the Icewalker
		{ 47284, 3 }, -- Icewalker Treads
		{ 47919, 3 }, -- Acidmaw Boots
		{ 47992, 3 }, -- Acidmaw Treads
		{ 45564, 3 }, -- Footpads of Silence
	},
	Ring = {
		{ 50402, 1 }, -- Ashen Band of Endless Vengeance
		{ 54576, 1 }, -- Signet of Twilight
		{ 50604, 3 }, -- Band of the Bone Colossus
		{ 50401, 3 }, -- Ashen Band of Unmatched Vengeance
		{ 50618, 3 }, -- Frostbrood Sapphire Ring
		{ 51900, 3 }, -- Saurfang's Cold-Forged Band
		{ 50186, 3 }, -- Frostbrood Sapphire Ring
		{ 50678, 3 }, -- Seal of Many Mouths
		{ 50803, 3 }, -- Saurfang's Cold-Forged Band
		{ 49949, 3 }, -- Band of the Bone Colossus
		{ 51843, 3 }, -- Seal of the Twilight Queen
		{ 45608, 3 }, -- Brann's Signet Ring
		{ 47730, 3 }, -- Dexterous Brightstone Ring
		{ 50387, 3 }, -- Ashen Band of Greater Vengeance
		{ 47075, 3 }, -- Ring of Callous Aggression
		{ 47443, 3 }, -- Band of Callous Aggression
		{ 51387, 3 }, -- Seal of the Twilight Queen
		{ 47934, 3 }, -- Planestalker Signet
		{ 48007, 3 }, -- Planestalker Band
		{ 46048, 3 }, -- Band of Lights
		{ 47070, 3 }, -- Ring of Callous Aggression
		{ 47282, 3 }, -- Band of Callous Aggression
	},
	Trinket = {
		{ 54590, 1 }, -- Sharpened Twilight Scale
		{ 50363, 1 }, -- Deathbringer's Will
		{ 47131, 3 }, -- Death's Verdict
		{ 47464, 3 }, -- Death's Choice
		{ 50355, 3 }, -- Herkuml War Token
		{ 45609, 3 }, -- Comet's Trail
		{ 50343, 3 }, -- Whispering Fanged Skull
		{ 47115, 3 }, -- Death's Verdict
		{ 47303, 3 }, -- Death's Choice
		{ 50342, 3 }, -- Whispering Fanged Skull
		{ 50362, 3 }, -- Deathbringer's Will
		{ 50706, 3 }, -- Tiny Abomination in a Jar
		{ 50351, 3 }, -- Tiny Abomination in a Jar
		{ 46038, 3 }, -- Dark Matter
	},
	MainHand = {
		{ 50641, 1 }, -- Heartpierce
		{ 50736, 3 }, -- Heaven's Fall, Kryss of a Thousand Lies
		{ 50676, 3 }, -- Rib Spreader
		{ 50426, 3 }, -- Heaven's Fall, Kryss of a Thousand Lies
		{ 49982, 3 }, -- Heartpierce
		{ 51942, 3 }, -- Stormfury, Black Blade of the Betrayer
		{ 51846, 3 }, -- Bloodsipper
		{ 47113, 3 }, -- Twin Spike
		{ 47461, 3 }, -- Gouge of the Frigid Heart
		{ 51800, 3 }, -- Stormfury, Black Blade of the Betrayer
		{ 51518, 3 }, -- Wrathful Gladiator's Spike
		{ 45607, 3 }, -- Fang of Oblivion
		{ 51384, 3 }, -- Bloodsipper
	},
	OffHand = {
		{ 50621, 1 }, -- Lungbreaker
		{ 51868, 3 }, -- Flesh-Carving Scalpel
		{ 50654, 3 }, -- Scourgeborne Waraxe
		{ 50183, 3 }, -- Lungbreaker
		{ 46969, 3 }, -- Steel Bladebreaker
		{ 47416, 3 }, -- Stygian Bladebreaker
		{ 51938, 3 }, -- Bone Warden's Splitter
		{ 51011, 3 }, -- Flesh-Carving Scalpel
		{ 45484, 3 }, -- Bladetwister
		{ 50411, 3 }, -- Scourgeborne Waraxe
		{ 51442, 3 }, -- Wrathful Gladiator's Dirk
		{ 50759, 3 }, -- Bone Warden's Splitter
	},
	Ranged = {
		{ 50733, 1 }, -- Fal'inrush, Defender of Quel'thalas
		{ 51940, 3 }, -- Windrunner's Heartseeker
		{ 51845, 3 }, -- Stakethrower
		{ 46995, 3 }, -- Talonstrike
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 49981, 3 }, -- Fal'inrush, Defender of Quel'thalas
		{ 51927, 3 }, -- Njorndar Bone Bow
		{ 51880, 3 }, -- Gluth's Fetching Knife
		{ 51802, 3 }, -- Windrunner's Heartseeker
		{ 51385, 3 }, -- Stakethrower
		{ 47521, 3 }, -- BRK-1000
		{ 47523, 3 }, -- Fezzik's Autocannon
		{ 50474, 3 }, -- Shrapnel Star
		{ 47950, 3 }, -- The Diplomat
		{ 48022, 3 }, -- Widebarrel Flintlock
	},
})
