-- GENERATED by scripts/build_data.py -- do not edit by hand; the next build
-- overwrites it. Sources: AzerothCore world DB, the realm client's DBC files,
-- and the Wowhead guides listed in scripts/guides.json.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/shaman/elemental/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("SHAMAN", "Elemental", "PreRaid", {
	Head = {
		{ 42555, 1 }, -- Electroflux Sight Enhancers
		{ 34332, 2 }, -- Cowl of Gul'dan
		{ 37180, 2 }, -- Battlemap Hide Helm
		{ 37592, 2 }, -- Brood Plague Helmet
	},
	Neck = {
		{ 42647, 1 }, -- Titanium Spellshock Necklace
		{ 34359, 2 }, -- Pendant of Sunfire
		{ 40681, 2 }, -- Lattice Choker of Light
		{ 37595, 2 }, -- Necklace of Taldaram
		{ 43285, 2 }, -- Amulet of the Spell Flinger
	},
	Shoulder = {
		{ 34390, 1 }, -- Erupting Epaulets
		{ 37875, 1 }, -- Spaulders of the Violet Hold
		{ 37673, 1 }, -- Dark Runic Mantle
		{ 31023, 2 }, -- Skyshatter Mantle
		{ 37398, 2 }, -- Mantle of Discarded Ways
	},
	Back = {
		{ 41610, 1 }, -- Deathchill Cloak
		{ 37291, 2 }, -- Ancient Dragon Spirit Cape
		{ 34242, 2 }, -- Tattered Cape of Antonidas
		{ 44167, 2 }, -- Shroud of Dedicated Research
	},
	Chest = {
		{ 39592, 1 }, -- Heroes' Earthshatter Hauberk
		{ 43461, 2 }, -- Revenant's Breastplate
		{ 43410, 2 }, -- Moragg's Chestguard
		{ 37256, 2 }, -- Scaled Armor of Drakos
		{ 34396, 2 }, -- Garments of Crashing Shores
		{ 31017, 2 }, -- Skyshatter Breastplate
	},
	Wrist = {
		{ 37788, 1 }, -- Limb Regeneration Bracers
		{ 37884, 1 }, -- Azure Cloth Bindings
		{ 34437, 2 }, -- Skyshatter Bands
		{ 37725, 2 }, -- Savage Wound Wrap
		{ 32586, 2 }, -- Bracers of Nimble Thought
	},
	Hands = {
		{ 39593, 1 }, -- Heroes' Earthshatter Gloves
		{ 37623, 2 }, -- Fiery Obelisk Handguards
		{ 42113, 2 }, -- Spellweave Gloves
		{ 34344, 2 }, -- Handguards of Defiled Worlds
		{ 34350, 2 }, -- Gauntlets of the Ancient Shadowmoon
	},
	Waist = {
		{ 40696, 1 }, -- Plush Sash of Guzbah
		{ 44181, 2 }, -- Ghostflicker Waistband
		{ 37643, 2 }, -- Sash of Blood Removal
		{ 34542, 2 }, -- Skyshatter Cord
		{ 30038, 2 }, -- Belt of Blasting
	},
	Legs = {
		{ 37695, 1 }, -- Legguards of Nature's Power
		{ 37791, 1 }, -- Leggings of the Winged Serpent
		{ 44931, 1 }, -- Windripper Leggings
		{ 34186, 2 }, -- Chain Links of the Tumultuous Storm
	},
	Feet = {
		{ 43469, 1 }, -- Revenant's Treads
		{ 44202, 1 }, -- Sandals of Crimson Fury
		{ 44930, 1 }, -- Windripper Boots
		{ 37654, 2 }, -- Sabatons of the Ages
		{ 34566, 2 }, -- Skyshatter Treads
	},
	Ring = {
		{ 40585, 1 }, -- Signet of the Kirin Tor
		{ 42644, 1 }, -- Titanium Spellshock Ring
		{ 43253, 1 }, -- Ring of Northern Tears
		{ 37694, 2 }, -- Band of Guile
		{ 37192, 2 }, -- Annhylde's Ring
		{ 34230, 2 }, -- Ring of Omnipotence
		{ 34362, 2 }, -- Loop of Forged Power
	},
	Trinket = {
		{ 40682, 1 }, -- Sundial of the Exiled
		{ 37873, 1 }, -- Mark of the War Prisoner
		{ 42395, 1 }, -- Figurine - Twilight Serpent
		{ 37660, 2 }, -- Forge Ember
		{ 32483, 2 }, -- The Skull of Gul'dan
		{ 34429, 2 }, -- Shifting Naaru Sliver
	},
	MainHand = {
		{ 41384, 1 }, -- Titansteel Guardian
		{ 45085, 1 }, -- Titansteel Spellblade
		{ 44173, 2 }, -- Flameheart Spell Scalpel
		{ 37169, 2 }, -- War Mace of Unrequited Love
		{ 44199, 2 }, -- Gavel of the Brewing Storm
		{ 34336, 2 }, -- Sunflare
	},
	OffHand = {
		{ 40698, 1 }, -- Ward of the Violet Citadel
		{ 40700, 1 }, -- Protective Barricade of the Light
		{ 38322, 2 }, -- Iron-bound Tome
		{ 37061, 2 }, -- Tor's Crest
		{ 30872, 2 }, -- Chronicle of Dark Secrets
		{ 34179, 2 }, -- Heart of the Pit
	},
	Ranged = {
		{ 40708, 1 }, -- Totem of the Elemental Plane
		{ 32330, 2 }, -- Totem of Ancestral Guidance
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/elemental/dps-bis-gear-pve-phase-1
ns:RegisterBiS("SHAMAN", "Elemental", "P1", {
	Head = {
		{ 40516, 1 }, -- Valorous Earthshatter Helm
		{ 39594, 2 }, -- Heroes' Earthshatter Helm
		{ 40339, 2 }, -- Gothik's Cowl
		{ 39405, 2 }, -- Helmet of the Inner Sanctum
		{ 42555, 2 }, -- Electroflux Sight Enhancers
	},
	Neck = {
		{ 44661, 1 }, -- Wyrmrest Necklace of Power
		{ 40374, 2 }, -- Cosmic Lights
		{ 44658, 2 }, -- Chain of the Ancient Wyrm
		{ 39472, 2 }, -- Chain of Latent Energies
		{ 42647, 2 }, -- Titanium Spellshock Necklace
	},
	Shoulder = {
		{ 40286, 1 }, -- Mantle of the Corrupted
		{ 40518, 2 }, -- Valorous Earthshatter Shoulderpads
		{ 39596, 2 }, -- Heroes' Earthshatter Shoulderpads
		{ 40439, 2 }, -- Mantle of the Eternal Sentinel
	},
	Back = {
		{ 44005, 1 }, -- Pennant Cloak
		{ 41610, 2 }, -- Deathchill Cloak
		{ 40251, 2 }, -- Shroud of Luminosity
		{ 39415, 2 }, -- Shroud of the Citadel
	},
	Chest = {
		{ 40514, 1 }, -- Valorous Earthshatter Hauberk
		{ 39592, 2 }, -- Heroes' Earthshatter Hauberk
		{ 40283, 2 }, -- Fallout Impervious Tunic
		{ 40526, 2 }, -- Gown of the Spell-Weaver
		{ 40234, 2 }, -- Heigan's Putrid Vestments
	},
	Wrist = {
		{ 40324, 1 }, -- Bands of Mutual Respect
		{ 40325, 1 }, -- Bindings of the Expansive Mind
		{ 37788, 2 }, -- Limb Regeneration Bracers
		{ 37884, 2 }, -- Azure Cloth Bindings
	},
	Hands = {
		{ 40302, 1 }, -- Benefactor's Gauntlets
		{ 40515, 2 }, -- Valorous Earthshatter Gloves
		{ 39593, 2 }, -- Heroes' Earthshatter Gloves
		{ 40380, 2 }, -- Gloves of Grandeur
		{ 39243, 2 }, -- Handgrips of the Foredoomed
	},
	Waist = {
		{ 40301, 1 }, -- Cincture of Polarity
		{ 40327, 2 }, -- Girdle of Recuperation
		{ 40696, 2 }, -- Plush Sash of Guzbah
		{ 44181, 2 }, -- Ghostflicker Waistband
	},
	Legs = {
		{ 40560, 1 }, -- Leggings of the Wanton Spellcaster
		{ 40352, 2 }, -- Leggings of Voracious Shadows
		{ 39720, 2 }, -- Leggings of Atrophy
		{ 40517, 2 }, -- Valorous Earthshatter Kilt
		{ 39595, 2 }, -- Heroes' Earthshatter Kilt
	},
	Feet = {
		{ 40519, 1 }, -- Footsteps of Malygos
		{ 40237, 1 }, -- Eruption-Scarred Boots
		{ 40246, 1 }, -- Boots of Impetuous Ideals
		{ 43469, 2 }, -- Revenant's Treads
	},
	Ring = {
		{ 40399, 1 }, -- Signet of Manifested Pain
		{ 37694, 1 }, -- Band of Guile
		{ 39389, 2 }, -- Signet of the Malevolent
		{ 40585, 2 }, -- Signet of the Kirin Tor
		{ 39244, 2 }, -- Ring of the Fated
		{ 42644, 2 }, -- Titanium Spellshock Ring
		{ 43253, 2 }, -- Ring of Northern Tears
	},
	Trinket = {
		{ 40432, 1 }, -- Illustration of the Dragon Soul
		{ 40255, 1 }, -- Dying Curse
		{ 39229, 2 }, -- Embrace of the Spider
		{ 40682, 2 }, -- Sundial of the Exiled
		{ 37873, 2 }, -- Mark of the War Prisoner
		{ 42395, 2 }, -- Figurine - Twilight Serpent
	},
	MainHand = {
		{ 40395, 1 }, -- Torch of Holy Fire
		{ 39763, 2 }, -- Wraith Strike
		{ 39423, 2 }, -- Hammer of the Astral Plane
		{ 41384, 2 }, -- Titansteel Guardian
		{ 45085, 2 }, -- Titansteel Spellblade
	},
	OffHand = {
		{ 40401, 1 }, -- Voice of Reason
		{ 39233, 2 }, -- Aegis of Damnation
		{ 40273, 2 }, -- Surplus Limb
		{ 40698, 2 }, -- Ward of the Violet Citadel
	},
	Ranged = {
		{ 40267, 1 }, -- Totem of Hex
		{ 40708, 2 }, -- Totem of the Elemental Plane
		{ 32330, 2 }, -- Totem of Ancestral Guidance
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/elemental/dps-bis-gear-pve-phase-2
ns:RegisterBiS("SHAMAN", "Elemental", "P2", {
	Head = {
		{ 46209, 1 }, -- Conqueror's Worldbreaker Helm
		{ 45408, 2 }, -- Valorous Worldbreaker Helm
	},
	Neck = {
		{ 45933, 1 }, -- Pendant of the Shallow Grave
		{ 45133, 2 }, -- Pendant of Fiery Havoc
		{ 44661, 2 }, -- Wyrmrest Necklace of Power
		{ 45443, 2 }, -- Charm of Meticulous Timing
		{ 46047, 2 }, -- Pendant of the Somber Witness
	},
	Shoulder = {
		{ 46211, 1 }, -- Conqueror's Worldbreaker Shoulderpads
		{ 45410, 2 }, -- Valorous Worldbreaker Shoulderpads
		{ 46044, 2 }, -- Observer's Mantle
		{ 45474, 2 }, -- Pauldrons of the Combatant
	},
	Back = {
		{ 45242, 1 }, -- Drape of Mortal Downfall
		{ 46042, 2 }, -- Drape of the Messenger
		{ 44005, 2 }, -- Pennant Cloak
		{ 45486, 2 }, -- Drape of the Sullen Goddess
	},
	Chest = {
		{ 46206, 1 }, -- Conqueror's Worldbreaker Hauberk
		{ 45411, 2 }, -- Valorous Worldbreaker Hauberk
		{ 45867, 2 }, -- Breastplate of the Stoneshaper
	},
	Wrist = {
		{ 45460, 1 }, -- Bindings of Winter Gale
		{ 45275, 2 }, -- Bracers of Unleashed Magic
		{ 40324, 2 }, -- Bands of Mutual Respect
	},
	Hands = {
		{ 45665, 1 }, -- Pharos Gloves
		{ 46207, 1 }, -- Conqueror's Worldbreaker Gloves
		{ 45406, 2 }, -- Valorous Worldbreaker Gloves
		{ 45943, 2 }, -- Gloves of Whispering Winds
	},
	Waist = {
		{ 45616, 1 }, -- Star-beaded Clutch
		{ 45151, 2 }, -- Belt of the Fallen Wyrm
		{ 45557, 2 }, -- Sash of Ancient Power
		{ 45554, 2 }, -- Blue Belt of Chaos
	},
	Legs = {
		{ 46210, 1 }, -- Conqueror's Worldbreaker Kilt
		{ 45409, 2 }, -- Valorous Worldbreaker Kilt
		{ 45488, 2 }, -- Leggings of the Enslaved Idol
		{ 45238, 2 }, -- Overload Legwraps
	},
	Feet = {
		{ 45537, 1 }, -- Treads of the False Oracle
		{ 45615, 2 }, -- Planewalker Treads
		{ 45563, 2 }, -- Lightning Grounded Boots
	},
	Ring = {
		{ 45495, 1 }, -- Conductive Seal
		{ 46046, 1 }, -- Nebula Band
		{ 45614, 2 }, -- Starshine Circle
		{ 45946, 2 }, -- Fire Orchid Signet
		{ 45168, 2 }, -- Pyrelight Circle
		{ 45451, 2 }, -- Frozen Loop
		{ 40399, 2 }, -- Signet of Manifested Pain
	},
	Trinket = {
		{ 45518, 1 }, -- Flare of the Heavens
		{ 40255, 1 }, -- Dying Curse
		{ 45466, 2 }, -- Scale of Fates
		{ 45148, 2 }, -- Living Flame
		{ 45308, 2 }, -- Eye of the Broodmother
		{ 40432, 2 }, -- Illustration of the Dragon Soul
	},
	MainHand = {
		{ 45612, 1 }, -- Constellus
		{ 45970, 2 }, -- Furious Gladiator's Mageblade
		{ 45620, 2 }, -- Starshard Edge
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
		{ 45527, 2 }, -- Soulscribe
	},
	OffHand = {
		{ 45470, 1 }, -- Wisdom's Hold
		{ 45617, 2 }, -- Cosmos
		{ 45887, 2 }, -- Ice Layered Barrier
		{ 40401, 2 }, -- Voice of Reason
		{ 45682, 2 }, -- Pulsing Spellshield
	},
	Ranged = {
		{ 40267, 1 }, -- Totem of Hex
		{ 40708, 2 }, -- Totem of the Elemental Plane
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/elemental/dps-bis-gear-pve-phase-3
ns:RegisterBiS("SHAMAN", "Elemental", "P3", {
	Head = {
		{ 48323, 1 }, -- Nobundo's Helm of Triumph
		{ 48328, 1 }, -- Thrall's Helm of Triumph
		{ 48318, 2 }, -- Nobundo's Helm of Triumph
		{ 48333, 2 }, -- Thrall's Helm of Triumph
		{ 48313, 2 }, -- Nobundo's Helm of Conquest
		{ 48338, 2 }, -- Thrall's Helm of Conquest
		{ 46209, 2 }, -- Conqueror's Worldbreaker Helm
	},
	Neck = {
		{ 47144, 1 }, -- Wail of the Val'kyr
		{ 47468, 1 }, -- Cry of the Val'kyr
		{ 45933, 2 }, -- Pendant of the Shallow Grave
		{ 45133, 2 }, -- Pendant of Fiery Havoc
		{ 44661, 2 }, -- Wyrmrest Necklace of Power
		{ 45443, 2 }, -- Charm of Meticulous Timing
	},
	Shoulder = {
		{ 48321, 1 }, -- Nobundo's Shoulderpads of Triumph
		{ 48330, 1 }, -- Thrall's Shoulderpads of Triumph
		{ 48320, 2 }, -- Nobundo's Shoulderpads of Triumph
		{ 48331, 2 }, -- Thrall's Shoulderpads of Triumph
		{ 48315, 2 }, -- Nobundo's Shoulderpads of Conquest
		{ 48340, 2 }, -- Thrall's Shoulderpads of Conquest
		{ 46211, 2 }, -- Conqueror's Worldbreaker Shoulderpads
		{ 46044, 2 }, -- Observer's Mantle
		{ 45474, 2 }, -- Pauldrons of the Combatant
	},
	Back = {
		{ 47552, 1 }, -- Jaina's Radiance
		{ 47551, 1 }, -- Aethas' Intensity
		{ 48671, 2 }, -- Drape of Bitter Incantation
		{ 48666, 2 }, -- Drape of the Sunreavers
		{ 47095, 2 }, -- Cloak of Displacement
		{ 47452, 2 }, -- Shroud of Displacement
		{ 45242, 2 }, -- Drape of Mortal Downfall
		{ 46042, 2 }, -- Drape of the Messenger
		{ 49491, 2 }, -- Flowing Sapphiron Drape
		{ 44005, 2 }, -- Pennant Cloak
		{ 45486, 2 }, -- Drape of the Sullen Goddess
	},
	Chest = {
		{ 48325, 1 }, -- Nobundo's Hauberk of Triumph
		{ 48326, 1 }, -- Thrall's Hauberk of Triumph
		{ 47603, 2 }, -- Merlin's Robe
		{ 47604, 2 }, -- Merlin's Robe
		{ 48316, 2 }, -- Nobundo's Hauberk of Triumph
		{ 48335, 2 }, -- Thrall's Hauberk of Triumph
		{ 48310, 2 }, -- Nobundo's Hauberk of Conquest
		{ 48336, 2 }, -- Thrall's Hauberk of Conquest
		{ 46206, 2 }, -- Conqueror's Worldbreaker Hauberk
		{ 45867, 2 }, -- Breastplate of the Stoneshaper
	},
	Wrist = {
		{ 45460, 1 }, -- Bindings of Winter Gale
		{ 47586, 2 }, -- Bejeweled Wizard's Bracers
		{ 47143, 2 }, -- Bindings of Dark Essence
		{ 47467, 2 }, -- Dark Essence Bindings
		{ 47927, 2 }, -- Felspark Bindings
		{ 48000, 2 }, -- Felspark Bracers
		{ 45275, 2 }, -- Bracers of Unleashed Magic
		{ 40324, 2 }, -- Bands of Mutual Respect
	},
	Hands = {
		{ 48324, 1 }, -- Nobundo's Gloves of Triumph
		{ 48327, 1 }, -- Thrall's Gloves of Triumph
		{ 48317, 2 }, -- Nobundo's Gloves of Triumph
		{ 48334, 2 }, -- Thrall's Gloves of Triumph
		{ 48312, 2 }, -- Nobundo's Gloves of Conquest
		{ 48337, 2 }, -- Thrall's Gloves of Conquest
		{ 45665, 2 }, -- Pharos Gloves
		{ 46207, 2 }, -- Conqueror's Worldbreaker Gloves
		{ 45943, 2 }, -- Gloves of Whispering Winds
	},
	Waist = {
		{ 47084, 1 }, -- Cord of Biting Cold
		{ 47447, 1 }, -- Belt of Biting Cold
		{ 47994, 2 }, -- Icehowl Binding
		{ 47921, 2 }, -- Icehowl Cinch
		{ 45616, 2 }, -- Star-beaded Clutch
		{ 45151, 2 }, -- Belt of the Fallen Wyrm
		{ 45557, 2 }, -- Sash of Ancient Power
		{ 45554, 2 }, -- Blue Belt of Chaos
	},
	Legs = {
		{ 47190, 1 }, -- Legwraps of the Awakening
		{ 47479, 1 }, -- Leggings of the Awakening
		{ 48322, 2 }, -- Nobundo's Kilt of Triumph
		{ 48329, 2 }, -- Thrall's Kilt of Triumph
		{ 48319, 2 }, -- Nobundo's Kilt of Triumph
		{ 48332, 2 }, -- Thrall's Kilt of Triumph
		{ 48314, 2 }, -- Nobundo's Kilt of Conquest
		{ 48339, 2 }, -- Thrall's Kilt of Conquest
		{ 46210, 2 }, -- Conqueror's Worldbreaker Kilt
		{ 45488, 2 }, -- Leggings of the Enslaved Idol
	},
	Feet = {
		{ 47099, 1 }, -- Boots of Tremoring Earth
		{ 47456, 1 }, -- Sabatons of Tremoring Earth
		{ 45537, 2 }, -- Treads of the False Oracle
		{ 45615, 2 }, -- Planewalker Treads
		{ 49238, 2 }, -- Boots of Tortured Space
		{ 49237, 2 }, -- Sabatons of Tortured Space
		{ 45563, 2 }, -- Lightning Grounded Boots
	},
	Ring = {
		{ 45495, 1 }, -- Conductive Seal
		{ 46046, 1 }, -- Nebula Band
		{ 47928, 2 }, -- Firestorm Ring
		{ 48001, 2 }, -- Firestorm Band
		{ 47224, 2 }, -- Ring of the Darkmender
		{ 47439, 2 }, -- Circle of the Darkmender
		{ 45614, 2 }, -- Starshine Circle
		{ 45168, 2 }, -- Pyrelight Circle
		{ 45451, 2 }, -- Frozen Loop
	},
	Trinket = {
		{ 47188, 1 }, -- Reign of the Unliving
		{ 47477, 1 }, -- Reign of the Dead
		{ 45518, 1 }, -- Flare of the Heavens
		{ 47213, 2 }, -- Abyssal Rune
		{ 40255, 2 }, -- Dying Curse
		{ 45466, 2 }, -- Scale of Fates
		{ 45148, 2 }, -- Living Flame
		{ 45308, 2 }, -- Eye of the Broodmother
		{ 40432, 2 }, -- Illustration of the Dragon Soul
	},
	MainHand = {
		{ 46980, 1 }, -- Blade of Tarasque
		{ 47422, 1 }, -- Barb of Tarasque
		{ 47206, 2 }, -- Misery's End
		{ 47483, 2 }, -- Suffering's End
		{ 45612, 2 }, -- Constellus
		{ 45620, 2 }, -- Starshard Edge
		{ 48709, 2 }, -- Heartcrusher
		{ 48693, 2 }, -- Heartsmasher
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
		{ 45527, 2 }, -- Soulscribe
	},
	OffHand = {
		{ 47085, 1 }, -- Bastion of Purity
		{ 47448, 1 }, -- Bastion of Resolve
		{ 45470, 2 }, -- Wisdom's Hold
		{ 45617, 2 }, -- Cosmos
		{ 45887, 2 }, -- Ice Layered Barrier
		{ 40401, 2 }, -- Voice of Reason
	},
	Ranged = {
		{ 47666, 1 }, -- Totem of Electrifying Wind
		{ 40267, 2 }, -- Totem of Hex
		{ 40708, 2 }, -- Totem of the Elemental Plane
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/elemental/dps-bis-gear-pve-phase-4
ns:RegisterBiS("SHAMAN", "Elemental", "P4", {
	Head = {
		{ 51237, 1 }, -- Sanctified Frost Witch's Helm
		{ 51202, 2 }, -- Sanctified Frost Witch's Helm
		{ 50843, 2 }, -- Frost Witch's Helm
		{ 48323, 2 }, -- Nobundo's Helm of Triumph
		{ 48328, 2 }, -- Thrall's Helm of Triumph
		{ 46209, 2 }, -- Conqueror's Worldbreaker Helm
	},
	Neck = {
		{ 50658, 1 }, -- Amulet of the Silent Eulogy
		{ 50724, 2 }, -- Blood Queen's Crimson Choker
		{ 51894, 2 }, -- Soulcleave Pendant
		{ 47144, 2 }, -- Wail of the Val'kyr
		{ 47468, 2 }, -- Cry of the Val'kyr
		{ 45133, 2 }, -- Pendant of Fiery Havoc
		{ 45933, 2 }, -- Pendant of the Shallow Grave
	},
	Shoulder = {
		{ 50698, 1 }, -- Horrific Flesh Epaulets
		{ 51235, 1 }, -- Sanctified Frost Witch's Shoulderpads
		{ 51204, 2 }, -- Sanctified Frost Witch's Shoulderpads
		{ 50845, 2 }, -- Frost Witch's Shoulderpads
		{ 48321, 2 }, -- Nobundo's Shoulderpads of Triumph
		{ 48330, 2 }, -- Thrall's Shoulderpads of Triumph
		{ 46044, 2 }, -- Observer's Mantle
	},
	Back = {
		{ 54583, 1 }, -- Cloak of Burning Dusk
		{ 50628, 2 }, -- Frostbinder's Shredded Cape
		{ 47552, 2 }, -- Jaina's Radiance
		{ 47551, 2 }, -- Aethas' Intensity
		{ 48671, 2 }, -- Drape of Bitter Incantation
		{ 48666, 2 }, -- Drape of the Sunreavers
		{ 47095, 2 }, -- Cloak of Displacement
		{ 47452, 2 }, -- Shroud of Displacement
		{ 45242, 2 }, -- Drape of Mortal Downfall
		{ 46042, 2 }, -- Drape of the Messenger
	},
	Chest = {
		{ 51239, 1 }, -- Sanctified Frost Witch's Hauberk
		{ 51200, 2 }, -- Sanctified Frost Witch's Hauberk
		{ 50841, 2 }, -- Frost Witch's Hauberk
		{ 48325, 2 }, -- Nobundo's Hauberk of Triumph
		{ 48326, 2 }, -- Thrall's Hauberk of Triumph
		{ 47603, 2 }, -- Merlin's Robe
		{ 47604, 2 }, -- Merlin's Robe
		{ 45867, 2 }, -- Breastplate of the Stoneshaper
	},
	Wrist = {
		{ 54582, 1 }, -- Bracers of Fiery Night
		{ 54584, 2 }, -- Phaseshifter's Bracers
		{ 50687, 2 }, -- Bloodsunder's Bracers
		{ 45460, 2 }, -- Bindings of Winter Gale
		{ 47586, 2 }, -- Bejeweled Wizard's Bracers
		{ 47143, 2 }, -- Bindings of Dark Essence
		{ 47467, 2 }, -- Dark Essence Bindings
		{ 47927, 2 }, -- Felspark Bindings
		{ 48000, 2 }, -- Felspark Bracers
	},
	Hands = {
		{ 51238, 1 }, -- Sanctified Frost Witch's Gloves
		{ 51201, 2 }, -- Sanctified Frost Witch's Gloves
		{ 50842, 2 }, -- Frost Witch's Gloves
		{ 54560, 2 }, -- Changeling Gloves
		{ 51827, 2 }, -- Stormbringer Gloves
		{ 48324, 2 }, -- Nobundo's Gloves of Triumph
		{ 48327, 2 }, -- Thrall's Gloves of Triumph
		{ 45943, 2 }, -- Gloves of Whispering Winds
	},
	Waist = {
		{ 54587, 1 }, -- Split Shape Belt
		{ 50613, 2 }, -- Crushing Coldwraith Belt
		{ 50992, 2 }, -- Waistband of Despair
		{ 47084, 2 }, -- Cord of Biting Cold
		{ 47447, 2 }, -- Belt of Biting Cold
		{ 47994, 2 }, -- Icehowl Binding
		{ 47921, 2 }, -- Icehowl Cinch
		{ 45616, 2 }, -- Star-beaded Clutch
		{ 45557, 2 }, -- Sash of Ancient Power
	},
	Legs = {
		{ 51236, 1 }, -- Sanctified Frost Witch's Kilt
		{ 51203, 2 }, -- Sanctified Frost Witch's Kilt
		{ 50844, 2 }, -- Frost Witch's Kilt
		{ 50694, 2 }, -- Plaguebringer's Stained Pants
		{ 49891, 2 }, -- Leggings of Woven Death
		{ 49900, 2 }, -- Lightning-Infused Leggings
		{ 47190, 2 }, -- Legwraps of the Awakening
		{ 47479, 2 }, -- Leggings of the Awakening
		{ 48322, 2 }, -- Nobundo's Kilt of Triumph
		{ 48329, 2 }, -- Thrall's Kilt of Triumph
	},
	Feet = {
		{ 50699, 1 }, -- Plague Scientist's Boots
		{ 49896, 2 }, -- Earthsoul Boots
		{ 47099, 2 }, -- Boots of Tremoring Earth
		{ 47456, 2 }, -- Sabatons of Tremoring Earth
		{ 45537, 2 }, -- Treads of the False Oracle
	},
	Ring = {
		{ 50664, 1 }, -- Ring of Rapid Ascent
		{ 50398, 1 }, -- Ashen Band of Endless Destruction
		{ 50714, 2 }, -- Valanar's Other Signet Ring
		{ 54563, 2 }, -- Saviana's Tribute
		{ 45495, 2 }, -- Conductive Seal
		{ 46046, 2 }, -- Nebula Band
	},
	Trinket = {
		{ 50348, 1 }, -- Dislodged Foreign Object
		{ 50365, 1 }, -- Phylactery of the Nameless Lich
		{ 54588, 2 }, -- Charred Twilight Scale
		{ 47188, 2 }, -- Reign of the Unliving
		{ 47477, 2 }, -- Reign of the Dead
		{ 45518, 2 }, -- Flare of the Heavens
		{ 50345, 2 }, -- Muradin's Spyglass
		{ 47182, 2 }, -- Reign of the Unliving
		{ 47316, 2 }, -- Reign of the Dead
	},
	MainHand = {
		{ 50734, 1 }, -- Royal Scepter of Terenas II
		{ 50608, 2 }, -- Frozen Bonespike
		{ 51939, 2 }, -- Tel'thas, Dagger of the Blood King
		{ 46980, 2 }, -- Blade of Tarasque
		{ 47422, 2 }, -- Barb of Tarasque
		{ 47206, 2 }, -- Misery's End
		{ 47483, 2 }, -- Suffering's End
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
	},
	OffHand = {
		{ 50616, 1 }, -- Bulwark of Smouldering Steel
		{ 47085, 2 }, -- Bastion of Purity
		{ 47448, 2 }, -- Bastion of Resolve
		{ 45470, 2 }, -- Wisdom's Hold
		{ 47079, 2 }, -- Bastion of Purity
		{ 47287, 2 }, -- Bastion of Resolve
	},
	Ranged = {
		{ 50458, 1 }, -- Bizuri's Totem of Shattered Ice
		{ 47666, 2 }, -- Totem of Electrifying Wind
		{ 40267, 2 }, -- Totem of Hex
		{ 40708, 2 }, -- Totem of the Elemental Plane
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/enhancement/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("SHAMAN", "Enhancement", "PreRaid", {
	Head = {
		{ 42551, 1 }, -- Truesight Ice Blinders
		{ 37293, 2 }, -- Mask of the Watcher
		{ 43311, 2 }, -- Helmet of the Shrine
		{ 34244, 2 }, -- Duplicitous Guise
		{ 32235, 2 }, -- Cursed Vision of Sargeras
	},
	Neck = {
		{ 40678, 1 }, -- Pendant of the Outcast Hero
		{ 37096, 2 }, -- Necklace of the Chrono-Lord
		{ 37595, 2 }, -- Necklace of Taldaram
		{ 42645, 2 }, -- Titanium Impact Choker
		{ 34177, 2 }, -- Clutch of Demise
	},
	Shoulder = {
		{ 37373, 1 }, -- Massive Spaulders of the Jormungar
		{ 43481, 2 }, -- Trollwoven Spaulders
		{ 37679, 2 }, -- Spaulders of the Abomination
		{ 44257, 2 }, -- Spaulders of the Black Arrow
		{ 31024, 2 }, -- Skyshatter Pauldrons
	},
	Back = {
		{ 43566, 1 }, -- Ice Striker's Cloak
		{ 37840, 1 }, -- Shroud of Reverberation
		{ 38614, 2 }, -- Embrace of Sorrow
		{ 34241, 2 }, -- Cloak of Unforgivable Sin
	},
	Chest = {
		{ 39597, 1 }, -- Heroes' Earthshatter Chestguard
		{ 44295, 2 }, -- Polished Regimental Hauberk
		{ 37219, 2 }, -- Custodian's Chestpiece
		{ 37800, 2 }, -- Aviary Guardsman's Hauberk
		{ 34369, 2 }, -- Carapace of Sun and Shadow
	},
	Wrist = {
		{ 43131, 1 }, -- Eaglebane Bracers
		{ 37656, 2 }, -- Raging Construct Bands
		{ 40490, 2 }, -- Necromantic Wristguards
		{ 37170, 2 }, -- Interwoven Scale Bracers
		{ 34439, 2 }, -- Skyshatter Wristguards
	},
	Hands = {
		{ 39601, 1 }, -- Heroes' Earthshatter Grips
		{ 37409, 2 }, -- Gilt-Edged Leather Gauntlets
		{ 37886, 2 }, -- Handgrips of the Savage Emissary
		{ 37639, 2 }, -- Grips of the Beast God
		{ 34374, 2 }, -- Fletcher's Gloves of the Phoenix
	},
	Waist = {
		{ 37407, 1 }, -- Sovereign's Belt
		{ 40692, 2 }, -- Vereesa's Silver Chain Belt
		{ 40694, 2 }, -- Jorach's Crocolisk Skin Belt
		{ 37194, 2 }, -- Sharp-Barbed Leather Belt
		{ 34545, 2 }, -- Skyshatter Girdle
	},
	Legs = {
		{ 37644, 1 }, -- Gored Hide Legguards
		{ 37669, 1 }, -- Leggings of the Stone Halls
		{ 37221, 1 }, -- Hollowed Mandible Legplates
		{ 44179, 2 }, -- Mind-Expanding Leggings
		{ 34168, 2 }, -- Starstalker Legguards
	},
	Feet = {
		{ 44297, 1 }, -- Boots of the Neverending Path
		{ 37167, 2 }, -- Dragon Slayer's Sabatons
		{ 37666, 2 }, -- Boots of the Whirling Mist
		{ 37870, 2 }, -- Twin-Headed Boots
		{ 44182, 2 }, -- Boots of Twinkling Stars
		{ 34567, 2 }, -- Skyshatter Greaves
	},
	Ring = {
		{ 37642, 1 }, -- Hemorrhaging Circle
		{ 40586, 1 }, -- Band of the Kirin Tor
		{ 37685, 1 }, -- Mobius Band
		{ 37651, 2 }, -- The Prospector's Prize
		{ 43251, 2 }, -- Ring of Scarlet Shadows
		{ 34361, 2 }, -- Hard Khorium Band
		{ 32526, 2 }, -- Band of Devastation
	},
	Trinket = {
		{ 40684, 1 }, -- Mirror of Truth
		{ 37390, 1 }, -- Meteorite Whetstone
		{ 44253, 2 }, -- Darkmoon Card: Greatness
		{ 37166, 2 }, -- Sphere of Red Dragon's Blood
		{ 43573, 2 }, -- Tears of Bitter Anguish
		{ 34427, 2 }, -- Blackened Naaru Sliver
		{ 28830, 2 }, -- Dragonspine Trophy
	},
	MainHand = {
		{ 45085, 1 }, -- Titansteel Spellblade
		{ 41384, 1 }, -- Titansteel Guardian
		{ 41383, 1 }, -- Titansteel Bonecrusher
		{ 37693, 2 }, -- Greed
		{ 37871, 2 }, -- The Key
		{ 44192, 2 }, -- Stalactite Chopper
		{ 34331, 2 }, -- Hand of the Deceiver
	},
	OffHand = {
		{ 40704, 1 }, -- Pride
		{ 34346, 2 }, -- Mounting Vengeance
	},
	Ranged = {
		{ 40708, 1 }, -- Totem of the Elemental Plane
		{ 37575, 2 }, -- Totem of the Tundra
		{ 33507, 2 }, -- Stonebreaker's Totem
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/enhancement/dps-bis-gear-pve-phase-1
ns:RegisterBiS("SHAMAN", "Enhancement", "P1", {
	Head = {
		{ 40543, 1 }, -- Blue Aspect Helm
		{ 40521, 1 }, -- Valorous Earthshatter Faceguard
		{ 39602, 2 }, -- Heroes' Earthshatter Faceguard
		{ 40451, 2 }, -- Hyaline Helm of the Sniper
		{ 40329, 2 }, -- Hood of the Exodus
		{ 42551, 2 }, -- Truesight Ice Blinders
	},
	Neck = {
		{ 44661, 1 }, -- Wyrmrest Necklace of Power
		{ 39146, 2 }, -- Collar of Dissolution
		{ 40065, 2 }, -- Fool's Trial
		{ 44658, 2 }, -- Chain of the Ancient Wyrm
		{ 40369, 2 }, -- Icy Blast Amulet
		{ 40678, 2 }, -- Pendant of the Outcast Hero
	},
	Shoulder = {
		{ 40524, 1 }, -- Valorous Earthshatter Shoulderguards
		{ 39604, 2 }, -- Heroes' Earthshatter Shoulderguards
		{ 40315, 2 }, -- Shoulderpads of Secret Arts
		{ 40299, 2 }, -- Pauldrons of the Abandoned
		{ 44003, 2 }, -- Upstanding Spaulders
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 44005, 2 }, -- Pennant Cloak
		{ 39404, 2 }, -- Cloak of Mastery
		{ 40721, 2 }, -- Hammerhead Sharkskin Cloak
		{ 40250, 2 }, -- Aged Winter Cloak
	},
	Chest = {
		{ 40523, 1 }, -- Valorous Earthshatter Chestguard
		{ 39597, 2 }, -- Heroes' Earthshatter Chestguard
		{ 39724, 2 }, -- Cult's Chestguard
		{ 40539, 2 }, -- Chestguard of the Recluse
		{ 43998, 2 }, -- Chestguard of Flagrant Prowess
		{ 44295, 2 }, -- Polished Regimental Hauberk
	},
	Wrist = {
		{ 40736, 1 }, -- Armguard of the Tower Archer
		{ 40186, 1 }, -- Thrusting Bands
		{ 40282, 1 }, -- Slime Stream Bands
		{ 39702, 2 }, -- Arachnoid Gold Band
		{ 43131, 2 }, -- Eaglebane Bracers
	},
	Hands = {
		{ 40520, 1 }, -- Valorous Earthshatter Grips
		{ 40541, 1 }, -- Frosted Adroit Handguards
		{ 39727, 2 }, -- Dislocating Handguards
		{ 40262, 2 }, -- Gloves of Calculated Risk
		{ 39601, 2 }, -- Heroes' Earthshatter Grips
		{ 37409, 2 }, -- Gilt-Edged Leather Gauntlets
	},
	Waist = {
		{ 39762, 1 }, -- Torn Web Wrapping
		{ 40260, 1 }, -- Belt of the Tortured
		{ 40275, 1 }, -- Depraved Linked Belt
		{ 37407, 2 }, -- Sovereign's Belt
	},
	Legs = {
		{ 40522, 1 }, -- Valorous Earthshatter War-Kilt
		{ 39603, 2 }, -- Heroes' Earthshatter War-Kilt
		{ 40560, 2 }, -- Leggings of the Wanton Spellcaster
		{ 44011, 2 }, -- Leggings of the Honored
		{ 40331, 2 }, -- Leggings of Failed Escape
		{ 40201, 2 }, -- Leggings of Colossal Strides
		{ 37644, 2 }, -- Gored Hide Legguards
	},
	Feet = {
		{ 40549, 1 }, -- Boots of the Renewed Flight
		{ 40746, 1 }, -- Pack-Ice Striders
		{ 39701, 1 }, -- Dawnwalkers
		{ 40367, 1 }, -- Boots of the Great Construct
		{ 40184, 1 }, -- Crippled Treads
		{ 40243, 2 }, -- Footwraps of Vile Deceit
		{ 43469, 2 }, -- Revenant's Treads
	},
	Ring = {
		{ 40474, 1 }, -- Surge Needle Ring
		{ 40074, 1 }, -- Strong-Handed Ring
		{ 40717, 2 }, -- Ring of Invincibility
		{ 40399, 2 }, -- Signet of Manifested Pain
		{ 39389, 2 }, -- Signet of the Malevolent
		{ 37642, 2 }, -- Hemorrhaging Circle
		{ 40586, 2 }, -- Band of the Kirin Tor
	},
	Trinket = {
		{ 40255, 1 }, -- Dying Curse
		{ 40684, 1 }, -- Mirror of Truth
		{ 37390, 1 }, -- Meteorite Whetstone
		{ 44253, 2 }, -- Darkmoon Card: Greatness
		{ 40431, 2 }, -- Fury of the Five Flights
		{ 37166, 2 }, -- Sphere of Red Dragon's Blood
		{ 40371, 2 }, -- Bandit's Insignia
		{ 40531, 2 }, -- Mark of Norgannon
		{ 43573, 2 }, -- Tears of Bitter Anguish
	},
	MainHand = {
		{ 39763, 1 }, -- Wraith Strike
		{ 40383, 2 }, -- Calamity's Grasp
		{ 40189, 2 }, -- Angry Dread
		{ 39416, 2 }, -- Kel'Thuzad's Reach
		{ 45085, 2 }, -- Titansteel Spellblade
		{ 40429, 2 }, -- Crimson Steel
		{ 41384, 2 }, -- Titansteel Guardian
		{ 41383, 2 }, -- Titansteel Bonecrusher
		{ 37693, 2 }, -- Greed
		{ 37871, 2 }, -- The Key
		{ 43407, 2 }, -- Stormstrike Mace
		{ 44192, 2 }, -- Stalactite Chopper
	},
	OffHand = {
		{ 39468, 1 }, -- The Stray
		{ 42232, 2 }, -- Deadly Gladiator's Chopper
		{ 40704, 2 }, -- Pride
	},
	Ranged = {
		{ 40322, 1 }, -- Totem of Dueling
		{ 40708, 2 }, -- Totem of the Elemental Plane
		{ 33507, 2 }, -- Stonebreaker's Totem
		{ 37575, 2 }, -- Totem of the Tundra
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/enhancement/dps-bis-gear-pve-phase-2
ns:RegisterBiS("SHAMAN", "Enhancement", "P2", {
	Head = {
		{ 45610, 1 }, -- Boundless Gaze
		{ 46212, 2 }, -- Conqueror's Worldbreaker Faceguard
		{ 40543, 2 }, -- Blue Aspect Helm
		{ 45412, 2 }, -- Valorous Worldbreaker Faceguard
		{ 45329, 2 }, -- Circlet of True Sight
	},
	Neck = {
		{ 45517, 1 }, -- Pendulum of Infinity
		{ 45133, 2 }, -- Pendant of Fiery Havoc
		{ 44661, 2 }, -- Wyrmrest Necklace of Power
	},
	Shoulder = {
		{ 46203, 1 }, -- Conqueror's Worldbreaker Shoulderguards
		{ 45415, 2 }, -- Valorous Worldbreaker Shoulderguards
		{ 45543, 2 }, -- Shoulders of Misfortune
	},
	Back = {
		{ 45461, 1 }, -- Drape of Icy Intent
		{ 45242, 2 }, -- Drape of Mortal Downfall
		{ 46032, 2 }, -- Drape of the Faceless General
	},
	Chest = {
		{ 46205, 1 }, -- Conqueror's Worldbreaker Chestguard
		{ 45413, 2 }, -- Valorous Worldbreaker Chestguard
		{ 45473, 2 }, -- Embrace of the Gladiator
	},
	Wrist = {
		{ 45460, 1 }, -- Bindings of Winter Gale
		{ 45454, 2 }, -- Frost-bound Chain Bracers
		{ 45869, 2 }, -- Fluxing Energy Coils
	},
	Hands = {
		{ 46200, 1 }, -- Conqueror's Worldbreaker Grips
		{ 45414, 2 }, -- Valorous Worldbreaker Grips
		{ 45444, 2 }, -- Gloves of the Steady Hand
		{ 45665, 2 }, -- Pharos Gloves
	},
	Waist = {
		{ 45553, 1 }, -- Belt of Dragons
		{ 45827, 2 }, -- Belt of the Ardent Marksman
		{ 45491, 2 }, -- Waistguard of the Creator
	},
	Legs = {
		{ 46208, 1 }, -- Conqueror's Worldbreaker War-Kilt
		{ 45416, 2 }, -- Valorous Worldbreaker War-Kilt
		{ 45844, 2 }, -- Leggings of the Tireless Sentry
	},
	Feet = {
		{ 45989, 1 }, -- Tempered Mercury Greaves
		{ 45244, 2 }, -- Greaves of Swift Vengeance
		{ 45537, 2 }, -- Treads of the False Oracle
	},
	Ring = {
		{ 45456, 1 }, -- Loop of the Agile
		{ 46046, 1 }, -- Nebula Band
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 46048, 2 }, -- Band of Lights
		{ 45503, 2 }, -- Metallic Loop of the Sufferer
	},
	Trinket = {
		{ 45609, 1 }, -- Comet's Trail
		{ 46038, 1 }, -- Dark Matter
		{ 45263, 2 }, -- Wrathstone
		{ 45522, 2 }, -- Blood of the Old God
		{ 45931, 2 }, -- Mjolnir Runestone
	},
	MainHand = {
		{ 45620, 1 }, -- Starshard Edge
		{ 45132, 1 }, -- Golden Saronite Dragon
		{ 45612, 2 }, -- Constellus
		{ 46097, 2 }, -- Caress of Insanity
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
		{ 45449, 2 }, -- The Masticator
		{ 42209, 2 }, -- Furious Gladiator's Cleaver
		{ 39763, 2 }, -- Wraith Strike
		{ 45463, 2 }, -- Vulmir, the Northern Tempest
		{ 46031, 2 }, -- Touch of Madness
	},
	OffHand = {
		{ 39468, 2 }, -- The Stray
	},
	Ranged = {
		{ 42608, 1 }, -- Furious Gladiator's Totem of Indomitability
		{ 40322, 2 }, -- Totem of Dueling
		{ 40708, 2 }, -- Totem of the Elemental Plane
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/enhancement/dps-bis-gear-pve-phase-3
ns:RegisterBiS("SHAMAN", "Enhancement", "P3", {
	Head = {
		{ 48353, 1 }, -- Nobundo's Faceguard of Triumph
		{ 48358, 1 }, -- Thrall's Faceguard of Triumph
		{ 48348, 2 }, -- Nobundo's Faceguard of Triumph
		{ 48363, 2 }, -- Thrall's Faceguard of Triumph
		{ 48343, 2 }, -- Nobundo's Faceguard of Conquest
		{ 48368, 2 }, -- Thrall's Faceguard of Conquest
		{ 45610, 2 }, -- Boundless Gaze
		{ 46212, 2 }, -- Conqueror's Worldbreaker Faceguard
		{ 40543, 2 }, -- Blue Aspect Helm
		{ 45412, 2 }, -- Valorous Worldbreaker Faceguard
	},
	Neck = {
		{ 47060, 1 }, -- Charge of the Demon Lord
		{ 47433, 1 }, -- Charge of the Eredar
		{ 45517, 2 }, -- Pendulum of Infinity
		{ 45133, 2 }, -- Pendant of Fiery Havoc
		{ 44661, 2 }, -- Wyrmrest Necklace of Power
	},
	Shoulder = {
		{ 48351, 1 }, -- Nobundo's Shoulderguards of Triumph
		{ 48360, 1 }, -- Thrall's Shoulderguards of Triumph
		{ 48350, 2 }, -- Nobundo's Shoulderguards of Triumph
		{ 48361, 2 }, -- Thrall's Shoulderguards of Triumph
		{ 48345, 2 }, -- Nobundo's Shoulderguards of Conquest
		{ 48370, 2 }, -- Thrall's Shoulderguards of Conquest
		{ 46203, 2 }, -- Conqueror's Worldbreaker Shoulderguards
		{ 45415, 2 }, -- Valorous Worldbreaker Shoulderguards
		{ 45543, 2 }, -- Shoulders of Misfortune
	},
	Back = {
		{ 47552, 1 }, -- Jaina's Radiance
		{ 47551, 1 }, -- Aethas' Intensity
		{ 48671, 2 }, -- Drape of Bitter Incantation
		{ 48666, 2 }, -- Drape of the Sunreavers
		{ 46971, 2 }, -- Drape of the Untamed Predator
		{ 47418, 2 }, -- Cloak of the Untamed Predator
		{ 45461, 2 }, -- Drape of Icy Intent
		{ 45242, 2 }, -- Drape of Mortal Downfall
	},
	Chest = {
		{ 46965, 1 }, -- Breastplate of Cruel Intent
		{ 47412, 1 }, -- Cuirass of Cruel Intent
		{ 48355, 2 }, -- Nobundo's Chestguard of Triumph
		{ 48356, 2 }, -- Thrall's Chestguard of Triumph
		{ 48346, 2 }, -- Nobundo's Chestguard of Triumph
		{ 48365, 2 }, -- Thrall's Chestguard of Triumph
		{ 48341, 2 }, -- Nobundo's Chestguard of Conquest
		{ 48366, 2 }, -- Thrall's Chestguard of Conquest
		{ 45473, 2 }, -- Embrace of the Gladiator
		{ 46205, 2 }, -- Conqueror's Worldbreaker Chestguard
		{ 45413, 2 }, -- Valorous Worldbreaker Chestguard
	},
	Wrist = {
		{ 47916, 1 }, -- Armbands of the Northern Stalker
		{ 47989, 1 }, -- Bracers of the Northern Stalker
		{ 47143, 1 }, -- Bindings of Dark Essence
		{ 47467, 1 }, -- Dark Essence Bindings
		{ 47576, 2 }, -- Crusader's Dragonscale Bracers
		{ 47577, 2 }, -- Crusader's Dragonscale Bracers
		{ 47155, 2 }, -- Bracers of Dark Determination
		{ 47474, 2 }, -- Armbands of Dark Determination
		{ 45611, 2 }, -- Solar Bindings
		{ 45460, 2 }, -- Bindings of Winter Gale
		{ 45454, 2 }, -- Frost-bound Chain Bracers
		{ 45869, 2 }, -- Fluxing Energy Coils
	},
	Hands = {
		{ 48354, 1 }, -- Nobundo's Grips of Triumph
		{ 48357, 1 }, -- Thrall's Grips of Triumph
		{ 48347, 2 }, -- Nobundo's Grips of Triumph
		{ 48364, 2 }, -- Thrall's Grips of Triumph
		{ 48342, 2 }, -- Nobundo's Grips of Conquest
		{ 48367, 2 }, -- Thrall's Grips of Conquest
		{ 46200, 2 }, -- Conqueror's Worldbreaker Grips
		{ 45414, 2 }, -- Valorous Worldbreaker Grips
		{ 45444, 2 }, -- Gloves of the Steady Hand
		{ 45665, 2 }, -- Pharos Gloves
	},
	Waist = {
		{ 47112, 1 }, -- Belt of the Merciless Killer
		{ 47460, 1 }, -- Belt of the Pitiless Killer
		{ 47084, 1 }, -- Cord of Biting Cold
		{ 47447, 1 }, -- Belt of Biting Cold
		{ 45553, 2 }, -- Belt of Dragons
		{ 45827, 2 }, -- Belt of the Ardent Marksman
		{ 45491, 2 }, -- Waistguard of the Creator
	},
	Legs = {
		{ 48352, 1 }, -- Nobundo's War-Kilt of Triumph
		{ 48359, 1 }, -- Thrall's War-Kilt of Triumph
		{ 48349, 2 }, -- Nobundo's War-Kilt of Triumph
		{ 48362, 2 }, -- Thrall's War-Kilt of Triumph
		{ 48344, 2 }, -- Nobundo's War-Kilt of Conquest
		{ 48369, 2 }, -- Thrall's War-Kilt of Conquest
		{ 46208, 2 }, -- Conqueror's Worldbreaker War-Kilt
		{ 45416, 2 }, -- Valorous Worldbreaker War-Kilt
		{ 45844, 2 }, -- Leggings of the Tireless Sentry
	},
	Feet = {
		{ 47099, 1 }, -- Boots of Tremoring Earth
		{ 47456, 1 }, -- Sabatons of Tremoring Earth
		{ 47933, 2 }, -- Sentinel Scouting Greaves
		{ 48006, 2 }, -- Warsong Poacher's Greaves
		{ 45989, 2 }, -- Tempered Mercury Greaves
		{ 45244, 2 }, -- Greaves of Swift Vengeance
	},
	Ring = {
		{ 47075, 1 }, -- Ring of Callous Aggression
		{ 47443, 1 }, -- Band of Callous Aggression
		{ 46046, 1 }, -- Nebula Band
		{ 45456, 2 }, -- Loop of the Agile
		{ 47928, 2 }, -- Firestorm Ring
		{ 48001, 2 }, -- Firestorm Band
		{ 45608, 2 }, -- Brann's Signet Ring
		{ 45503, 2 }, -- Metallic Loop of the Sufferer
	},
	Trinket = {
		{ 47188, 1 }, -- Reign of the Unliving
		{ 47477, 1 }, -- Reign of the Dead
		{ 45609, 1 }, -- Comet's Trail
		{ 46038, 2 }, -- Dark Matter
		{ 47734, 2 }, -- Mark of Supremacy
		{ 45263, 2 }, -- Wrathstone
		{ 45522, 2 }, -- Blood of the Old God
	},
	MainHand = {
		{ 47206, 1 }, -- Misery's End
		{ 47483, 1 }, -- Suffering's End
		{ 46980, 1 }, -- Blade of Tarasque
		{ 47422, 1 }, -- Barb of Tarasque
		{ 47156, 1 }, -- Stormpike Cleaver
		{ 47475, 1 }, -- Hellscream Slicer
		{ 45620, 2 }, -- Starshard Edge
		{ 45132, 2 }, -- Golden Saronite Dragon
		{ 45612, 2 }, -- Constellus
		{ 46097, 2 }, -- Caress of Insanity
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
		{ 39763, 2 }, -- Wraith Strike
		{ 45463, 2 }, -- Vulmir, the Northern Tempest
	},
	Ranged = {
		{ 47666, 1 }, -- Totem of Electrifying Wind
		{ 42608, 2 }, -- Furious Gladiator's Totem of Indomitability
		{ 40322, 2 }, -- Totem of Dueling
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/enhancement/dps-bis-gear-pve-phase-4
ns:RegisterBiS("SHAMAN", "Enhancement", "P4", {
	Head = {
		{ 51242, 1 }, -- Sanctified Frost Witch's Faceguard
		{ 51197, 2 }, -- Sanctified Frost Witch's Faceguard
		{ 50832, 2 }, -- Frost Witch's Faceguard
		{ 48353, 2 }, -- Nobundo's Faceguard of Triumph
		{ 48358, 2 }, -- Thrall's Faceguard of Triumph
		{ 48348, 2 }, -- Nobundo's Faceguard of Triumph
		{ 48363, 2 }, -- Thrall's Faceguard of Triumph
	},
	Neck = {
		{ 50658, 1 }, -- Amulet of the Silent Eulogy
		{ 50633, 1 }, -- Sindragosa's Cruel Claw
		{ 51890, 2 }, -- Precious's Putrid Collar
		{ 51894, 2 }, -- Soulcleave Pendant
		{ 47060, 2 }, -- Charge of the Demon Lord
		{ 47433, 2 }, -- Charge of the Eredar
		{ 45517, 2 }, -- Pendulum of Infinity
		{ 45133, 2 }, -- Pendant of Fiery Havoc
	},
	Shoulder = {
		{ 51240, 1 }, -- Sanctified Frost Witch's Shoulderguards
		{ 51199, 2 }, -- Sanctified Frost Witch's Shoulderguards
		{ 50834, 2 }, -- Frost Witch's Shoulderguards
		{ 48351, 2 }, -- Nobundo's Shoulderguards of Triumph
		{ 48360, 2 }, -- Thrall's Shoulderguards of Triumph
		{ 48350, 2 }, -- Nobundo's Shoulderguards of Triumph
		{ 48361, 2 }, -- Thrall's Shoulderguards of Triumph
	},
	Back = {
		{ 54583, 1 }, -- Cloak of Burning Dusk
		{ 50653, 2 }, -- Shadowvault Slayer's Cloak
		{ 50628, 2 }, -- Frostbinder's Shredded Cape
		{ 47552, 2 }, -- Jaina's Radiance
		{ 47551, 2 }, -- Aethas' Intensity
		{ 48671, 2 }, -- Drape of Bitter Incantation
		{ 48666, 2 }, -- Drape of the Sunreavers
		{ 46971, 2 }, -- Drape of the Untamed Predator
		{ 47418, 2 }, -- Cloak of the Untamed Predator
		{ 45461, 2 }, -- Drape of Icy Intent
		{ 45242, 2 }, -- Drape of Mortal Downfall
	},
	Chest = {
		{ 51244, 1 }, -- Sanctified Frost Witch's Chestguard
		{ 51195, 2 }, -- Sanctified Frost Witch's Chestguard
		{ 50830, 2 }, -- Frost Witch's Chestguard
		{ 46965, 2 }, -- Breastplate of Cruel Intent
		{ 47412, 2 }, -- Cuirass of Cruel Intent
		{ 48355, 2 }, -- Nobundo's Chestguard of Triumph
		{ 48356, 2 }, -- Thrall's Chestguard of Triumph
		{ 48346, 2 }, -- Nobundo's Chestguard of Triumph
		{ 48365, 2 }, -- Thrall's Chestguard of Triumph
	},
	Wrist = {
		{ 54580, 1 }, -- Umbrage Armbands
		{ 50655, 2 }, -- Scourge Hunter's Vambraces
		{ 50687, 2 }, -- Bloodsunder's Bracers
		{ 51914, 2 }, -- Icecrown Rampart Bracers
		{ 47916, 2 }, -- Armbands of the Northern Stalker
		{ 47989, 2 }, -- Bracers of the Northern Stalker
		{ 47143, 2 }, -- Bindings of Dark Essence
		{ 47467, 2 }, -- Dark Essence Bindings
		{ 47576, 2 }, -- Crusader's Dragonscale Bracers
		{ 47577, 2 }, -- Crusader's Dragonscale Bracers
		{ 45869, 2 }, -- Fluxing Energy Coils
	},
	Hands = {
		{ 50619, 1 }, -- Anub'ar Stalker's Gloves
		{ 51243, 1 }, -- Sanctified Frost Witch's Grips
		{ 51196, 2 }, -- Sanctified Frost Witch's Grips
		{ 50831, 2 }, -- Frost Witch's Grips
		{ 48354, 2 }, -- Nobundo's Grips of Triumph
		{ 48357, 2 }, -- Thrall's Grips of Triumph
		{ 48347, 2 }, -- Nobundo's Grips of Triumph
		{ 48364, 2 }, -- Thrall's Grips of Triumph
	},
	Waist = {
		{ 54587, 1 }, -- Split Shape Belt
		{ 50688, 2 }, -- Nerub'ar Stalker's Cord
		{ 50613, 2 }, -- Crushing Coldwraith Belt
		{ 50993, 2 }, -- Band of the Night Raven
		{ 47112, 2 }, -- Belt of the Merciless Killer
		{ 47460, 2 }, -- Belt of the Pitiless Killer
		{ 47084, 2 }, -- Cord of Biting Cold
		{ 47447, 2 }, -- Belt of Biting Cold
		{ 45553, 2 }, -- Belt of Dragons
		{ 45827, 2 }, -- Belt of the Ardent Marksman
	},
	Legs = {
		{ 51241, 1 }, -- Sanctified Frost Witch's War-Kilt
		{ 51198, 2 }, -- Sanctified Frost Witch's War-Kilt
		{ 50833, 2 }, -- Frost Witch's War-Kilt
		{ 48352, 2 }, -- Nobundo's War-Kilt of Triumph
		{ 48359, 2 }, -- Thrall's War-Kilt of Triumph
		{ 48349, 2 }, -- Nobundo's War-Kilt of Triumph
		{ 48362, 2 }, -- Thrall's War-Kilt of Triumph
	},
	Feet = {
		{ 50711, 1 }, -- Treads of the Wasteland
		{ 47099, 2 }, -- Boots of Tremoring Earth
		{ 47456, 2 }, -- Sabatons of Tremoring Earth
		{ 47933, 2 }, -- Sentinel Scouting Greaves
		{ 48006, 2 }, -- Warsong Poacher's Greaves
		{ 45989, 2 }, -- Tempered Mercury Greaves
	},
	Ring = {
		{ 50604, 1 }, -- Band of the Bone Colossus
		{ 50402, 1 }, -- Ashen Band of Endless Vengeance
		{ 47075, 2 }, -- Ring of Callous Aggression
		{ 47443, 2 }, -- Band of Callous Aggression
		{ 46046, 2 }, -- Nebula Band
		{ 45456, 2 }, -- Loop of the Agile
	},
	Trinket = {
		{ 54588, 1 }, -- Charred Twilight Scale
		{ 50365, 1 }, -- Phylactery of the Nameless Lich
		{ 50363, 2 }, -- Deathbringer's Will
		{ 50343, 2 }, -- Whispering Fanged Skull
		{ 50355, 2 }, -- Herkuml War Token
		{ 47188, 2 }, -- Reign of the Unliving
		{ 47477, 2 }, -- Reign of the Dead
		{ 45609, 2 }, -- Comet's Trail
		{ 47182, 2 }, -- Reign of the Unliving
		{ 47316, 2 }, -- Reign of the Dead
		{ 46038, 2 }, -- Dark Matter
	},
	MainHand = {
		{ 50734, 1 }, -- Royal Scepter of Terenas II
		{ 50737, 1 }, -- Havoc's Call, Blade of Lordaeron Kings
		{ 51939, 2 }, -- Tel'thas, Dagger of the Blood King
		{ 50692, 2 }, -- Black Bruise
		{ 51941, 2 }, -- Pugius, Fist of Defiance
		{ 47206, 2 }, -- Misery's End
		{ 47483, 2 }, -- Suffering's End
		{ 46980, 2 }, -- Blade of Tarasque
		{ 47422, 2 }, -- Barb of Tarasque
		{ 47156, 2 }, -- Stormpike Cleaver
		{ 47475, 2 }, -- Hellscream Slicer
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
		{ 46097, 2 }, -- Caress of Insanity
	},
	OffHand = {
		{ 50710, 2 }, -- Keleseth's Seducer
	},
	Ranged = {
		{ 50458, 1 }, -- Bizuri's Totem of Shattered Ice
		{ 47666, 2 }, -- Totem of Electrifying Wind
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/restoration/healer-bis-gear-pre-raid-pve
ns:RegisterBiS("SHAMAN", "Restoration", "PreRaid", {
	Head = {
		{ 42555, 1 }, -- Electroflux Sight Enhancers
		{ 34332, 2 }, -- Cowl of Gul'dan
		{ 37180, 2 }, -- Battlemap Hide Helm
		{ 37592, 2 }, -- Brood Plague Helmet
	},
	Neck = {
		{ 40681, 1 }, -- Lattice Choker of Light
		{ 42647, 2 }, -- Titanium Spellshock Necklace
		{ 34359, 2 }, -- Pendant of Sunfire
		{ 37141, 2 }, -- Amulet of Dazzling Light
		{ 43285, 2 }, -- Amulet of the Spell Flinger
	},
	Shoulder = {
		{ 34390, 1 }, -- Erupting Epaulets
		{ 37875, 1 }, -- Spaulders of the Violet Hold
		{ 37673, 1 }, -- Dark Runic Mantle
		{ 31022, 2 }, -- Skyshatter Shoulderpads
		{ 37398, 2 }, -- Mantle of Discarded Ways
	},
	Back = {
		{ 41610, 1 }, -- Deathchill Cloak
		{ 41609, 2 }, -- Wispcloak
		{ 37291, 2 }, -- Ancient Dragon Spirit Cape
		{ 34242, 2 }, -- Tattered Cape of Antonidas
		{ 44167, 2 }, -- Shroud of Dedicated Research
	},
	Chest = {
		{ 39588, 1 }, -- Heroes' Earthshatter Tunic
		{ 44180, 2 }, -- Robes of Crackling Flame
		{ 43461, 2 }, -- Revenant's Breastplate
		{ 43410, 2 }, -- Moragg's Chestguard
		{ 37256, 2 }, -- Scaled Armor of Drakos
		{ 34396, 2 }, -- Garments of Crashing Shores
		{ 31016, 2 }, -- Skyshatter Chestguard
	},
	Wrist = {
		{ 37788, 1 }, -- Limb Regeneration Bracers
		{ 37884, 1 }, -- Azure Cloth Bindings
		{ 34438, 2 }, -- Skyshatter Bracers
		{ 37725, 2 }, -- Savage Wound Wrap
		{ 32586, 2 }, -- Bracers of Nimble Thought
	},
	Hands = {
		{ 39591, 1 }, -- Heroes' Earthshatter Handguards
		{ 44204, 2 }, -- Grips of Fierce Pronouncements
		{ 37623, 2 }, -- Fiery Obelisk Handguards
		{ 42113, 2 }, -- Spellweave Gloves
		{ 34350, 2 }, -- Gauntlets of the Ancient Shadowmoon
	},
	Waist = {
		{ 40693, 1 }, -- Beadwork Belt of Shamanic Vision
		{ 37643, 2 }, -- Sash of Blood Removal
		{ 44302, 2 }, -- Belt of Dark Mending
		{ 44181, 2 }, -- Ghostflicker Waistband
		{ 34543, 2 }, -- Skyshatter Belt
	},
	Legs = {
		{ 37791, 1 }, -- Leggings of the Winged Serpent
		{ 37622, 2 }, -- Skirt of the Old Kingdom
		{ 44305, 2 }, -- Kilt of Dark Mercy
		{ 37695, 2 }, -- Legguards of Nature's Power
		{ 44931, 2 }, -- Windripper Leggings
		{ 34186, 2 }, -- Chain Links of the Tumultuous Storm
	},
	Feet = {
		{ 43469, 1 }, -- Revenant's Treads
		{ 44202, 1 }, -- Sandals of Crimson Fury
		{ 44930, 1 }, -- Windripper Boots
		{ 37654, 2 }, -- Sabatons of the Ages
		{ 34565, 2 }, -- Skyshatter Boots
	},
	Ring = {
		{ 40585, 1 }, -- Signet of the Kirin Tor
		{ 37694, 1 }, -- Band of Guile
		{ 44283, 1 }, -- Signet of Hopeful Light
		{ 42644, 2 }, -- Titanium Spellshock Ring
		{ 37192, 2 }, -- Annhylde's Ring
		{ 32528, 2 }, -- Blessed Band of Karabor
		{ 34363, 2 }, -- Ring of Flowing Life
	},
	Trinket = {
		{ 40685, 1 }, -- The Egg of Mortal Essence
		{ 37111, 1 }, -- Soul Preserver
		{ 37835, 2 }, -- Je'Tze's Bell
		{ 37657, 2 }, -- Spark of Life
		{ 37844, 2 }, -- Winged Talisman
		{ 32496, 2 }, -- Memento of Tyrande
	},
	MainHand = {
		{ 37169, 1 }, -- War Mace of Unrequited Love
		{ 41384, 2 }, -- Titansteel Guardian
		{ 44199, 2 }, -- Gavel of the Brewing Storm
		{ 34335, 2 }, -- Hammer of Sanctification
	},
	OffHand = {
		{ 40700, 1 }, -- Protective Barricade of the Light
		{ 38322, 2 }, -- Iron-bound Tome
		{ 37061, 2 }, -- Tor's Crest
		{ 34206, 2 }, -- Book of Highborne Hymns
		{ 34231, 2 }, -- Aegis of Angelic Fortune
	},
	Ranged = {
		{ 40709, 1 }, -- Totem of Forest Growth
		{ 38368, 2 }, -- Totem of the Bay
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/restoration/healer-bis-gear-pve-phase-1
ns:RegisterBiS("SHAMAN", "Restoration", "P1", {
	Head = {
		{ 40510, 1 }, -- Valorous Earthshatter Headpiece
		{ 39583, 2 }, -- Heroes' Earthshatter Headpiece
		{ 40340, 2 }, -- Helm of Unleashed Energy
		{ 40304, 2 }, -- Headpiece of Fungal Bloom
		{ 40339, 2 }, -- Gothik's Cowl
		{ 39405, 2 }, -- Helmet of the Inner Sanctum
		{ 42555, 2 }, -- Electroflux Sight Enhancers
	},
	Neck = {
		{ 44662, 1 }, -- Life-Binder's Locket
		{ 40374, 2 }, -- Cosmic Lights
		{ 44657, 2 }, -- Torque of the Red Dragonflight
		{ 40071, 2 }, -- Chains of Adoration
		{ 42647, 2 }, -- Titanium Spellshock Necklace
	},
	Shoulder = {
		{ 40513, 1 }, -- Valorous Earthshatter Spaulders
		{ 39590, 2 }, -- Heroes' Earthshatter Spaulders
		{ 40439, 2 }, -- Mantle of the Eternal Sentinel
		{ 40438, 2 }, -- Council Chamber Epaulets
		{ 40288, 2 }, -- Spaulders of Incoherence
		{ 40289, 2 }, -- Sympathetic Amice
	},
	Back = {
		{ 44005, 1 }, -- Pennant Cloak
		{ 39425, 2 }, -- Cloak of the Dying
		{ 40724, 2 }, -- Cloak of Kea Feathers
		{ 40254, 2 }, -- Cloak of Averted Crisis
		{ 41610, 2 }, -- Deathchill Cloak
		{ 40251, 2 }, -- Shroud of Luminosity
		{ 39415, 2 }, -- Shroud of the Citadel
	},
	Chest = {
		{ 40508, 1 }, -- Valorous Earthshatter Tunic
		{ 39588, 2 }, -- Heroes' Earthshatter Tunic
		{ 40588, 2 }, -- Tunic of the Artifact Guardian
		{ 40061, 2 }, -- Quivering Tunic
		{ 40283, 2 }, -- Fallout Impervious Tunic
		{ 40249, 2 }, -- Vest of Vitality
	},
	Wrist = {
		{ 40209, 1 }, -- Bindings of the Decrepit
		{ 40741, 1 }, -- Cuffs of the Shadow Ascendant
		{ 40338, 2 }, -- Bindings of Yearning
		{ 40324, 2 }, -- Bands of Mutual Respect
		{ 37788, 2 }, -- Limb Regeneration Bracers
		{ 37884, 2 }, -- Azure Cloth Bindings
	},
	Hands = {
		{ 40564, 1 }, -- Winter Spectacle Gloves
		{ 40509, 2 }, -- Valorous Earthshatter Handguards
		{ 39591, 2 }, -- Heroes' Earthshatter Handguards
		{ 39718, 2 }, -- Corpse Scarab Handguards
		{ 40303, 2 }, -- Wraps of the Persecuted
		{ 40302, 2 }, -- Benefactor's Gauntlets
		{ 39243, 2 }, -- Handgrips of the Foredoomed
	},
	Waist = {
		{ 40272, 1 }, -- Girdle of the Gambit
		{ 40327, 1 }, -- Girdle of Recuperation
		{ 39721, 1 }, -- Sash of the Parlor
		{ 40693, 2 }, -- Beadwork Belt of Shamanic Vision
		{ 37643, 2 }, -- Sash of Blood Removal
	},
	Legs = {
		{ 40512, 1 }, -- Valorous Earthshatter Legguards
		{ 39589, 2 }, -- Heroes' Earthshatter Legguards
		{ 40352, 2 }, -- Leggings of Voracious Shadows
		{ 40196, 2 }, -- Legguards of the Undisturbed
		{ 39217, 2 }, -- Avenging Combat Leggings
	},
	Feet = {
		{ 39734, 1 }, -- Atonement Greaves
		{ 40519, 1 }, -- Footsteps of Malygos
		{ 40236, 2 }, -- Serene Echoes
		{ 40237, 2 }, -- Eruption-Scarred Boots
		{ 43469, 2 }, -- Revenant's Treads
	},
	Ring = {
		{ 40399, 1 }, -- Signet of Manifested Pain
		{ 40375, 1 }, -- Ring of Decaying Beauty
		{ 40433, 2 }, -- Wyrmrest Band
		{ 40108, 2 }, -- Seized Beauty
		{ 40720, 2 }, -- Renewal of Life
		{ 40585, 2 }, -- Signet of the Kirin Tor
		{ 39244, 2 }, -- Ring of the Fated
		{ 42644, 2 }, -- Titanium Spellshock Ring
	},
	Trinket = {
		{ 40432, 1 }, -- Illustration of the Dragon Soul
		{ 37111, 1 }, -- Soul Preserver
		{ 39229, 1 }, -- Embrace of the Spider
		{ 40685, 1 }, -- The Egg of Mortal Essence
		{ 40258, 2 }, -- Forethought Talisman
		{ 40382, 2 }, -- Soul of the Dead
		{ 37835, 2 }, -- Je'Tze's Bell
		{ 37657, 2 }, -- Spark of Life
		{ 37844, 2 }, -- Winged Talisman
	},
	MainHand = {
		{ 40395, 1 }, -- Torch of Holy Fire
		{ 39763, 2 }, -- Wraith Strike
		{ 39423, 2 }, -- Hammer of the Astral Plane
		{ 37169, 2 }, -- War Mace of Unrequited Love
		{ 41384, 2 }, -- Titansteel Guardian
	},
	OffHand = {
		{ 40401, 1 }, -- Voice of Reason
		{ 39716, 2 }, -- Shield of Assimilation
		{ 39233, 2 }, -- Aegis of Damnation
		{ 40700, 2 }, -- Protective Barricade of the Light
	},
	Ranged = {
		{ 40709, 1 }, -- Totem of Forest Growth
		{ 38368, 2 }, -- Totem of the Bay
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/restoration/healer-bis-gear-pve-phase-2
ns:RegisterBiS("SHAMAN", "Restoration", "P2", {
	Head = {
		{ 46201, 1 }, -- Conqueror's Worldbreaker Headpiece
		{ 45402, 2 }, -- Valorous Worldbreaker Headpiece
	},
	Neck = {
		{ 45443, 1 }, -- Charm of Meticulous Timing
		{ 45933, 2 }, -- Pendant of the Shallow Grave
		{ 46047, 2 }, -- Pendant of the Somber Witness
	},
	Shoulder = {
		{ 46204, 1 }, -- Conqueror's Worldbreaker Spaulders
		{ 45404, 2 }, -- Valorous Worldbreaker Spaulders
		{ 46044, 2 }, -- Observer's Mantle
		{ 45474, 2 }, -- Pauldrons of the Combatant
	},
	Back = {
		{ 45486, 1 }, -- Drape of the Sullen Goddess
		{ 44005, 1 }, -- Pennant Cloak
		{ 45541, 2 }, -- Shroud of Alteration
		{ 46341, 2 }, -- Drape of the Spellweaver
		{ 40724, 2 }, -- Cloak of Kea Feathers
	},
	Chest = {
		{ 46198, 1 }, -- Conqueror's Worldbreaker Tunic
		{ 45867, 1 }, -- Breastplate of the Stoneshaper
		{ 45405, 2 }, -- Valorous Worldbreaker Tunic
	},
	Wrist = {
		{ 45460, 1 }, -- Bindings of Winter Gale
		{ 45187, 2 }, -- Wristguards of the Firetender
		{ 45316, 2 }, -- Armbraces of the Vibrant Flame
	},
	Hands = {
		{ 45665, 1 }, -- Pharos Gloves
		{ 46199, 1 }, -- Conqueror's Worldbreaker Handguards
		{ 45401, 2 }, -- Valorous Worldbreaker Handguards
		{ 45943, 2 }, -- Gloves of Whispering Winds
	},
	Waist = {
		{ 45616, 1 }, -- Star-beaded Clutch
		{ 45151, 1 }, -- Belt of the Fallen Wyrm
		{ 45554, 2 }, -- Blue Belt of Chaos
	},
	Legs = {
		{ 46202, 1 }, -- Conqueror's Worldbreaker Legguards
		{ 45403, 2 }, -- Valorous Worldbreaker Legguards
		{ 45544, 2 }, -- Leggings of the Tortured Earth
		{ 45845, 2 }, -- Leggings of the Weary Mystic
	},
	Feet = {
		{ 45537, 1 }, -- Treads of the False Oracle
		{ 45615, 2 }, -- Planewalker Treads
		{ 45563, 2 }, -- Lightning Grounded Boots
	},
	Ring = {
		{ 45614, 1 }, -- Starshine Circle
		{ 46046, 1 }, -- Nebula Band
		{ 45946, 2 }, -- Fire Orchid Signet
		{ 45168, 2 }, -- Pyrelight Circle
		{ 46323, 2 }, -- Starshine Signet
		{ 40399, 2 }, -- Signet of Manifested Pain
	},
	Trinket = {
		{ 45535, 1 }, -- Show of Faith
		{ 45466, 1 }, -- Scale of Fates
		{ 37111, 2 }, -- Soul Preserver
		{ 45490, 2 }, -- Pandora's Plea
		{ 45929, 2 }, -- Sif's Remembrance
		{ 45308, 2 }, -- Eye of the Broodmother
		{ 40432, 2 }, -- Illustration of the Dragon Soul
	},
	MainHand = {
		{ 46017, 1 }, -- Val'anyr, Hammer of Ancient Kings
		{ 45612, 2 }, -- Constellus
		{ 45970, 2 }, -- Furious Gladiator's Mageblade
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
		{ 45527, 2 }, -- Soulscribe
	},
	OffHand = {
		{ 45470, 1 }, -- Wisdom's Hold
		{ 45887, 2 }, -- Ice Layered Barrier
		{ 40401, 2 }, -- Voice of Reason
		{ 45682, 2 }, -- Pulsing Spellshield
	},
	Ranged = {
		{ 45114, 1 }, -- Steamcaller's Totem
		{ 40709, 2 }, -- Totem of Forest Growth
		{ 38368, 2 }, -- Totem of the Bay
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/restoration/healer-bis-gear-pve-phase-3
ns:RegisterBiS("SHAMAN", "Restoration", "P3", {
	Head = {
		{ 46201, 1 }, -- Conqueror's Worldbreaker Headpiece
		{ 45402, 2 }, -- Valorous Worldbreaker Headpiece
		{ 48323, 2 }, -- Nobundo's Helm of Triumph
		{ 48328, 2 }, -- Thrall's Helm of Triumph
		{ 48318, 2 }, -- Nobundo's Helm of Triumph
		{ 48333, 2 }, -- Thrall's Helm of Triumph
		{ 48313, 2 }, -- Nobundo's Helm of Conquest
		{ 48338, 2 }, -- Thrall's Helm of Conquest
	},
	Neck = {
		{ 47144, 1 }, -- Wail of the Val'kyr
		{ 47468, 1 }, -- Cry of the Val'kyr
		{ 45443, 2 }, -- Charm of Meticulous Timing
		{ 45933, 2 }, -- Pendant of the Shallow Grave
	},
	Shoulder = {
		{ 46204, 1 }, -- Conqueror's Worldbreaker Spaulders
		{ 45404, 2 }, -- Valorous Worldbreaker Spaulders
		{ 48321, 2 }, -- Nobundo's Shoulderpads of Triumph
		{ 48330, 2 }, -- Thrall's Shoulderpads of Triumph
		{ 48320, 2 }, -- Nobundo's Shoulderpads of Triumph
		{ 48331, 2 }, -- Thrall's Shoulderpads of Triumph
		{ 48315, 2 }, -- Nobundo's Shoulderpads of Conquest
		{ 48340, 2 }, -- Thrall's Shoulderpads of Conquest
		{ 46044, 2 }, -- Observer's Mantle
		{ 45474, 2 }, -- Pauldrons of the Combatant
	},
	Back = {
		{ 47552, 1 }, -- Jaina's Radiance
		{ 47551, 1 }, -- Aethas' Intensity
		{ 48671, 2 }, -- Drape of Bitter Incantation
		{ 48666, 2 }, -- Drape of the Sunreavers
		{ 47238, 2 }, -- Maiden's Favor
		{ 47490, 2 }, -- Maiden's Adoration
		{ 45486, 2 }, -- Drape of the Sullen Goddess
		{ 49491, 2 }, -- Flowing Sapphiron Drape
		{ 44005, 2 }, -- Pennant Cloak
		{ 45541, 2 }, -- Shroud of Alteration
		{ 40724, 2 }, -- Cloak of Kea Feathers
	},
	Chest = {
		{ 46198, 1 }, -- Conqueror's Worldbreaker Tunic
		{ 45405, 2 }, -- Valorous Worldbreaker Tunic
		{ 48294, 2 }, -- Nobundo's Tunic of Triumph
		{ 48305, 2 }, -- Thrall's Tunic of Triumph
		{ 47603, 2 }, -- Merlin's Robe
		{ 45867, 2 }, -- Breastplate of the Stoneshaper
		{ 48285, 2 }, -- Nobundo's Tunic of Triumph
		{ 48300, 2 }, -- Thrall's Tunic of Triumph
		{ 48281, 2 }, -- Nobundo's Tunic of Conquest
		{ 48295, 2 }, -- Thrall's Tunic of Conquest
	},
	Wrist = {
		{ 45460, 1 }, -- Bindings of Winter Gale
		{ 47586, 2 }, -- Bejeweled Wizard's Bracers
		{ 47579, 2 }, -- Black Chitin Bracers
		{ 47580, 2 }, -- Black Chitin Bracers
		{ 47068, 2 }, -- Bracers of Cloudy Omen
		{ 47441, 2 }, -- Wristwraps of Cloudy Omen
		{ 45187, 2 }, -- Wristguards of the Firetender
	},
	Hands = {
		{ 46199, 1 }, -- Conqueror's Worldbreaker Handguards
		{ 45401, 2 }, -- Valorous Worldbreaker Handguards
		{ 45665, 2 }, -- Pharos Gloves
		{ 48293, 2 }, -- Nobundo's Handguards of Triumph
		{ 48306, 2 }, -- Thrall's Handguards of Triumph
		{ 45943, 2 }, -- Gloves of Whispering Winds
		{ 48286, 2 }, -- Nobundo's Handguards of Triumph
		{ 48301, 2 }, -- Thrall's Handguards of Triumph
		{ 48284, 2 }, -- Nobundo's Handguards of Conquest
		{ 48296, 2 }, -- Thrall's Handguards of Conquest
	},
	Waist = {
		{ 46991, 1 }, -- Belt of the Ice Burrower
		{ 47426, 1 }, -- Binding of the Ice Burrower
		{ 47145, 2 }, -- Cord of Pale Thorns
		{ 47469, 2 }, -- Belt of Pale Thorns
		{ 45616, 2 }, -- Star-beaded Clutch
		{ 45151, 2 }, -- Belt of the Fallen Wyrm
		{ 47932, 2 }, -- Girdle of the Farseer
		{ 48005, 2 }, -- Darkspear Ritual Binding
		{ 45554, 2 }, -- Blue Belt of Chaos
	},
	Legs = {
		{ 47190, 1 }, -- Legwraps of the Awakening
		{ 47479, 1 }, -- Leggings of the Awakening
		{ 47087, 2 }, -- Legguards of Concealed Hatred
		{ 47450, 2 }, -- Leggings of Concealed Hatred
		{ 48291, 2 }, -- Nobundo's Legguards of Triumph
		{ 48308, 2 }, -- Thrall's Legguards of Triumph
		{ 48303, 2 }, -- Thrall's Legguards of Triumph
		{ 48288, 2 }, -- Nobundo's Legguards of Triumph
		{ 48282, 2 }, -- Nobundo's Legguards of Conquest
		{ 48298, 2 }, -- Thrall's Legguards of Conquest
		{ 46202, 2 }, -- Conqueror's Worldbreaker Legguards
		{ 45403, 2 }, -- Valorous Worldbreaker Legguards
		{ 45845, 2 }, -- Leggings of the Weary Mystic
		{ 45544, 2 }, -- Leggings of the Tortured Earth
	},
	Feet = {
		{ 47099, 1 }, -- Boots of Tremoring Earth
		{ 47456, 1 }, -- Sabatons of Tremoring Earth
		{ 45537, 2 }, -- Treads of the False Oracle
		{ 45615, 2 }, -- Planewalker Treads
		{ 45563, 2 }, -- Lightning Grounded Boots
	},
	Ring = {
		{ 47224, 1 }, -- Ring of the Darkmender
		{ 47439, 1 }, -- Circle of the Darkmender
		{ 45614, 1 }, -- Starshine Circle
		{ 46046, 2 }, -- Nebula Band
		{ 45946, 2 }, -- Fire Orchid Signet
		{ 45168, 2 }, -- Pyrelight Circle
	},
	Trinket = {
		{ 47059, 1 }, -- Solace of the Defeated
		{ 47432, 1 }, -- Solace of the Fallen
		{ 45535, 1 }, -- Show of Faith
		{ 45466, 1 }, -- Scale of Fates
		{ 37111, 2 }, -- Soul Preserver
		{ 45490, 2 }, -- Pandora's Plea
		{ 45929, 2 }, -- Sif's Remembrance
		{ 45308, 2 }, -- Eye of the Broodmother
		{ 40432, 2 }, -- Illustration of the Dragon Soul
	},
	MainHand = {
		{ 46017, 1 }, -- Val'anyr, Hammer of Ancient Kings
		{ 47483, 2 }, -- Suffering's End
		{ 47206, 2 }, -- Misery's End
		{ 45612, 2 }, -- Constellus
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
		{ 45527, 2 }, -- Soulscribe
	},
	OffHand = {
		{ 47085, 1 }, -- Bastion of Purity
		{ 47448, 1 }, -- Bastion of Resolve
		{ 45470, 2 }, -- Wisdom's Hold
		{ 45887, 2 }, -- Ice Layered Barrier
		{ 40401, 2 }, -- Voice of Reason
	},
	Ranged = {
		{ 47665, 1 }, -- Totem of Calming Tides
		{ 45114, 2 }, -- Steamcaller's Totem
		{ 40709, 2 }, -- Totem of Forest Growth
		{ 38368, 2 }, -- Totem of the Bay
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/restoration/healer-bis-gear-pve-phase-4
ns:RegisterBiS("SHAMAN", "Restoration", "P4", {
	Head = {
		{ 51247, 1 }, -- Sanctified Frost Witch's Headpiece
		{ 51192, 2 }, -- Sanctified Frost Witch's Headpiece
		{ 50837, 2 }, -- Frost Witch's Headpiece
		{ 46201, 2 }, -- Conqueror's Worldbreaker Headpiece
		{ 48323, 2 }, -- Nobundo's Helm of Triumph
		{ 48328, 2 }, -- Thrall's Helm of Triumph
	},
	Neck = {
		{ 50724, 1 }, -- Blood Queen's Crimson Choker
		{ 51894, 2 }, -- Soulcleave Pendant
		{ 51871, 2 }, -- Choker of Filthy Diamonds
		{ 47144, 2 }, -- Wail of the Val'kyr
		{ 47468, 2 }, -- Cry of the Val'kyr
		{ 45443, 2 }, -- Charm of Meticulous Timing
	},
	Shoulder = {
		{ 51245, 1 }, -- Sanctified Frost Witch's Spaulders
		{ 51194, 2 }, -- Sanctified Frost Witch's Spaulders
		{ 50839, 2 }, -- Frost Witch's Spaulders
		{ 46204, 2 }, -- Conqueror's Worldbreaker Spaulders
		{ 48321, 2 }, -- Nobundo's Shoulderpads of Triumph
		{ 48330, 2 }, -- Thrall's Shoulderpads of Triumph
	},
	Back = {
		{ 54583, 1 }, -- Cloak of Burning Dusk
		{ 50628, 2 }, -- Frostbinder's Shredded Cape
		{ 47552, 2 }, -- Jaina's Radiance
		{ 47551, 2 }, -- Aethas' Intensity
		{ 48671, 2 }, -- Drape of Bitter Incantation
		{ 48666, 2 }, -- Drape of the Sunreavers
		{ 47238, 2 }, -- Maiden's Favor
		{ 47490, 2 }, -- Maiden's Adoration
		{ 45486, 2 }, -- Drape of the Sullen Goddess
	},
	Chest = {
		{ 51249, 1 }, -- Sanctified Frost Witch's Tunic
		{ 51190, 2 }, -- Sanctified Frost Witch's Tunic
		{ 50835, 2 }, -- Frost Witch's Tunic
		{ 46198, 2 }, -- Conqueror's Worldbreaker Tunic
		{ 48294, 2 }, -- Nobundo's Tunic of Triumph
		{ 48305, 2 }, -- Thrall's Tunic of Triumph
		{ 47603, 2 }, -- Merlin's Robe
	},
	Wrist = {
		{ 54582, 1 }, -- Bracers of Fiery Night
		{ 54584, 2 }, -- Phaseshifter's Bracers
		{ 50687, 2 }, -- Bloodsunder's Bracers
		{ 45460, 2 }, -- Bindings of Winter Gale
		{ 47586, 2 }, -- Bejeweled Wizard's Bracers
		{ 47579, 2 }, -- Black Chitin Bracers
		{ 47580, 2 }, -- Black Chitin Bracers
	},
	Hands = {
		{ 50703, 1 }, -- Unclean Surgical Gloves
		{ 51248, 1 }, -- Sanctified Frost Witch's Handguards
		{ 54560, 2 }, -- Changeling Gloves
		{ 51827, 2 }, -- Stormbringer Gloves
		{ 50980, 2 }, -- Blizzard Keeper's Mitts
		{ 51191, 2 }, -- Sanctified Frost Witch's Handguards
		{ 50836, 2 }, -- Frost Witch's Handguards
		{ 46199, 2 }, -- Conqueror's Worldbreaker Handguards
		{ 45665, 2 }, -- Pharos Gloves
		{ 48293, 2 }, -- Nobundo's Handguards of Triumph
		{ 48306, 2 }, -- Thrall's Handguards of Triumph
	},
	Waist = {
		{ 54587, 1 }, -- Split Shape Belt
		{ 50613, 2 }, -- Crushing Coldwraith Belt
		{ 50671, 2 }, -- Belt of the Blood Nova
		{ 50992, 2 }, -- Waistband of Despair
		{ 46991, 2 }, -- Belt of the Ice Burrower
		{ 47426, 2 }, -- Binding of the Ice Burrower
		{ 47145, 2 }, -- Cord of Pale Thorns
		{ 47469, 2 }, -- Belt of Pale Thorns
		{ 45616, 2 }, -- Star-beaded Clutch
	},
	Legs = {
		{ 51246, 1 }, -- Sanctified Frost Witch's Legguards
		{ 51193, 2 }, -- Sanctified Frost Witch's Legguards
		{ 50838, 2 }, -- Frost Witch's Legguards
		{ 49891, 2 }, -- Leggings of Woven Death
		{ 49900, 2 }, -- Lightning-Infused Leggings
		{ 47190, 2 }, -- Legwraps of the Awakening
		{ 47479, 2 }, -- Leggings of the Awakening
		{ 47087, 2 }, -- Legguards of Concealed Hatred
		{ 47450, 2 }, -- Leggings of Concealed Hatred
		{ 48291, 2 }, -- Nobundo's Legguards of Triumph
		{ 48308, 2 }, -- Thrall's Legguards of Triumph
		{ 46202, 2 }, -- Conqueror's Worldbreaker Legguards
	},
	Feet = {
		{ 50699, 1 }, -- Plague Scientist's Boots
		{ 51920, 2 }, -- Boots of the Frozen Seed
		{ 49896, 2 }, -- Earthsoul Boots
		{ 47099, 2 }, -- Boots of Tremoring Earth
		{ 47456, 2 }, -- Sabatons of Tremoring Earth
		{ 45537, 2 }, -- Treads of the False Oracle
	},
	Ring = {
		{ 54585, 1 }, -- Ring of Phased Regeneration
		{ 50400, 1 }, -- Ashen Band of Endless Wisdom
		{ 50664, 2 }, -- Ring of Rapid Ascent
		{ 50610, 2 }, -- Marrowgar's Frigid Eye
		{ 47224, 2 }, -- Ring of the Darkmender
		{ 47439, 2 }, -- Circle of the Darkmender
		{ 45614, 2 }, -- Starshine Circle
		{ 46046, 2 }, -- Nebula Band
		{ 45946, 2 }, -- Fire Orchid Signet
	},
	Trinket = {
		{ 47059, 1 }, -- Solace of the Defeated
		{ 47432, 1 }, -- Solace of the Fallen
		{ 54589, 1 }, -- Glowing Twilight Scale
		{ 47041, 2 }, -- Solace of the Defeated
		{ 47271, 2 }, -- Solace of the Fallen
		{ 50366, 2 }, -- Althor's Abacus
		{ 50358, 2 }, -- Purified Lunar Dust
		{ 45535, 2 }, -- Show of Faith
		{ 45466, 2 }, -- Scale of Fates
		{ 37111, 2 }, -- Soul Preserver
		{ 45490, 2 }, -- Pandora's Plea
		{ 45929, 2 }, -- Sif's Remembrance
		{ 45308, 2 }, -- Eye of the Broodmother
		{ 40432, 2 }, -- Illustration of the Dragon Soul
	},
	MainHand = {
		{ 46017, 1 }, -- Val'anyr, Hammer of Ancient Kings
		{ 50734, 1 }, -- Royal Scepter of Terenas II
		{ 50685, 2 }, -- Trauma
		{ 51875, 2 }, -- Lockjaw
		{ 51910, 2 }, -- Midnight Sun
		{ 47483, 2 }, -- Suffering's End
		{ 47206, 2 }, -- Misery's End
		{ 45612, 2 }, -- Constellus
		{ 46035, 2 }, -- Aesuga, Hand of the Ardent Champion
	},
	OffHand = {
		{ 50616, 1 }, -- Bulwark of Smouldering Steel
		{ 51812, 2 }, -- Lost Pavise of the Blue Flight
		{ 47085, 2 }, -- Bastion of Purity
		{ 47448, 2 }, -- Bastion of Resolve
		{ 45470, 2 }, -- Wisdom's Hold
		{ 45887, 2 }, -- Ice Layered Barrier
	},
	Ranged = {
		{ 47665, 1 }, -- Totem of Calming Tides
		{ 40709, 2 }, -- Totem of Forest Growth
	},
})
