-- GENERATED by scripts/build_data.py -- do not edit by hand; the next build
-- overwrites it. Sources: AzerothCore world DB, the realm client's DBC files,
-- and the Wowhead guides listed in scripts/guides.json.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/warrior/arms/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("WARRIOR", "Arms", "PreRaid", {
	Head = {
		{ 41386, 1 }, -- Spiked Titansteel Helm
		{ 42552, 3 }, -- Charged Titanium Specs
		{ 34345, 3 }, -- Crown of Anasterian
		{ 37237, 3 }, -- Chitin Shell Greathelm
	},
	Neck = {
		{ 42645, 1 }, -- Titanium Impact Choker
		{ 40678, 1 }, -- Pendant of the Outcast Hero
		{ 37397, 1 }, -- Gold Amulet of Kings
	},
	Shoulder = {
		{ 44195, 1 }, -- Spaulders of the Giant Lords
		{ 44111, 3 }, -- Gold Star Spaulders
		{ 34388, 3 }, -- Pauldrons of Berserking
	},
	Back = {
		{ 37647, 1 }, -- Cloak of Bloodied Waters
		{ 37840, 3 }, -- Shroud of Reverberation
		{ 44216, 3 }, -- Cloak of Holy Extermination
	},
	Chest = {
		{ 39606, 1 }, -- Heroes' Dreadnaught Battleplate
		{ 44303, 3 }, -- Darkheart Chestguard
		{ 37612, 3 }, -- Bonegrinder Breastplate
	},
	Wrist = {
		{ 41355, 1 }, -- Vengeance Bindings
		{ 44203, 1 }, -- Dragonfriend Bracers
		{ 37853, 3 }, -- Advanced Tooled-Leather Bands
	},
	Hands = {
		{ 39609, 1 }, -- Heroes' Dreadnaught Gauntlets
		{ 37363, 3 }, -- Gauntlets of Dragon Wrath
		{ 34341, 3 }, -- Borderland Paingrips
	},
	Waist = {
		{ 40694, 1 }, -- Jorach's Crocolisk Skin Belt
		{ 37171, 3 }, -- Flame-Bathed Steel Girdle
		{ 37194, 3 }, -- Sharp-Barbed Leather Belt
	},
	Legs = {
		{ 37193, 1 }, -- Staggering Legplates
		{ 44205, 1 }, -- Legplates of Bloody Reprisal
		{ 34180, 3 }, -- Felfury Legplates
	},
	Feet = {
		{ 44306, 1 }, -- Death-Inured Sabatons
		{ 37150, 3 }, -- Rift Striders
		{ 43402, 3 }, -- The Obliterator Greaves
	},
	Ring = {
		{ 37642, 1 }, -- Hemorrhaging Circle
		{ 44935, 1 }, -- Ring of the Kirin Tor
		{ 42642, 1 }, -- Titanium Impact Band
		{ 43251, 3 }, -- Ring of Scarlet Shadows
		{ 37151, 3 }, -- Band of Frosted Thorns
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 37166, 1 }, -- Sphere of Red Dragon's Blood
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 33831, 3 }, -- Berserker's Call
	},
	TwoHand = {
		{ 37852, 1 }, -- Colossal Skull-Clad Cleaver
		{ 43409, 1 }, -- Saliva Corroded Pike
		{ 43281, 1 }, -- Edge of Oblivion
		{ 37653, 3 }, -- Sword of Justice
	},
	Ranged = {
		{ 37191, 1 }, -- Drake-Mounted Crossbow
		{ 44504, 3 }, -- Nesingwary 4000
		{ 44245, 3 }, -- Zombie Sweeper Shotgun
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/arms/dps-bis-gear-pve-phase-1
ns:RegisterBiS("WARRIOR", "Arms", "P1", {
	Head = {
		{ 40528, 1 }, -- Valorous Dreadnaught Helmet
		{ 44006, 3 }, -- Obsidian Greathelm
		{ 39605, 3 }, -- Heroes' Dreadnaught Helmet
		{ 41386, 3 }, -- Spiked Titansteel Helm
	},
	Neck = {
		{ 44664, 1 }, -- Favor of the Dragon Queen
		{ 44659, 3 }, -- Pendant of the Dragonsworn
		{ 40065, 3 }, -- Fool's Trial
		{ 37397, 3 }, -- Gold Amulet of Kings
	},
	Shoulder = {
		{ 40530, 1 }, -- Valorous Dreadnaught Shoulderplates
		{ 40185, 1 }, -- Shoulderguards of Opportunity
		{ 39608, 3 }, -- Heroes' Dreadnaught Shoulderplates
		{ 44195, 3 }, -- Spaulders of the Giant Lords
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 40250, 1 }, -- Aged Winter Cloak
		{ 39404, 3 }, -- Cloak of Mastery
		{ 37647, 3 }, -- Cloak of Bloodied Waters
	},
	Chest = {
		{ 40539, 1 }, -- Chestguard of the Recluse
		{ 40525, 3 }, -- Valorous Dreadnaught Battleplate
		{ 39606, 1 }, -- Heroes' Dreadnaught Battleplate
		{ 40365, 3 }, -- Breastplate of Frozen Pain
	},
	Wrist = {
		{ 40330, 1 }, -- Bracers of Unrelenting Attack
		{ 40733, 3 }, -- Wristbands of the Sentinel Huntress
		{ 39765, 3 }, -- Sinner's Bindings
		{ 41355, 3 }, -- Vengeance Bindings
	},
	Hands = {
		{ 40541, 1 }, -- Frosted Adroit Handguards
		{ 40527, 3 }, -- Valorous Dreadnaught Gauntlets
		{ 39609, 3 }, -- Heroes' Dreadnaught Gauntlets
		{ 40261, 3 }, -- Crude Discolored Battlegrips
	},
	Waist = {
		{ 40317, 1 }, -- Girdle of Razuvious
		{ 40260, 3 }, -- Belt of the Tortured
		{ 40278, 3 }, -- Girdle of Chivalry
		{ 40694, 3 }, -- Jorach's Crocolisk Skin Belt
		{ 37171, 3 }, -- Flame-Bathed Steel Girdle
	},
	Legs = {
		{ 40318, 1 }, -- Legplates of Double Strikes
		{ 40529, 1 }, -- Valorous Dreadnaught Legplates
		{ 44011, 3 }, -- Leggings of the Honored
		{ 43994, 3 }, -- Belabored Legplates
	},
	Feet = {
		{ 40591, 1 }, -- Melancholy Sabatons
		{ 40206, 3 }, -- Iron-Spring Jumpers
		{ 39706, 3 }, -- Sabatons of Sudden Reprisal
		{ 40742, 3 }, -- Bladed Steelboots
	},
	Ring = {
		{ 40717, 1 }, -- Ring of Invincibility
		{ 43993, 1 }, -- Greatring of Collision
		{ 40474, 3 }, -- Surge Needle Ring
		{ 40075, 3 }, -- Ruthlessness
		{ 37642, 3 }, -- Hemorrhaging Circle
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 40256, 1 }, -- Grim Toll
		{ 40431, 3 }, -- Fury of the Five Flights
		{ 39257, 3 }, -- Loatheb's Shadow
		{ 40684, 3 }, -- Mirror of Truth
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
	},
	TwoHand = {
		{ 40384, 1 }, -- Betrayer of Humanity
		{ 40208, 3 }, -- Cryptfiend's Bite
		{ 39417, 1 }, -- Death's Bite
		{ 40497, 3 }, -- Black Ice
		{ 37852, 3 }, -- Colossal Skull-Clad Cleaver
	},
	Ranged = {
		{ 40385, 1 }, -- Envoy of Mortality
		{ 40190, 3 }, -- Spinning Fate
		{ 39419, 3 }, -- Nerubian Conquerer
		{ 37191, 3 }, -- Drake-Mounted Crossbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/arms/dps-bis-gear-pve-phase-2
ns:RegisterBiS("WARRIOR", "Arms", "P2", {
	Head = {
		{ 46151, 1 }, -- Conqueror's Siegebreaker Helmet
		{ 45472, 3 }, -- Warhelm of the Champion
		{ 45431, 3 }, -- Valorous Siegebreaker Helmet
		{ 45993, 3 }, -- Mimiron's Flight Goggles
	},
	Neck = {
		{ 45459, 1 }, -- Frigid Strength of Hodir
		{ 45517, 1 }, -- Pendulum of Infinity
		{ 45820, 3 }, -- Broach of the Wailing Night
		{ 44664, 3 }, -- Favor of the Dragon Queen
	},
	Shoulder = {
		{ 46149, 1 }, -- Conqueror's Siegebreaker Shoulderplates
		{ 46037, 1 }, -- Shoulderplates of the Celestial Watch
		{ 45245, 3 }, -- Shoulderpads of the Intruder
		{ 45433, 3 }, -- Valorous Siegebreaker Shoulderplates
	},
	Back = {
		{ 46032, 1 }, -- Drape of the Faceless General
		{ 45138, 3 }, -- Drape of the Drakerider
		{ 45973, 3 }, -- Stylish Power Cape
	},
	Chest = {
		{ 46146, 1 }, -- Conqueror's Siegebreaker Battleplate
		{ 45473, 3 }, -- Embrace of the Gladiator
		{ 45453, 3 }, -- Winter's Icy Embrace
		{ 45429, 3 }, -- Valorous Siegebreaker Battleplate
	},
	Wrist = {
		{ 45611, 1 }, -- Solar Bindings
		{ 45663, 1 }, -- Armbands of Bedlam
		{ 45888, 3 }, -- Bitter Cold Armguards
	},
	Hands = {
		{ 45444, 1 }, -- Gloves of the Steady Hand
		{ 46148, 1 }, -- Conqueror's Siegebreaker Gauntlets
		{ 45481, 3 }, -- Gauntlets of Ruthless Reprisal
		{ 45833, 3 }, -- Bladebreaker Gauntlets
	},
	Waist = {
		{ 45241, 1 }, -- Belt of Colossal Rage
		{ 46095, 1 }, -- Soul-Devouring Cinch
		{ 46041, 3 }, -- Starfall Girdle
		{ 45550, 3 }, -- Belt of the Titans
	},
	Legs = {
		{ 45536, 1 }, -- Legguards of Cunning Deception
		{ 45134, 3 }, -- Plated Leggings of Ruination
		{ 45141, 3 }, -- Proto-hide Leggings
	},
	Feet = {
		{ 45599, 1 }, -- Sabatons of Lifeless Night
		{ 40591, 1 }, -- Melancholy Sabatons
		{ 45559, 3 }, -- Battlelord's Plate Boots
	},
	Ring = {
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 46322, 1 }, -- Brann's Sealing Ring
		{ 45534, 3 }, -- Seal of the Betrayed King
		{ 45469, 3 }, -- Sif's Promise
		{ 46048, 3 }, -- Band of Lights
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 45609, 1 }, -- Comet's Trail
		{ 46038, 3 }, -- Dark Matter
		{ 40256, 3 }, -- Grim Toll
		{ 40684, 3 }, -- Mirror of Truth
	},
	TwoHand = {
		{ 45516, 1 }, -- Voldrethar, Dark Blade of Oblivion
		{ 45533, 1 }, -- Dark Edge of Depravity
		{ 45498, 3 }, -- Lotrafen, Spear of the Damned
		{ 45868, 3 }, -- Aesir's Edge
		{ 45165, 3 }, -- Worldcarver
		{ 40384, 3 }, -- Betrayer of Humanity
	},
	Ranged = {
		{ 45296, 1 }, -- Twirling Blades
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 40385, 3 }, -- Envoy of Mortality
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/arms/dps-bis-gear-pve-phase-3
ns:RegisterBiS("WARRIOR", "Arms", "P3", {
	Head = {
		{ 48398, 1 }, -- Hellscream's Helmet of Triumph
		{ 48383, 1 }, -- Wrynn's Helmet of Triumph
		{ 49478, 1 }, -- Helmet of Wrath
		{ 48393, 3 }, -- Hellscream's Helmet of Triumph
		{ 48378, 3 }, -- Wrynn's Helmet of Triumph
		{ 47675, 3 }, -- Faceplate of Thunderous Rampage
		{ 47674, 3 }, -- Helm of Thunderous Rampage
		{ 45472, 3 }, -- Warhelm of the Champion
	},
	Neck = {
		{ 47988, 1 }, -- Collar of Unending Torment
		{ 47915, 1 }, -- Collar of Ceaseless Torment
		{ 47433, 3 }, -- Charge of the Eredar
		{ 47060, 3 }, -- Charge of the Demon Lord
		{ 47458, 3 }, -- The Executioner's Vice
		{ 47110, 3 }, -- The Executioner's Malice
		{ 45459, 3 }, -- Frigid Strength of Hodir
		{ 45517, 3 }, -- Pendulum of Infinity
	},
	Shoulder = {
		{ 48400, 1 }, -- Hellscream's Shoulderplates of Triumph
		{ 48381, 1 }, -- Wrynn's Shoulderplates of Triumph
		{ 47709, 3 }, -- Duskstalker Pauldrons
		{ 47708, 3 }, -- Duskstalker Shoulderpads
		{ 48395, 3 }, -- Hellscream's Shoulderplates of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
	},
	Back = {
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 48668, 1 }, -- Cloak of Serrated Blades
		{ 48673, 1 }, -- Cloak of the Silver Covenant
		{ 47418, 1 }, -- Cloak of the Untamed Predator
		{ 46971, 1 }, -- Drape of the Untamed Predator
		{ 46032, 1 }, -- Drape of the Faceless General
	},
	Chest = {
		{ 48396, 1 }, -- Hellscream's Battleplate of Triumph
		{ 48385, 1 }, -- Wrynn's Battleplate of Triumph
		{ 48391, 1 }, -- Hellscream's Battleplate of Triumph
		{ 48376, 1 }, -- Wrynn's Battleplate of Triumph
		{ 48026, 3 }, -- Vest of Shifting Shadows
		{ 47954, 3 }, -- Armor of Shifting Shadows
		{ 46146, 3 }, -- Conqueror's Siegebreaker Battleplate
		{ 45473, 3 }, -- Embrace of the Gladiator
	},
	Wrist = {
		{ 47442, 1 }, -- Bracers of the Silent Massacre
		{ 47074, 1 }, -- Bracers of the Untold Massacre
		{ 48008, 3 }, -- Armplates of the Nether Lord
		{ 47935, 3 }, -- Armguards of the Nether Lord
		{ 47474, 3 }, -- Armbands of Dark Determination
		{ 47155, 3 }, -- Bracers of Dark Determination
		{ 45611, 3 }, -- Solar Bindings
		{ 45663, 3 }, -- Armbands of Bedlam
	},
	Hands = {
		{ 47492, 1 }, -- Gauntlets of Bitter Reprisal
		{ 47240, 1 }, -- Gloves of Bitter Reprisal
		{ 48017, 1 }, -- Sunreaver Assassin's Gloves
		{ 47945, 1 }, -- Gloves of the Silver Assassin
		{ 47990, 3 }, -- Gauntlets of Mounting Anger
		{ 47917, 3 }, -- Gauntlets of Rising Anger
		{ 46148, 3 }, -- Conqueror's Siegebreaker Gauntlets
	},
	Waist = {
		{ 47472, 1 }, -- Waistguard of Deathly Dominion
		{ 47153, 1 }, -- Belt of Deathly Dominion
		{ 47460, 3 }, -- Belt of the Pitiless Killer
		{ 47112, 3 }, -- Belt of the Merciless Killer
		{ 47429, 3 }, -- Bloodbath Girdle
		{ 47002, 3 }, -- Bloodbath Belt
		{ 47998, 3 }, -- Belt of the Impaler
		{ 47925, 3 }, -- Girdle of the Impaler
	},
	Legs = {
		{ 48399, 1 }, -- Hellscream's Legplates of Triumph
		{ 48382, 1 }, -- Wrynn's Legplates of Triumph
		{ 47480, 1 }, -- Leggings of the Lurking Threat
		{ 47191, 1 }, -- Legguards of the Lurking Threat
		{ 48394, 3 }, -- Hellscream's Legplates of Triumph
		{ 48379, 3 }, -- Wrynn's Legplates of Triumph
		{ 45536, 3 }, -- Legguards of Cunning Deception
	},
	Feet = {
		{ 47445, 1 }, -- Icewalker Treads
		{ 47077, 1 }, -- Treads of the Icewalker
		{ 47457, 1 }, -- Greaves of Ruthless Judgment
		{ 47109, 1 }, -- Sabatons of Ruthless Judgment
		{ 47473, 3 }, -- Greaves of the Saronite Citadel
		{ 47154, 3 }, -- Greaves of the 7th Legion
		{ 45599, 3 }, -- Sabatons of Lifeless Night
		{ 40591, 3 }, -- Melancholy Sabatons
	},
	Ring = {
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 48007, 1 }, -- Planestalker Band
		{ 47934, 1 }, -- Planestalker Signet
		{ 47443, 1 }, -- Band of Callous Aggression
		{ 47075, 1 }, -- Ring of Callous Aggression
		{ 46322, 3 }, -- Brann's Sealing Ring
	},
	Trinket = {
		{ 47464, 1 }, -- Death's Choice
		{ 47131, 1 }, -- Death's Verdict
		{ 46038, 1 }, -- Dark Matter
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 42987, 3 }, -- Darkmoon Card: Greatness
	},
	TwoHand = {
		{ 47446, 1 }, -- Dual-blade Butcher
		{ 47078, 1 }, -- Justicebringer
		{ 47491, 1 }, -- Hellion Glaive
		{ 47239, 1 }, -- Archon Glaive
		{ 47516, 3 }, -- Fleshrender
		{ 47515, 3 }, -- Decimation
		{ 45516, 3 }, -- Voldrethar, Dark Blade of Oblivion
	},
	Ranged = {
		{ 46995, 1 }, -- Talonstrike
		{ 47428, 1 }, -- Death's Head Crossbow
		{ 45296, 1 }, -- Twirling Blades
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/arms/dps-bis-gear-pve-phase-4
ns:RegisterBiS("WARRIOR", "Arms", "P4", {
	Head = {
		{ 51227, 1 }, -- Sanctified Ymirjar Lord's Helmet
		{ 51212, 3 }, -- Sanctified Ymirjar Lord's Helmet
		{ 50080, 3 }, -- Ymirjar Lord's Helmet
		{ 51877, 3 }, -- Taldron's Short-Sighted Helm
	},
	Neck = {
		{ 54581, 1 }, -- Penumbra Pendant
		{ 50728, 1 }, -- Lana'thel's Chain of Flagellation
		{ 51822, 3 }, -- Rimetooth Pendant
		{ 50633, 3 }, -- Sindragosa's Cruel Claw
		{ 47433, 3 }, -- Charge of the Eredar
		{ 47060, 3 }, -- Charge of the Demon Lord
	},
	Shoulder = {
		{ 51229, 1 }, -- Sanctified Ymirjar Lord's Shoulderplates
		{ 51210, 3 }, -- Sanctified Ymirjar Lord's Shoulderplates
		{ 50082, 3 }, -- Ymirjar Lord's Shoulderplates
		{ 51830, 3 }, -- Skinned Whelp Shoulders
	},
	Back = {
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 50653, 3 }, -- Shadowvault Slayer's Cloak
		{ 50470, 3 }, -- Recovered Scarlet Onslaught Cape
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 48673, 3 }, -- Cloak of the Silver Covenant
	},
	Chest = {
		{ 51225, 1 }, -- Sanctified Ymirjar Lord's Battleplate
		{ 51214, 3 }, -- Sanctified Ymirjar Lord's Battleplate
		{ 50078, 3 }, -- Ymirjar Lord's Battleplate
		{ 51923, 3 }, -- Chestguard of the Frigid Noose
	},
	Wrist = {
		{ 54580, 1 }, -- Umbrage Armbands
		{ 50670, 1 }, -- Toskk's Maximized Wristguards
		{ 50659, 3 }, -- Polar Bear Claw Bracers
		{ 50655, 3 }, -- Scourge Hunter's Vambraces
		{ 47442, 1 }, -- Bracers of the Silent Massacre
		{ 47074, 1 }, -- Bracers of the Untold Massacre
	},
	Hands = {
		{ 51226, 1 }, -- Sanctified Ymirjar Lord's Gauntlets
		{ 51213, 3 }, -- Sanctified Ymirjar Lord's Gauntlets
		{ 50079, 3 }, -- Ymirjar Lord's Gauntlets
		{ 50675, 3 }, -- Aldriana's Gloves of Secrecy
	},
	Waist = {
		{ 50707, 1 }, -- Astrylian's Sutured Cinch
		{ 50620, 3 }, -- Coldwraith Links
		{ 50688, 3 }, -- Nerub'ar Stalker's Cord
		{ 47429, 3 }, -- Bloodbath Girdle
		{ 47002, 3 }, -- Bloodbath Belt
	},
	Legs = {
		{ 50645, 1 }, -- Leggings of Northern Lights
		{ 51841, 3 }, -- Ivory-Inlaid Leggings
		{ 51228, 3 }, -- Sanctified Ymirjar Lord's Legplates
		{ 49903, 3 }, -- Legplates of Painful Death
	},
	Feet = {
		{ 54578, 1 }, -- Apocalypse's Advance
		{ 50639, 1 }, -- Blood-Soaked Saronite Stompers
		{ 50607, 3 }, -- Frostbitten Fur Boots
		{ 51856, 3 }, -- Taldaram's Soft Slippers
		{ 49906, 3 }, -- Hellfrozen Bonegrinders
	},
	Ring = {
		{ 50402, 1 }, -- Ashen Band of Endless Vengeance
		{ 50618, 1 }, -- Frostbrood Sapphire Ring
		{ 50693, 3 }, -- Might of Blight
		{ 51900, 3 }, -- Saurfang's Cold-Forged Band
		{ 50401, 3 }, -- Ashen Band of Unmatched Vengeance
		{ 47443, 3 }, -- Band of Callous Aggression
		{ 47075, 3 }, -- Ring of Callous Aggression
		{ 45608, 3 }, -- Brann's Signet Ring
	},
	Trinket = {
		{ 50363, 1 }, -- Deathbringer's Will
		{ 50362, 1 }, -- Deathbringer's Will
		{ 50343, 1 }, -- Whispering Fanged Skull
		{ 47464, 1 }, -- Death's Choice
		{ 47131, 1 }, -- Death's Verdict
		{ 45609, 3 }, -- Comet's Trail
	},
	TwoHand = {
		{ 49623, 1 }, -- Shadowmourne
		{ 50735, 1 }, -- Oathbinder, Charge of the Ranger-General
		{ 50730, 3 }, -- Glorenzelg, High-Blade of the Silver Hand
		{ 50727, 3 }, -- Bloodfall
		{ 50709, 3 }, -- Bryntroll, the Bone Arbiter
		{ 51857, 3 }, -- Hersir's Greatspear
		{ 49888, 3 }, -- Shadow's Edge
	},
	Ranged = {
		{ 50733, 1 }, -- Fal'inrush, Defender of Quel'thalas
		{ 51940, 1 }, -- Windrunner's Heartseeker
		{ 51845, 1 }, -- Stakethrower
		{ 51927, 3 }, -- Njorndar Bone Bow
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 46995, 3 }, -- Talonstrike
		{ 45296, 3 }, -- Twirling Blades
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/fury/dps-bis-gear-pre-raid-pve
ns:RegisterBiS("WARRIOR", "Fury", "PreRaid", {
	Head = {
		{ 41386, 1 }, -- Spiked Titansteel Helm
		{ 42552, 3 }, -- Charged Titanium Specs
		{ 34345, 3 }, -- Crown of Anasterian
		{ 37237, 3 }, -- Chitin Shell Greathelm
	},
	Neck = {
		{ 42645, 1 }, -- Titanium Impact Choker
		{ 40678, 1 }, -- Pendant of the Outcast Hero
		{ 37397, 1 }, -- Gold Amulet of Kings
	},
	Shoulder = {
		{ 44195, 1 }, -- Spaulders of the Giant Lords
		{ 34388, 3 }, -- Pauldrons of Berserking
		{ 44111, 3 }, -- Gold Star Spaulders
	},
	Back = {
		{ 37647, 1 }, -- Cloak of Bloodied Waters
		{ 37840, 3 }, -- Shroud of Reverberation
		{ 44216, 3 }, -- Cloak of Holy Extermination
	},
	Chest = {
		{ 39606, 1 }, -- Heroes' Dreadnaught Battleplate
		{ 44303, 3 }, -- Darkheart Chestguard
		{ 37612, 3 }, -- Bonegrinder Breastplate
	},
	Wrist = {
		{ 41355, 1 }, -- Vengeance Bindings
		{ 44203, 1 }, -- Dragonfriend Bracers
		{ 37853, 3 }, -- Advanced Tooled-Leather Bands
	},
	Hands = {
		{ 39609, 1 }, -- Heroes' Dreadnaught Gauntlets
		{ 37363, 3 }, -- Gauntlets of Dragon Wrath
		{ 34341, 3 }, -- Borderland Paingrips
	},
	Waist = {
		{ 40694, 1 }, -- Jorach's Crocolisk Skin Belt
		{ 37171, 3 }, -- Flame-Bathed Steel Girdle
		{ 37194, 3 }, -- Sharp-Barbed Leather Belt
	},
	Legs = {
		{ 37193, 1 }, -- Staggering Legplates
		{ 44205, 1 }, -- Legplates of Bloody Reprisal
		{ 34180, 3 }, -- Felfury Legplates
	},
	Feet = {
		{ 44306, 1 }, -- Death-Inured Sabatons
		{ 37150, 3 }, -- Rift Striders
		{ 43402, 3 }, -- The Obliterator Greaves
	},
	Ring = {
		{ 37642, 1 }, -- Hemorrhaging Circle
		{ 43251, 3 }, -- Ring of Scarlet Shadows
		{ 42642, 3 }, -- Titanium Impact Band
		{ 44935, 3 }, -- Ring of the Kirin Tor
		{ 37151, 3 }, -- Band of Frosted Thorns
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 40684, 1 }, -- Mirror of Truth
		{ 37166, 1 }, -- Sphere of Red Dragon's Blood
		{ 37390, 3 }, -- Meteorite Whetstone
		{ 33831, 3 }, -- Berserker's Call
	},
	TwoHand = {
		{ 37852, 1 }, -- Colossal Skull-Clad Cleaver
		{ 41257, 1 }, -- Titansteel Destroyer
		{ 44249, 1 }, -- Runeblade of Demonstrable Power
		{ 44244, 1 }, -- Argent Skeleton Crusher
		{ 37653, 1 }, -- Sword of Justice
	},
	Ranged = {
		{ 37191, 1 }, -- Drake-Mounted Crossbow
		{ 44504, 3 }, -- Nesingwary 4000
		{ 44245, 3 }, -- Zombie Sweeper Shotgun
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/fury/dps-bis-gear-pve-phase-1
ns:RegisterBiS("WARRIOR", "Fury", "P1", {
	Head = {
		{ 40528, 1 }, -- Valorous Dreadnaught Helmet
		{ 44006, 3 }, -- Obsidian Greathelm
		{ 39605, 3 }, -- Heroes' Dreadnaught Helmet
		{ 41386, 3 }, -- Spiked Titansteel Helm
	},
	Neck = {
		{ 44664, 1 }, -- Favor of the Dragon Queen
		{ 44659, 3 }, -- Pendant of the Dragonsworn
		{ 40065, 3 }, -- Fool's Trial
		{ 37397, 3 }, -- Gold Amulet of Kings
	},
	Shoulder = {
		{ 40530, 1 }, -- Valorous Dreadnaught Shoulderplates
		{ 40185, 1 }, -- Shoulderguards of Opportunity
		{ 39608, 3 }, -- Heroes' Dreadnaught Shoulderplates
		{ 44195, 3 }, -- Spaulders of the Giant Lords
	},
	Back = {
		{ 40403, 1 }, -- Drape of the Deadly Foe
		{ 40250, 1 }, -- Aged Winter Cloak
		{ 39404, 3 }, -- Cloak of Mastery
		{ 37647, 3 }, -- Cloak of Bloodied Waters
	},
	Chest = {
		{ 40539, 1 }, -- Chestguard of the Recluse
		{ 40525, 1 }, -- Valorous Dreadnaught Battleplate
		{ 39606, 1 }, -- Heroes' Dreadnaught Battleplate
		{ 40365, 3 }, -- Breastplate of Frozen Pain
	},
	Wrist = {
		{ 39765, 1 }, -- Sinner's Bindings
		{ 40330, 1 }, -- Bracers of Unrelenting Attack
		{ 40733, 3 }, -- Wristbands of the Sentinel Huntress
		{ 41355, 3 }, -- Vengeance Bindings
	},
	Hands = {
		{ 40541, 1 }, -- Frosted Adroit Handguards
		{ 40527, 3 }, -- Valorous Dreadnaught Gauntlets
		{ 39609, 3 }, -- Heroes' Dreadnaught Gauntlets
		{ 40261, 3 }, -- Crude Discolored Battlegrips
		{ 40347, 3 }, -- Zeliek's Gauntlets
	},
	Waist = {
		{ 40205, 1 }, -- Stalk-Skin Belt
		{ 40317, 1 }, -- Girdle of Razuvious
		{ 40260, 3 }, -- Belt of the Tortured
		{ 40278, 3 }, -- Girdle of Chivalry
		{ 40694, 3 }, -- Jorach's Crocolisk Skin Belt
		{ 37171, 3 }, -- Flame-Bathed Steel Girdle
	},
	Legs = {
		{ 40318, 1 }, -- Legplates of Double Strikes
		{ 40529, 3 }, -- Valorous Dreadnaught Legplates
		{ 44011, 1 }, -- Leggings of the Honored
		{ 43994, 3 }, -- Belabored Legplates
	},
	Feet = {
		{ 40591, 1 }, -- Melancholy Sabatons
		{ 40206, 3 }, -- Iron-Spring Jumpers
		{ 40742, 3 }, -- Bladed Steelboots
	},
	Ring = {
		{ 40717, 1 }, -- Ring of Invincibility
		{ 43993, 1 }, -- Greatring of Collision
		{ 40474, 3 }, -- Surge Needle Ring
		{ 40075, 3 }, -- Ruthlessness
		{ 37642, 1 }, -- Hemorrhaging Circle
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 40256, 1 }, -- Grim Toll
		{ 40431, 1 }, -- Fury of the Five Flights
		{ 39257, 3 }, -- Loatheb's Shadow
		{ 40684, 3 }, -- Mirror of Truth
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
	},
	TwoHand = {
		{ 40384, 1 }, -- Betrayer of Humanity
		{ 40406, 3 }, -- Inevitable Defeat
		{ 39417, 1 }, -- Death's Bite
		{ 40343, 3 }, -- Armageddon
		{ 37852, 3 }, -- Colossal Skull-Clad Cleaver
	},
	Ranged = {
		{ 40385, 1 }, -- Envoy of Mortality
		{ 40190, 3 }, -- Spinning Fate
		{ 37191, 3 }, -- Drake-Mounted Crossbow
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/fury/dps-bis-gear-pve-phase-2
ns:RegisterBiS("WARRIOR", "Fury", "P2", {
	Head = {
		{ 46151, 1 }, -- Conqueror's Siegebreaker Helmet
		{ 45472, 3 }, -- Warhelm of the Champion
		{ 45431, 3 }, -- Valorous Siegebreaker Helmet
		{ 45993, 3 }, -- Mimiron's Flight Goggles
	},
	Neck = {
		{ 45459, 1 }, -- Frigid Strength of Hodir
		{ 45517, 1 }, -- Pendulum of Infinity
		{ 45820, 3 }, -- Broach of the Wailing Night
		{ 44664, 3 }, -- Favor of the Dragon Queen
	},
	Shoulder = {
		{ 46149, 1 }, -- Conqueror's Siegebreaker Shoulderplates
		{ 46037, 1 }, -- Shoulderplates of the Celestial Watch
		{ 45245, 3 }, -- Shoulderpads of the Intruder
		{ 45433, 3 }, -- Valorous Siegebreaker Shoulderplates
	},
	Back = {
		{ 46032, 1 }, -- Drape of the Faceless General
		{ 45138, 3 }, -- Drape of the Drakerider
		{ 45973, 3 }, -- Stylish Power Cape
	},
	Chest = {
		{ 46146, 1 }, -- Conqueror's Siegebreaker Battleplate
		{ 45473, 3 }, -- Embrace of the Gladiator
		{ 45453, 3 }, -- Winter's Icy Embrace
		{ 45429, 3 }, -- Valorous Siegebreaker Battleplate
	},
	Wrist = {
		{ 45611, 1 }, -- Solar Bindings
		{ 45663, 3 }, -- Armbands of Bedlam
		{ 45888, 3 }, -- Bitter Cold Armguards
	},
	Hands = {
		{ 46148, 1 }, -- Conqueror's Siegebreaker Gauntlets
		{ 45481, 3 }, -- Gauntlets of Ruthless Reprisal
		{ 45833, 3 }, -- Bladebreaker Gauntlets
	},
	Waist = {
		{ 46095, 1 }, -- Soul-Devouring Cinch
		{ 46041, 3 }, -- Starfall Girdle
		{ 45550, 3 }, -- Belt of the Titans
	},
	Legs = {
		{ 45536, 1 }, -- Legguards of Cunning Deception
		{ 45134, 3 }, -- Plated Leggings of Ruination
		{ 45141, 3 }, -- Proto-hide Leggings
	},
	Feet = {
		{ 45599, 1 }, -- Sabatons of Lifeless Night
		{ 40591, 1 }, -- Melancholy Sabatons
		{ 45559, 3 }, -- Battlelord's Plate Boots
	},
	Ring = {
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 46322, 1 }, -- Brann's Sealing Ring
		{ 45469, 3 }, -- Sif's Promise
		{ 45534, 3 }, -- Seal of the Betrayed King
		{ 46048, 3 }, -- Band of Lights
	},
	Trinket = {
		{ 42987, 1 }, -- Darkmoon Card: Greatness
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 45609, 1 }, -- Comet's Trail
		{ 46038, 3 }, -- Dark Matter
		{ 40256, 3 }, -- Grim Toll
		{ 40684, 3 }, -- Mirror of Truth
	},
	TwoHand = {
		{ 45516, 1 }, -- Voldrethar, Dark Blade of Oblivion
		{ 45868, 1 }, -- Aesir's Edge
		{ 46067, 3 }, -- Hammer of Crushing Whispers
		{ 45233, 3 }, -- Stormrune Edge
		{ 45165, 3 }, -- Worldcarver
		{ 40384, 3 }, -- Betrayer of Humanity
	},
	Ranged = {
		{ 45296, 1 }, -- Twirling Blades
		{ 45870, 3 }, -- Magnetized Projectile Emitter
		{ 40385, 3 }, -- Envoy of Mortality
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/fury/dps-bis-gear-pve-phase-3
ns:RegisterBiS("WARRIOR", "Fury", "P3", {
	Head = {
		{ 48398, 1 }, -- Hellscream's Helmet of Triumph
		{ 48383, 1 }, -- Wrynn's Helmet of Triumph
		{ 48393, 1 }, -- Hellscream's Helmet of Triumph
		{ 48378, 1 }, -- Wrynn's Helmet of Triumph
		{ 49478, 3 }, -- Helmet of Wrath
		{ 45472, 3 }, -- Warhelm of the Champion
	},
	Neck = {
		{ 47433, 1 }, -- Charge of the Eredar
		{ 47060, 1 }, -- Charge of the Demon Lord
		{ 47458, 1 }, -- The Executioner's Vice
		{ 47110, 1 }, -- The Executioner's Malice
		{ 47988, 3 }, -- Collar of Unending Torment
		{ 47915, 3 }, -- Collar of Ceaseless Torment
		{ 45459, 3 }, -- Frigid Strength of Hodir
		{ 45517, 3 }, -- Pendulum of Infinity
	},
	Shoulder = {
		{ 48400, 1 }, -- Hellscream's Shoulderplates of Triumph
		{ 48381, 1 }, -- Wrynn's Shoulderplates of Triumph
		{ 48049, 3 }, -- Shoulderpads of the Snow Bandit
		{ 47972, 3 }, -- Spaulders of the Snow Bandit
		{ 48395, 3 }, -- Hellscream's Shoulderplates of Triumph
		{ 45245, 3 }, -- Shoulderpads of the Intruder
	},
	Back = {
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 48668, 1 }, -- Cloak of Serrated Blades
		{ 48673, 1 }, -- Cloak of the Silver Covenant
		{ 47418, 1 }, -- Cloak of the Untamed Predator
		{ 46971, 1 }, -- Drape of the Untamed Predator
		{ 46032, 1 }, -- Drape of the Faceless General
	},
	Chest = {
		{ 48396, 1 }, -- Hellscream's Battleplate of Triumph
		{ 48385, 1 }, -- Wrynn's Battleplate of Triumph
		{ 48391, 1 }, -- Hellscream's Battleplate of Triumph
		{ 48376, 1 }, -- Wrynn's Battleplate of Triumph
		{ 47431, 3 }, -- Vest of Calamitous Fate
		{ 47004, 3 }, -- Cuirass of Calamitous Fate
		{ 46146, 3 }, -- Conqueror's Siegebreaker Battleplate
		{ 45473, 3 }, -- Embrace of the Gladiator
	},
	Wrist = {
		{ 47442, 1 }, -- Bracers of the Silent Massacre
		{ 47074, 1 }, -- Bracers of the Untold Massacre
		{ 47414, 1 }, -- Boneshatter Vambraces
		{ 46967, 1 }, -- Boneshatter Armplates
		{ 47474, 1 }, -- Armbands of Dark Determination
		{ 47155, 1 }, -- Bracers of Dark Determination
		{ 45611, 3 }, -- Solar Bindings
		{ 45663, 3 }, -- Armbands of Bedlam
	},
	Hands = {
		{ 47492, 1 }, -- Gauntlets of Bitter Reprisal
		{ 47240, 1 }, -- Gloves of Bitter Reprisal
		{ 48017, 1 }, -- Sunreaver Assassin's Gloves
		{ 47945, 1 }, -- Gloves of the Silver Assassin
		{ 47990, 1 }, -- Gauntlets of Mounting Anger
		{ 47917, 1 }, -- Gauntlets of Rising Anger
		{ 46148, 1 }, -- Conqueror's Siegebreaker Gauntlets
	},
	Waist = {
		{ 47429, 1 }, -- Bloodbath Girdle
		{ 47002, 1 }, -- Bloodbath Belt
		{ 46095, 1 }, -- Soul-Devouring Cinch
		{ 47472, 3 }, -- Waistguard of Deathly Dominion
		{ 47153, 3 }, -- Belt of Deathly Dominion
		{ 47998, 3 }, -- Belt of the Impaler
		{ 47925, 3 }, -- Girdle of the Impaler
	},
	Legs = {
		{ 48399, 1 }, -- Hellscream's Legplates of Triumph
		{ 48382, 1 }, -- Wrynn's Legplates of Triumph
		{ 48394, 1 }, -- Hellscream's Legplates of Triumph
		{ 48379, 1 }, -- Wrynn's Legplates of Triumph
		{ 47480, 3 }, -- Leggings of the Lurking Threat
		{ 47191, 3 }, -- Legguards of the Lurking Threat
		{ 45536, 3 }, -- Legguards of Cunning Deception
	},
	Feet = {
		{ 47473, 1 }, -- Greaves of the Saronite Citadel
		{ 47154, 1 }, -- Greaves of the 7th Legion
		{ 47445, 3 }, -- Icewalker Treads
		{ 47077, 3 }, -- Treads of the Icewalker
		{ 45599, 3 }, -- Sabatons of Lifeless Night
		{ 40591, 3 }, -- Melancholy Sabatons
	},
	Ring = {
		{ 47443, 1 }, -- Band of Callous Aggression
		{ 47075, 1 }, -- Ring of Callous Aggression
		{ 47413, 1 }, -- Ring of the Violent Temperament
		{ 46966, 1 }, -- Band of the Violent Temperment
		{ 47993, 1 }, -- Gormok's Band
		{ 47920, 1 }, -- Carnivorous Band
		{ 45608, 1 }, -- Brann's Signet Ring
		{ 46322, 1 }, -- Brann's Sealing Ring
	},
	Trinket = {
		{ 47464, 1 }, -- Death's Choice
		{ 47131, 1 }, -- Death's Verdict
		{ 45931, 1 }, -- Mjolnir Runestone
		{ 45609, 1 }, -- Comet's Trail
		{ 46038, 3 }, -- Dark Matter
		{ 42987, 3 }, -- Darkmoon Card: Greatness
	},
	TwoHand = {
		{ 47446, 1 }, -- Dual-blade Butcher
		{ 47078, 1 }, -- Justicebringer
		{ 47520, 1 }, -- Grievance
		{ 47519, 1 }, -- Catastrophe
		{ 45516, 3 }, -- Voldrethar, Dark Blade of Oblivion
		{ 47516, 3 }, -- Fleshrender
		{ 47515, 3 }, -- Decimation
		{ 45868, 3 }, -- Aesir's Edge
	},
	Ranged = {
		{ 47428, 1 }, -- Death's Head Crossbow
		{ 46995, 1 }, -- Talonstrike
		{ 47523, 1 }, -- Fezzik's Autocannon
		{ 47521, 1 }, -- BRK-1000
		{ 45296, 1 }, -- Twirling Blades
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/fury/dps-bis-gear-pve-phase-4
ns:RegisterBiS("WARRIOR", "Fury", "P4", {
	Head = {
		{ 51227, 1 }, -- Sanctified Ymirjar Lord's Helmet
		{ 51212, 3 }, -- Sanctified Ymirjar Lord's Helmet
		{ 50080, 3 }, -- Ymirjar Lord's Helmet
		{ 51866, 3 }, -- Discarded Bag of Entrails
	},
	Neck = {
		{ 54581, 1 }, -- Penumbra Pendant
		{ 50633, 3 }, -- Sindragosa's Cruel Claw
		{ 51822, 3 }, -- Rimetooth Pendant
		{ 50728, 3 }, -- Lana'thel's Chain of Flagellation
		{ 47433, 3 }, -- Charge of the Eredar
		{ 47060, 3 }, -- Charge of the Demon Lord
	},
	Shoulder = {
		{ 51229, 1 }, -- Sanctified Ymirjar Lord's Shoulderplates
		{ 51210, 3 }, -- Sanctified Ymirjar Lord's Shoulderplates
		{ 50082, 3 }, -- Ymirjar Lord's Shoulderplates
		{ 51830, 3 }, -- Skinned Whelp Shoulders
	},
	Back = {
		{ 47546, 1 }, -- Sylvanas' Cunning
		{ 47545, 1 }, -- Vereesa's Dexterity
		{ 50653, 1 }, -- Shadowvault Slayer's Cloak
		{ 50470, 3 }, -- Recovered Scarlet Onslaught Cape
		{ 48668, 3 }, -- Cloak of Serrated Blades
		{ 48673, 3 }, -- Cloak of the Silver Covenant
	},
	Chest = {
		{ 51225, 1 }, -- Sanctified Ymirjar Lord's Battleplate
		{ 51214, 3 }, -- Sanctified Ymirjar Lord's Battleplate
		{ 50078, 3 }, -- Ymirjar Lord's Battleplate
		{ 51923, 3 }, -- Chestguard of the Frigid Noose
	},
	Wrist = {
		{ 54580, 1 }, -- Umbrage Armbands
		{ 50670, 1 }, -- Toskk's Maximized Wristguards
		{ 50659, 3 }, -- Polar Bear Claw Bracers
		{ 50655, 3 }, -- Scourge Hunter's Vambraces
		{ 47442, 3 }, -- Bracers of the Silent Massacre
		{ 47074, 3 }, -- Bracers of the Untold Massacre
	},
	Hands = {
		{ 50675, 1 }, -- Aldriana's Gloves of Secrecy
		{ 50690, 3 }, -- Fleshrending Gauntlets
		{ 51904, 1 }, -- Scourge Stranglers
		{ 50977, 3 }, -- Gatecrasher's Gauntlets
		{ 47492, 3 }, -- Gauntlets of Bitter Reprisal
		{ 47240, 3 }, -- Gloves of Bitter Reprisal
	},
	Waist = {
		{ 50707, 1 }, -- Astrylian's Sutured Cinch
		{ 50620, 1 }, -- Coldwraith Links
		{ 50688, 3 }, -- Nerub'ar Stalker's Cord
		{ 47429, 3 }, -- Bloodbath Girdle
		{ 47002, 3 }, -- Bloodbath Belt
	},
	Legs = {
		{ 51228, 1 }, -- Sanctified Ymirjar Lord's Legplates
		{ 51211, 3 }, -- Sanctified Ymirjar Lord's Legplates
		{ 50081, 3 }, -- Ymirjar Lord's Legplates
		{ 50645, 3 }, -- Leggings of Northern Lights
		{ 49903, 3 }, -- Legplates of Painful Death
	},
	Feet = {
		{ 54578, 1 }, -- Apocalypse's Advance
		{ 50639, 1 }, -- Blood-Soaked Saronite Stompers
		{ 50607, 3 }, -- Frostbitten Fur Boots
		{ 51856, 3 }, -- Taldaram's Soft Slippers
		{ 49906, 3 }, -- Hellfrozen Bonegrinders
	},
	Ring = {
		{ 50402, 1 }, -- Ashen Band of Endless Vengeance
		{ 50618, 1 }, -- Frostbrood Sapphire Ring
		{ 50693, 3 }, -- Might of Blight
		{ 51900, 3 }, -- Saurfang's Cold-Forged Band
		{ 50401, 3 }, -- Ashen Band of Unmatched Vengeance
		{ 47443, 3 }, -- Band of Callous Aggression
		{ 47075, 3 }, -- Ring of Callous Aggression
		{ 45608, 3 }, -- Brann's Signet Ring
	},
	Trinket = {
		{ 50363, 1 }, -- Deathbringer's Will
		{ 54590, 1 }, -- Sharpened Twilight Scale
		{ 50362, 3 }, -- Deathbringer's Will
		{ 50343, 3 }, -- Whispering Fanged Skull
		{ 47464, 3 }, -- Death's Choice
		{ 47131, 3 }, -- Death's Verdict
		{ 45609, 3 }, -- Comet's Trail
	},
	TwoHand = {
		{ 49623, 1 }, -- Shadowmourne
		{ 50730, 1 }, -- Glorenzelg, High-Blade of the Silver Hand
		{ 51946, 3 }, -- Warmace of Menethil
		{ 50603, 3 }, -- Cryptmaker
		{ 50709, 3 }, -- Bryntroll, the Bone Arbiter
		{ 49888, 3 }, -- Shadow's Edge
	},
	Ranged = {
		{ 50733, 1 }, -- Fal'inrush, Defender of Quel'thalas
		{ 51940, 1 }, -- Windrunner's Heartseeker
		{ 51845, 1 }, -- Stakethrower
		{ 51927, 3 }, -- Njorndar Bone Bow
		{ 47428, 3 }, -- Death's Head Crossbow
		{ 46995, 3 }, -- Talonstrike
		{ 45296, 3 }, -- Twirling Blades
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/protection/tank-bis-gear-pre-raid-pve
ns:RegisterBiS("WARRIOR", "Protection", "PreRaid", {
	Head = {
		{ 42549, 1 }, -- Armored Titanium Goggles
		{ 34401, 3 }, -- Helm of Uther's Resolve
		{ 37633, 3 }, -- Ground Tremor Helm
		{ 36969, 3 }, -- Helm of the Ley-Guardian
		{ 37135, 3 }, -- Arcane-Shielded Helm
		{ 41387, 3 }, -- Tempered Titansteel Helm
		{ 44040, 3 }, -- The Crusader's Resolution
	},
	Neck = {
		{ 37646, 1 }, -- Burning Skull Pendant
		{ 40679, 3 }, -- Chained Military Gorget
		{ 42646, 3 }, -- Titanium Earthguard Chain
		{ 43282, 3 }, -- Shadowseeker's Pendant
		{ 37689, 3 }, -- Pendant of the Nathrezim
		{ 37053, 3 }, -- Amulet of Deflected Blows
		{ 39655, 3 }, -- Betrayer's Choker
	},
	Shoulder = {
		{ 34389, 1 }, -- Spaulders of the Thalassian Defender
		{ 44312, 3 }, -- Wapach's Spaulders of Solidarity
		{ 34192, 1 }, -- Pauldrons of Perseverance
		{ 37814, 3 }, -- Iron Dwarf Smith Pauldrons
		{ 37635, 3 }, -- Pauldrons of the Colossus
		{ 44373, 3 }, -- Pauldrons of Reconnaissance
	},
	Back = {
		{ 37197, 3 }, -- Tattered Castle Drape
		{ 37728, 3 }, -- Cloak of the Enemy
		{ 44188, 3 }, -- Cloak of Peaceful Resolutions
	},
	Chest = {
		{ 39611, 1 }, -- Heroes' Dreadnaught Breastplate
		{ 44198, 3 }, -- Breastplate of the Solemn Council
		{ 37658, 3 }, -- Sun-Emblazoned Chestplate
		{ 37722, 3 }, -- Breastplate of Undeath
		{ 37735, 3 }, -- Ziggurat Imprinted Chestguard
		{ 44383, 3 }, -- Battleplate of Unheard Ovation
	},
	Wrist = {
		{ 37620, 1 }, -- Bracers of the Herald
		{ 37682, 3 }, -- Bindings of Dark Will
		{ 37040, 3 }, -- Svala's Bloodied Shackles
		{ 34442, 3 }, -- Onslaught Wristguards
		{ 44341, 3 }, -- Bracers of Reverence
	},
	Hands = {
		{ 37645, 1 }, -- Horn-Tipped Gauntlets
		{ 39622, 3 }, -- Heroes' Dreadnaught Handguards
		{ 44183, 3 }, -- Fireproven Gauntlets
		{ 37862, 3 }, -- Gauntlets of the Water Revenant
		{ 43213, 3 }, -- Gauntlets of Vigilance
	},
	Waist = {
		{ 34547, 1 }, -- Onslaught Waistguard
		{ 37379, 2 }, -- Skadi's Iron Belt
		{ 40689, 3 }, -- Waistguard of Living Iron
		{ 37241, 3 }, -- Ancient Aligned Girdle
		{ 37826, 3 }, -- The General's Steel Girdle
	},
	Legs = {
		{ 43500, 1 }, -- Bolstered Legplates
		{ 37292, 3 }, -- Ley-Guardian's Legguards
		{ 34382, 3 }, -- Judicator's Legguards
		{ 34381, 3 }, -- Felstrength Legplates
		{ 37688, 3 }, -- Legplates of the Infinite Drakonid
		{ 44240, 3 }, -- Special Issue Legplates
	},
	Feet = {
		{ 44895, 3 }, -- Titan-Forged Greaves of Triumph
		{ 40878, 3 }, -- Hateful Gladiator's Greaves of Triumph
		{ 44201, 3 }, -- Sabatons of Draconic Vigor
		{ 44243, 3 }, -- Toxin-Tempered Sabatons
		{ 37082, 3 }, -- Slaughterhouse Sabatons
	},
	Ring = {
		{ 34213, 1 }, -- Ring of Hardened Resolve
		{ 37186, 2 }, -- Unsmashable Heavy Band
		{ 37784, 3 }, -- Keystone Great-Ring
		{ 42643, 3 }, -- Titanium Earthguard Ring
		{ 29297, 3 }, -- Band of the Eternal Defender
		{ 44935, 3 }, -- Ring of the Kirin Tor
		{ 37642, 1 }, -- Hemorrhaging Circle
		{ 36961, 3 }, -- Dragonflight Great-Ring
		{ 38617, 3 }, -- Woeful Band
		{ 37257, 3 }, -- Band of Torture
		{ 37591, 3 }, -- Nerubian Shield Ring
	},
	Trinket = {
		{ 49116, 3 }, -- Bitter Balebrew Charm
		{ 49118, 3 }, -- Bubbling Brightbrew Charm
		{ 44063, 3 }, -- Figurine - Monarch Crab
		{ 37220, 3 }, -- Essence of Gossamer
		{ 42341, 3 }, -- Figurine - Ruby Hare
		{ 37872, 3 }, -- Lavanthor's Talisman
		{ 29387, 3 }, -- Gnomeregan Auto-Blocker 600
		{ 38289, 3 }, -- Coren's Lucky Coin
		{ 37166, 3 }, -- Sphere of Red Dragon's Blood
		{ 36993, 3 }, -- Seal of the Pantheon
		{ 44323, 3 }, -- Indestructible Alchemist's Stone
		{ 40767, 3 }, -- Sonic Booster
		{ 37638, 3 }, -- Offering of Sacrifice
	},
	MainHand = {
		{ 37401, 1 }, -- Red Sword of Courage
		{ 37260, 3 }, -- Cloudstrider's Waraxe
		{ 37179, 3 }, -- Infantry Assault Blade
		{ 36984, 3 }, -- Eternally Folded Blade
		{ 37255, 3 }, -- The Interrogator
		{ 44187, 3 }, -- Fang of Truth
		{ 44735, 3 }, -- Crescent of Brooding Fury
		{ 44734, 3 }, -- Hammer of Quiet Mourning
		{ 44745, 3 }, -- Blade of the Empty Void
	},
	OffHand = {
		{ 43085, 1 }, -- Royal Crest of Lordaeron
		{ 40701, 3 }, -- Crygil's Discarded Plate Panel
		{ 42508, 3 }, -- Titansteel Shield Wall
		{ 37162, 3 }, -- Bulwark of the Noble Protector
		{ 35642, 3 }, -- Riot Shield
		{ 37107, 3 }, -- Leeka's Shield
		{ 34185, 1 }, -- Sword Breaker's Bulwark
		{ 41113, 3 }, -- Saronite Bulwark
	},
	Ranged = {
		{ 41168, 1 }, -- Armor Plated Combat Shotgun
		{ 44118, 3 }, -- Stolen Vrykul Harpoon
		{ 40716, 3 }, -- Lillehoff's Winged Blades
		{ 43284, 3 }, -- Amanitar Skullbow
		{ 37615, 3 }, -- Titanium Compound Bow
		{ 43187, 3 }, -- Weighted Throwing Axe
		{ 42863, 3 }, -- Sharpened Hyldnir Harpoon
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/protection/tank-bis-gear-pve-phase-1
ns:RegisterBiS("WARRIOR", "Protection", "P1", {
	Head = {
		{ 40546, 1 }, -- Valorous Dreadnaught Greathelm
		{ 39610, 1 }, -- Heroes' Dreadnaught Greathelm
		{ 40328, 1 }, -- Helm of Vital Protection
		{ 40366, 3 }, -- Platehelm of the Great Wyrm
		{ 42549, 4 }, -- Armored Titanium Goggles
		{ 39395, 3 }, -- Thane's Tainted Greathelm
	},
	Neck = {
		{ 40387, 1 }, -- Boundless Ambition
		{ 44665, 3 }, -- Nexus War Champion Beads
		{ 40069, 3 }, -- Heritage
		{ 39470, 1 }, -- Medallion of the Disgraced
		{ 44660, 3 }, -- Drakescale Collar
	},
	Shoulder = {
		{ 39704, 1 }, -- Pauldrons of Unnatural Death
		{ 40548, 3 }, -- Valorous Dreadnaught Pauldrons
		{ 39267, 1 }, -- Abomination Shoulderblades
		{ 40334, 3 }, -- Burdened Shoulderplates
		{ 39613, 3 }, -- Heroes' Dreadnaught Pauldrons
	},
	Back = {
		{ 40722, 1 }, -- Platinum Mesh Cloak
		{ 40410, 3 }, -- Shadow of the Ghoul
		{ 40252, 1 }, -- Cloak of the Shadowed Sun
		{ 43988, 1 }, -- Gale-Proof Cloak
		{ 39225, 3 }, -- Cloak of Armed Strife
	},
	Chest = {
		{ 40203, 1 }, -- Breastplate of Tormented Rage
		{ 44000, 1 }, -- Dragonstorm Breastplate
		{ 40544, 3 }, -- Valorous Dreadnaught Breastplate
		{ 39398, 1 }, -- Massive Skeletal Ribcage
		{ 40279, 3 }, -- Chestguard of the Exhausted
		{ 39611, 4 }, -- Heroes' Dreadnaught Breastplate
	},
	Wrist = {
		{ 39764, 1 }, -- Bindings of the Hapless Prey
		{ 40734, 3 }, -- Bracers of Dalaran's Parapets
		{ 40306, 1 }, -- Bracers of the Unholy Knight
		{ 39467, 1 }, -- Minion Bracers
	},
	Hands = {
		{ 40545, 1 }, -- Valorous Dreadnaught Handguards
		{ 40188, 2 }, -- Gauntlets of the Disobedient
		{ 39726, 1 }, -- Callous-Hearted Gauntlets
		{ 39622, 4 }, -- Heroes' Dreadnaught Handguards
	},
	Waist = {
		{ 39759, 1 }, -- Ablative Chitin Girdle
		{ 39298, 1 }, -- Waistguard of the Tutor
		{ 40263, 3 }, -- Fleshless Girdle
	},
	Legs = {
		{ 40589, 1 }, -- Legplates of Sovereignty
		{ 40446, 3 }, -- Dragon Brood Legguards
		{ 40547, 3 }, -- Valorous Dreadnaught Legguards
		{ 39258, 1 }, -- Legplates of Inescapable Death
		{ 40240, 3 }, -- Greaves of Turbulence
		{ 39612, 3 }, -- Heroes' Dreadnaught Legguards
	},
	Feet = {
		{ 39717, 1 }, -- Inexorable Sabatons
		{ 40297, 3 }, -- Sabatons of Endurance
		{ 40743, 3 }, -- Kyzoc's Ground Stompers
		{ 39234, 1 }, -- Plague-Impervious Boots
	},
	Ring = {
		{ 40370, 1 }, -- Gatekeeper
		{ 40718, 3 }, -- Signet of the Impregnable Fortress
		{ 40107, 1 }, -- Sand-Worn Band
		{ 40426, 1 }, -- Signet of the Accord
		{ 39141, 3 }, -- Deflection Band
		{ 37784, 3 }, -- Keystone Great-Ring
	},
	Trinket = {
		{ 49116, 3 }, -- Bitter Balebrew Charm
		{ 49118, 3 }, -- Bubbling Brightbrew Charm
		{ 44063, 3 }, -- Figurine - Monarch Crab
		{ 44253, 3 }, -- Darkmoon Card: Greatness
		{ 40257, 3 }, -- Defender's Code
		{ 37220, 3 }, -- Essence of Gossamer
		{ 42341, 3 }, -- Figurine - Ruby Hare
		{ 37872, 3 }, -- Lavanthor's Talisman
		{ 36993, 3 }, -- Seal of the Pantheon
		{ 39292, 3 }, -- Repelling Charge
	},
	MainHand = {
		{ 40402, 1 }, -- Last Laugh
		{ 40264, 3 }, -- Split Greathammer
		{ 40491, 3 }, -- Hailstorm
		{ 39344, 3 }, -- Slayer of the Lifeless
		{ 37401, 4 }, -- Red Sword of Courage
		{ 40345, 3 }, -- Broken Promise
	},
	OffHand = {
		{ 40400, 1 }, -- Wall of Terror
		{ 40475, 2 }, -- Barricade of Eternity
		{ 40266, 3 }, -- Hero's Surrender
		{ 39276, 3 }, -- The Skull of Ruin
	},
	Ranged = {
		{ 41168, 1 }, -- Armor Plated Combat Shotgun
		{ 44118, 3 }, -- Stolen Vrykul Harpoon
		{ 40716, 3 }, -- Lillehoff's Winged Blades
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/protection/tank-bis-gear-pve-phase-2
ns:RegisterBiS("WARRIOR", "Protection", "P2", {
	Head = {
		{ 45502, 1 }, -- Helm of the Faceless
		{ 46166, 2 }, -- Conqueror's Siegebreaker Greathelm
		{ 45935, 3 }, -- Ironbark Faceguard
		{ 46151, 3 }, -- Conqueror's Siegebreaker Helmet
		{ 45425, 3 }, -- Valorous Siegebreaker Greathelm
	},
	Neck = {
		{ 45485, 1 }, -- Bronze Pendant of the Vanir
		{ 45262, 3 }, -- Necklace of Unerring Mettle
		{ 45821, 3 }, -- Shard of the Crystal Forest
		{ 45538, 3 }, -- Titanstone Pendant
		{ 45696, 1 }, -- Mark of the Unyielding
	},
	Shoulder = {
		{ 46167, 1 }, -- Conqueror's Siegebreaker Pauldrons
		{ 45251, 3 }, -- Shoulderplates of the Deconstructor
		{ 45428, 3 }, -- Valorous Siegebreaker Pauldrons
		{ 45697, 3 }, -- Shoulderguards of the Solemn Watch
	},
	Back = {
		{ 45496, 1 }, -- Titanskin Cloak
		{ 45319, 3 }, -- Cloak of the Makers
		{ 46014, 1 }, -- Saronite Animus Cloak
	},
	Chest = {
		{ 46162, 1 }, -- Conqueror's Siegebreaker Breastplate
		{ 46039, 2 }, -- Breastplate of the Timeless
		{ 45334, 3 }, -- Unbreakable Chestguard
		{ 45424, 1 }, -- Valorous Siegebreaker Breastplate
	},
	Wrist = {
		{ 45111, 1 }, -- Mimiron's Inferno Couplings
		{ 45283, 1 }, -- Flamewatch Armguards
	},
	Hands = {
		{ 45487, 1 }, -- Handguards of Revitalization
		{ 46164, 3 }, -- Conqueror's Siegebreaker Handguards
		{ 46148, 3 }, -- Conqueror's Siegebreaker Gauntlets
		{ 45228, 3 }, -- Handguards of the Enclave
		{ 45834, 3 }, -- Gauntlets of the Royal Watch
		{ 45426, 1 }, -- Valorous Siegebreaker Handguards
	},
	Waist = {
		{ 45139, 1 }, -- Dragonslayer's Brace
		{ 45551, 1 }, -- Indestructible Plate Girdle
		{ 45825, 3 }, -- Shieldwarder Girdle
		{ 45304, 1 }, -- Stormtempered Girdle
	},
	Legs = {
		{ 45594, 1 }, -- Legplates of the Endless Void
		{ 46169, 3 }, -- Conqueror's Siegebreaker Legguards
		{ 46150, 1 }, -- Conqueror's Siegebreaker Legplates
		{ 45295, 1 }, -- Gilded Steel Legplates
		{ 45427, 3 }, -- Valorous Siegebreaker Legguards
		{ 45842, 3 }, -- Wyrmguard Legplates
	},
	Feet = {
		{ 45988, 1 }, -- Greaves of the Iron Army
		{ 45542, 1 }, -- Greaves of the Stonewarder
		{ 45560, 3 }, -- Spiked Deathdealers
		{ 45166, 3 }, -- Charred Saronite Greaves
	},
	Ring = {
		{ 45471, 1 }, -- Fate's Clutch
		{ 45247, 3 }, -- Signet of the Earthshaker
		{ 45326, 3 }, -- Platinum Band of the Aesir
		{ 45112, 3 }, -- The Leviathan's Coil
		{ 45874, 1 }, -- Signet of Winter
	},
	Trinket = {
		{ 45158, 3 }, -- Heart of Iron
		{ 46021, 3 }, -- Royal Seal of King Llane
		{ 44063, 3 }, -- Figurine - Monarch Crab
		{ 45313, 1 }, -- Furnace Stone
		{ 40257, 3 }, -- Defender's Code
		{ 37220, 3 }, -- Essence of Gossamer
		{ 37872, 3 }, -- Lavanthor's Talisman
	},
	MainHand = {
		{ 45442, 1 }, -- Sorthalis, Hammer of the Watchers
		{ 45876, 2 }, -- Shiver
		{ 45110, 3 }, -- Titanguard
		{ 40402, 1 }, -- Last Laugh
		{ 45892, 3 }, -- Legacy of Thunder
		{ 45700, 3 }, -- Stoneguard
	},
	OffHand = {
		{ 45587, 1 }, -- Bulwark of Algalon
		{ 45877, 1 }, -- The Boreal Guard
		{ 45450, 1 }, -- Northern Barrier
		{ 45707, 3 }, -- Shieldwall of the Breaker
	},
	Ranged = {
		{ 45137, 1 }, -- Veranus' Bane
		{ 41168, 1 }, -- Armor Plated Combat Shotgun
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/protection/tank-bis-gear-pve-phase-3
ns:RegisterBiS("WARRIOR", "Protection", "P3", {
	Head = {
		{ 48433, 1 }, -- Wrynn's Greathelm of Triumph
		{ 48468, 1 }, -- Hellscream's Greathelm of Triumph
		{ 48430, 1 }, -- Wrynn's Greathelm of Triumph
		{ 48463, 1 }, -- Hellscream's Greathelm of Triumph
		{ 49479, 3 }, -- Helm of Wrath
		{ 46166, 1 }, -- Conqueror's Siegebreaker Greathelm
	},
	Neck = {
		{ 47133, 1 }, -- The Arbiter's Muse
		{ 47466, 1 }, -- Legionnaire's Gorget
		{ 47939, 3 }, -- Endurance of the Infernal
		{ 48011, 3 }, -- Fortitude of the Infernal
		{ 45485, 1 }, -- Bronze Pendant of the Vanir
		{ 47116, 3 }, -- The Arbiter's Muse
		{ 47305, 3 }, -- Legionnaire's Gorget
		{ 49492, 3 }, -- Eskhandar's Links
	},
	Shoulder = {
		{ 48455, 1 }, -- Wrynn's Pauldrons of Triumph
		{ 48470, 1 }, -- Hellscream's Pauldrons of Triumph
		{ 48454, 1 }, -- Wrynn's Pauldrons of Triumph
		{ 48465, 1 }, -- Hellscream's Pauldrons of Triumph
		{ 47944, 3 }, -- Pauldrons of the Silver Defender
		{ 48016, 3 }, -- Sunreaver Defender's Pauldrons
		{ 46167, 1 }, -- Conqueror's Siegebreaker Pauldrons
	},
	Back = {
		{ 47549, 1 }, -- Magni's Resolution
		{ 47550, 1 }, -- Cairne's Endurance
		{ 48675, 3 }, -- Cloak of the Unmoving Guardian
		{ 48670, 3 }, -- Cloak of the Unflinching Guardian
		{ 47063, 3 }, -- Pride of the Eredar
		{ 47436, 3 }, -- Pride of the Demon Lord
		{ 45496, 1 }, -- Titanskin Cloak
	},
	Chest = {
		{ 46968, 1 }, -- Chestplate of the Towering Monstrosity
		{ 47415, 1 }, -- Hauberk of the Towering Monstrosity
		{ 48451, 1 }, -- Wrynn's Breastplate of Triumph
		{ 48466, 1 }, -- Hellscream's Breastplate of Triumph
		{ 46962, 3 }, -- Chestplate of the Towering Monstrosity
		{ 47254, 3 }, -- Hauberk of the Towering Monstrosity
		{ 47964, 3 }, -- Chestguard of the Warden
		{ 48041, 3 }, -- Stoneskin Chestplate
		{ 48450, 3 }, -- Wrynn's Breastplate of Triumph
		{ 48461, 3 }, -- Hellscream's Breastplate of Triumph
		{ 46162, 1 }, -- Conqueror's Siegebreaker Breastplate
		{ 45334, 3 }, -- Unbreakable Chestguard
	},
	Wrist = {
		{ 47111, 1 }, -- Bracers of the Shieldmaiden
		{ 47459, 1 }, -- Armguards of the Shieldmaiden
		{ 47918, 3 }, -- Dreadscale Armguards
		{ 47991, 3 }, -- Dreadscale Bracers
		{ 47570, 3 }, -- Saronite Swordbreakers
		{ 47571, 3 }, -- Saronite Swordbreakers
		{ 47108, 3 }, -- Bracers of the Shieldmaiden
		{ 47298, 3 }, -- Armguards of the Shieldmaiden
		{ 45111, 1 }, -- Mimiron's Inferno Couplings
	},
	Hands = {
		{ 48453, 1 }, -- Wrynn's Handguards of Triumph
		{ 48467, 1 }, -- Hellscream's Handguards of Triumph
		{ 48452, 1 }, -- Wrynn's Handguards of Triumph
		{ 48462, 1 }, -- Hellscream's Handguards of Triumph
		{ 45487, 1 }, -- Handguards of Revitalization
	},
	Waist = {
		{ 47076, 1 }, -- Girdle of Bloodied Scars
		{ 47444, 1 }, -- Belt of Bloodied Scars
		{ 47072, 3 }, -- Girdle of Bloodied Scars
		{ 47283, 3 }, -- Belt of Bloodied Scars
		{ 47937, 3 }, -- Girdle of the Nether Champion
		{ 48009, 3 }, -- Belt of the Nether Champion
		{ 45139, 1 }, -- Dragonslayer's Brace
	},
	Legs = {
		{ 48447, 1 }, -- Wrynn's Legguards of Triumph
		{ 48469, 1 }, -- Hellscream's Legguards of Triumph
		{ 48446, 1 }, -- Wrynn's Legguards of Triumph
		{ 48464, 1 }, -- Hellscream's Legguards of Triumph
		{ 47061, 3 }, -- Legguards of Feverish Dedication
		{ 47434, 3 }, -- Legplates of Feverish Dedication
		{ 45594, 1 }, -- Legplates of the Endless Void
	},
	Feet = {
		{ 47003, 1 }, -- Dawnbreaker Greaves
		{ 47430, 1 }, -- Dawnbreaker Sabatons
		{ 47952, 3 }, -- Sabatons of the Lingering Vortex
		{ 48024, 3 }, -- Greaves of the Lingering Vortex
		{ 45988, 1 }, -- Greaves of the Iron Army
		{ 46997, 3 }, -- Dawnbreaker Greaves
		{ 47269, 3 }, -- Dawnbreaker Sabatons
	},
	Ring = {
		{ 47157, 1 }, -- Signet of the Traitor King
		{ 47476, 1 }, -- Band of the Traitor King
		{ 45471, 3 }, -- Fate's Clutch
		{ 47955, 3 }, -- Loop of the Twin Val'kyr
		{ 48027, 3 }, -- Band of the Twin Val'kyr
		{ 47731, 3 }, -- Clutch of Fortification
		{ 45247, 4 }, -- Signet of the Earthshaker
		{ 47149, 3 }, -- Signet of the Traitor King
		{ 47315, 3 }, -- Band of the Traitor King
		{ 49489, 3 }, -- Signified Ring of Binding
	},
	Trinket = {
		{ 47088, 1 }, -- Satrina's Impeding Scarab
		{ 47451, 1 }, -- Juggernaut's Vitality
		{ 47080, 3 }, -- Satrina's Impeding Scarab
		{ 47290, 3 }, -- Juggernaut's Vitality
		{ 47735, 1 }, -- Glyph of Indomitability
		{ 45158, 3 }, -- Heart of Iron
		{ 47216, 3 }, -- The Black Heart
		{ 46021, 3 }, -- Royal Seal of King Llane
		{ 49487, 3 }, -- Purified Onyxia Blood Talisman
	},
	MainHand = {
		{ 47506, 1 }, -- Silverwing Defender
		{ 47513, 1 }, -- Orgrim's Deflector
		{ 45442, 3 }, -- Sorthalis, Hammer of the Watchers
		{ 47967, 3 }, -- Crusader's Glory
		{ 48044, 3 }, -- Ardent Guard
		{ 48714, 3 }, -- Honor of the Fallen
		{ 48699, 3 }, -- Blood and Glory
		{ 45876, 3 }, -- Shiver
		{ 49495, 3 }, -- Burnished Quel'Serrar
	},
	OffHand = {
		{ 45587, 1 }, -- Bulwark of Algalon
		{ 46964, 2 }, -- Crystal Plated Vanguard
		{ 47421, 2 }, -- Forlorn Barrier
		{ 45877, 3 }, -- The Boreal Guard
		{ 45450, 1 }, -- Northern Barrier
	},
	Ranged = {
		{ 47660, 1 }, -- Blades of the Sable Cross
		{ 45137, 1 }, -- Veranus' Bane
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warrior/protection/tank-bis-gear-pve-phase-4
ns:RegisterBiS("WARRIOR", "Protection", "P4", {
	Head = {
		{ 50640, 1 }, -- Broken Ram Skull Helm
		{ 51221, 1 }, -- Sanctified Ymirjar Lord's Greathelm
		{ 49986, 1 }, -- Broken Ram Skull Helm
		{ 51218, 1 }, -- Sanctified Ymirjar Lord's Greathelm
		{ 48433, 1 }, -- Wrynn's Greathelm of Triumph
		{ 48468, 1 }, -- Hellscream's Greathelm of Triumph
		{ 50848, 3 }, -- Ymirjar Lord's Greathelm
	},
	Neck = {
		{ 50682, 1 }, -- Bile-Encrusted Medallion
		{ 50023, 3 }, -- Bile-Encrusted Medallion
		{ 50627, 3 }, -- Noose of Malachite
		{ 47133, 1 }, -- The Arbiter's Muse
		{ 47466, 1 }, -- Legionnaire's Gorget
		{ 51934, 1 }, -- Marrowgar's Scratching Choker
		{ 50195, 3 }, -- Noose of Malachite
	},
	Shoulder = {
		{ 51224, 1 }, -- Sanctified Ymirjar Lord's Pauldrons
		{ 50660, 1 }, -- Boneguard Commander's Pauldrons
		{ 51215, 3 }, -- Sanctified Ymirjar Lord's Pauldrons
		{ 50003, 3 }, -- Boneguard Commander's Pauldrons
		{ 51847, 1 }, -- Spaulders of the Blood Princes
		{ 48455, 1 }, -- Wrynn's Pauldrons of Triumph
		{ 48470, 1 }, -- Hellscream's Pauldrons of Triumph
		{ 50846, 3 }, -- Ymirjar Lord's Pauldrons
	},
	Back = {
		{ 50718, 1 }, -- Royal Crimson Cloak
		{ 47549, 1 }, -- Magni's Resolution
		{ 47550, 1 }, -- Cairne's Endurance
		{ 50466, 3 }, -- Sentinel's Winter Cloak
		{ 51888, 1 }, -- Cloak of Many Skins
		{ 50074, 3 }, -- Royal Crimson Cloak
	},
	Chest = {
		{ 51220, 1 }, -- Sanctified Ymirjar Lord's Breastplate
		{ 50681, 3 }, -- Blightborne Warplate
		{ 51219, 3 }, -- Sanctified Ymirjar Lord's Breastplate
		{ 51917, 1 }, -- Ghoul Commander's Cuirass
		{ 50024, 3 }, -- Blightborne Warplate
		{ 50850, 3 }, -- Ymirjar Lord's Breastplate
		{ 46968, 1 }, -- Chestplate of the Towering Monstrosity
		{ 47415, 1 }, -- Hauberk of the Towering Monstrosity
	},
	Wrist = {
		{ 50611, 1 }, -- Bracers of Dark Reckoning
		{ 51901, 2 }, -- Gargoyle Spit Bracers
		{ 49960, 3 }, -- Bracers of Dark Reckoning
		{ 50802, 3 }, -- Gargoyle Spit Bracers
		{ 47111, 3 }, -- Bracers of the Shieldmaiden
		{ 47459, 3 }, -- Armguards of the Shieldmaiden
		{ 47918, 3 }, -- Dreadscale Armguards
		{ 47991, 3 }, -- Dreadscale Bracers
	},
	Hands = {
		{ 51222, 1 }, -- Sanctified Ymirjar Lord's Handguards
		{ 50716, 3 }, -- Taldaram's Plated Fists
		{ 51217, 3 }, -- Sanctified Ymirjar Lord's Handguards
		{ 51835, 1 }, -- Veincrusher Gauntlets
		{ 50075, 3 }, -- Taldaram's Plated Fists
		{ 50849, 3 }, -- Ymirjar Lord's Handguards
		{ 48453, 1 }, -- Wrynn's Handguards of Triumph
		{ 48467, 1 }, -- Hellscream's Handguards of Triumph
	},
	Waist = {
		{ 50691, 1 }, -- Belt of Broken Bones
		{ 50991, 2 }, -- Verdigris Chain Belt
		{ 51831, 3 }, -- Ironrope Belt of Ymirjar
		{ 50036, 3 }, -- Belt of Broken Bones
		{ 47076, 1 }, -- Girdle of Bloodied Scars
		{ 47444, 1 }, -- Belt of Bloodied Scars
	},
	Legs = {
		{ 51223, 1 }, -- Sanctified Ymirjar Lord's Legguards
		{ 49904, 1 }, -- Pillars of Might
		{ 50612, 3 }, -- Legguards of Lost Hope
		{ 51895, 1 }, -- Deathforged Legplates
		{ 49964, 3 }, -- Legguards of Lost Hope
		{ 51216, 3 }, -- Sanctified Ymirjar Lord's Legguards
		{ 48447, 1 }, -- Wrynn's Legguards of Triumph
		{ 48469, 1 }, -- Hellscream's Legguards of Triumph
		{ 50847, 3 }, -- Ymirjar Lord's Legguards
	},
	Feet = {
		{ 50625, 1 }, -- Grinning Skull Greatboots
		{ 54579, 1 }, -- Treads of Impending Resurrection
		{ 51816, 1 }, -- Scourge Fanged Stompers
		{ 53129, 3 }, -- Treads of Impending Resurrection
		{ 54564, 3 }, -- Scion's Treads
		{ 50190, 3 }, -- Grinning Skull Greatboots
		{ 49907, 3 }, -- Boots of Kingly Upheaval
		{ 47003, 1 }, -- Dawnbreaker Greaves
		{ 47430, 1 }, -- Dawnbreaker Sabatons
	},
	Ring = {
		{ 50622, 1 }, -- Devium's Eternally Cold Ring
		{ 50185, 2 }, -- Devium's Eternally Cold Ring
		{ 50642, 3 }, -- Juggernaut Band
		{ 50404, 3 }, -- Ashen Band of Endless Courage
		{ 51913, 1 }, -- Abomination's Bloody Ring
		{ 47955, 1 }, -- Loop of the Twin Val'kyr
		{ 48027, 1 }, -- Band of the Twin Val'kyr
		{ 49985, 3 }, -- Juggernaut Band
		{ 50447, 3 }, -- Harbinger's Bone Band
		{ 50403, 3 }, -- Ashen Band of Unmatched Courage
		{ 47157, 1 }, -- Signet of the Traitor King
		{ 47476, 1 }, -- Band of the Traitor King
		{ 49489, 3 }, -- Signified Ring of Binding
	},
	Trinket = {
		{ 50364, 1 }, -- Sindragosa's Flawless Fang
		{ 50344, 1 }, -- Unidentifiable Organ
		{ 54591, 3 }, -- Petrified Twilight Scale
		{ 47088, 3 }, -- Satrina's Impeding Scarab
		{ 47451, 3 }, -- Juggernaut's Vitality
		{ 45158, 3 }, -- Heart of Iron
		{ 50356, 3 }, -- Corroded Skeleton Key
		{ 47735, 3 }, -- Glyph of Indomitability
	},
	MainHand = {
		{ 50738, 1 }, -- Mithrios, Bronzebeard's Legacy
		{ 51947, 2 }, -- Troggbane, Axe of the Frostborne King
		{ 49997, 3 }, -- Mithrios, Bronzebeard's Legacy
		{ 50708, 3 }, -- Last Word
		{ 51869, 3 }, -- The Facelifter
		{ 51937, 3 }, -- Bonebreaker Scepter
		{ 47506, 1 }, -- Silverwing Defender
		{ 47513, 1 }, -- Orgrim's Deflector
	},
	OffHand = {
		{ 50729, 1 }, -- Icecrown Glacial Wall
		{ 50065, 3 }, -- Icecrown Glacial Wall
		{ 51909, 3 }, -- Neverending Winter
		{ 45587, 1 }, -- Bulwark of Algalon
		{ 46964, 1 }, -- Crystal Plated Vanguard
		{ 47421, 1 }, -- Forlorn Barrier
	},
	Ranged = {
		{ 51834, 1 }, -- Dreamhunter's Carbine
		{ 50444, 3 }, -- Rowan's Rifle of Silver Bullets
		{ 51561, 3 }, -- Dreamhunter's Carbine
		{ 47660, 1 }, -- Blades of the Sable Cross
	},
})
