-- GENERATED by scripts/build_guides.py -- do not edit by hand.
-- Source: Wowhead WotLK comparison of the realm's client data with stock 3.3.5 (extract_talents.py).
local _, ns = ...

ns.Realm = {
	-- spells whose numbers or text differ from stock
	spells = {
		[1543] = true, [2818] = true, [2819] = true, [2823] = true, [2824] = true, [2825] = true, [3408] = true, [3409] = true, [5760] = true, [5761] = true, [8024] = true, [8027] = true,
		[8030] = true, [8033] = true, [8038] = true, [8232] = true, [8235] = true, [8679] = true, [8680] = true, [8685] = true, [8686] = true, [8688] = true, [8689] = true, [10456] = true,
		[10486] = true, [11335] = true, [11336] = true, [11337] = true, [11338] = true, [11339] = true, [11340] = true, [11353] = true, [11354] = true, [11355] = true, [11356] = true, [12298] = true,
		[12328] = true, [12724] = true, [12725] = true, [12726] = true, [12727] = true, [12809] = true, [13218] = true, [13219] = true, [13222] = true, [13223] = true, [13224] = true, [13225] = true,
		[13226] = true, [13227] = true, [16339] = true, [16341] = true, [16342] = true, [16355] = true, [16356] = true, [16362] = true, [21178] = true, [22842] = true, [23602] = true, [25349] = true,
		[25351] = true, [25489] = true, [25500] = true, [25505] = true, [25681] = true, [25682] = true, [25683] = true, [26688] = true, [26785] = true, [26890] = true, [26891] = true, [26967] = true,
		[26968] = true, [27186] = true, [27187] = true, [27188] = true, [27189] = true, [29059] = true, [29140] = true, [29143] = true, [29144] = true, [29593] = true, [29594] = true, [29598] = true,
		[29599] = true, [31700] = true, [31879] = true, [31880] = true, [31881] = true, [33648] = true, [33953] = true, [34453] = true, [34454] = true, [35446] = true, [35448] = true, [35449] = true,
		[46917] = true, [47294] = true, [47295] = true, [47296] = true, [49152] = true, [51730] = true, [51988] = true, [51991] = true, [51992] = true, [51993] = true, [51994] = true, [55451] = true,
		[55546] = true, [57724] = true, [57934] = true, [57964] = true, [57965] = true, [57967] = true, [57968] = true, [57969] = true, [57970] = true, [57972] = true, [57973] = true, [57974] = true,
		[57975] = true, [57977] = true, [57978] = true, [57981] = true, [57982] = true, [58785] = true, [58789] = true, [58790] = true, [58794] = true, [58795] = true, [58796] = true, [58801] = true,
		[58803] = true, [58804] = true, [58872] = true, [58874] = true, [59285] = true, [60062] = true, [60063] = true, [60064] = true, [60065] = true, [62716] = true, [64193] = true, [68067] = true,
	},
	-- talents the realm added or changed: class -> "tab:tier:col"
	talents = {
		HUNTER = { ["1:6:1"] = true },
		PALADIN = { ["3:8:2"] = true },
		WARRIOR = { ["1:5:2"] = true, ["1:8:2"] = true, ["2:11:2"] = true, ["3:1:2"] = true, ["3:3:3"] = true, ["3:5:2"] = true, ["3:7:1"] = true, ["3:7:3"] = true, ["3:7:4"] = true, ["3:8:2"] = true, ["3:9:3"] = true, ["3:10:3"] = true },
	},
}
