-- GENERATED by scripts/build_guides.py -- do not edit by hand.
-- Source: Wowhead WotLK talent and glyph guides (see scripts/guides.json),
-- decoded against this realm's own talent trees.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/druid/balance/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("DRUID", "Balance", {
	builds = {
		{
			name = "58/0/13 Balance",
			pts = { 58, 0, 13 },
			trees = {
				{ { 1, 2, 5 }, { 1, 3, 1 }, { 2, 2, 2 }, { 2, 4, 2 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 2, 5 }, { 4, 3, 3 }, { 5, 1, 3 }, { 5, 2, 1 }, { 5, 3, 3 }, { 6, 2, 3 }, { 6, 3, 2 }, { 7, 2, 1 }, { 7, 3, 3 }, { 7, 4, 3 }, { 8, 3, 5 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 1 }, { 9, 4, 2 }, { 10, 2, 3 }, { 11, 2, 1 } },
				{  },
				{ { 1, 1, 2 }, { 1, 3, 5 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 2 } },
			},
			note = "If you are looking for more single-target damage and are not concerned about trash, you can remove points from {spell:48514} and place them in either {spell:16836} or {spell:48389}.\n\n{spell:16836} Is fairly strong for Lord Marrowgar in Icecrown Citadel as his Bonestorm ability procs the damage and hits all raid members, regardless of distance.\n\nFor Glyphs: Glyph of Focus is only viable on about half of the fights due to movement or the need for the raid to spread out, you won't always be able to get within 20 yards of a boss. For these occasions, swap to Glyph of Starfire. See table below.\n\nBoss\nGlyph\n\nMarrowgar\nGlyph of Starfire / Glyph of Focus (Not Recommended)\n\nLady Deathwhisper\nGlyph of Starfire / Glyph of Focus (Not Recommended)\n\nSaurfang\nGlyph of Focus\n\nFestergut\nGlyph of Focus\n\nRotface\nGlyph of Focus\n\nPutricide\nGlyph of Starfire\n\nBlood Princes\nGlyph of Starfire\n\nBlood Queen Lana'thel\nGlyph of Focus\n\nDreamwalker\nGlyph of Starfire\n\nSindragosa\nGlyph of Starfire\n\nThe Lich King\nGlyph of Focus",
		},
		{
			name = "59/0/12 Balance",
			pts = { 59, 0, 12 },
			trees = {
				{ { 1, 2, 5 }, { 1, 3, 1 }, { 2, 2, 2 }, { 2, 4, 2 }, { 3, 1, 3 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 2, 5 }, { 4, 3, 3 }, { 5, 1, 3 }, { 5, 2, 1 }, { 5, 3, 3 }, { 6, 2, 3 }, { 6, 3, 2 }, { 7, 2, 1 }, { 7, 3, 3 }, { 7, 4, 3 }, { 8, 3, 5 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 1 }, { 10, 2, 3 }, { 11, 2, 1 } },
				{  },
				{ { 1, 1, 2 }, { 1, 3, 5 }, { 2, 3, 3 }, { 3, 3, 2 } },
			},
			note = "While this build is recommended, it is not your only option for talents in Phase 3. Next, I will outline the changes as well as alternative options.\n\nWhile minor, moving the single point from {spell:16845} and placing it into {spell:57810} is a DPS increase over the alternative. If mana is a concern the point can be moved back into {spell:16845}.\n\nOne point was taken out of {spell:16819} and placed into {spell:16840} for the added Treant damage. While it also boosts the damage caused by {spell:53307}, this damage is minor and only gets worse with how geared your tank gets.\n\nWith the lack of trash in , the usage of spells like {spell:50516} and {spell:48467} will get much less use. Because of this, both points were removed from {spell:48488} and placed into {spell:16840} for the above reason.\n\nYou will also notice the removal of {spell:16864}. This was done for the same reason as the {spell:16845} change. For progression, where {spell:48477} will get much more use, I recommend removing a point from {spell:16840} and placing it back into {spell:16864}.\n\nAlternatively: If you enjoy more of an RNG talent, all 3 points from {spell:16840} can be moved into {spell:48389}. It is much less consistent, but when it procs, it can provide a large damage increase. Some fights like Faction Champions in have shown promising results for proc rates, provided one of the melee champions is ...",
		},
		{
			name = "58/0/13 Balance",
			pts = { 58, 0, 13 },
			trees = {
				{ { 1, 2, 5 }, { 2, 1, 1 }, { 2, 2, 2 }, { 2, 4, 2 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 2, 5 }, { 4, 3, 3 }, { 5, 1, 3 }, { 5, 2, 1 }, { 5, 3, 3 }, { 6, 2, 3 }, { 6, 3, 2 }, { 7, 2, 1 }, { 7, 3, 3 }, { 7, 4, 3 }, { 8, 3, 5 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 1 }, { 9, 4, 2 }, { 10, 2, 3 }, { 11, 2, 1 } },
				{  },
				{ { 1, 1, 2 }, { 1, 3, 5 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 2 } },
			},
			note = "The changes in this build are fairly minor from the Phase 1 spec. We drop 2 points in {spell:16845} and place them in {spell:16822}. The second change is optional and that consists of removing 1 point from {spell:16820} and placing it into {spell:57851}. \nFor Glyph changes, we replace Glyph of Focus with Glyph of Starfire as it performs better on longer fights and with the loss of 2pc Tier 7.\n\nUlduar Progression Note: It Is recommended for Hardmode fights to remove Glyph of Insect Swarm and replace it with Glyph of Rebirth. This will allow your {spell:48477} to revive the target with full health, reducing the chance of them immediately dying. Removing Glyph of Insect Swarm also allows your {spell:48468} to apply a debuff to the boss, reducing its chance to hit by 3% and increasing tank survivability.\n\nOn fights like (HM), , (HM), and , it is recommended to remove Glyph of Typhoon as the knockback is very useful for mechanics on these fights.",
		},
		{
			name = "58/0/13 Balance",
			pts = { 58, 0, 13 },
			trees = {
				{ { 1, 2, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 2 }, { 4, 2, 5 }, { 4, 3, 3 }, { 5, 1, 3 }, { 5, 2, 1 }, { 5, 3, 2 }, { 6, 2, 3 }, { 6, 3, 2 }, { 7, 2, 1 }, { 7, 3, 3 }, { 7, 4, 3 }, { 8, 3, 5 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 1 }, { 9, 4, 2 }, { 10, 2, 3 }, { 11, 2, 1 } },
				{  },
				{ { 1, 1, 2 }, { 1, 3, 5 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 2 } },
			},
			note = "This is a pretty straightforward cookie-cutter talent build that picks up all the important damage increases in the Balance Tree and goes slightly into the Restoration Tree in order to pick up some vital points there. With proper gearing, mana shouldn't be an issue due to {spell:24858} but if you find that you are going out of mana too fast you could talent into these but you'll lose out on a good amount of damage. If you find you are having issues with mana, removing points from {spell:57849} and even one point from {spell:16820} and placing them into {spell:33956} will help a fair amount.",
		},
	},
	glyphs = {
		major = {
			{ 40921, "Glyph of Starfall", "Glyph of Starfall reduces the cooldown of Starfall by 30 seconds which is incredibly powerful since Starfall is a big burst of damage." },
			{ 44928, "Glyph of Focus", "Glyph of Focus increases the damage done by Starfall by 10% but decreases the radius by 50%. With proper planned positioning, this glyph is a nice increase in damage. The decrease in radius can also come in handy if you want to use Starfall in dungeons or other places where accidentally pulling mobs can be a problem." },
			{ 40916, "Glyph of Starfire", "Glyph of Starfire causes Starfire to increase the duration of Moonfire on the target by 3 seconds, up to 9 additional seconds." },
			{ 40923, "Glyph of Moonfire", "Glyph of Moonfire increases the periodic damage of Moonfire by 75% but the initial damage is decreased by 90%. This is a good trade off if the target doesn't die too quickly." },
			{ 40919, "Glyph of Insect Swarm", "Glyph of Insect Swarm increases the damage of Insect Swarm by 30% but causes it to no longer affect the target's chance to hit." },
		},
		minor = {
			{ 43331, "Glyph of Unburdened Rebirth", "Glyph of Unburdened Rebirth causes your Rebirth spell to no longer require an reagent." },
			{ 43335, "Glyph of the Wild", "Glyph of the Wild reduces the mana cost of Mark of the Wild and Gift of the WIld by 50%." },
			{ 43674, "Glyph of Dash", "Glyph of Dash reduces the cooldown of Dash by 20%. This is useful if you use Dash to get out of bad ground effects quickly or want to position fast." },
			{ 43332, "Glyph of Thorns", "Glyph of Thorns increases the duration of your Thorns by 50 minutes when cast on yourself. You'll realistically only put Thorns on yourself when solo questing or for PvP." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/druid/feral/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("DRUID", "Feral DPS", {
	builds = {
		{
			name = "Standard PvE 0/53/18 Feral",
			pts = { 0, 53, 18 },
			trees = {
				{  },
				{ { 1, 2, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 1, 2 }, { 3, 2, 1 }, { 3, 3, 3 }, { 4, 1, 2 }, { 4, 2, 3 }, { 4, 3, 2 }, { 4, 4, 2 }, { 5, 3, 1 }, { 6, 2, 5 }, { 6, 3, 3 }, { 7, 2, 1 }, { 7, 3, 2 }, { 8, 1, 2 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 10, 2, 5 }, { 10, 3, 1 }, { 11, 2, 1 } },
				{ { 1, 1, 2 }, { 1, 3, 5 }, { 2, 1, 5 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 2 } },
			},
			note = "This is the standard PvE build that the majority of Feral Druids should run when playing a pure DPS role. The build makes no appreciable sacrifices to your DPS output on either trash packs or single target bosses, while still picking up 2/2 {spell:34300} for the unique raid healing utility it provides.\n\nWhile most of the talents taken in this build are self-explanatory due to the obvious damage or stat buffs they provide, it is worth calling attention to a few talent choices that may be less clear for new players. Firstly, {spell:24866} and {spell:49377} are both mandatory mobility talents that should never be omitted in any build. Movement speed in general is one of the most impactful DPS stats you have at your disposal, as it increases your active uptime on your targets, and these two talents complement one another by giving you extremely high passive movement speed in {spell:768} plus the {spell:49376} cooldown for quickly bridging the gap to your target from afar. WotLK raids feature lots of mechanics that require you to move out of melee range temporarily, so these talents will contribute enormous amounts of DPS.\n\nSecondly, this build maxes out the {spell:17061} talent and also takes 2 points in {spell:57876} in order to exploit an advanced rotation tactic called \"bearweaving\". This tactic is described in more detail in our rotation guide, but in short, you can gain a ...",
		},
		{
			name = "Hybrid Off-Tanking 0/54/17 Feral",
			pts = { 0, 54, 17 },
			trees = {
				{  },
				{ { 1, 2, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 1, 2 }, { 3, 2, 1 }, { 3, 3, 3 }, { 4, 1, 2 }, { 4, 2, 3 }, { 4, 3, 2 }, { 4, 4, 2 }, { 5, 3, 1 }, { 6, 2, 5 }, { 6, 3, 3 }, { 7, 2, 1 }, { 8, 1, 3 }, { 8, 3, 2 }, { 9, 1, 3 }, { 9, 2, 1 }, { 10, 2, 5 }, { 10, 3, 1 }, { 11, 2, 1 } },
				{ { 1, 1, 2 }, { 1, 3, 4 }, { 2, 1, 5 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 2 } },
			},
			note = "This is a hybrid build for encounters in which you will be off-tanking hard hitting mobs in {spell:9634} for part of the time, and then DPSing in {spell:768} for the remainder. Examples of this include tanking an early kill target on the Assembly of Iron encounter in and then DPSing the other council members, or picking up adds in the encounter within . Just as in TBC, Feral Druids excel at performing such hybrid off-tanking roles, since the most essential tanking talents in the tree can be picked up with only a minor loss to the Feral's DPS output.\n\nSince the pure DPS build above already talents {spell:61336} and 2/3 {spell:57876}, only 4 additional talent points must be sacrificed in order to max out {spell:57877} and {spell:16931}, which are the two most impactful mitigation talents for hard hitting encounters. The hybrid build gives up {spell:34300}, the 5th point in {spell:17061} (which only raises your effective Energy cap while bearweaving from 80 to 85), and one point in {spell:33867} in order to accommodate these tanking talents with minimal DPS loss.",
		},
	},
	glyphs = {
		major = {
			{ 40901, "Glyph of Shred", "Causes each {spell:48572} hit to add 1 additional {spell:49800} tick, up to a maximum of 3. This is by far your most valuable Glyph for single target DPS, as it not only significantly boosts the Damage Per Energy (DPE) efficiency of Rip, but also makes it much easier not to lose Rip uptime while keeping up {spell:52610}." },
			{ 40902, "Glyph of Rip", "Adds 2 additional bleed ticks from each {spell:49800} cast. Stacks with Glyph of Shred, resulting in a whopping 10 second extension to the base Rip duration of 12 seconds, and boosting the Attack Power scaling of Rip from 30% to 55%." },
			{ 45604, "Glyph of Savage Roar", "Makes your {spell:52610} 10% more effective, boosting its damage multiplier from 1.3 to 1.33. This should be your default third Glyph to use on most single target fights." },
			{ 45601, "Glyph of Berserk", "For very short fight lengths, Glyph of Berserk will outperform Glyph of Savage Roar, so it can be swapped into the third Glyph slot if you want to min-max your damage on specific encounters." },
			{ 40897, "Glyph of Maul", "On trash fights or multi-target boss encounters, you will want to use Glyph of Maul even as a pure DPS player for min-maxing your cleave damage. The Glyph not only doubles your {spell:48480} damage when bearweaving, but also doubles your chance of obtaining a {spell:16870} proc from each {spell:48480}, allowing you to return to {spell:768} sooner and pump out additional {spell:62078} casts for free." },
		},
		minor = {
			{ 43335, "Glyph of the Wild", "Unlike the other Minor Glyphs, which are completely optional, Glyph of the Wild is mandatory for min-maxing your damage output as a Feral Druid. In WotLK, {spell:48470} can proc {spell:16864} at a rate that scales with the number of targets buffed by the spell. As a result, casting {spell:48470} in a 25-man raid group will nearly guarantee a {spell:16870} proc, so you will be doing it very often and will need the Glyph in order to sustain this tactic." },
			{ 43674, "Glyph of Dash", "Reduces the cooldown of {spell:33357} by 36 seconds, which can be situationally useful in PvE but will be most noticeable in PvP and when farming." },
			{ 43331, "Glyph of Unburdened Rebirth", "Pure quality of life boost that saves you from needing to carry around Starleaf Seeds anymore." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/druid/restoration/healer-talent-builds-glyphs-pve
ns:RegisterTalentGuide("DRUID", "Restoration", {
	builds = {
		{
			name = "Thicc Resto - 856 Haste Cap 11/0/60 Restoration",
			pts = { 11, 0, 60 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 3, 1 } },
				{  },
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 2 }, { 4, 2, 1 }, { 4, 3, 3 }, { 5, 1, 1 }, { 5, 2, 5 }, { 6, 1, 2 }, { 6, 3, 5 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 2 }, { 8, 2, 5 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 3, 5 }, { 11, 2, 1 } },
			},
			note = "This build improves single target healing at the expense of haste, increasing the haste cap to 856. While below this haste cap, this build shifts healing throughput from raid damage to tank damage due to lacking the additional haste from {spell:16924}.\n\nMoveable Talents\n\n{spell:24968}: \n\n- Additional points here will help with the heavy mana cost of spamming {spell:50464} during a difficult tank healing encounter. Can be very useful for keep {spell:48500} active.\n{spell:34153}: \n\n- One point can be carved out of here in favor of filling out {spell:33883}. Ranging from fully buffed 1000 spirit (average gear) to 1700 spirit (icc bis), missing 5% additional spirit translates to a loss of 50-85 spirit, roughly 10-17 Spell Power and 40-68 MP5. \n{spell:33883}: \n\n- Crit is a relatively weak stat for Resto Druids unless you are spamming your direct heals. This talent pales in comparison to the crit bonus of {spell:17078} so it is not a critical pick up. Definitely a good place to add points if you're looking to trim your build to be more throughput focused and less mana conscious.\n{spell:48545}:\n\n- While considered heresy, trimming points from Revitalize is an option. The DPS gains are marginal and barely an argument for investing 3 talents points. The main benefit is the scaling 1% mana return on your healers to provide them with potentially 100 MP5 each when continuously hotted. ...",
		},
		{
			name = "CF Spec - 735 Haste Cap 18/0/53 Restoration",
			pts = { 18, 0, 53 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 3, 3 } },
				{  },
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 2 }, { 4, 2, 1 }, { 4, 3, 3 }, { 5, 1, 1 }, { 5, 2, 5 }, { 6, 1, 2 }, { 6, 3, 3 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 2, 5 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 3, 5 }, { 11, 2, 1 } },
			},
			note = "This build is centered around spending 18 points in the Balance Tree in order to pick up {spell:16924} and reducing the amount of Haste you need on gear to 735 in order to reach the haste cap. {spell:16819} is recommended to help reach other players with your {spell:29166}",
		},
	},
	glyphs = {
		major = {
		},
		minor = {
			{ 43331, "Glyph of Unburdened Rebirth", "Glyph of Unburdened Rebirth causes your Rebirth spell to no longer require an reagent." },
			{ 43335, "Glyph of the Wild", "Glyph of the Wild reduces the mana cost of Mark of the Wild and Gift of the WIld by 50%. Gift of the Wild is almost guaranteed to trigger Omen of Clarity in a 25 person raid, so there is minimal benefit to buffing mid-raid and casting a free Lifebloom for mana when you cannot drink." },
			{ 43674, "Glyph of Dash", "Glyph of Dash reduces the cooldown of Dash by 20%. This is useful if you use Dash to get out of bad ground effects quickly or want to position fast." },
			{ 43332, "Glyph of Thorns", "Glyph of Thorns increases the duration of your Thorns by 50 minutes when cast on yourself. You'll realistically only put Thorns on yourself when solo questing or for PvP." },
		},
	},
})
