-- GENERATED by scripts/build_guides.py -- do not edit by hand.
-- Source: Wowhead WotLK talent and glyph guides (see scripts/guides.json),
-- decoded against this realm's own talent trees.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/mage/arcane/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("MAGE", "Arcane", {
	builds = {
		{
			name = "Arcane",
			pts = { 57, 3, 11 },
			trees = {
				{ { 1, 2, 3 }, { 1, 3, 3 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 2, 3 }, { 3, 4, 1 }, { 4, 3, 3 }, { 4, 4, 3 }, { 5, 2, 1 }, { 5, 4, 5 }, { 6, 2, 3 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 3 }, { 8, 2, 2 }, { 8, 3, 5 }, { 9, 3, 5 }, { 10, 2, 3 }, { 10, 3, 2 }, { 11, 2, 1 } },
				{ { 1, 2, 3 } },
				{ { 1, 2, 2 }, { 1, 3, 3 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 2, 1 } },
			},
			note = "While not fully optimized for damage, this specialization focuses on survivability and consistent damage. Also several bosses in Icecrown Citadel have constant aura damage which will mess with your {spell:42846} and {spell:12051} if you don't have some sort of pushback protection, taking three points in {spell:12464} alongside {spell:19746} will have you sorted out. \n\nOverall the specialization loses:\n\n- Range from {spell:11247};\n\n- Mana saving from {spell:12575};\n\n- Threat reduction from {spell:11210};\n\nIn return it gains:\n\n- A fair bit of resistance from two points in {spell:29444};\n\n- Pushback protection from {spell:12464}.",
		},
		{
			name = "Arcane",
			pts = { 57, 3, 11 },
			trees = {
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 3, 5 }, { 3, 1, 1 }, { 3, 2, 3 }, { 3, 4, 1 }, { 4, 3, 3 }, { 4, 4, 3 }, { 5, 2, 1 }, { 5, 4, 5 }, { 6, 2, 3 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 3 }, { 8, 2, 2 }, { 8, 3, 5 }, { 9, 3, 5 }, { 10, 2, 3 }, { 10, 3, 2 }, { 11, 2, 1 } },
				{ { 1, 2, 3 } },
				{ { 1, 2, 2 }, { 1, 3, 3 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 2, 1 } },
			},
			note = "While similar to the baseline specialization, this one comes equipped with {spell:44396} allowing for incredibly high burst phases, this can be activated with self damage from tools such as Global Thermal Sapper Charge or Dark Rune; but it's also easily activated through raid damage from bosses such as , , , and .\n\nAs a alternative build, you can drop {spell:44425} and {spell:11247} for two points in {spell:29441} to make it safer through the raid damage in and . This combined with {spell:28332} for both safety and extra mana to keep pumping through longer fights, this spec is suggested for .",
		},
		{
			name = "Arcane",
			pts = { 56, 3, 12 },
			trees = {
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 3, 5 }, { 3, 1, 1 }, { 3, 2, 3 }, { 3, 3, 3 }, { 3, 4, 1 }, { 4, 3, 3 }, { 4, 4, 3 }, { 5, 2, 1 }, { 5, 4, 5 }, { 6, 2, 3 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 2, 2 }, { 8, 3, 5 }, { 9, 3, 5 }, { 10, 2, 3 }, { 10, 3, 2 } },
				{ { 1, 2, 3 } },
				{ { 1, 2, 2 }, { 1, 3, 3 }, { 2, 1, 3 }, { 2, 3, 3 }, { 3, 2, 1 } },
			},
			note = "This will be the highest damage spec for overall damage including AoE and Trash. It's burst heavy and provides some basic raid damage increase through{spell:31583} which provides extra 3% damage to the entire raid within a wide area, as well as buffing {spell:42846} further. {spell:54646} is a single target buff you provide to a raid member and it gives 3% Critical Strike Chance, as well as giving you 3% Critical Strike Chance in return as well. The basic rotation of this specialization is based around using {spell:42897} up to 3 or 4 stacks, and then using procs of {spell:54490} to cast {spell:42846} and reset the stacks of {spell:42897}.",
		},
	},
	glyphs = {
		major = {
			{ 44955, "Glyph of Arcane Blast", "Increases the damage of {spell:42897} by 3%." },
			{ 42735, "Glyph of Arcane Missiles", "Increases the critical strike damage bonus of {spell:8417} by 25%" },
			{ 42751, "Glyph of Molten Armor", "Provides an additional 20% of your Spirit as Critical Strike Rating." },
		},
		minor = {
			{ 43339, "Glyph of Arcane Intellect", "Reduces the mana cost of your {spell:43002} and {spell:42995} by half, not impressive by any means but some good quality of life." },
			{ 43364, "Glyph of Slow Fall", "Removes the need for Light Feather to use your {spell:130} spell. These are so minor that this is actually worth considering." },
			{ 43361, "Glyph of the Penguin", "Changes your polymorth from a Sheep to a Penguin, none of the other minor glyphs have any benefit for PVE either. So just pick this or whatever else." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/mage/fire/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("MAGE", "Fire", {
	builds = {
		{
			name = "Icecrown Citadel Progress Recommended 18/53/0",
			pts = { 18, 53, 0 },
			trees = {
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 4, 3 } },
				{ { 1, 3, 5 }, { 2, 1, 5 }, { 2, 3, 3 }, { 3, 1, 2 }, { 3, 3, 1 }, { 3, 4, 2 }, { 4, 1, 3 }, { 4, 4, 3 }, { 5, 1, 3 }, { 5, 2, 3 }, { 6, 3, 5 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 2 }, { 8, 3, 3 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "While very similar to the next specialization which focuses on pure single target damage, here you take {spell:29444} for resistances which will be very valuable for surviving in Icecrown Citadel where there's a lot of AoE damage which can nearly one-shot most mages.",
		},
		{
			name = "Pure Single Target Fire 18/53/0",
			pts = { 18, 53, 0 },
			trees = {
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 3, 5 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 4, 3 } },
				{ { 1, 3, 5 }, { 2, 1, 5 }, { 2, 3, 3 }, { 3, 1, 2 }, { 3, 3, 1 }, { 3, 4, 2 }, { 4, 1, 3 }, { 4, 4, 3 }, { 5, 1, 3 }, { 5, 2, 3 }, { 6, 3, 5 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 2 }, { 8, 3, 3 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "This specialization is made for single target only, ignoring most of the AoE focused talents since has no trash mobs, only bosses - because of this you can be greedier with your talents. You can alternatively use two points into {spell:44397} instead of {spell:12353} in order to focus more on damage and less on consistently, the latter talent will be more beginner friendly since it allows for more mistakes in positioning.",
		},
		{
			name = "Overall Damage Fire",
			pts = { 18, 53, 0 },
			trees = {
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 3, 5 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 4, 3 } },
				{ { 1, 3, 5 }, { 2, 1, 5 }, { 2, 3, 3 }, { 3, 3, 1 }, { 3, 4, 2 }, { 4, 1, 3 }, { 4, 4, 2 }, { 5, 1, 3 }, { 5, 2, 3 }, { 5, 3, 1 }, { 6, 3, 5 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 2 }, { 8, 3, 3 }, { 9, 1, 1 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "This build performs better in raids with a lot of trash, where you can focus on your overall damage using {spell:31661} and {spell:11113} followed by instant cast {spell:42926} from the {spell:44442} talent, this is a great specialization for raids such as .",
		},
		{
			name = "Frostfire",
			pts = { 0, 56, 15 },
			trees = {
				{  },
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 1, 5 }, { 2, 3, 3 }, { 3, 1, 2 }, { 3, 3, 1 }, { 3, 4, 2 }, { 4, 1, 3 }, { 4, 4, 3 }, { 5, 1, 3 }, { 5, 2, 3 }, { 5, 3, 1 }, { 6, 3, 5 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 2 }, { 8, 3, 3 }, { 9, 1, 1 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 2, 2 }, { 1, 3, 3 }, { 2, 1, 3 }, { 2, 3, 3 }, { 3, 1, 3 }, { 3, 2, 1 } },
			},
			note = "Frostfire mage because it has access to {spell:29440} requires 3% less overall hit, up to 6% less for the cast of {spell:47610} itself due to double dipping on this talent. Because of this it's a lot easier to reach hit cap making it great for early-mid gearing stages. Not to be dismissed as a early spec only, since it also double dips on some buffs and debuffs that provide crititical strike chance, and has higher crit damage modifiers than normal fire. Sadly, it loses access to {spell:54646} which provides both you and another caster some critical strike, but it can be outweighed by the benefits it provides. \n\nNote that you can swap two points into {spell:12518} from {spell:11100}. But the latter talent matches their range by 1 yard (40 yard range {spell:47610} and 41 yard range for the other two). This can make the spec a lot easier to play if you're not used to it. Downside is you lose some mana cost reduction and threat, both of which can be mitigated with external cooldowns such as {spell:29166} and {spell:1038} if they're ever an issue.",
		},
	},
	glyphs = {
		major = {
			{ 42739, "Glyph of Fireball", "Reduces the casting time of your {spell:42833} spell by 0.15 sec.\nPick this if playing Normal Fire Spec." },
			{ 44684, "Glyph of Frostfire", "Increases the damage dealt by {spell:47610} by 2% and its critical strike chance by 2%.\nPick this if playing Frostfire spec." },
			{ 45737, "Glyph of Living Bomb", "The periodic damage from your {spell:55362} can now critical strike." },
			{ 42751, "Glyph of Molten Armor", "Provides an additional 20% of your Spirit as Critical Strike Rating." },
		},
		minor = {
			{ 43339, "Glyph of Arcane Intellect", "Reduces the mana cost of your {spell:43002} and {spell:42995} by half, not impressive by any means but some good quality of life." },
			{ 43364, "Glyph of Slow Fall", "Removes the need for Light Feather to use your {spell:130} spell. These are so minor that this is actually worth considering." },
			{ 44920, "Glyph of Blast Wave", "The mana cost of your {spell:42945} spell is reduced by 15%, and it no longer knocks enemies back." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/mage/frost/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("MAGE", "Frost", {
	builds = {
		{
			name = "Frost",
			pts = { 18, 0, 53 },
			trees = {
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 2, 3, 5 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 1 }, { 4, 4, 3 } },
				{  },
				{ { 1, 2, 5 }, { 1, 3, 3 }, { 2, 1, 3 }, { 2, 3, 3 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 1 }, { 4, 1, 1 }, { 4, 2, 3 }, { 4, 3, 3 }, { 5, 2, 1 }, { 6, 3, 3 }, { 7, 2, 1 }, { 7, 3, 5 }, { 8, 2, 2 }, { 8, 3, 2 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
			},
			note = "This specialization will perform about the same regardless of fight length - be it extremely sort or insanely long fights. It won't perform as well as Fire or Arcane mage but has it's niche as a basic support class for 5 or 10 man groups. This is because it can provide replenishment through {spell:44561}, as well as {spell:11180} as an alternative for {spell:42859} or {spell:17803}.\n\nThe rotation continues to be mostly {spell:42842} spamming, but now includes {spell:44549} for instant cast {spell:47610}s, as well as {spell:44545} which allows for usage of {spell:58534} on bosses. The damage isn't as bad as it was in TBC, since the spec is equipped with changes that were made towards the end of the expansion originally.",
		},
	},
	glyphs = {
		major = {
			{ 50045, "Glyph of Eternal Water", "Your {spell:31687} now lasts indefinitely. But your Water Elemental can no longer cast Freeze which in PVE raid content you never do regardless." },
			{ 42742, "Glyph of Frostbolt", "Increases the damage dealt by {spell:42842} by 5%, but removes the slowing effect." },
			{ 42751, "Glyph of Molten Armor", "Provides an additional 20% of your Spirit as Critical Strike Rating." },
		},
		minor = {
			{ 43339, "Glyph of Arcane Intellect", "Reduces the mana cost of your {spell:43002} and {spell:42995} by half, not impressive by any means but some good quality of life." },
			{ 43364, "Glyph of Slow Fall", "Removes the need for Light Feather to use your {spell:130} spell. These are so minor that this is actually worth considering." },
			{ 43361, "Glyph of the Penguin", "Changes your polymorth from a Sheep to a Penguin, none of the other minor glyphs have any benefit for PVE either. So just pick this or whatever else." },
		},
	},
})
