-- GENERATED by scripts/build_guides.py -- do not edit by hand.
-- Source: Wowhead WotLK talent and glyph guides (see scripts/guides.json),
-- decoded against this realm's own talent trees.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/priest/discipline/healer-talent-builds-glyphs-pve
ns:RegisterTalentGuide("PRIEST", "Discipline", {
	builds = {
		{
			name = "Standard Discipline 55/16/0",
			pts = { 56, 15, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 2, 3 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 3 }, { 4, 2, 3 }, { 5, 2, 5 }, { 5, 3, 1 }, { 6, 1, 2 }, { 6, 3, 3 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 3 }, { 8, 1, 1 }, { 8, 2, 3 }, { 8, 3, 2 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 1, 2 }, { 1, 3, 4 }, { 2, 2, 5 }, { 3, 1, 1 }, { 3, 4, 3 } },
				{  },
			},
			note = "This is your bread-and-butter spec that provides just about everything you could need for raiding both 10-mans and 25-mans, as such there's only a few flexible talents.\n\nAlthough {spell:45234} is chosen by default, {spell:15014} provides about 68 Mp5 when casting {spell:53007} on cooldown, making it an option for low levels of gear at least. The main downside is that it also requires you to spend another talent point in the Holy tree to be able to take it, which would be your second {spell:57470} point.\n\nAnother possibility is to swap the {spell:27904} talents into {spell:18535} or {spell:14908} but from this point onwards the extra survivability from Spell Warding is generally the best choice, as there are plenty of mechanics that deal magic damage, Renew is barely ever used and Divine Fury is primarily good when raid tiers are trivial enough to allow you to smite during downtime on the easier bosses.",
		},
		{
			name = "Smite Discipline 53/18/0",
			pts = { 53, 18, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 2, 3 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 3 }, { 4, 2, 3 }, { 5, 2, 5 }, { 5, 3, 1 }, { 6, 1, 2 }, { 6, 3, 3 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 1, 1 }, { 8, 2, 3 }, { 8, 3, 2 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 1, 2 }, { 1, 3, 5 }, { 2, 3, 5 }, { 3, 1, 1 }, { 3, 4, 3 }, { 4, 3, 2 } },
				{  },
			},
			note = "This is an alternate version of the build above that drops some sustain and healing throughput talents to deal more damage with {spell:48123} during downtime, especially useful for T7 and T9. Although the embed above shows the fully optimized version of it, you can opt to keep some of your healing talents if certain trade-offs do not seem worthwhile.\n\nThe basic priority for dealing damage with this spec when your healing is not needed is as follows:\n\n- Pre-cast {spell:48066} on the pull for {spell:52800}\n\n- Apply {spell:48300} if it's not currently active\n\n- Apply {spell:48125} if it's not currently active\n\n- Use {spell:48135} to put up the debuff\n\n- Cast {spell:48123} while the Holy Fire debuff is up\n\nThat said, with instant casts and channeled spells not consuming {spell:52800} and clipping DoTs sometimes being worth it, there is a lot of room for optimization.\n\nIn the example below, casting a {spell:48066} mid-fight is a net gain, as you almost fully recover the second through haste, while also providing some healing and increasing your damage if you are still using the T8 4-piece bonus.\n\n- Cast {spell:48066} for {spell:52800}\n\n- Apply {spell:48300} and {spell:48125}\n\n- Cast {spell:53007} if {spell:15363} is already active or unnecessary for the encounter\n\n- Use {spell:48135} to put up the debuff\n\n- Cast {spell:48123} while the Holy Fire debuff is up",
		},
		{
			name = "Shadowfiend Discipline 52/2/17",
			pts = { 52, 2, 17 },
			trees = {
				{ { 1, 3, 5 }, { 2, 2, 3 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 3 }, { 4, 2, 3 }, { 5, 2, 5 }, { 5, 3, 1 }, { 6, 1, 2 }, { 6, 3, 3 }, { 7, 2, 1 }, { 7, 3, 3 }, { 8, 1, 1 }, { 8, 2, 3 }, { 8, 3, 2 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 1 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 1, 2 } },
				{ { 1, 1, 3 }, { 1, 2, 2 }, { 1, 3, 5 }, { 2, 2, 1 }, { 2, 3, 3 }, { 3, 3, 1 }, { 4, 2, 2 } },
			},
			note = "This build sacrifices all talents in the holy skill tree, as well as one {spell:47516} point to unlock {spell:15311}, which provides a great amount of additional regeneration, as long as the encounter is long enough to get the extra use off.\n\nThe main downside is that you can no longer provide {spell:15363} meaning you'd have to go without the buff or rely on another Shaman or Priest in your raid to apply it, which isn't exactly ideal. Besides that, there's a lot of survivability you lose from not having {spell:27904} and {spell:19236} as well as a fair bit of throughput from Holy Specialization.\n\nAll in all, missing out on all of these talents, especially Inspiration, makes this a questionable choice for most content and is mostly listed for the sake of completion.",
		},
	},
	glyphs = {
		major = {
			{ 42408, "Glyph of Power Word: Shield", "Glyph of Power Word: Shield is a nice 20% boost to your PW:S throughput, which can even crit and proc small {spell:47515} bubbles. Definitely a must-have for Discipline s." },
			{ 45756, "Glyph of Penance", "Glyph of Penance lowers the cooldown of the spell from 12 seconds down to 8 when combined with {spell:47508}. As we practically cast Penance on cooldown, this is the second Glyph we will never swap out." },
			{ 42409, "Glyph of Prayer of Healing", "Glyph of Prayer of Healing adds a Heal over Time component to your {spell:48072}. This Glyph will be used for your third slot most of the time." },
			{ 42401, "Glyph of Holy Nova", "Glyph of Holy Nova buffs the healing and damage of your Holy Nova spell by 20%. This Glyph is a good pick for your third slot on the Heroic Lich King encounter." },
			{ 42416, "Glyph of Smite", "Glyph of Smite simply allows you to deal more healer dps during downtime and is another possible pick for your third slot." },
			{ 42405, "Glyph of Mind Control", "Glyph of Mind Control can be swapped in as your third Glyph for encounters like or to reduce the chance of your {spell:605} getting resisted." },
		},
		minor = {
			{ 43374, "Glyph of Shadowfiend", "Glyph of Shadowfiend refunds 5% of your total mana whenever your Shadowfiend dies, and does not trigger from dismissing it. While your Shadowfiend is unlikely to die, especially when shielded, this Glyph grants you one extra hit worth of mana if it does happen." },
			{ 43370, "Glyph of Levitate", "Glyph of Levitate simply lets you cast the spell without needing to bring the reagent, good for avoiding fall damage or walking on water." },
			{ 43371, "Glyph of Fortitude", "Glyph of Fortitude halves the mana cost of your fortitude buffs, so you will spend less time drinking and will not have to use up as much mana for rebuffs mid-fight." },
			{ 43372, "Glyph of Shadow Protection", "Glyph of Shadow Protection just makes it easier to keep Shadow Protection up on your entire raid by not having to rebuff as often, but can easily be dropped since the buff isn't always needed." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/priest/holy/healer-talent-builds-glyphs-pve
ns:RegisterTalentGuide("PRIEST", "Holy", {
	builds = {
		{
			name = "Standard Holy 18/53/0",
			pts = { 18, 53, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 2, 3 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 1 }, { 4, 2, 3 } },
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 1, 3, 4 }, { 2, 2, 5 }, { 3, 1, 1 }, { 3, 4, 3 }, { 4, 1, 2 }, { 5, 1, 2 }, { 5, 2, 1 }, { 5, 3, 5 }, { 6, 1, 1 }, { 6, 3, 5 }, { 7, 1, 3 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "This is your go-to spec that takes the most valueable talents while also providing you with a great deal of flexibility for 10-mans and 25-mans alike. Holy is quite constrained when it comes to skill points, so there's a handful of possible variations, but only a few swaps really make sense.\n\nAlthough it comes at the cost of two talent points, {spell:64127} is a great utility talent that can be used to speed up raids or help raid members avoid movement-related mechanics. Just make sure to coordinate your {spell:48066} usage with your Discipline , if there is one in the raid.\n\nDepending on how frequently you use {spell:48068}, you could opt to drop down to 1/3 {spell:63543} to still be able to trigger {spell:33154}, while also allowing you to spend these two points on different talents. \n\nDue to the charges being doubled, cooldown being lowered and the effect now only cancelling when heavy damage is taken, {spell:724} is actually a solid talent as long as you properly play around it and also train your raid to use it. It only has to make up around 1% of your overall healing for it to be worth the point, which should easily be achieved with a single HoT doing about 10k healing in T7 gear.",
		},
		{
			name = "Soul Warding Holy 21/50/0",
			pts = { 21, 50, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 2, 3 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 2, 1 }, { 3, 3, 3 }, { 4, 2, 3 }, { 5, 3, 1 } },
				{ { 1, 1, 2 }, { 1, 3, 5 }, { 2, 3, 5 }, { 3, 1, 1 }, { 3, 4, 3 }, { 4, 1, 2 }, { 4, 3, 2 }, { 5, 1, 2 }, { 5, 2, 1 }, { 5, 3, 5 }, { 6, 1, 2 }, { 6, 3, 5 }, { 7, 1, 3 }, { 7, 3, 1 }, { 8, 1, 2 }, { 8, 3, 3 }, { 9, 2, 1 }, { 10, 2, 5 } },
				{  },
			},
			note = "This spec is an alternate version of the build above that simply drops points from {spell:47558} as well as {spell:47788} to pick up {spell:63574}. \n\nThis is done to be able to spam {spell:48066} on as many raid members as possible for {spell:64129} to move between packs more quickly, specifically meant for T7 runs. Ideally you would also want to be the only healer priest in the raid when running this spec, as your shields would otherwise clash with the Discipline Priests' casts.\n\nThe main change in playstyle compared to a regular Holy build is the fact that {spell:48066} replaces {spell:48068} as your main filler cast to both provide the speed buff and the usual effective HP increase to your raid, rather than HoT ticks that tend to have high overhealing. This is why {spell:14908} is dropped in favour of {spell:18535} and {spell:15017} to be able to dps more effectively during downtime or on trivial bosses.\n\nBeyond Phase 1 this build as well as the alternate Hybrid version are obsolete as they do not have an external defensive cooldown at all, have lacking sustain due to missing out on Rapture, and also occupy a spot that could otherwise be filled by a regular Discipline Priest providing all the other utility, like Power Infusion and Pain Suppression. \n\nAs such, even in a raid group that already has one Discipline Priest, bringing in another one is generally better than opting ...",
		},
	},
	glyphs = {
		major = {
			{ 42396, "Glyph of Circle of Healing", "Glyph of Circle of Healing is practically a 20% boost to your CoH throughput, which means that it's definitely a must-have for all Holy s." },
			{ 42409, "Glyph of Prayer of Healing", "Glyph of Prayer of Healing adds a Heal over Time component to your PoH that does a decent amount of additional healing. As this is your best spell for raidhealing alongside CoH, it's another mandatory Glyph regardless of what content you are doing." },
			{ 45755, "Glyph of Guardian Spirit", "Glyph of Guardian Spirit lowers the cooldown of the spell by a whole minute whenever it doesn't proc the death prevention. Having this allows you to use it more frequently and carelessly to benefit from the 40% healing increase." },
			{ 42408, "Glyph of Power Word: Shield", "Glyph of Power Word: Shield is a nice 20% boost to your PW:S throughput and can even crit and proc {spell:33154}. A great choice for the third Glyph slot when running the Soul Warding or oMDS build, as you cannot make use of the Guardian Spirit Glyph." },
			{ 42400, "Glyph of Flash Heal", "Glyph of Flash Heal makes your spothealing more efficient, allowing you to easily stack up Serendipity stacks at a low cost. As it doesn't add a significant amount of sustain, you can easily skip it unless you are really struggling on mana." },
			{ 42416, "Glyph of Smite", "Glyph of Smite simply allows you to deal more healer dps during downtime and is another possible pick for your third slot." },
			{ 42405, "Glyph of Mind Control", "Can be swapped in as your third Glyph for encounters like or to reduce the chance of your {spell:605} getting resisted." },
		},
		minor = {
			{ 43374, "Glyph of Shadowfiend", "Glyph of Shadowfiend refunds 5% of your total mana whenever your Shadowfiend dies, and does not trigger from dismissing it. While your Shadowfiend is unlikely to die, especially when shielded, this Glyph grants you one extra hit worth of mana if it does happen." },
			{ 43370, "Glyph of Levitate", "Glyph of Levitate simply lets you cast the spell without needing to bring the reagent, good for avoiding fall damage or walking on water." },
			{ 43371, "Glyph of Fortitude", "Glyph of Fortitude halves the mana cost of your fortitude buffs, so you will spend less time drinking and will not have to use up as much mana for rebuffs mid-fight." },
			{ 43372, "Glyph of Shadow Protection", "Glyph of Shadow Protection is similar to the fortitude one, and just makes it easier to keep Shadow Protection up on your entire raid by not having to rebuff as often, but can easily be dropped since Shadow Protection isn't always needed." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/priest/shadow/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("PRIEST", "Shadow", {
	builds = {
		{
			name = "Shadow",
			pts = { 14, 0, 57 },
			trees = {
				{ { 1, 3, 5 }, { 2, 2, 3 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 2, 1 } },
				{  },
				{ { 1, 1, 3 }, { 1, 2, 2 }, { 1, 3, 5 }, { 2, 2, 2 }, { 2, 3, 3 }, { 3, 2, 5 }, { 3, 3, 1 }, { 4, 2, 2 }, { 4, 3, 2 }, { 4, 4, 3 }, { 5, 2, 1 }, { 5, 4, 2 }, { 6, 1, 2 }, { 6, 3, 3 }, { 7, 2, 1 }, { 7, 3, 5 }, { 8, 1, 2 }, { 8, 3, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 3, 5 }, { 11, 2, 1 } },
			},
			note = "Our glyph choice also doesn't have much wiggle room. You always want to run Glyph of Shadow and Glyph of Mind Flay but the third is optional between Glyph of Dispersion and Glyph of Shadow Word: Death depending on if you want a more defensive or a more offensive build. For minors there really isn't much to consider except if you want Glyph of Fortitude for cheaper {spell:48162} casts or Glyph of Shadow Protection to make you have to refresh {spell:48170} less often.",
		},
	},
	glyphs = {
		major = {
			{ 42407, "Glyph of Shadow", "Glyph of Shadow makes your non-DoT crits give you 30% of your Spirit as Spell Power, making Spirit and {spell:15338} even more valuable. You always want to use this." },
			{ 42415, "Glyph of Mind Flay", "Glyph of Mind Flay increases the damage of {spell:48156} as long as {spell:48125} is up, which should basically be always. You always want to use this." },
			{ 45753, "Glyph of Dispersion", "Glyph of Dispersion reduces the cooldown of {spell:47585}. This isn't amazing, but we don't have many good Major Glyphs so you take what you can get." },
			{ 42414, "Glyph of Shadow Word: Death", "Glyph of Shadow Word: Death increases the damage dealt by {spell:48158} by 10% to targets under 35% health, making it slightly more appealing as an execute style spell. Unfortunately this is only active for small parts of fights and isn't a massively significant amount of damage." },
		},
		minor = {
			{ 43374, "Glyph of Shadowfiend", "Glyph of Shadowfiend is really the only significant Minor Glyph for us. If your {spell:34433} dies early because of damage, you recover 5% of your maximum mana. While you do lose the damage it would deal, this at least helps offset the mana you didn't gain." },
			{ 43371, "Glyph of Fortitude", "Glyph of Fortitude halves the mana cost of {spell:48161} and {spell:48162}. While this isn't much in the grand scheme of things, it is always nice to have to drink less when you have to rebuff, and this also makes it less damaging if you ever have to rebuff mid combat." },
			{ 43372, "Glyph of Shadow Protection", "Glyph of Shadow Protection increases the duration of {spell:48169} and {spell:48170}, which is useful as they are a shorter duration than most of your other buffs." },
			{ 43370, "Glyph of Levitate", "Glyph of Levitate removes the reagent cost of {spell:1706}. Never get caught jumping off a high building with no Light Feather again!" },
		},
	},
})
