-- GENERATED by scripts/build_guides.py -- do not edit by hand.
-- Source: Wowhead WotLK talent and glyph guides (see scripts/guides.json),
-- decoded against this realm's own talent trees.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/rogue/assassination/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("ROGUE", "Assassination", {
	builds = {
		{
			name = "Assassination 51/13/7",
			pts = { 51, 13, 7 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 4, 3 }, { 3, 1, 1 }, { 3, 3, 4 }, { 4, 2, 3 }, { 4, 3, 5 }, { 5, 1, 2 }, { 5, 2, 1 }, { 6, 2, 5 }, { 6, 3, 2 }, { 7, 2, 1 }, { 8, 1, 3 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 3, 5 }, { 2, 4, 5 }, { 3, 3, 3 } },
				{ { 1, 1, 5 }, { 1, 3, 2 } },
			},
			note = "The Assassination talent specialization utilizes the {spell:58410} talent to remove a huge drawback of the {spell:57993} ability and with this talent, Envenom becomes an absolute all-star damage dealing finishing move. With {spell:51669} as well, your Envenoms will pull double-duty also refreshing your {spell:6774}. With a full 3 ranks of {spell:16515} and 5 ranks of {spell:14117}, you can see how this all comes together to make a specialization that deals an absurd amount of poison damage.\n\nYou will want to pick one fast dagger either 1.3 or 1.4 speed and put Deadly Poison IX on it. Choose the highest DPS fast dagger you have. Your second dagger can be either fast or slow, just choose the highest DPS option you have and put Instant Poison IX on it.\n\nYou should put the Deadly Poison IX weapon in the main hand and the Instant Poison IX weapon in the off hand.\n\n{spell:14164} and {spell:51633} are skipped because you will almost exclusively be using {spell:57993} as your finishing move over and over and rarely cast any other finisher so these talents are not very desirable.\n\n{spell:31209} is a great damage dealing talent that may not appear to be a damage dealing talent at first glance. Having increased movement speed means you spent less time moving between enemies and more time actually attacking and damaging enemies. Being out of melee range essentially \"turns off\" everything ...",
		},
		{
			name = "Assassination 51/18/2",
			pts = { 51, 18, 2 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 4, 3 }, { 3, 1, 1 }, { 3, 3, 4 }, { 4, 2, 3 }, { 4, 3, 5 }, { 5, 1, 2 }, { 5, 2, 1 }, { 6, 2, 5 }, { 6, 3, 2 }, { 7, 2, 1 }, { 8, 1, 3 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 3, 5 }, { 2, 4, 5 }, { 3, 3, 5 }, { 4, 3, 3 } },
				{ { 1, 1, 2 } },
			},
			note = "This version of Assassination opts for more passive haste and critical strike chance with more investment in the combat tree, sacrificing {spell:48666} damage and energy generation from {spell:58425}. It is hard to say for sure which is better. There is not really a meaningful difference in damage output between these two specializations according to current simulation and spreadsheet tools. Some gear sets very slightly prefer one or the other but it essentially doesn't matter, you should use whichever one you prefer.",
		},
		{
			name = "Assassination 44/21/6",
			pts = { 44, 21, 6 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 4, 3 }, { 3, 1, 1 }, { 3, 3, 4 }, { 4, 2, 3 }, { 4, 3, 5 }, { 5, 1, 2 }, { 5, 2, 1 }, { 6, 2, 5 }, { 6, 3, 2 }, { 7, 2, 1 }, { 8, 1, 3 }, { 8, 3, 2 }, { 9, 1, 3 }, { 9, 2, 1 } },
				{ { 1, 3, 5 }, { 2, 1, 2 }, { 2, 4, 5 }, { 3, 3, 5 }, { 4, 3, 3 }, { 5, 2, 1 } },
				{ { 1, 1, 5 }, { 1, 3, 1 } },
			},
			note = "This variant of Assassination drops some points at the end of the Assassination tree in favor of investing enough into Combat to acquire {spell:13877}. This build will typically do a bit less damage on a single target encounter than the builds with {spell:51662}, but much more damage on encounters with multiple targets.\n\nYou weapon and poison selection is the same as standard Assassination builds. Because you don't have {spell:51669}, you will need to spend a few combo points throughout the fight manually refreshing your {spell:6774} to make sure it stays active.",
		},
	},
	glyphs = {
		major = {
			{ 45767, "Glyph of Tricks of the Trade", "Increasing someone else's damage by 15% for 4 more seconds every 30 seconds through the use of {spell:57934} is a pretty strong effect. Of your three glyphs, this one is the weakest in terms of pure damage output." },
			{ 45761, "Glyph of Hunger for Blood", "It may not be exciting, but there is no doubt Glyph of Hunger for Blood is very strong. You'll be casting {spell:60177} whether or not you have this Glyph so there is no additional cost to utilize this benefit - its just 3% more damage." },
			{ 45768, "Glyph of Mutilate", "In a build that is so hungry for combo points and energy, Glyph of Mutilate is an all-star. Reducing the cost of your primary combo point builder by 5 amounts to quite a lot of energy quite quickly." },
			{ 42963, "Glyph of Feint", "This glyph reduces the cost of using feint to zero, turning it into an extremely strong defensive ability. On many boss encounters in Ulduar there is heavy raid damage and rogues will want to use this glyph to give them free use of Feint." },
		},
		minor = {
			{ 43379, "Glyph of Blurred Speed", "Walking on water is always fun, and this also allows you to swim to the surface, {spell:11305} to stand on the water, then get on your flying mount from the middle of a lake! Normally you cannot get on your flying mount while swimming and would need to go to the land." },
			{ 43378, "Glyph of Safe Fall", "Not taking fall damage is always nice, and this really amps up the power of your Safe Fall passive." },
			{ 43376, "Glyph of Distract", "A little extra range on {spell:1725} can help make getting those clutch Distracts easier." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/combat/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("ROGUE", "Combat", {
	builds = {
		{
			name = "Combat 20/51/0",
			pts = { 20, 51, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 3, 5 }, { 4, 2, 1 }, { 4, 3, 4 } },
				{ { 1, 2, 2 }, { 1, 3, 5 }, { 2, 1, 2 }, { 2, 4, 5 }, { 3, 1, 1 }, { 4, 3, 3 }, { 4, 4, 5 }, { 5, 2, 1 }, { 5, 3, 5 }, { 6, 2, 2 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 3, 5 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "In most circumstances it is best to pair both of your weapons so that they match one of the weapon specialization talents, either Fist & Dagger weapons with {spell:13807}, Sword & Axe weapons with {spell:13964}, or Mace weapons with {spell:13803}. Which talent specialization you use should always be decided by what weapons you actually have on your character. You should look at what your strongest weapons are and then decide which talent specialization to use to match those weapons.\n\nNo matter which weapon specialization you choose, you will always want to have a slow mainhand weapon (2.6 or 2.7 speed) and a fast offhand weapon (1.3, 1.4, or 1.5 speed). The slow mainhand weapon is important to increase damage per cast of {spell:48638}, as well as increase the odds to trigger Instant Poison IX with each cast of {spell:48638}. The fast offhand weapon is very important for more triggers of {spell:35553} - faster weapon means more energy.\n\nIt may surprise some readers that we pass over the old favorite {spell:58425}. This is still a very strong talent, but in Wrath of the Lich King the power of rogue poisons is just so high that we cannot pass up taking points in {spell:16515} and {spell:14117} to push that advantage even further. Since those are fourth-level talents in Assassination, we cannot afford any points into {spell:58425}.",
		},
		{
			name = "Combat 20/51/0",
			pts = { 20, 51, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 3, 5 }, { 4, 2, 1 }, { 4, 3, 4 } },
				{ { 1, 2, 2 }, { 1, 3, 5 }, { 2, 1, 2 }, { 2, 4, 5 }, { 3, 1, 1 }, { 3, 3, 5 }, { 4, 3, 3 }, { 4, 4, 5 }, { 5, 2, 1 }, { 6, 2, 2 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 3, 5 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "In most circumstances it is best to pair both of your weapons so that they match one of the weapon specialization talents, either Fist & Dagger weapons with {spell:13807}, Sword & Axe weapons with {spell:13964}, or Mace weapons with {spell:13803}. Which talent specialization you use should always be decided by what weapons you actually have on your character. You should look at what your strongest weapons are and then decide which talent specialization to use to match those weapons.\n\nNo matter which weapon specialization you choose, you will always want to have a slow mainhand weapon (2.6 or 2.7 speed) and a fast offhand weapon (1.3, 1.4, or 1.5 speed). The slow mainhand weapon is important to increase damage per cast of {spell:48638}, as well as increase the odds to trigger Instant Poison IX with each cast of {spell:48638}. The fast offhand weapon is very important for more triggers of {spell:35553} - faster weapon means more energy.\n\nIt may surprise some readers that we pass over the old favorite {spell:58425}. This is still a very strong talent, but in Wrath of the Lich King the power of rogue poisons is just so high that we cannot pass up taking points in {spell:16515} and {spell:14117} to push that advantage even further. Since those are fourth-level talents in Assassination, we cannot afford any points into {spell:58425}.",
		},
		{
			name = "Combat 20/51/0",
			pts = { 20, 51, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 3, 5 }, { 4, 2, 1 }, { 4, 3, 4 } },
				{ { 1, 2, 2 }, { 1, 3, 5 }, { 2, 1, 2 }, { 2, 4, 5 }, { 3, 3, 5 }, { 4, 3, 3 }, { 4, 4, 1 }, { 5, 2, 1 }, { 5, 3, 5 }, { 6, 2, 2 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 3, 5 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "In most circumstances it is best to pair both of your weapons so that they match one of the weapon specialization talents, either Fist & Dagger weapons with {spell:13807}, Sword & Axe weapons with {spell:13964}, or Mace weapons with {spell:13803}. Which talent specialization you use should always be decided by what weapons you actually have on your character. You should look at what your strongest weapons are and then decide which talent specialization to use to match those weapons.\n\nNo matter which weapon specialization you choose, you will always want to have a slow mainhand weapon (2.6 or 2.7 speed) and a fast offhand weapon (1.3, 1.4, or 1.5 speed). The slow mainhand weapon is important to increase damage per cast of {spell:48638}, as well as increase the odds to trigger Instant Poison IX with each cast of {spell:48638}. The fast offhand weapon is very important for more triggers of {spell:35553} - faster weapon means more energy.\n\nIt may surprise some readers that we pass over the old favorite {spell:58425}. This is still a very strong talent, but in Wrath of the Lich King the power of rogue poisons is just so high that we cannot pass up taking points in {spell:16515} and {spell:14117} to push that advantage even further. Since those are fourth-level talents in Assassination, we cannot afford any points into {spell:58425}.",
		},
		{
			name = "Combat 20/51/0",
			pts = { 20, 51, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 3, 5 }, { 4, 2, 1 }, { 4, 3, 4 } },
				{ { 1, 2, 2 }, { 1, 3, 5 }, { 2, 1, 2 }, { 2, 4, 5 }, { 3, 3, 1 }, { 4, 3, 3 }, { 4, 4, 5 }, { 5, 1, 5 }, { 5, 2, 1 }, { 6, 2, 2 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 3, 5 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "In most circumstances it is best to pair both of your weapons so that they match one of the weapon specialization talents, either Fist & Dagger weapons with {spell:13807}, Sword & Axe weapons with {spell:13964}, or Mace weapons with {spell:13803}. Which talent specialization you use should always be decided by what weapons you actually have on your character. You should look at what your strongest weapons are and then decide which talent specialization to use to match those weapons.\n\nNo matter which weapon specialization you choose, you will always want to have a slow mainhand weapon (2.6 or 2.7 speed) and a fast offhand weapon (1.3, 1.4, or 1.5 speed). The slow mainhand weapon is important to increase damage per cast of {spell:48638}, as well as increase the odds to trigger Instant Poison IX with each cast of {spell:48638}. The fast offhand weapon is very important for more triggers of {spell:35553} - faster weapon means more energy.\n\nIt may surprise some readers that we pass over the old favorite {spell:58425}. This is still a very strong talent, but in Wrath of the Lich King the power of rogue poisons is just so high that we cannot pass up taking points in {spell:16515} and {spell:14117} to push that advantage even further. Since those are fourth-level talents in Assassination, we cannot afford any points into {spell:58425}.",
		},
		{
			name = "Combat 20/51/0",
			pts = { 20, 51, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 3, 5 }, { 4, 2, 1 }, { 4, 3, 4 } },
				{ { 1, 2, 2 }, { 1, 3, 5 }, { 2, 1, 2 }, { 2, 4, 5 }, { 3, 1, 1 }, { 4, 3, 3 }, { 4, 4, 2 }, { 5, 1, 5 }, { 5, 2, 1 }, { 5, 3, 3 }, { 6, 2, 2 }, { 6, 3, 2 }, { 7, 1, 3 }, { 7, 2, 1 }, { 8, 3, 5 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "In most circumstances it is best to pair both of your weapons so that they match one of the weapon specialization talents, either Fist & Dagger weapons with {spell:13807}, Sword & Axe weapons with {spell:13964}, or Mace weapons with {spell:13803}. Which talent specialization you use should always be decided by what weapons you actually have on your character. You should look at what your strongest weapons are and then decide which talent specialization to use to match those weapons.\n\nNo matter which weapon specialization you choose, you will always want to have a slow mainhand weapon (2.6 or 2.7 speed) and a fast offhand weapon (1.3, 1.4, or 1.5 speed). The slow mainhand weapon is important to increase damage per cast of {spell:48638}, as well as increase the odds to trigger Instant Poison IX with each cast of {spell:48638}. The fast offhand weapon is very important for more triggers of {spell:35553} - faster weapon means more energy.\n\nIt may surprise some readers that we pass over the old favorite {spell:58425}. This is still a very strong talent, but in Wrath of the Lich King the power of rogue poisons is just so high that we cannot pass up taking points in {spell:16515} and {spell:14117} to push that advantage even further. Since those are fourth-level talents in Assassination, we cannot afford any points into {spell:58425}.",
		},
		{
			name = "Hybrid 38/33/0",
			pts = { 38, 33, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 1, 1 }, { 3, 3, 5 }, { 4, 2, 3 }, { 4, 3, 5 }, { 5, 1, 2 }, { 5, 2, 1 }, { 6, 2, 5 }, { 6, 3, 2 }, { 7, 2, 1 }, { 8, 1, 3 } },
				{ { 1, 2, 2 }, { 1, 3, 5 }, { 2, 1, 2 }, { 2, 4, 5 }, { 3, 1, 2 }, { 3, 3, 5 }, { 4, 3, 3 }, { 4, 4, 1 }, { 5, 2, 1 }, { 6, 2, 2 }, { 6, 3, 2 }, { 7, 1, 2 }, { 7, 2, 1 } },
				{  },
			},
			note = "If you are interested in using both of your Dual Talent Specialization slots for PvE talent specializations and want to have a really strong AoE specialization, this is a great choice. A player looking to maximize their overall boss and trash damage dealt in a raid might take standard 20/51/0 Combat in one of their talent slots and this hybrid build in the other then swap during raids depending on the situation. This build's boss damage is much weaker than either standard Combat or standard Assassination, so if you are interested in only boss damage, this build is not for you.\n\nThis build's purpose is very simple: it is to maximize the damage dealt by {spell:51723} and give extra energy to cast it more often. You will want two slow weapons, ideally fist weapons to synergize with {spell:13807}. Both weapons will use Instant Poison IX and their slow speed means the chance per hit to trigger Instant Poison will be high.\n\nOn pulls with large numbers of enemies this build is completely unmatched and offers arguably the strongest AoE potential of any class in the entire game. The more enemies in the pull, the better it is for this specialization. At lower enemy counts you will have more serious competition from other classes.\n\nA typical pull has you using {spell:57934} on your tank, then quickly entering and exiting {spell:1784} to trigger {spell:58426}. If {spell:14177}, ...",
		},
	},
	glyphs = {
		major = {
			{ 45767, "Glyph of Tricks of the Trade", "There is no doubt that increasing someone else's damage by 15% for 4 more seconds every 30 seconds through the use of {spell:57934} is one of the best damage increases a glyph can offer. This is undoubtedly your strongest glyph as any specialization of rogue." },
			{ 45762, "Glyph of Killing Spree", "Killing Spree is an immensely powerful cooldown and you will want to use it as much as possible. A massive 45 second reduction to the cooldown nets you many many more uses of Killing Spree throughout a raid." },
			{ 42962, "Glyph of Expose Armor", "If you find yourself in a raid without any s to apply {spell:7386}, you will need to apply {spell:8647} and this glyph should be used as the third glyph." },
			{ 42972, "Glyph of Sinister Strike", "This Glyph will sometimes give you extra combo points when your Sinister Strike gets a critical hit. Sinister Strike Glyph is not a very strong effect for Combat because you typically already have enough combo points to maintain your important finishers {spell:6774} and {spell:48672}. Getting extra combo points is usually making you cast more {spell:48668}, which is just not a very strong finishing move. The extra randomness in your combo point generation makes it more difficult to efficiently spend your combo points, sometimes resulting in inefficient early refreshes of your important abilities {spell:6774} and {spell:48672}. That makes this glyph really only a contender for your third slot and a fine choice for that." },
			{ 45766, "Glyph of Fan of Knives", "Fan of Knives is an exceptional AoE ability and boosting it up by 20% is a pretty substantial increase in damage. If your raid values your damage dealt to trash mobs and likes doing big pulls of enemies, this is a very strong choice for your third glyph." },
		},
		minor = {
			{ 43379, "Glyph of Blurred Speed", "Walking on water is always fun, and this also allows you to swim to the surface, {spell:11305} to stand on the water, then get on your flying mount from the middle of a lake! Normally you cannot get on your flying mount while swimming and would need to go to the land." },
			{ 43378, "Glyph of Safe Fall", "Not taking fall damage is always nice, and this really amps up the power of your Safe Fall passive." },
			{ 43376, "Glyph of Distract", "A little extra range on {spell:1725} can help make getting those clutch Distracts easier." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/rogue/subtlety/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("ROGUE", "Subtlety", {
	builds = {
		{
			name = "Subtlety 20/0/51",
			pts = { 19, 0, 52 },
			trees = {
				{ { 1, 1, 3 }, { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 2 }, { 3, 1, 1 }, { 3, 3, 1 }, { 4, 2, 1 }, { 4, 3, 3 } },
				{  },
				{ { 1, 1, 5 }, { 1, 3, 2 }, { 2, 1, 2 }, { 2, 3, 3 }, { 3, 1, 2 }, { 3, 3, 3 }, { 4, 2, 3 }, { 5, 1, 1 }, { 5, 2, 1 }, { 5, 3, 2 }, { 5, 4, 1 }, { 6, 1, 3 }, { 6, 3, 5 }, { 7, 2, 1 }, { 7, 3, 1 }, { 8, 2, 5 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
			},
			note = "As a Subtlety rogue in PvE you will be using {spell:48660} as your primary combo point builder, but you won't use it often. Your {spell:51701} talent will provide the majority of the combo points that you generate. A slow fist, sword, or mace in the mainhand with {spell:57968} is preferred, but a slow dagger is also acceptable. The offhand should be as fast as possible of any weapon type and have {spell:57973} on it.",
		},
	},
	glyphs = {
		major = {
			{ 45767, "Glyph of Tricks of the Trade", "There is no doubt that increasing someone else's damage by 15% for 4 more seconds every 20 seconds through the use of {spell:57934} is one of the best damage increases a glyph can offer. This is undoubtedly your strongest glyph as any specialization of rogue." },
			{ 42967, "Glyph of Hemorrhage", "Hemorrhage's bonus damage is a pretty strong boost amounting to around 750 bonus damage per cast, and this boosts it up to 1050. For an ability you cast as often as Hemorrhage, this is a great boost. The bonus from Hemorrhage is usually not contributing to your personal damage output though because most of the charges will consumed by your teammates." },
			{ 45764, "Glyph of Shadow Dance", "Shadow Dance offers a pretty substantial burst damage window when setup correctly, and increasing the duration of the dance by 2 seconds will sometimes allow an extra use of a stealth ability before it ends." },
		},
		minor = {
			{ 43379, "Glyph of Blurred Speed", "Walking on water is always fun, and this also allows you to swim to the surface, {spell:11305} to stand on the water, then get on your flying mount from the middle of a lake! Normally you cannot get on your flying mount while swimming and would need to go to the land." },
			{ 43378, "Glyph of Safe Fall", "Not taking fall damage is always nice, and this really amps up the power of your Safe Fall passive." },
			{ 43376, "Glyph of Distract", "A little extra range on {spell:1725} can help make getting those clutch Distracts easier." },
		},
	},
})
