-- GENERATED by scripts/build_guides.py -- do not edit by hand.
-- Source: Wowhead WotLK talent and glyph guides (see scripts/guides.json),
-- decoded against this realm's own talent trees.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/shaman/elemental/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("SHAMAN", "Elemental", {
	builds = {
		{
			name = "Standard 57/14/0 Elemental",
			pts = { 57, 14, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 3 }, { 3, 2, 1 }, { 3, 3, 5 }, { 4, 1, 2 }, { 4, 4, 3 }, { 5, 1, 2 }, { 5, 2, 1 }, { 5, 4, 3 }, { 6, 1, 3 }, { 6, 3, 5 }, { 7, 2, 1 }, { 7, 3, 3 }, { 8, 1, 2 }, { 8, 2, 2 }, { 8, 3, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 3, 5 }, { 2, 2, 5 }, { 3, 1, 3 }, { 3, 3, 1 } },
				{  },
			},
			note = "{spell:52456} should be used if there is no other with it in the raid, as it will make the totem buff significantly better than {spell:57623}. Otherwise maximize {spell:17489} as exemplified in the talent build above.\n\n{spell:16110}, {spell:30666} and {spell:28996} are interchangeable and help you manage your Mana and / or your survivability, if needed. With gear Mana is no longer a major concern, which makes us recommend Elemental Warding, as many Ulduar encounters do significant area damage on the raid.",
		},
		{
			name = "Standard 60/11/0 Elemental",
			pts = { 60, 11, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 2, 3 }, { 3, 1, 5 }, { 3, 2, 1 }, { 3, 3, 5 }, { 4, 4, 3 }, { 5, 1, 2 }, { 5, 2, 1 }, { 5, 4, 3 }, { 6, 3, 5 }, { 7, 2, 1 }, { 7, 3, 3 }, { 8, 1, 2 }, { 8, 2, 2 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 2, 2 }, { 1, 3, 3 }, { 2, 1, 2 }, { 2, 2, 1 }, { 2, 3, 2 }, { 3, 3, 1 } },
				{  },
			},
			note = "This goal of this build is to combine most of the throughput Elemental talents with defensive talents such as {spell:28998} and {spell:51479}. {spell:16293} is also great for its {spell:8177} cooldown reduction and {spell:16287} grants extra mobility, while {spell:16130} synergizes well with Glyph of Stoneclaw Totem to increase the amount of personal absorbs you can get.\n\nYou can also swap some of the defensive talents into more offense by maximizing {spell:16255} and {spell:16266}, if you are feeling very tanky or you are not the main enemy target in your comp.",
		},
	},
	glyphs = {
		major = {
			{ 41536, "Glyph of Lightning Bolt", "{spell:49238} deals 4% more damage, a simple yet effective damage increase." },
			{ 45776, "Glyph of Totem of Wrath", "Dropping {spell:57722} grants you 30% extra Spell Power for 5 minutes, which is another straightforward damage increase." },
			{ 41532, "Glyph of Flametongue Weapon", "{spell:58790} grants 2% Spell Crit when you have it active on your weapon, increasing your damage." },
			{ 41529, "Glyph of Fire Elemental Totem", "Causes {spell:2894} to have half its regular cooldown, which can be useful in long fights, but is not usually necessary as Fire Elemental Totem resets along with most other cooldowns when an encounter ends." },
			{ 41524, "Glyph of Lava", "Causes {spell:60043} to scale better with your Spellpower, which is a small throughput increase." },
			{ 45778, "Glyph of Stoneclaw Totem", "A PvP glyph, it grants you a significant absorb shield whenever you cast {spell:58582}." },
			{ 45770, "Glyph of Thunder", "Another PvP glyph, it reduces {spell:59159}'s cooldown by 10 seconds, allowing you to knockback your enemies more often." },
		},
		minor = {
			{ 44923, "Glyph of Thunderstorm", "Removes the knockback on {spell:59159}, which makes it much safer to use for general PvE purposes, and also increases its Mana gain." },
			{ 43386, "Glyph of Water Shield", "Increases the amount of charges on {spell:57960} by 1, allowing you to have to recast it less often." },
			{ 43385, "Glyph of Renewed Life", "Removes the reagent cost of {spell:20608}, making your life a little bit easier." },
			{ 43388, "Glyph of Water Walking", "Removes the reagent cost on {spell:546}, also making your life a little bit easier." },
			{ 43344, "Glyph of Water Breathing", "Removes the reagent cost of {spell:131}, making your life a little bit easier." },
			{ 43725, "Glyph of Ghost Wolf", "Causes {spell:2645} to regenerate 1% of your life every 5 seconds. Not very significant but better than nothing whenever you can use Ghost Wolf regularly." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/enhancement/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("SHAMAN", "Enhancement", {
	builds = {
		{
			name = "Standard 18/53/0 Enhancement",
			pts = { 19, 52, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 1, 3 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 5 }, { 4, 1, 2 } },
				{ { 1, 1, 3 }, { 1, 3, 3 }, { 2, 2, 5 }, { 3, 1, 3 }, { 3, 3, 1 }, { 4, 2, 5 }, { 5, 1, 2 }, { 5, 2, 1 }, { 5, 3, 3 }, { 6, 1, 3 }, { 6, 3, 3 }, { 7, 1, 3 }, { 7, 2, 1 }, { 7, 3, 1 }, { 8, 1, 3 }, { 8, 2, 1 }, { 8, 3, 1 }, { 9, 1, 3 }, { 9, 2, 1 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "{spell:16164} is an important talent for Mana sustain, especially early on and in area of effect situations, where it will be activating constantly from {spell:61657} hitting multiple enemies.\n\nOnce you are doing level content, it becomes important to have {spell:28996} maxed out and Mana talents become redundant with the high amount of Intellect in your gear, thus you can move points there from {spell:16161}, {spell:16164}, and {spell:51521}.\n\nIf you have another in the raid with {spell:52456}, you can maximize {spell:17486} instead. If you have a with {spell:55610} or another with {spell:29193} in the raid, you can use the 2 talent points spent on {spell:29193} on {spell:51521}, {spell:43338}, {spell:28996}, {spell:16262} or one of the other PvP focused talents, instead.",
		},
		{
			name = "Standard 20/51/0 Enhancement",
			pts = { 17, 54, 0 },
			trees = {
				{ { 1, 3, 5 }, { 2, 2, 3 }, { 2, 3, 3 }, { 3, 1, 5 }, { 3, 2, 1 } },
				{ { 1, 2, 2 }, { 1, 3, 3 }, { 2, 2, 5 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 3, 1 }, { 4, 2, 5 }, { 5, 2, 1 }, { 5, 3, 3 }, { 6, 1, 3 }, { 6, 3, 3 }, { 6, 4, 2 }, { 7, 1, 1 }, { 7, 2, 1 }, { 7, 3, 1 }, { 8, 1, 3 }, { 8, 2, 1 }, { 8, 3, 2 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
			},
			note = "This goal of this build is to combine most of the throughput Enhancement talents with defensive talents such as {spell:28998} and utility talents such as {spell:16115}. {spell:16287} grants extra mobility, while {spell:16130} synergizes well with Glyph of Stoneclaw Totem to increase the amount of personal absorbs you can get.\n\nWhile not taken in the above build, {spell:16293} can also be great for its {spell:8177} cooldown reduction and you could also get a small amount of throughput for a melee cleave by getting {spell:16259} and {spell:29192} or become more resilient to disarms with {spell:16254}. Remove talent points from {spell:16115} or {spell:29080} / {spell:51527} for this purpose.",
		},
	},
	glyphs = {
		major = {
			{ 41539, "Glyph of Stormstrike", "{spell:17364}'s Nature damage bonus goes from 20% to 28%. This is a pretty decent damage increase." },
			{ 41530, "Glyph of Fire Nova", "{spell:61657} cooldown is 3 seconds lower. As its base cooldown is already so short, this is can be a large AoE damage increase." },
			{ 41532, "Glyph of Flametongue Weapon", "{spell:58790} grants 2% Spell Crit per weapon imbued with it. With double Flametongue on a Spellhance setup, this totals 4% Crit and a significant amount of added damage." },
			{ 41542, "Glyph of Windfury Weapon", "{spell:58804} has 2% higher chance to trigger, while this is a weak effect at low gear levels, it scales better with gear than Flametongue, making it a strong option in the later tiers." },
			{ 45771, "Glyph of Feral Spirit", "{spell:51533} will hit even harder with this glyph, as it will make them scale better with your own gear." },
			{ 41526, "Glyph of Shocking", "Your shocks have a 0.5 second lower cooldown. This allows you to quickly weave in other abilities for higher burst damage in PvP." },
			{ 41537, "Glyph of Lightning Shield", "{spell:49281} deals 20% more damage, a simple throughput increase that is much better when soloing." },
		},
		minor = {
			{ 43388, "Glyph of Water Walking", "Removes the reagent cost on {spell:546}, making your life a little bit easier." },
			{ 43385, "Glyph of Renewed Life", "Removes the reagent cost of {spell:20608}, a quality of life increase." },
			{ 43344, "Glyph of Water Breathing", "Removes the reagent cost of {spell:131}, which is also a quality of life increase." },
			{ 43386, "Glyph of Water Shield", "Increases the amount of charges on {spell:57960} by 1, allowing you to have to recast it less often." },
			{ 43725, "Glyph of Ghost Wolf", "Causes {spell:2645} to regenerate 1% of your life every 5 seconds. Not very significant but better than nothing whenever you can use Ghost Wolf regularly." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/shaman/restoration/healer-talent-builds-glyphs-pve
ns:RegisterTalentGuide("SHAMAN", "Restoration", {
	builds = {
		{
			name = "Standard 0/13/58 Restoration",
			pts = { 0, 13, 58 },
			trees = {
				{  },
				{ { 1, 3, 5 }, { 2, 2, 5 }, { 2, 4, 3 } },
				{ { 1, 2, 5 }, { 2, 3, 5 }, { 3, 1, 3 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 3 }, { 4, 2, 3 }, { 4, 3, 5 }, { 5, 1, 3 }, { 5, 3, 1 }, { 6, 3, 5 }, { 7, 2, 1 }, { 7, 3, 1 }, { 8, 1, 2 }, { 8, 2, 2 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
			},
			note = "This specialization gets all the healing improving talents for {spell:49273} and {spell:55459} in order to maximize healing efficiency and open up strong single and area target healing.\n\nWhile Glyph of Earthliving Weapon benefits your {spell:55459} (and thus AoE healing) when Glyph of Lesser Healing Wave does not, the {spell:25420} glyph is excellent for tank healing, especially in situations where you know the tank will be tanking a huge amount of damage in a short period, such as when {spell:69409} is cast on the Lich King tank. Glyph of Fire Elemental Totem is also a strong option if extra healing is not necessary.\n\n{spell:52456} should be used if there is no other with it in the raid, as it will make the totem buff significantly better than {spell:57623}. Otherwise maximize {spell:17489}.\n\n{spell:16240} is an important tank buff, but it can be skipped if you have other healer Shamans or multiple {spell:15363} Priests who can maintain it. {spell:16232} is also important to minimize cast time loss in some fights, especially in the later phases, but Wrath makes spell pushback much less of a problem, and thus it can be skipped occasionally, especially in fights where you take little to no damage.",
		},
		{
			name = "PvP 0/17/54 Restoration",
			pts = { 0, 17, 54 },
			trees = {
				{  },
				{ { 1, 2, 2 }, { 1, 3, 3 }, { 2, 1, 2 }, { 2, 2, 4 }, { 2, 3, 2 }, { 2, 4, 3 }, { 3, 3, 1 } },
				{ { 1, 2, 5 }, { 2, 2, 3 }, { 2, 3, 2 }, { 3, 1, 3 }, { 3, 2, 3 }, { 3, 3, 1 }, { 3, 4, 3 }, { 4, 2, 3 }, { 5, 1, 3 }, { 5, 3, 1 }, { 5, 4, 3 }, { 6, 3, 5 }, { 7, 2, 1 }, { 7, 3, 1 }, { 8, 1, 2 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 2 }, { 10, 2, 5 }, { 11, 2, 1 } },
			},
			note = "This is a build meant to boost {spell:49273} and its efficient healing while also getting as many PvP talents as possible and swapping to PvP glyphs. {spell:16293} is great for its {spell:8177} cooldown reduction and {spell:16287} grants extra mobility, while {spell:30866} shortens interruptions. {spell:16130} synergizes well with Glyph of Stoneclaw Totem to increase the amount of personal absorbs you can get. {spell:29191} is also great for PvP due to making your {spell:974} and other helpful effects harder to remove.\n\n{spell:30881} is skipped due to its low impact, while requiring a lot of talent points, especially when you are already very tanky due to the Stoneclaw combo, Mail armor and 's multiple spell cast disruption tools.",
		},
	},
	glyphs = {
		major = {
			{ 45775, "Glyph of Earth Shield", "{spell:49284} heals for 20% more, a simple yet powerful throughput increase as the extra healing is constantly happening is is unlikely to overheal." },
			{ 41517, "Glyph of Chain Heal", "{spell:55459} jumps an additional time. While its healing will be vastly reduced on the 4th jump, it can still proc special effects such as {spell:16198}, {spell:51994} and {spell:16240}, making it better than it looks at a first glance." },
			{ 41527, "Glyph of Earthliving Weapon", "{spell:51994} has an extra 5% chance to proc, which can be a significant amount of healing when combined with liberal {spell:55459} usage and Glyph of Chain Heal." },
			{ 41535, "Glyph of Lesser Healing Wave", "{spell:25420} heals for 20% more on targets with {spell:49284}. This makes it very strong whenever you know you will be spamming the tank a lot, but not if your main concern is AoE healing." },
			{ 41529, "Glyph of Fire Elemental Totem", "{spell:2894} has a 5 minute lower cooldown. While this is a damage gain, rather than a healing glyph like the others, it adds significant damage over the course of a raid, and should be the default choice if extra healing is not needed, in place of Glyph of Earthliving Weapon or Glyph of Lesser Healing Wave, which have the smallest effect out of all recommended Major glyphs." },
			{ 41534, "Glyph of Healing Wave", "{spell:49273} heals you for 20% when you heal other targets. While situational, this glyph is great whenever you are expected to take a fair bit of damage on yourself, such as in PvP scenarios." },
			{ 45778, "Glyph of Stoneclaw Totem", "A PvP glyph, it grants you a significant absorb shield whenever you cast {spell:58582}." },
			{ 41533, "Glyph of Healing Stream Totem", "{spell:58757} heals for 20% more. While occasionally strong, Healing Stream Totem only heals your party and you need to occupy your Water Totem slot with it, thus the benefit of this glyph is rather situational." },
			{ 45772, "Glyph of Riptide", "{spell:61301} lasts for 6 seconds longer. This can potentially increase its healing if the target is still injured after the 15 seconds baseline duration and you do not consume it before with {spell:55459}, but the value of having extra Riptides available to boost Chain Heals with during periods of burst damage is also not to be underestimated." },
			{ 41541, "Glyph of Water Mastery", "{spell:57960} grants you 30% more Mp5 passively. While not huge, this Mp5 increase should allow you to cast more spells in a given fight before running out of Mana, thus also contributing towards higher healing throughput." },
		},
		minor = {
			{ 43386, "Glyph of Water Shield", "Increases the amount of charges on {spell:57960} by 1, allowing you to have to recast it less often." },
			{ 43385, "Glyph of Renewed Life", "Removes the reagent cost of {spell:20608}, making your life a little bit easier." },
			{ 43388, "Glyph of Water Walking", "Removes the reagent cost on {spell:546}, also making your life a little bit easier." },
			{ 43344, "Glyph of Water Breathing", "Removes the reagent cost of {spell:131}, making your life a little bit easier." },
			{ 43725, "Glyph of Ghost Wolf", "Causes {spell:2645} to regenerate 1% of your life every 5 seconds. Not very significant but better than nothing whenever you can use Ghost Wolf regularly." },
		},
	},
})
