-- GENERATED by scripts/build_guides.py -- do not edit by hand.
-- Source: Wowhead WotLK talent and glyph guides (see scripts/guides.json),
-- decoded against this realm's own talent trees.
local _, ns = ...

-- https://www.wowhead.com/wotlk/guide/classes/warlock/affliction/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("WARLOCK", "Affliction", {
	builds = {
		{
			name = "Affliction 55/0/16",
			pts = { 55, 0, 16 },
			trees = {
				{ { 1, 1, 2 }, { 1, 2, 3 }, { 1, 3, 5 }, { 2, 4, 2 }, { 3, 2, 3 }, { 4, 2, 2 }, { 4, 4, 3 }, { 5, 1, 5 }, { 5, 2, 1 }, { 6, 1, 2 }, { 6, 2, 5 }, { 7, 1, 3 }, { 7, 2, 5 }, { 8, 3, 3 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 1 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{  },
				{ { 1, 2, 5 }, { 1, 3, 5 }, { 3, 3, 5 }, { 4, 1, 1 } },
			},
			note = "This is the standard Affliction Warlock build for Wrath of the Lich King. Most talent points in Affliction and Destruction are a must-have that increases your damage, however, there are a few points that are up to your preference or fulfill certain niche situations. Overall {spell:18176} can be swapped out the better our gear gets, and instead, these points can be put towards other beneficial talents. {spell:18372} and {spell:18183} do not benefit us with the most significant direct damage increases but they can have potential benefits by either saving us an {spell:57946} or by limiting the odds that we have to throttle our DPS (though it should be noted as a big chunk of our threat still comes from Destruction spells as well). \n\n{spell:18288} saves us a marginal amount of cast time and as such potentially increases our DPS a tiny bit. However, you should note that the better our gear becomes, the lower the benefit of this talent is, as we naturally get closer to the GCD cap (1 seconds) from haste rating.\n\n{spell:18219} and {spell:17918} are best combined if taken, due to the fact that we make use of a mix of both Destruction and Affliction spells, else you left standing at closer range if you only opt for either. {spell:18095} is another option on this tier of talents, resulting in a slight DPS boost overall thanks to instant cast {spell:47809}.\n\nIn the Destruction tree there ...",
		},
	},
	glyphs = {
		major = {
			{ 45785, "Glyph of Life Tap", "Spirit is more valuable than ever before, partly thanks to Glyph of Life Tap (and {spell:47893}). {spell:57946} converts spirit into spell power for a duration of 40 seconds. This makes Glyph of Life Tap one of the strongest Glyphs for all the Warlock Specializations. It should be stated that you can {spell:57946} before combat, to start an encounter with the buff already up." },
			{ 50077, "Glyph of Quick Decay", "Everything Affliction Warlocks do have to do with {spell:47813}. All caster stats affect {spell:47813}, except for haste rating, or does it? Glyph of Quick Decay causes {spell:47813} to benefit from haste rating and other cast speed increases such as {spell:47197}, and {spell:2825}." },
			{ 45779, "Glyph of Haunt", "This is the least special of the major glyphs. All it does is boost our {spell:59164} by 3%, however, that 3% does impact most of our damage-dealing spells. Making this still a big damage increasing from a single glyph." },
		},
		minor = {
			{ 43390, "Glyph of Drain Soul", "Glyph of Drain Soul is the only minor glyph that has any noticeable impact, we spend plenty of time casting {spell:47855}, and in turn spending all the shar{spell:47855} we can get. This reduces the requirement to ever farm shar{spell:47855} again. All other minor glyphs aside from this one do not provide any real impact." },
			{ 43389, "Glyph of Unending Breath", "Swimming a tiny bit faster is always welcome whenever we go for dipping our toes." },
			{ 43394, "Glyph of Souls", "It doesnt happen too often that you will need to summon closely before combat, so the benefit of this is rather a small bit of convenience." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warlock/demonology/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("WARLOCK", "Demonology", {
	builds = {
		{
			name = "Demonology 0/56/15",
			pts = { 0, 56, 15 },
			trees = {
				{  },
				{ { 1, 3, 3 }, { 1, 4, 2 }, { 2, 2, 3 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 1 }, { 3, 4, 3 }, { 4, 2, 5 }, { 4, 3, 2 }, { 5, 3, 2 }, { 6, 2, 5 }, { 6, 3, 3 }, { 7, 2, 1 }, { 7, 3, 3 }, { 8, 2, 5 }, { 8, 3, 2 }, { 9, 1, 2 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
				{ { 1, 2, 5 }, { 1, 3, 5 }, { 3, 3, 5 } },
			},
			note = "This is the standard Demonology Warlock build for Wrath of the Lich King. Most talent points in Demonology and Destruction are a must-have that increases your damage, however, there are a few points that are up to your preference or fulfill certain niche situations. There are two points that we can easily move around that we can either put into talents that will further boost our damage, or fulfill a niche utility.\n\nThe points into {spell:47231} in the above build could also be put into {spell:18693}. This would mostly be useful during progression, though a Destruction Warlock could also easily put a point into this.\n\nAside from {spell:47231}, you got two other points that you can move around for your preference, in the above build they are put into {spell:54349}. Let us go over the utility options first, we can opt to put a few points into {spell:18176} for the extra hit rating, it should be noted that the hit chance from this doesn't get carried over to our . This would be most useful during pre-raid gearing. Another option would be to put them into {spell:17918} the issue with that is that you still need to move closer too use {spell:47813} and your curse. Alternatively, you could put 2 points into {spell:18136} for the reduced pushback, along with with {spell:19746} from a Paladin this removes the possibility of pushback occurring, aside from {spell:47836} for AOE.\n\nIf you ...",
		},
	},
	glyphs = {
		major = {
			{ 45785, "Glyph of Life Tap", "Spirit is more valuable than ever before, partly thanks to Glyph of Life Tap (and {spell:47893}). {spell:57946} converts spirit into spell power for a duration of 40 seconds. This makes Glyph of Life Tap one of the strongest Glyphs for all the Warlock Specializations. It should be stated that you can {spell:57946} before combat, to start an encounter with the buff already up." },
			{ 42459, "Glyph of Felguard", "Our is good for roughly one-fifth of our total damage, being able to boost his Attack Power by 20% is nothing to snuff at." },
			{ 50077, "Glyph of Quick Decay", "Whilst {spell:47813} isn't the biggest source of our damage, this is one of the better glyphs we can use to boost our total damage." },
			{ 45780, "Glyph of Metamorphosis", "This glyph increases the duration of our {spell:59672} by six seconds. We mostly would use this instead of Glyph of Felguard, when our can not deal any damage in the fight." },
		},
		minor = {
			{ 43390, "Glyph of Drain Soul", "Glyph of Drain Soul is the only minor glyph that has any noticeable impact, we spend plenty of time casting {spell:47855}, and in turn, spending all the Soul Shards we can get. This reduces the requirement to farm Soul Shard. All other minor glyphs aside from this one do not provide any real impact." },
			{ 43389, "Glyph of Unending Breath", "Swimming a tiny bit faster is always welcome whenever we go for dipping our toes." },
			{ 43394, "Glyph of Souls", "It doesnt happen too often that you will need to summon closely before combat, so the benefit of this is rather a small bit of convenience." },
		},
	},
})

-- https://www.wowhead.com/wotlk/guide/classes/warlock/destruction/dps-talent-builds-glyphs-pve
ns:RegisterTalentGuide("WARLOCK", "Destruction", {
	builds = {
		{
			name = "Destruction 0/10/56",
			pts = { 0, 10, 56 },
			trees = {
				{  },
				{ { 1, 2, 3 }, { 1, 3, 3 }, { 1, 4, 1 }, { 2, 3, 3 } },
				{ { 1, 3, 5 }, { 2, 1, 2 }, { 2, 3, 3 }, { 3, 1, 2 }, { 3, 3, 5 }, { 4, 1, 2 }, { 4, 2, 2 }, { 5, 2, 3 }, { 5, 3, 1 }, { 6, 3, 5 }, { 7, 2, 1 }, { 7, 3, 3 }, { 7, 4, 3 }, { 8, 2, 5 }, { 8, 3, 1 }, { 9, 1, 3 }, { 9, 2, 1 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
			},
			note = "First off this talent build is not complete and leaves you with 5 points free to spend elsewhere!\n\nThis is the standard Destruction Warlock build for Wrath of the Lich King. Most talent points in Destruction and Demonology are a must-have that increases your damage, however, there are a few points that are up to your preference or fulfill certain niche situations. There are five points that we can easily move around that we can either put into talents that will further boost our damage, or fulfill a niche utility.\n\nOne of the more obvious choices early on especially is found in the Affliction talent tree. {spell:18176} provides us with a significant amount of hit rating, something that can often be hard to find on our gear early on. This also allows opens up other gearing opportunities at times. Another Affliction option would be {spell:17814}, this sees nearly no use on single target encounters as we don't use {spell:47813} in our normal rotation. However, we do use plenty of {spell:47836} when dealing with large encounters. \n\nWe could spend the additional points into the Demonology tree. Most notable for DPS would be {spell:30145} which arguably is a must have, it is listed as optional because this is the place you would swap out for additional utility talents (depending on niche encounters). Another option would be {spell:18708}, this can really come in handy as the is the ...",
		},
		{
			name = "Destruction 0/19/52",
			pts = { 0, 19, 52 },
			trees = {
				{  },
				{ { 1, 2, 3 }, { 1, 3, 3 }, { 1, 4, 1 }, { 2, 3, 3 }, { 3, 2, 1 }, { 3, 3, 1 }, { 3, 4, 3 }, { 4, 2, 4 } },
				{ { 1, 3, 5 }, { 2, 1, 2 }, { 2, 3, 3 }, { 3, 1, 2 }, { 3, 3, 5 }, { 4, 1, 2 }, { 4, 2, 1 }, { 5, 1, 2 }, { 5, 2, 3 }, { 5, 3, 1 }, { 6, 3, 5 }, { 7, 2, 1 }, { 7, 4, 3 }, { 8, 2, 5 }, { 9, 1, 3 }, { 9, 3, 3 }, { 10, 2, 5 }, { 11, 2, 1 } },
			},
			note = "This talent build has a bigger focus on the throughput of your Imp. This by swapping out {spell:56242} in favor of {spell:56248}. On top of that {spell:18772} is taken to further boost the Imps damage. This talent build mostly starts to outperform the \"standard\" in Trail of the Grand Crusader. Especially in combination with two-piece bonus from / which increases your pet's critical strike chance with all its attacks by 10%.",
		},
	},
	glyphs = {
		major = {
			{ 42454, "Glyph of Conflagrate", "This Glyph is a must-have to make the Destruction specialization work properly. What this does is make it so that you do not need to recast {spell:47811} each and every time you use {spell:17962}. Not only that but otherwise you would be casting {spell:47811} every 10 seconds instead of every 15, or you would be casting {spell:17962} only whenever {spell:47811} was about to run out. In other words, you win cast time by not having to recast and you win DPS due to the fact that you do not consume {spell:47811} and don't have to postpone using {spell:17962}." },
			{ 42453, "Glyph of Incinerate", "{spell:47838} is our main filler spell, and you can not go wrong with adding 5% damage to one of our most used spells that is good for the majority of our damage." },
			{ 45785, "Glyph of Life Tap", "Spirit is more valuable than ever before, partly thanks to Glyph of Life Tap (and {spell:47893}). {spell:57946} converts spirit into spell power for a duration of 40 seconds. This makes Glyph of Life Tap one of the strongest Glyphs for all the Warlock Specializations. It should be stated that you can {spell:57946} before combat, to start an encounter with the buff already up." },
			{ 42464, "Glyph of Immolate", "Glyph of Immolate doesn't only boost the damage from our {spell:47811} but also the damage from our {spell:17962}. This is because the damage from our {spell:47811} determines how much damage {spell:17962} deals." },
		},
		minor = {
			{ 43390, "Glyph of Drain Soul", "Glyph of Drain Soul is the only minor glyph that has any noticeable impact, we spend plenty of time casting {spell:47855}, and in turn, spending all the Soul Shards we can get. This reduces the requirement to farm Soul Shard. All other minor glyphs aside from this one do not provide any real impact." },
			{ 43389, "Glyph of Unending Breath", "Swimming a tiny bit faster is always welcome whenever we go for dipping our toes." },
			{ 43394, "Glyph of Souls", "It doesnt happen too often that you will need to summon closely before combat, so the benefit of this is rather a small bit of convenience." },
		},
	},
})
